### PR TITLE
Kubernetes jobs cancel does not delete pod

### PR DESCRIPTION
**Pull request by fg91**
## What changes are proposed in this pull request?
When calling `submitted_kubernetes_run.cancel()`, the job is deleted but the associated pod continues to do its work. 
Replacing `kubernetes.client.V1DeleteOptions()` with `kubernetes.client.V1DeleteOptions(propagation_policy="Background")` ensures that the pod is deleted as well.

## How is this patch tested?
All tests in `./dev/run-small-python-tests.sh` pass.

### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

### What component(s), interfaces, languages, and integrations does this PR affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>
### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [x] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Review by tnte — APPROVED** [review]
Observing the same issue and would suggest the same bug-fix.

**Comment by fg91** [comment]
> Observing the same issue and would suggest the same bug-fix.

`At least 1 approving review is required by reviewers with write access`
@tnte Do you have write access?

**Comment by tnte** [comment]
> > Observing the same issue and would suggest the same bug-fix.
> 
> `At least 1 approving review is required by reviewers with write access`
> @tnte Do you have write access?

Unfortunately not

**Comment by adrianloy** [comment]
Any chance of this getting merged? I would propose the same bugfix and observe the same issue. @harupy who was write access to get this merged?

**Pull request closed without merging**
