### PR TITLE
Remove mlflow.sklearn.eval_and_log_metrics() API

### PR DESCRIPTION
**Pull request by dbczumar**
Signed-off-by: dbczumar <corey.zumar@databricks.com>

## What changes are proposed in this pull request?

Remove `mlflow.sklearn.eval_and_log_metrics()` API in favor of `mlflow.evaluate()`

## How is this patch tested?

Existing tests

## Does this PR change the documentation?

- [X] No. You can skip the rest of this section.
- [ ] Yes. Make sure the changed pages / sections render correctly by following the steps below.

1. Click the `Details` link on the `Preview docs` check.
2. Find the changed pages / sections and make sure they render correctly.

## Release Notes

Remove the `mlflow.sklearn.eval_and_log_metrics()` API in favor of `mlflow.evaluate()`

### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [X] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?
Components
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>
### How should the PR be classified in the release notes? Choose one:

- [X] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by dbczumar** [comment]
@yxiong @jimmyxu-db FYI. Let's work together to migrate AutoML to `mlflow.evaluate()` prior to the release of MLflow 2.0

**Review by harupy — APPROVED** [review]
LGTM!

**Comment by yxiong** [comment]
If we merge this now, the AutoML DUST test we set up for mlflow 2.0 branch will fail. Can we wait for @jimmyxu-db to migrate the usage of `eval_and_log_metrics` to `evaluate` API first before removing in the branch?

**Comment by dbczumar** [comment]
> If we merge this now, the AutoML DUST test we set up for mlflow 2.0 branch will fail. Can we wait for @jimmyxu-db to migrate the usage of `eval_and_log_metrics` to `evaluate` API first before removing in the branch?

@yxiong I'm inclined to merge this as motivation to restore DUST test health, especially since `mlflow.evaluate()` should be adopted as soon as possible to give ample time for testing & identification of issues. Let me know if you're strongly opposed.

**Comment by yxiong** [comment]
The problem is that if we merge now, the DUST test will fail (because we haven't migrated), we'll have to disable it, and then some other potential incompatibilities will not be caught.

Does `evaluate` already support all functionalities of `eval_and_log_metrics` today? Are we unblocked for the migration now?

**Comment by dbczumar** [comment]
Why does the DUST test need to be disabled? I'm not sure I follow the reasoning there; this test shouldn't block release

**Comment by dbczumar** [comment]
I think it already supports the desired functionality, but the goal of the exercise is to try it out and let us know what's missing as early in the quarter as is feasible

**Review by jimmyxu-db — APPROVED** [review]

**Pull request merged**
