### PR TITLE
Expose mlflow.tracking.is_tracking_uri_set()

### PR DESCRIPTION
**Pull request by fhoering**
## What changes are proposed in this pull request?

Fixes:
https://github.com/mlflow/mlflow/issues/2005

## How is this patch tested?

On our Criteo Mlflow server

### Is this a user-facing change?

- [] No. You can skip the rest of this section.
- [x] Yes. Give a description of this change to be included in the release notes for MLflow users.

Exposed `mlflow.tracking.is_tracking_uri_set()` to determine whether or not the tracking URI is set via environment variable or `set_tracking_uri`. This is distinct from `get_tracking_uri`, which will return a default value if the URI is not set.

### What component(s) does this PR affect?

- [ ] UI
- [ ] CLI
- [ ] API
- [ ] REST-API
- [ ] Examples
- [ ] Docs
- [ ] Tracking
- [ ] Projects
- [ ] Artifacts
- [ ] Models
- [ ] Scoring
- [ ] Serving
- [ ] R
- [ ] Java
- [x] Python

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [x] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Review by dbczumar — APPROVED** [review]
LGTM. Thanks @fhoering!

**Comment by mateiz** [comment]
I'm not sure whether you guys discussed this, but why not just check whether `get_tracking_uri` returns None (and make it return None in this case)? Adding lots of top level fluid APIs might be confusing to users.

**Comment by fhoering** [comment]
python -c "import mlflow;mlflow.set_experiment('test');mlflow.log_param('key', 'value')"

**Comment by fhoering** [comment]
@mateiz @dbczumar 
Returning None in `get_tracking_uri`  would be also fine. I even think it would be clearer to explicitly require the user to set this.

I suppose this implies to delete the [default local tracking uri](https://github.com/mlflow/mlflow/blob/master/mlflow/tracking/_tracking_service/utils.py#L67.) and then to add an exception that the tracking uri is not set. 

The only valid use case I see for returning a default local filesystem is debugging.

This currently works:
```
pip install
python -c "import mlflow;mlflow.set_experiment('test');mlflow.log_param('key', 'value')"
mlflow server
```

And it would become one more line with the change (and fail otehrwise):
```
pip install
python -c "import mlflow;mlflow.set_tracking_uri('/tmp');mlflow.set_experiment('test');mlflow.log_param('key', 'value')"
mlflow server
```

Can you decide on your side ? Both solutions are fine with me if I'm able to check if this has been set.

**Comment by mateiz** [comment]
Ah, I see what you mean; I didn't realize that `get_tracking_uri` returned the local one by default. We do want projects to run in a meaningful way with no config, but we should look into whether we can change `get_tracking_uri` to return None if you haven't set it from outside, or to recommend another way to see whether the tracking URI is set to the default (for example maybe your code can check whether the environment variable MLFLOW_TRACKING_URI is set instead). It's quite confusing to have an API called `get_tracking_uri` that returns something, while another API called `is_tracking_uri_set` does not return anything. We don't want stuff like that to appear in our easiest-to-use top-level API. It would be better to offer another easy way to check for what you're testing without confusing users who are just learning the basic API.

**Comment by fhoering** [comment]
I agree that having both methods might be confusing.

Checking the env variable MLFLOW_TRACKING_URI is not good enough because mlflow.set_tracking_uri sets a global variable that overloads this. So it is not possible to only check for this.

If it can be reexposed in another public module like mlflow.utils.is_tracking_uri_set that would be also fine.

Personally I like removing the default local path as not setting this explicitly doesn't make sense for a real use case and can be confusing. an exception with a link to the doc "please set the tracking uri" is clear and easy to understand.

**Comment by fhoering** [comment]
If it can be of interest the code I am writing ist here https://github.com/criteo/tf-yarn/blob/master/tf_yarn/mlflow.py#L39

This is basically a robust/optional wrapper of the MLFlow client. (Ideally most of this code would be integrated one day into the client by default).

It doesn't make sense to log stuff to the local file system because this wrapper can be executed from multiple containers on the cluster for the same run.

**Comment by aarondav** [comment]
Agree with @mateiz, this should not be exposed in the fluent API (mlflow/__init__.py). It sounds like it would be sufficient to expose it in mlflow.tracking?

Also, I don't think we can even consider breaking backwards compatibility of get_tracking_uri until 2.0.

**Comment by fhoering** [comment]
OK with me as well. Removed it from `mlflow.__init__`
The only thing I would really like to prevent is to use an internal API. 

Side note: If you don't want to break backward compatibility then it should just be re-exposed inside mlflow.utils. This is already a regression actually.

**Comment by aarondav** [comment]
@fhoering With regards to it being exposed in mlflow.utils, I'm sorry but I couldn't find when/where that was, and when it was broken. I didn't find a reference to `is_tracking_uri` in the linked commit, for example, nor could I find it defined in `branch-1.2` or `branch-1.3` in `mlflow/utils/__init__.py`. Could you link how this was exposed previously?

**Comment by fhoering** [comment]
Sorry, I meant mlflow.tracking.utils
https://github.com/mlflow/mlflow/blob/branch-1.3/mlflow/tracking/utils.py#L31

Now utils class has been moved:
https://github.com/mlflow/mlflow/blob/master/mlflow/tracking/_tracking_service/utils.py

**Comment by aarondav** [comment]
Got it, thanks. I see why this happened - we pretty much consider public APIs only those which are exposed through our documentation, and `mlflow.tracking.utils` is not exposed in this way ([1.3 docs](https://www.mlflow.org/docs/1.3.0/python_api/mlflow.tracking.html)), but of course from Python one can find and load other modules.

If people are generally depending on libraries that are not exposed there, that is problematic and we should consider treating them as public stable APIs (even if accidentally exposed as such).

As a first step, though, I think exposing this method in `mlflow.tracking` as you have done here makes sense, as that is agreed to be a public API.

**Comment by fhoering** [comment]
Thanks

**Pull request merged**
