### PR TITLE
Modify `.[extras]` with single quotes

### LINKED ISSUE #5913: Wrap `.[extras]` with single quotes
The following pip install command in [CONTRIBUTING.rst](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#manual-python-development-environment-configuration):

```
pip install -e .[extras]
```

fails on zsh with the following error:

```
zsh: no matches found: .[extras]
```

As explained in [zsh: no matches found: requests[security]](https://stackoverflow.com/questions/30539798/zsh-no-matches-found-requestssecurity), `.[extras]` needs to be quoted as follows:

```diff
diff --git a/CONTRIBUTING.rst b/CONTRIBUTING.rst
index 610a7cd10..4876f93ee 100644
--- a/CONTRIBUTING.rst
+++ b/CONTRIBUTING.rst
@@ -199,14 +199,14 @@ by running the following from your checkout of MLflow:
 
     conda create --name mlflow-dev-env python=3.7
     conda activate mlflow-dev-env
-    pip install -e .[extras] # installs mlflow from current checkout with some useful extra utilities
+    pip install -e '.[extras]' # installs mlflow from current checkout with some useful extra utilities
 
 If you plan on doing development and testing, you will also need to install the following into the conda environment:
 
 .. code-block:: bash
 
     pip install -r requirements/dev-requirements.txt
-    pip install -e .[extras]  # installs mlflow from current checkout
+    pip install -e '.[extras]'  # installs mlflow from current checkout
     pip install -e tests/resources/mlflow-test-plugin # installs `mlflow-test-plugin` that is required for running certain MLflow tests
```

### PR DESCRIPTION
**Pull request by yashaswikakumanu**
Signed-off-by: Yashaswi Kakumanu <yashaswi.kakumanu@gmail.com>

Close #5913

#xxx

## What changes are proposed in this pull request?

(Please fill in changes proposed in this fix)

## How is this patch tested?

(Details)

## Does this PR change the documentation?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Make sure the changed pages / sections render correctly by following the steps below.

1. Check the status of the `ci/circleci: build_doc` check. If it's successful, proceed to the
   next step, otherwise fix it.
2. Click `Details` on the right to open the job page of CircleCI.
3. Click the `Artifacts` tab.
4. Click `docs/build/html/index.html`.
5. Find the changed pages / sections and make sure they render correctly.

### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?
Components
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>
### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by harupy** [comment]
@yashaswikakumanu Thanks for the PR, can you fix the PR title and correctly reference the issue this PR addresses?

**Comment by yashaswikakumanu** [comment]
@harupy Can you please check now

**Comment by harupy** [comment]
looks good!

**Comment by yashaswikakumanu** [comment]
@harupy when can I see my name under the contributor list

**Comment by harupy** [comment]
See https://github.com/mlflow/mlflow/graphs/contributors. Your name is already in the list.

**Pull request merged**
