### PR TITLE
Updated to conda activate for projects

### PR DESCRIPTION
**Pull request by eric-vader**
## What changes are proposed in this pull request?
 
Issue #965, enhancement to projects
 
## How is this patch tested?

Ran `./lint.sh` and `./travis/run-small-python-tests.sh`.
Did not introduce any errors.
 
### Is this a user-facing change? 

- [ ] No. You can skip the rest of this section.
- [X] Yes. Give a description of this change to be included in the release notes for MLflow users.
 
Updated to use Conda > 4.4 's activate syntax in projects.
 
### What component(s) does this PR affect?
 
- [ ] UI
- [ ] CLI 
- [ ] API 
- [ ] REST-API 
- [ ] Examples 
- [ ] Docs
- [ ] Tracking
- [X] Projects 
- [ ] Artifacts 
- [ ] Models 
- [ ] Scoring 
- [ ] Serving
- [ ] R
- [ ] Java
- [ ] Python

### How should the PR be classified in the release notes? Choose one:
 
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [X] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by nlaille** [comment]
@eric-vader could you fix the conflict ? Your patch would be welcome by a lot of people :)

**Comment by smurching** [comment]
Ah thanks @eric-vader and @nlaille! Would be great to support for newer condas merged - I looked into the same issue a bit in https://github.com/mlflow/mlflow/pull/1533. Unfortunately simply invoking `conda activate` doesn't work as `conda` is a shell function, rather than an executable on the PATH. It seems the recommended approach per the conda maintainers (see https://github.com/conda/conda/issues/7126) is to use the `CONDA_EXE` environment variable to find the path to the actual conda executable, then run invoke that, as is currently done in PR 1533 ([link](https://github.com/mlflow/mlflow/pull/1533/files#diff-312ec0fbfdd8727385a9a28df688a652R20)). I won't have time to update #1533 in the near future so if you're able to work on a fix that'd be awesome :)

**Comment by eric-vader** [comment]
Yeah, I was debating whether to get the conda executable or not but opted for the simpler solution.

Didn’t come across the conda maintainers’ recommendations till now! 

Right! I can perform the fixes not a problem, I can update it by this week ends!

**Comment by nlaille** [comment]
@smurching you created a new package to "handle" conda. Should the fix be applied as is or should we consider your modification ?
@eric-vader if you need some help I can help you.

**Comment by smurching** [comment]
Ah @nlaille @eric-vader no need to refactor conda helpers from projects/__init__.py to conda_utils.py - if you do want to include that refactor that'd be nice, ideally we'd use shared logic to create & activate conda environments for both projects & models (as #1533 does) but we can also defer the refactor for now.

**Comment by avinashraghuthu** [comment]
@smurching @nlaille We are working on a feature in our company in which we are using mlflow for model deployment. I am stuck for the same bug where source activate is not working .I have run through the thread and made code changes by getting the conda exe path and activating the profile.d conda.sh file as suggested by conda community.We need this fix urgently.So I made the necessary changes in this PR  https://github.com/mlflow/mlflow/pull/1576

Can you please review it?

**Comment by eric-vader** [comment]
@nlaille @smurching I have looked into it and merged some of both of your codes into my fork https://github.com/eric-vader/mlflow

Unfortunately, the issue is not simple to get around. The solution mentioned in https://github.com/conda/conda/issues/7126 does not work generally and does not work on my machine as conda is installed as a system package.

I will only be able to continue to work on it on the weekends - ie. next weekend. I have added @nlaille to the repo that I am working on for the fix, if you want to help out! Would appreciate the help from @nlaille

Any bright ideas how to locate `conda.sh`?

**Comment by nlaille** [comment]
@eric-vader you introduced a lot of changes with the merges.
I will investigate a bit, but there might be a solution with : https://github.com/mlflow/mlflow/pull/1576

**Comment by smurching** [comment]
@eric-vader thanks for the update, it's surprising to hear that https://github.com/conda/conda/issues/7126 doesn't work generally - what's the error you get when using that solution? What platform, conda version, and python version are you using?

**Comment by nlaille** [comment]
Fixed by #1576

**Pull request closed without merging**
