### PR TITLE
Update super usage

### PR DESCRIPTION
**Pull request by rahulporuri**
## What changes are proposed in this pull request?

The usage of the builtin super function has changed between Python 2 and Python 3 - on Python 3, super does not need to be called with any arguments in the normal cases where super is used.

This PR updates the super usage in the codebase.

Note that the changes were made using regex-based automated search and replace. The regex used is `(super)+\(+(\w+)(,)+\s(self)+\)+` - which matched e.g. `super(Store, self)` - which was replaced with `super()`. The changes were then verified one after another before being staged. All of the uses of `super` are trivial uses of the nature `super(ClassName, self)` called within the `class ClassName` so these changes should cause no behavioral changes in the codebase.

## How is this patch tested?

The changes are trivial and were not tested locally. I am reling on CI.

### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by harupy** [comment]
@rahulporuri Thanks for the PR! Could you merge the master branch? It should fix the failing CI checks.

**Comment by rahulporuri** [comment]
@harupy not sure why CI is still failing on this PR but three other PRs are happy - #3506 , #3508 , #3510

**Comment by harupy** [comment]
@rahulporuri Thanks for merging the master branch. I have created a PR to fix the error in the `Examples` check: https://github.com/mlflow/mlflow/pull/3521.

**Comment by harupy** [comment]
@rahulporuri #3251 has been merged. Could you merge the master branch again?

**Review by harupy — APPROVED** [review]
LGTM :)

**Pull request merged**
