### PR TITLE
Implement rate limit for OpenAI-compatible endpoints

### LINKED ISSUE #12699: [FR] Add rate limit support for OpenAI compatible endpoints
### Willingness to contribute

Yes. I can contribute this feature independently.

### Proposal Summary

Add rate limit support for OpenAI compatible endpoints.

### Motivation

> #### What is the use case for this feature?
To manage API request volumes effectively, ensuring fair usage, preventing abuse, and maintaining service performance and stability.

> #### Why is this use case valuable to support for MLflow users in general?
Prevents server overloads and ensures fair resource distribution. Maintains consistent performance and reliability across endpoint types.
 
> #### Why is this use case valuable to support for your project(s) or organization?
Ensures system scalability with a growing user base.

> #### Why is it currently difficult to achieve this use case?
Requires custom implementation without built-in rate limiting.

### Details

_No response_

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [X] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

### PR DESCRIPTION
**Pull request by danilopeixoto**
<details><summary>&#x1F6E0 DevTools &#x1F6E0</summary>
<p>

[Open in GitHub Codespaces](https://codespaces.new/danilopeixoto/mlflow/pull/12700?quickstart=1)

#### Install mlflow from this PR

```
pip install git+https://github.com/mlflow/mlflow.git@refs/pull/12700/merge
```

#### Checkout with GitHub CLI

```
gh pr checkout 12700
```

</p>
</details>

### Related Issues/PRs

Resolve #12699

### How is this PR tested?

- [x] Existing unit/integration tests
- [ ] New unit/integration tests
- [ ] Manual tests

### Does this PR require documentation update?

- [x] No. You can skip the rest of this section.
- [ ] Yes. I've updated:
  - [ ] Examples
  - [ ] API references
  - [ ] Instructions

#### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [x] Yes. Give a description of this change to be included in the release notes for MLflow users.

Implement rate limit for OpenAI-compatible endpoints in MLflow Deployments Server.

#### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [x] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>

#### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [x] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

#### Should this PR be included in the next patch release?

`Yes` should be selected for bug fixes, documentation updates, and other small changes. `No` should be selected for new features and larger changes. If you're unsure about the release classification of this PR, leave this unchecked to let the maintainers decide.

<details>
<summary>What is a minor/patch release?</summary>

- Minor release: a release that increments the second part of the version number (e.g., 1.2.0 -> 1.3.0).
  Bug fixes, doc updates and new features usually go into minor releases.
- Patch release: a release that increments the third part of the version number (e.g., 1.2.0 -> 1.2.1).
  Bug fixes and doc updates usually go into patch releases.

</details>

- [ ] Yes (this PR will be cherry-picked and included in the next patch release)
- [x] No (this PR will be included in the next minor release)

### CODE REVIEW

**Comment by BenWilson2** [comment]
Does this implementation have to be specific to OpenAI routes? Can this just be an abstract rate limiting implementation that can be applied to any route? 
Can we also test this functionality by firing off some async calls at a volume that exceeds the burst capacity of the endpoint's limiter to verify that the change will actually perform correct request limiting (spinning up, submitting, and then cleaning up a thread pool manager to submit the requests will probably be the cleanest way to do this). 
A feature like this will also require documentation updates to let users know that this is available. Can you include mentions of this in the deployments server docs about how to set these limits with a brief example of the yaml conf setup?

**Comment by danilopeixoto** [comment]
@BenWilson2 I don't have a solution to merge both implementations at the moment. However, we can definitely add the tests.

The documentation already includes information on rate limit configuration for users. What hasn't been documented yet - if I'm not wrong - is the existence of OpenAI-compatible endpoints introduced in https://github.com/mlflow/mlflow/pull/12003?

**Comment by BenWilson2** [comment]
@danilopeixoto I must be myopic. 
We do sort-of have it in the docs, but it's really buried. https://mlflow.org/docs/latest/llms/deployments/index.html#endpoints 
It might make sense to add a small section below that `Endpoints` header to highlight setting the limits via an endpoint config specifically for the OpenAI provider routes (quick config sample and 3-4 sentences that explain how to set them for the Deployments Server routes that you're updating with functionality here). 

Once the tests are added to validate rate limiting on the route, we'll be good to go! (Thanks for the refactoring via the handler decorator too for 4xx errors :) )

**Comment by BenWilson2** [comment]
(documenting the feature for what you're modifying is on us, though. We'll file a ticket to create a new section in the docs for these endpoints)

**Comment by danilopeixoto** [comment]
@BenWilson2 I replicated an existing rate limit test using parametrizing test. I believe this should work fine!

**Pull request closed without merging**
