### PR TITLE
added README.rst to REST API Example

### PR DESCRIPTION
**Pull request by jimthompson5802**
This provides instructions on how to run the sample

### CODE REVIEW

**Comment by mateiz** [comment]
This is a good idea; just rerunning tests but I don't think this could have affected them.

**Comment by jimthompson5802** [comment]
@mateiz Thank you for the comment.  

I'm not sure what is meant by 

> ...rerunning tests but I don't think this could have affected them.

Is there something else I need to do to bring this to closure?

**Comment by mateiz** [comment]
Nope, I just wanted to rerun the automated tests.

**Comment by jimthompson5802** [comment]
@mateiz  No problem.  Glad to be of help.

**Pull request merged**
