### PR TITLE
Change plotly to use scattergl

### PR DESCRIPTION
**Pull request by mjlbach**
## What changes are proposed in this pull request?

Switching scatter to scattergl uses plotly's gl backend, which is substantially faster for plots > 1000 points. The penalty is a (very) mild aesthetic impact in the rendering of the lines.

## How is this patch tested?
Tested locally with development server

### Is this a user-facing change?
Yes, it will affect the mlflow ui
- [ ] No. You can skip the rest of this section.
- [x] Yes. Give a description of this change to be included in the release notes for MLflow users.

MLflow metrics UI plots now scale to rendering thousands of points

### What component(s) does this PR affect?

- [x] UI
- [ ] CLI
- [ ] API
- [ ] REST-API
- [ ] Examples
- [ ] Docs
- [ ] Tracking
- [ ] Projects
- [ ] Artifacts
- [ ] Models
- [ ] Scoring
- [ ] Serving
- [ ] R
- [ ] Java
- [ ] Python

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by aarondav** [comment]
Thanks for the PR and sorry for the delay in review. I rebased the PR and tested it out locally. The result of this PR is that the plots look a little fuzzier, but the performance in terms of initial load is a lot better when there are thousands of points.

For 6 thousand runs, the previous code basically freezes for about 10 seconds before I can interact with the plot, while the new one is usable within about 1 second.

New:

image

Old:

image

I think the UI difference is small enough that it's a good change -- but maybe if @gioa or @Zangr have other opinions?

**Comment by mjlbach** [comment]
Thanks for posting the screenshots and handling the rebase!

**Review by aarondav — APPROVED** [review]

**Comment by gioa** [comment]
Thanks for the performance improvement! I prefer smooth interactions and agree it is a good change.

**Comment by aarondav** [comment]
Merged - thanks @mjlbach!

**Pull request merged**
