### PR TITLE
Fix Cron Job Failure by Removing MLflow requirement from example conda.yaml

### PR DESCRIPTION
**Pull request by zhidongqu-db**
## What changes are proposed in this pull request?

Fix Cron Job Failure by Removing MLflow requirement from example conda.yaml

### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [x] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Review by dbczumar — APPROVED** [review]
LGTM! Let's get input from @juntai-zheng and @harupy before merging.

**Review by juntai-zheng — APPROVED** [review]
LGTM. Should we be running examples tests on all future PRs to avoid things like this, or are the example tests still too bulky for small fixes like this? I'm leaning towards still excluding examples tests, but would like to hear from you guys.

**Comment by dbczumar** [comment]
I think example tests are too bulky, and the nightly cadence seems to have served its purpose in this case (we were ultimately alerted to an issue that was not pressing enough to have prevented the original PR from being merged). Thanks Juntai!

**Comment by jdlesage** [comment]
Hello. I see you reverted this PR. I am not sure to understand what was the problem at the beginning. But, IMO, currently we run the tests using the latest version of mlflow published on pypi. That's an issue for me : detection of problems only after a release of mlflow + difficulty to change the API of mlflow (should be compatible with the version currently on pypi)
Instead of removing mlflow from requirements, did you consider to use the `editable mode` https://pip.pypa.io/en/stable/reference/pip_install/#editable-installs of pypi to be sure to install in tests the version linked to the commit ?

**Comment by harupy** [comment]
@jdlesage Thanks for the comment! https://github.com/mlflow/mlflow/pull/3096 fixed this issue by installing the dev version instead of latest version on pypi.

**Pull request merged**
