### PR TITLE
Fix order of features

### PR DESCRIPTION
**Pull request by tobycheese**
In curl command, order of features is wrong. I left the feature values untouched, mazbe the numbers don't make sense anymore but the example runs now. In the swagger example below, feature order was already correct.

Signed-off-by: tobycheese <tobycheese@users.noreply.github.com>

## Related Issues/PRs

 #xxx

## What changes are proposed in this pull request?

(Please fill in changes proposed in this fix)

## How is this patch tested?

- [ ] Existing unit/integration tests
- [ ] New unit/integration tests
- [ ] Manual tests (describe details, including test results, below)

## Does this PR change the documentation?

- [ ] No. You can skip the rest of this section.
- [x] Yes. Make sure the changed pages / sections render correctly in the documentation preview.

### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [x] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Review by dbczumar — CHANGES_REQUESTED** [review]
@tobycheese Thank you for filing this PR. Can you provide more information about the error you encountered? Referencing https://github.com/mlflow/mlflow/blob/master/examples/sklearn_elasticnet_wine/wine-quality.csv, it appears that the current / preexisting value to column mapping is correct and that the proposed mapping is incorrect (from a dataset perspective).

**Comment by WeichenXu123** [comment]
I think the PR is just to make the POST request sending the columns with the same column order defined in https://github.com/mlflow/mlflow/blob/master/examples/sklearn_elasticnet_wine/wine-quality.csv

Shall we reorder the data values as well ? Or the data here is just randomly picked ?

**Comment by dbczumar** [comment]
> I think the PR is just to make the POST request sending the columns with the same column order defined in https://github.com/mlflow/mlflow/blob/master/examples/sklearn_elasticnet_wine/wine-quality.csv
> 
> Shall we reorder the data values as well ? Or the data here is just randomly picked ?

Ah, I see! Thanks for clarifying. Can we reorder the data values?

**Comment by tobycheese** [comment]
I have littgle knowledge of what these values mean, but at least pH seems to make more sense after reordering:  pH of 0.39 is probably not something anyone would enjoy drinking, 3.33 seems more appropriate. So, reordering done.

**Review by dbczumar — APPROVED** [review]
Thanks @tobycheese! LGTM!

**Review by WeichenXu123 — APPROVED** [review]

**Pull request merged**
