### PR TITLE
Fix transformers test

### PR DESCRIPTION
**Pull request by serena-ruan**
<details><summary>&#x1F6E0 DevTools &#x1F6E0</summary>
<p>

[Open in GitHub Codespaces](https://codespaces.new/serena-ruan/mlflow/pull/13219?quickstart=1)

#### Install mlflow from this PR

```
pip install git+https://github.com/mlflow/mlflow.git@refs/pull/13219/merge
```

#### Checkout with GitHub CLI

```
gh pr checkout 13219
```

</p>
</details>

### Related Issues/PRs

 #xxx

### What changes are proposed in this pull request?
setfit>=1.1.0 introduces dependency to transformers (e.g. https://github.com/huggingface/setfit/blob/146c7c9dacdc7dca678b2fffff8ddeb79dd762c2/src/setfit/trainer.py#L569), ~so now if we turn on autologging and train a SetFitTrainer, it triggers transformers autologging and produces runs.~

Update: The extra run is introduced by MLflowCallback that's included as the [default callback](https://github.com/huggingface/transformers/blob/11c27dd331151e7d2ac20016cce11d9d7c4b1756/src/transformers/trainer.py#L596), so no matter autologging is on or off, it always produces extra run.
The fix for the test is to remove the callback from the SetfitTrainer.
While this is only an issue for setfit>=1.1.0 because in 1.1.0 setfit trainer introduces [BCSentenceTransformersTrainer](https://github.com/huggingface/setfit/blob/146c7c9dacdc7dca678b2fffff8ddeb79dd762c2/src/setfit/trainer.py#L37) which internally uses transformers trainer directly.

### How is this PR tested?

- [x] Existing unit/integration tests
- [ ] New unit/integration tests
- [ ] Manual tests

### Does this PR require documentation update?

- [ ] No. You can skip the rest of this section.
- [ ] Yes. I've updated:
  - [ ] Examples
  - [ ] API references
  - [ ] Instructions

#### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

#### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>

#### How should the PR be classified in the release notes? Choose one:

- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

#### Should this PR be included in the next patch release?

`Yes` should be selected for bug fixes, documentation updates, and other small changes. `No` should be selected for new features and larger changes. If you're unsure about the release classification of this PR, leave this unchecked to let the maintainers decide.

<details>
<summary>What is a minor/patch release?</summary>

- Minor release: a release that increments the second part of the version number (e.g., 1.2.0 -> 1.3.0).
  Bug fixes, doc updates and new features usually go into minor releases.
- Patch release: a release that increments the third part of the version number (e.g., 1.2.0 -> 1.2.1).
  Bug fixes and doc updates usually go into patch releases.

</details>

- [ ] Yes (this PR will be cherry-picked and included in the next patch release)
- [x] No (this PR will be included in the next minor release)

### CODE REVIEW

**Review by B-Step62 — APPROVED** [review]
LGTM. Just to confirm, setfit creates a run because transformers automatically uses MLflow logger internally - so it cannot be disabled by `mlflow.transfomers.autolog(disable=False)`?

**Comment by serena-ruan** [comment]
> LGTM. Just to confirm, setfit creates a run because transformers automatically uses MLflow logger internally - so it cannot be disabled by `mlflow.transfomers.autolog(disable=False)`?

When mlflow.autolog() is turned on, it automatically includes `mlflow.transformers.autolog()`, and now setfitTrainer.train invokes transformers.train, so autologging produces run. It can be disabled if we disable transformers autolog.

**Comment by B-Step62** [comment]
> When mlflow.autolog() is turned on, it automatically includes mlflow.transformers.autolog(), and now setfitTrainer.train invokes transformers.train, so autologging produces run. It can be disabled if we disable transformers autolog.

Can we verify this and add test case for this? I thought `mlflow.transformers.autolog()` only disables autologging other submodules invoked by transformers.
https://github.com/mlflow/mlflow/blob/master/mlflow/transformers/__init__.py#L2912-L2914

**Comment by serena-ruan** [comment]
> > When mlflow.autolog() is turned on, it automatically includes mlflow.transformers.autolog(), and now setfitTrainer.train invokes transformers.train, so autologging produces run. It can be disabled if we disable transformers autolog.
> 
> Can we verify this and add test case for it? I thought `mlflow.transformers.autolog()` only disables autologging for other flavors that may be invoked by transformers. https://github.com/mlflow/mlflow/blob/master/mlflow/transformers/__init__.py#L2912-L2914

See https://github.com/mlflow/mlflow/blob/master/mlflow/tracking/fluent.py#L2328 setfit uses `mlflow.transformers.autolog`, there's no other flavors involved here. It's just before setfit 1.1.0, the internal implementation of setfit doesn't use transformers, so even with this line there's no autologging actually enabled.

**Comment by B-Step62** [comment]
@serena-ruan What I mean is that `mlflow.transformer.autolog()` patches the transformer's trainers `.train()` method to **disable other flavors autologging**. Since we set `manage_run` to `False` in the patching function, calling `.train()` should not create an MLflow run automatically?

**Comment by serena-ruan** [comment]
> @serena-ruan What I mean is that `mlflow.transformer.autolog()` patches the transformer's trainers `.train()` method for **disabling other flavors autologging** ([code](https://github.com/mlflow/mlflow/blob/master/mlflow/transformers/__init__.py#L2912-L2914)). Since we set `manage_run` to `False` in the patching function, calling `.train()` should not create an MLflow run automatically. Therefore, I was wondering where the auto-created run comes from, and how users can disable it.

Ahhh I see, just noticed we patch setfit inside transformers to avoid the run creation. Let me investigate further! Thanks!

**Review by BenWilson2 — APPROVED** [review]
LGTM

**Pull request merged**
