### PR TITLE
Model creation timestamp for log model in R

### PR DESCRIPTION
**Pull request by singankit**
## What changes are proposed in this pull request?

Model creation timestamp for log model in R is formatted as in Python API

## How is this patch tested?

(Details)

## Does this PR change the documentation?

- [X] No. You can skip the rest of this section.
- [ ] Yes. Make sure the changed pages / sections render correctly by following the steps below.

1. Check the status of the `ci/circleci: build_doc` check. If it's successful, proceed to the
   next step, otherwise fix it.
2. Click `Details` on the right to open the job page of CircleCI.
3. Click the `Artifacts` tab.
4. Click `docs/build/html/index.html`.
5. Find the changed pages / sections and make sure they render correctly.

### Is this a user-facing change?

- [X] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [X] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>
### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [X] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by singankit** [comment]
@lorenzwalthert The following [PR](https://github.com/mlflow/mlflow/pull/5215) got closed as I deleted and re-created the branch by mistake. I rebase for default branch. For the changes proposed on Python side, I can have a separate PR for it.

**Comment by lorenzwalthert** [comment]
@dbczumar can you trigger CI again here as the old or was closed by mistake? 

Also, what do you thinks about my suggestions for the Python API? 

@singankit lets wait with the Python suggestions until @dbczumar or other people give their ok.

**Review by lorenzwalthert — APPROVED** [review]

**Comment by lorenzwalthert** [comment]
@dbczumar this is ready to merge, all tests pass and I approved the changes, but can't merge. 

I think my other ideas for the Python API related to it are best adressed in a separate issue or PR.

**Comment by dbczumar** [comment]
Apologies for the delay, folks. Thank you for your contribution, @singankit , and thank you for reviewing, @lorenzwalthert . Feel free to file a separate issue or PR for the Python API changes & we can discuss.

**Review by dbczumar — APPROVED** [review]
LGTM :D

**Comment by singankit** [comment]
Thanks @lorenzwalthert and @dbczumar for the support.

**Pull request merged**
