### PR TITLE
Update json response style

### PR DESCRIPTION
**Pull request by nojaf**
<details><summary>&#x1F6E0 DevTools &#x1F6E0</summary>
<p>

[Open in GitHub Codespaces](https://codespaces.new/nojaf/mlflow/pull/12553?quickstart=1)

#### Install mlflow from this PR

```
pip install git+https://github.com/mlflow/mlflow.git@refs/pull/12553/merge
```

#### Checkout with GitHub CLI

```
gh pr checkout 12553
```

</p>
</details>

### Related Issues/PRs

This is related to the port of the tracking server to Go.
And is a cut-out from https://github.com/jgiannuzzi/mlflow/pull/3.

### What changes are proposed in this pull request?

Currently, the json produced by `f"{value}` is quite tied to Python.

Example:

```
POST http://localhost:5000/api/2.0/mlflow/runs/log-batch
Content-Type: application/json

{
    "run_id": "odcppTsGTMkHeDcqfZOYDMZSf",
    "metrics": [
        {
            "key": "m2",
            "value": 4,
            "step":1
        }
    ]
}
```

returns

```
HTTP/1.1 400 BAD REQUEST
Server: gunicorn
Date: Tue, 02 Jul 2024 12:00:40 GMT
Connection: close
Content-Type: application/json
Content-Length: 238

{
  "error_code": "INVALID_PARAMETER_VALUE",
  "message": "Invalid value [{'key': 'm2', 'value': 4, 'step': 1}] for parameter 'metrics' supplied. Hint: Value was of type 'list'. See the API docs for more information about request parameters."
}
```

After this PR:

```
HTTP/1.1 400 BAD REQUEST
Server: gunicorn
Date: Tue, 02 Jul 2024 12:05:50 GMT
Connection: close
Content-Type: application/json
Content-Length: 241

{
  "error_code": "INVALID_PARAMETER_VALUE",
  "message": "Invalid value [{\"key\":\"m2\",\"step\":1,\"value\":4}] for parameter 'metrics' supplied. Hint: Value was of type 'list'. See the API docs for more information about request parameters."
}
```

Notice the usage of `"` instead of `'`. No spaces around `,`, `}` and `]`.

### How is this PR tested?

- [x] Existing unit/integration tests
- [ ] New unit/integration tests
- [ ] Manual tests

### Does this PR require documentation update?

- [x] No. You can skip the rest of this section.
- [ ] Yes. I've updated:
  - [ ] Examples
  - [ ] API references
  - [ ] Instructions

#### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

Hmm, maybe? I depends I guess. The response message are ever so slightly different because of this change.

#### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [x] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>

#### How should the PR be classified in the release notes? Choose one:

It depends, you could go with `rn/none` or `rn/breaking-change` depending on the weight you give this.

- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

#### Should this PR be included in the next patch release?

`Yes` should be selected for bug fixes, documentation updates, and other small changes. `No` should be selected for new features and larger changes. If you're unsure about the release classification of this PR, leave this unchecked to let the maintainers decide.

<details>
<summary>What is a minor/patch release?</summary>

- Minor release: a release that increments the second part of the version number (e.g., 1.2.0 -> 1.3.0).
  Bug fixes, doc updates and new features usually go into minor releases.
- Patch release: a release that increments the third part of the version number (e.g., 1.2.0 -> 1.2.1).
  Bug fixes and doc updates usually go into patch releases.

</details>

- [x] Yes (this PR will be cherry-picked and included in the next patch release)
- [ ] No (this PR will be included in the next minor release)

### CODE REVIEW

**Comment by BenWilson2** [comment]
@dbczumar are there impacts to the managed side (tests or dependent parsing functionality) to making these errors JSON standard format?

**Review by WeichenXu123 — APPROVED** [review]
LGTM!

**Comment by nojaf** [comment]
Thanks, could someone retry `MLflow tests / database (pull_request)`, I'm not quite sure if anything is actually failing there. Job got stuck I think.

**Review by BenWilson2 — APPROVED** [review]
LGTM!

**Pull request merged**
