### PR TITLE
Fixing log_model() not automatically starting run

### PR DESCRIPTION
**Pull request by juntai-zheng**
Currently, if a user does not call `mlflow.tracking.start_run()` before logging a `tf` or `sklearn` model, an error will be thrown since logging requires an active run to exist. This happens when users call a script via Python CLI (i.e. `python script.py`, works fine when called via `mlflow run`).

This fix makes it such that `log_model()` for both model types either gets the active run or starts one if one doesn't exist. I've also updated the tests to test for this.

### CODE REVIEW

**Review by smurching — COMMENTED** [review]
Leaving a few comments, thanks @juntai-zheng :)

**Comment by juntai-zheng** [comment]
Should I also fix `spark.py` and `test_spark_model_export.py` for this issue? It looks like they might run into the same issue as tensorflow sklearn logging.

**Comment by smurching** [comment]
@juntai-zheng good question, yeah I'd go ahead and do that in this PR.

**Review by smurching — APPROVED** [review]
LGTM thanks @juntai-zheng!

**Pull request merged**
