### PR TITLE
Fix #5856 IsADirectoryError while selecting Azure artifact in the UI

### LINKED ISSUE #5856: [BUG] IsADirectoryError while selecting Azure artifact in the UI
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### System information

- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian GNU/Linux 11 (bullseye)
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 1.25.1
- **Python version**: 3.7
- **npm version, if running the dev UI**:

### Describe the problem

We deploy mlflow-server within a docker image on a kubernetes cluster on azure. As artifact store is an azure blob storage configured. MLFlow server is configured as artifact proxy. When logging a new model from a jupyter notebook on the client side, the model gets written correcty to the artifact store. We are also able to download the model again on the client side with the python api. As soon as we want to display the artifacts on the UI, it will not show up as expected. 
grafik

On the mlflow server we see the following exception:

`[2022-05-12 07:10:38 +0000] [20] [DEBUG] GET /get-artifact
2022/05/12 07:10:39 ERROR mlflow.server: Exception on /get-artifact [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/mlflow/server/__init__.py", line 53, in serve_artifacts
    return get_artifact_handler()
  File "/usr/local/lib/python3.7/site-packages/mlflow/server/handlers.py", line 327, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/mlflow/server/handlers.py", line 409, in get_artifact_handler
    return _send_artifact(artifact_repo, artifact_path)
  File "/usr/local/lib/python3.7/site-packages/mlflow/server/handlers.py", line 318, in _send_artifact
    return send_file(filename, mimetype="text/plain", as_attachment=True)
  File "/usr/local/lib/python3.7/site-packages/flask/helpers.py", line 623, in send_file
    cache_timeout=cache_timeout,
  File "/usr/local/lib/python3.7/site-packages/werkzeug/utils.py", line 491, in send_file
    file = open(path, "rb")  # type: ignore
IsADirectoryError: [Errno 21] Is a directory: '/tmp/tmpwsvta9ik/9/45c58ecb75b8420a8b58375015a20ea4/artifacts/sklearn-model/requirements.txt'`

When I then try to access the above file, I see that it actually is a directory and not a file:
grafik

I think this issue is related to the following to issues:
https://github.com/mlflow/mlflow/issues/3154
https://github.com/mlflow/mlflow/issues/2991

Unfortunately I cannot debug the mlflow server in an easy way to print something.

### Tracking information

mlflow server \
    --backend-store-uri postgresql://connection_string \
    --artifacts-destination wasbs://container_name@storage_account.blob.core.windows.net/ \
    --serve-artifacts \
    --host 0.0.0.0 \
    --port 5000 \
    --gunicorn-opts "--log-level debug"

### Code to reproduce issue

It is a mlflow server UI problem.

### Other info / logs

_No response_

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [X] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

### PR DESCRIPTION
**Pull request by nerdinand**
Signed-off-by: Ferdinand Niedermann <ferdinand.niedermann@sbb.ch>

## Related Issues/PRs

Fixes #5856

## What changes are proposed in this pull request?

Just a bug fix for the Azure integration. The bug led to artifacts not being shown in the UI.

## How is this patch tested?

- [ ] I have written tests (not required for typo or doc fix) and confirmed the proposed feature/bug-fix/change works.

## Does this PR change the documentation?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Make sure the changed pages / sections render correctly by following the steps below.

### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [x] Yes. Give a description of this change to be included in the release notes for MLflow users.

### What component(s), interfaces, languages, and integrations does this PR affect?
Components
- [x] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [x] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>
### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [x] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by nerdinand** [comment]
> @nerdinand Thanks for the contribution! The DCO check failed. Please sign off your commits by following the instructions here: https://github.com/mlflow/mlflow/runs/7318068069. See https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#sign-your-work for more details.

Fixed now.

**Comment by nerdinand** [comment]
Related question: We'd like to test this fix by building and deploying a docker container. When pip-installing the commit directly, the mlflow-Installation does not run as expected: "Unable to display MLflow UI - landing page (index.html) not found."
How can we build the pip package properly, so it will act as if downloaded from pypi?

**Comment by harupy** [comment]
> Related question: We'd like to test this fix by building and deploying a docker container. When pip-installing the commit directly, the mlflow-Installation does not run as expected: "Unable to display MLflow UI - landing page (index.html) not found." How can we build the pip package properly, so it will act as if downloaded from pypi?

To build assets for MLflow UI, you need to run `yarn build` in `mlflow/server/js`.

**Comment by nerdinand** [comment]
@harupy Thanks, that worked after a lot of fiddling... The JS ecosystem is a fickle one....

The fix in this PR has been rolled out and tested in one of our internal MLflow installations. Everything seems to work well. Hopefully this PR can be moved forward swiftly... ;)

**Comment by nerdinand** [comment]
The failure https://github.com/mlflow/mlflow/runs/7339545119?check_suite_focus=true seems completely unrelated to my change. Is there a way of fixing that?

**Comment by harupy** [comment]
> The failure https://github.com/mlflow/mlflow/runs/7339545119?check_suite_focus=true seems completely unrelated to my change. Is there a way of fixing that?

#6241 will fix it.

**Review by harupy — APPROVED** [review]
LGTM!

**Pull request merged**
