### PR TITLE
Allows empty string as parameter value (fixes #888)

### LINKED ISSUE #888: Tracking UI cannot show experiment if a run contains an empty parameter value
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: mlflow server ubuntu 16.04, client Win 7
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 0.8.2
- **Python version**: mlflow server 3.5.2, client 3.5.4
- **npm version (if running the dev UI):
- **Exact command to reproduce**:

### Describe the problem
From my client python program, I attempt to log a parameter whose value is the empty string. (This was not intentional, but it happened.) The client eventually times out with `failed to return code 200 after 3 tries` (see traceback below). This is probably expected behavior.

The problem is that then viewing the experiment for the run is not possible. The server log shows `Param 'sys.env.CUDA_VISIBLE_DEVICES' is malformed. No data found` (see traceback below). Upon inspecting the filesystem, there is an empty file for this parameter. So there seems to be a mismatch between the client API validation and the UI validation. Only the one experiment is affected; other experiments are still viewable. Removing the empty parameter file on the server restores expected behavior.

### Source code / logs

*Client program*
Simple invocation of tracking API:
```
mlflow.log_param('sys.env.CUDA_VISIBLE_DEVICES', '')
```

```
Traceback (most recent call last):
...
    mlflow.log_param(key, value)
  File "C:\Users\dstine\.virtualenvs\labs_nlp_topic_model-C2Cdqh84\lib\site-packages\mlflow\tracking\fluent.py", line 179, in log_param
    MlflowClient().log_param(run_id, key, value)
  File "C:\Users\dstine\.virtualenvs\labs_nlp_topic_model-C2Cdqh84\lib\site-packages\mlflow\tracking\client.py", line 144, in log_param
    self.store.log_param(run_id, param)
  File "C:\Users\dstine\.virtualenvs\labs_nlp_topic_model-C2Cdqh84\lib\site-packages\mlflow\store\rest_store.py", line 173, in log_param
    self._call_endpoint(LogParam, req_body)
  File "C:\Users\dstine\.virtualenvs\labs_nlp_topic_model-C2Cdqh84\lib\site-packages\mlflow\store\rest_store.py", line 58, in _call_endpoint
    host_creds=host_creds, endpoint=endpoint, method=method, json=json_body)
  File "C:\Users\dstine\.virtualenvs\labs_nlp_topic_model-C2Cdqh84\lib\site-packages\mlflow\utils\rest_utils.py", line 73, in http_request_safe
    response = http_request(host_creds=host_creds, endpoint=endpoint, **kwargs)
  File "C:\Users\dstine\.virtualenvs\labs_nlp_topic_model-C2Cdqh84\lib\site-packages\mlflow\utils\rest_utils.py", line 58, in http_request
    (url, retries))
mlflow.exceptions.MlflowException: API request to http://10.53.36.24:5000/api/2.0/preview/mlflow/runs/log-parameter failed to return code 200 after 3 tries
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Users\dstine\.virtualenvs\labs_nlp_topic_model-C2Cdqh84\lib\site-packages\mlflow\tracking\fluent.py", line 157, in end_run
    MlflowClient().set_terminated(_active_run_stack[-1].info.run_uuid, status)
  File "C:\Users\dstine\.virtualenvs\labs_nlp_topic_model-C2Cdqh84\lib\site-packages\mlflow\tracking\client.py", line 213, in set_terminated
    end_time=end_time)
  File "C:\Users\dstine\.virtualenvs\labs_nlp_topic_model-C2Cdqh84\lib\site-packages\mlflow\store\rest_store.py", line 130, in update_run_info
    response_proto = self._call_endpoint(UpdateRun, req_body)
  File "C:\Users\dstine\.virtualenvs\labs_nlp_topic_model-C2Cdqh84\lib\site-packages\mlflow\store\rest_store.py", line 58, in _call_endpoint
    host_creds=host_creds, endpoint=endpoint, method=method, json=json_body)
  File "C:\Users\dstine\.virtualenvs\labs_nlp_topic_model-C2Cdqh84\lib\site-packages\mlflow\utils\rest_utils.py", line 73, in http_request_safe
    response = http_request(host_creds=host_creds, endpoint=endpoint, **kwargs)
  File "C:\Users\dstine\.virtualenvs\labs_nlp_topic_model-C2Cdqh84\lib\site-packages\mlflow\utils\rest_utils.py", line 58, in http_request
    (url, retries))
mlflow.exceptions.MlflowException: API request to http://10.53.36.24:5000/api/2.0/preview/mlflow/runs/update failed to return code 200 after 3 tries
```

*Server log*
```
[2019-02-10 05:07:24,010] ERROR in app: Exception on /ajax-api/2.0/preview/mlflow/runs/search [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/mlflow-exp-KEZxtoN-/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/share/virtualenvs/mlflow-exp-KEZxtoN-/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/share/virtualenvs/mlflow-exp-KEZxtoN-/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/share/virtualenvs/mlflow-exp-KEZxtoN-/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/ubuntu/.local/share/virtualenvs/mlflow-exp-KEZxtoN-/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/share/virtualenvs/mlflow-exp-KEZxtoN-/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/.local/share/virtualenvs/mlflow-exp-KEZxtoN-/lib/python3.5/site-packages/mlflow/server/handlers.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/.local/share/virtualenvs/mlflow-exp-KEZxtoN-/lib/python3.5/site-packages/mlflow/server/handlers.py", line 272, in _search_runs
    run_view_type)
  File "/home/ubuntu/.local/share/virtualenvs/mlflow-exp-KEZxtoN-/lib/python3.5/site-packages/mlflow/store/file_store.py", line 519, in search_runs
    runs.extend(self.get_run(r.run_uuid) for r in run_infos)
  File "/home/ubuntu/.local/share/virtualenvs/mlflow-exp-KEZxtoN-/lib/python3.5/site-packages/mlflow/store/file_store.py", line 519, in <genexpr>
    runs.extend(self.get_run(r.run_uuid) for r in run_infos)
  File "/home/ubuntu/.local/share/virtualenvs/mlflow-exp-KEZxtoN-/lib/python3.5/site-packages/mlflow/store/file_store.py", line 355, in get_run
    params = self.get_all_params(run_uuid)
  File "/home/ubuntu/.local/share/virtualenvs/mlflow-exp-KEZxtoN-/lib/python3.5/site-packages/mlflow/store/file_store.py", line 474, in get_all_params
    params.append(self._get_param_from_file(parent_path, param_file))
  File "/home/ubuntu/.local/share/virtualenvs/mlflow-exp-KEZxtoN-/lib/python3.5/site-packages/mlflow/store/file_store.py", line 449, in _get_param_from_file
    raise Exception("Param '%s' is malformed. No data found." % param_name)
Exception: Param 'sys.env.CUDA_VISIBLE_DEVICES' is malformed. No data found.
```

### PR DESCRIPTION
**Pull request by hanyucui**

### CODE REVIEW

**Review by smurching — COMMENTED** [review]
@hanyucui thanks for the PR, would you mind adding a test for the new behavior in `tests/store/test_file_store.py` and `tests/store/test_sqlalchemy_store.py` (i.e. that an empty param can be logged & read back)?

**Comment by hanyucui** [comment]
@smurching  Sure, will do.

**Comment by mateiz** [comment]
Looks like this is failing lint:
```
tests/store/test_file_store.py:337:1: W293 blank line contains whitespace
tests/store/test_sqlalchemy_store.py:487:1: W293 blank line contains whitespace
The command "./lint.sh" exited with 1.
```

**Comment by hanyucui** [comment]
Thanks! Realized my VIM wasn't set up on this laptop.

**Comment by hanyucui** [comment]
@smurching This test fails for Python 3.6:
`tests/spark/test_spark_model_export.py::test_model_deployment FAILED`

It passed before the lint fix and seems irrelevant. Is there a way to rerun the tests?

**Comment by mateiz** [comment]
I just restarted that build.

**Comment by mateiz** [comment]
Thanks; looks like it was a flaky test.

**Pull request merged**
