### PR TITLE
Use `importlib` instead of `imp`

### PR DESCRIPTION
**Pull request by keigohtr**
## What changes are proposed in this pull request?

**Merge this after https://github.com/mlflow/mlflow/pull/2534 is merged.**
Use `importlib` instead of `imp` since `imp` is deprecated.

## How is this patch tested?

N.A.

### Is this a user-facing change?

- [x] No. You can skip the rest of this section.

## Related Issue
https://github.com/mlflow/mlflow/issues/2642

### CODE REVIEW

**Comment by harupy** [comment]
FYI https://github.com/mlflow/mlflow/pull/2534

**Comment by keigohtr** [comment]
@harupy Thanks :)

**Comment by keigohtr** [comment]
I have reverted the change which for removing python2.7 circleci job.
Could you check this after merging #2534 ?

**Comment by keigohtr** [comment]
Could you review and retest this please? @harupy

**Comment by smurching** [comment]
@keigohtr thanks for the PR, you can retrigger tests by merging master into your PR branch & pushing the merge commit back to your PR branch (Travis triggers tests on each push to a PR branch). This will also have the advantage of not running Python 2 tests, which have since been disabled in master - thanks!

**Comment by keigohtr** [comment]
@smurching 
Thank you! I have rebased to the latest master branch!

**Comment by keigohtr** [comment]
🤔 
According to the error messages, "spark" related tests were failed. But I did not change anything around it.

```
E               PermissionError: [Errno 13] Permission denied: '/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/pyspark/./bin/spark-submit'
```

**Comment by keigohtr** [comment]
Permission issue was solved by #2639

**Review by mparkhe — APPROVED** [review]
Thank you

**Pull request merged**
