### PR TITLE
Replace GPT-3.5-turbo with GPT-4o-mini

### PR DESCRIPTION
**Pull request by Acksout**
<details><summary>&#x1F6E0 DevTools &#x1F6E0</summary>
<p>

[Open in GitHub Codespaces](https://codespaces.new/Acksout/mlflow/pull/12740?quickstart=1)

#### Install mlflow from this PR

```
pip install git+https://github.com/mlflow/mlflow.git@refs/pull/12740/merge
```

#### Checkout with GitHub CLI

```
gh pr checkout 12740
```

</p>
</details>

This PR addresses #12724

This commit completes the migration from GPT-3.5-turbo to GPT-4o-mini across the codebase. However, a few references to the old model still remain:
gpt-3.5-turbo-xxxx
GPT-35-Turbo
GPT-3.5-Instruct
GPT 3.5
These instances have been left intentionally. 

Changes have been made in the following directories:
docs/
examples/

Summary:
OpenAI recently released the GPT-4o mini model. It is cheaper and more performant than GPT-3.5 Turbo, and they are planning to deprecate the GPT-3.5 Turbo in favor of the new one.

We still have many references to the old model in the documentation, examples, and tutorials. This PR updates those references to the new gpt-4o-mini model.

### What changes are proposed in this pull request?

- Update references from gpt-3.5-turbo to gpt-4o-mini in documentation
- Update examples and tutorials to use the new gpt-4o-mini model
- Maintain specific references to GPT-3.5 variants where necessary for backwards compatibility or historical context

### How is this PR tested?

- [ ] Existing unit/integration tests
- [ ] New unit/integration tests
- [x] Manual tests (manual review of updated documentation and examples)

### Does this PR require documentation update?

- [ ] No. You can skip the rest of this section.
- [x] Yes. I've updated:
  - [x] Examples
  - [x] API references
  - [x] Instructions

#### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [x] Yes. Description: Update documentation and examples to reflect the use of GPT-4o-mini instead of GPT-3.5-turbo.

#### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [x] `area/docs`: MLflow documentation pages
- [x] `area/examples`: Example code

#### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/none`
- [ ] `rn/breaking-change`
- [ ] `rn/feature`
- [ ] `rn/bug-fix`
- [x] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

#### Should this PR be included in the next patch release?

- [x] Yes (this PR will be cherry-picked and included in the next patch release)
- [ ] No (this PR will be included in the next minor release)

### CODE REVIEW

**Review by B-Step62 — APPROVED** [review]
Thanks @Acksout for the quick contribution! I think the references outside `docs/` and `examples/` can be also replaced (mainly docstring). Would you mind working on them as a follow-up?

**Comment by Acksout** [comment]
Sure. Should references other than "gpt-3.5-turbo" be removed too. Strings such as "gpt-3.5-turbo-xxxx, GPT-35-Turbo, GPT-3.5-Instruct, GPT 3.5" are present in the codebase. @B-Step62

**Comment by B-Step62** [comment]
@Acksout Thank you so much!

> Should references other than "gpt-3.5-turbo" be removed too. Strings such as "gpt-3.5-turbo-xxxx, GPT-35-Turbo, GPT-3.5-Instruct, GPT 3.5" are present in the codebase. 

I think we are good to replace them all, as long as them conform to the same API spec. We will also take a close look at each case in the PR🙂

**Comment by Acksout** [comment]
Made a new PR https://github.com/mlflow/mlflow/pull/12746
Thanks for reviewing. @B-Step62

**Pull request merged**
