### PR TITLE
Add SVG icon and logos

### PR DESCRIPTION
**Pull request by sisp**
I've added the MLflow icon and logos in SVG format to the repo. Before, only a link to a ZIP file existed in an [issue](https://github.com/mlflow/mlflow/issues/1853#issuecomment-557735692) which is a non-obvious location to search for these assets. I think they should be properly versioned and in case they're ever changed those changes are tracked via Git as well.

### CODE REVIEW

**Comment by BenWilson2** [comment]
Hi @sisp thank you for the submission. The CI check that is failing for the docs build is completely unrelated to your PR. Could you submit another push after merging master into your branch so that the circleci check will pass? I'll trigger the remainder of CI checks after you submit a merge push.

**Comment by sisp** [comment]
@BenWilson2 Done.

**Comment by sisp** [comment]
The failing CI job reports:

> Error: No release note category label is applied to this PR. Please select a checkbox in the release note category section: https://github.com/mlflow/mlflow/pull/5529#user-content-release-note-category or manually apply a release note category label (e.g. 'rn/bug-fix') if you're a maintainer of this repository. If this job failed when a release note category label is already applied, please re-run it.

The link doesn't work though and I see no checkboxes for selecting a release category. Is there anything you can do?

**Review by harupy — APPROVED** [review]
LGTM!

**Pull request merged**
