### PR TITLE
Fixes #6028: Don't add /code subdirectories to sys.path

### LINKED ISSUE #6028: [BUG] `load_model()` adding code directories to system path that shouldn't be added to path
### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

1.26.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.02
- **Python version**: 3.8
- **yarn version, if running the dev UI**: N/A

## Overview

The main problem is that MLflow is adding _all directories_ under the `/code` directory to the system path, which is not what one would always expect to be the case. This is causing imports to break / collide in a way that doesn't otherwise happen when running the same code outside of MLflow. It seems to me that one normally expects the top-level modules to be on the system path i.e. that only `<model_directory>/code` should be on the path, and not everything underneath it.

## Minimum Reproducible Example

See attached file for MLflow that this can be reproduced with:
[mlflow-issue-test.zip](https://github.com/mlflow/mlflow/files/8836294/mlflow-issue-test.zip)

#### Model Structure
```
mlflow-issue-test
├── code
│   ├── dir_one
│   │   ├── entrypoint.py
│   │   └── __init__.py
│   └── dir_two
│       ├── redis.py
│       └── __init__.py
├── conda.yml
├── data
└── MLmodel

```

#### Problem Setup

I have two directories in this model, `dir_one` and `dir_two`. `dir_one/entrypoint.py` is the entrypoint to the model and is pointed to by the `MLmodel` entrypoint field. The problem is that this entrypoint is going to try to import a 3rd party dependency (in this case, `redis`) that has a name that collides with the name of a file inside of another directory, `code/dir_two`. 

Under normal operation this doesn't matter since `dir_two/redis.py` isn't on the system path - it can only be imported by doing `from dir_two import redis`. However, since MLflow adds *all* directories under `/code` to the system path, this import is now conflicting with the system import and is breaking inference for us. Specifically, [this code](https://github.com/mlflow/mlflow/blob/master/mlflow/utils/model_utils.py#L120) is the offending logic.

#### Example Code

`code/dir_one/entrypoint.py`: the entrypoint
```python
import mlflow
import pandas as pd

# This should import the system redis-py "redis"
# but it actually grabs `/code/dir_two/redis.py` because
# MLflow messes with the import paths
import redis

class _ModelWrapper(mlflow.pyfunc.PythonModel):
    def predict(self, input_df: pd.DataFrame) -> pd.DataFrame:
        # Toy predict example
        return input_df

def _load_pyfunc(data_path: str) -> _ModelWrapper:
    return _ModelWrapper()
```

`code/dir_two/redis.py`: the colliding file
```python
# This file should not be imported!

raise RuntimeError(f"code/dir_two/redis.py has been imported!")
```

`MLmodel`
```yaml
flavors:
  python_function:
    code: code
    data: data
    env: conda.yml
    loader_module: dir_one.entrypoint
model_uuid: 66a6a42db8444965b7dae6ce6163549d
utc_time_created: '2022-06-03 20:49:12.836282'
```

#### Running the Example

```
>>> mlflow.pyfunc.load_model("mlflow-issue-test")
2022/06/04 00:38:36 WARNING mlflow.pyfunc: The specified model does not have a specified Python version. It may be incompatible with the version of Python that is currently running: Python 3.8.0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.env/lib/python3.8/site-packages/mlflow/pyfunc/__init__.py", line 735, in load_model
    model_impl = importlib.import_module(conf[MAIN])._load_pyfunc(data_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/mlflow-issue-test/code/dir_one/entrypoint.py", line 7, in <module>
    import redis
  File "/tmp/mlflow-issue-test/code/dir_two/redis.py", line 4, in <module>
    raise RuntimeError(f"code/dir_two/redis.py has been imported!")
RuntimeError: code/dir_two/redis.py has been imported!
```

#### Example Breakdown

Notice that when the entrypoint code calls `import redis`, it ends up importing `code/dir_two/redis.py` instead of the system `redis` module that would be expected. It's not expected that all files under parallel directories are magically on the system path.

### Tracking information

_No response_

### Code to reproduce issue

See attached file for MLflow that this can be reproduced with:
[mlflow-issue-test.zip](https://github.com/mlflow/mlflow/files/8836294/mlflow-issue-test.zip)

Simple unzip the file as an MLflow model and then try to load the model

```bash
unzip mlflow-issue-test.zip -d mlflow-issue-test
python3
```

```python3
>>> import mlflow
>>> mlflow.pyfunc.load_model("mlflow-issue-test")
````

Produces the outputs showed in the next section

### Other info / logs

```python
>>> mlflow.pyfunc.load_model("mlflow-issue-test")
2022/06/04 00:38:36 WARNING mlflow.pyfunc: The specified model does not have a specified Python version. It may be incompatible with the version of Python that is currently running: Python 3.8.0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.env/lib/python3.8/site-packages/mlflow/pyfunc/__init__.py", line 735, in load_model
    model_impl = importlib.import_module(conf[MAIN])._load_pyfunc(data_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/mlflow-issue-test/code/dir_one/entrypoint.py", line 7, in <module>
    import redis
  File "/tmp/mlflow-issue-test/code/dir_two/redis.py", line 4, in <module>
    raise RuntimeError(f"code/dir_two/redis.py has been imported!")
RuntimeError: code/dir_two/redis.py has been imported!
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

### PR DESCRIPTION
**Pull request by jhallard**
## Related Issues/PRs

https://github.com/mlflow/mlflow/issues/6028

## What changes are proposed in this pull request?

MLflow was not only adding `<model>/code` to the PYTHONPATH, but also all of the directories underneath `<model>/code` which caused unexpected import conflict errors with built-ins and 3rd-party libraries.

This change makes it so that only `<model>/code` is placed on the system path, as users are expected to import from the top-level directories directly themselves.

More details, including minimal reproducible example, can be found in issue \#6028

## How is this patch tested?

- [x] Existing unit/integration tests
- [ ] New unit/integration tests
- [ ] Manual tests (describe details, including test results, below)

## Does this PR change the documentation?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Make sure the changed pages / sections render correctly in the documentation preview.

### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [x] Yes. Give a description of this change to be included in the release notes for MLflow users.

Users of the `pyfunc` flavor of MLflow models may have had to deal with odd import conflicts with built-in and 3rd-party libraries resulting from incorrect handling of the `sys.path`. This change alters the path configuration logic to no longer place top-level directories on the `sys.path`.

### What component(s), interfaces, languages, and integrations does this PR affect?
Components
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [x] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>
### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by jhallard** [comment]
cc @BenWilson2 @dbczumar finally got around to adding this simple change. I did some TDD - lead with the failing example and changed the code to fix it

**Comment by dbczumar** [comment]
> cc @BenWilson2 @dbczumar finally got around to adding this simple change. I did some TDD - lead with the failing example and changed the code to fix it

Fantastic! Running tests now! Thanks so much for your contribution :)

**Comment by jhallard** [comment]
Whoops, I can trivially fix the lint issues this evening and get this ready to merge.

**Review by dbczumar — APPROVED** [review]
LGTM! Thanks @jhallard !

**Comment by jhallard** [comment]
@dbczumar apologies, I'm having trouble getting black/linters to run locally correctly and when I push I re-need approval to run workflows

**Pull request merged**
