### PR TITLE
Activated Ruff rule: redundant-open-modes (UP015) 

### PR DESCRIPTION
**Pull request by EdAbati**
## Related Issues/PRs

Step towards #8997 

## What changes are proposed in this pull request?

I have activated the Ruff rule: activated redundant-open-modes (UP015) and applied to the source code.

## How is this patch tested?

- [x] Existing unit/integration tests
- [ ] New unit/integration tests
- [ ] Manual tests (describe details, including test results, below)

## Does this PR change the documentation?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Make sure the changed pages / sections render correctly in the documentation preview.

### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Review by harupy — APPROVED** [review]
LGTM!

**Comment by harupy** [comment]
@EdAbati Thanks for the PR! Can we also enable `UP011` and `UP012`?

- https://beta.ruff.rs/docs/rules/lru-cache-without-parameters/
- https://beta.ruff.rs/docs/rules/unnecessary-encode-utf8/

**Comment by harupy** [comment]
@EdAbati Before making enabling them, can we make the following change?

```diff
diff --git a/.github/workflows/master.yml b/.github/workflows/master.yml
index a40e51103..48ce83621 100644
--- a/.github/workflows/master.yml
+++ b/.github/workflows/master.yml
@@ -53,18 +53,18 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          # pylint is ridiculously slow. It takes ~15 minutes to run on all files.
+          # pylint is ridiculously slow. It takes ~3 minutes to run on all files.
           # To fail fast for faster iteration, first run pylint only on changed files,
           # then run it on all files in the next step.
           changed_files=$(python dev/list_changed_files.py --repository mlflow/mlflow --pr-num ${{ github.event.number }})
           pre-commit run --files $changed_files
-      - name: Run pre-commit (pylint)
+      - name: Run pre-commit (all files)
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           changed_files=$(python dev/list_changed_files.py --repository mlflow/mlflow --pr-num ${{ github.event.number }})
           if echo "$changed_files" | grep -q '\.py$'; then
-            pre-commit run --all-files pylint
+            pre-commit run --all-files
           fi
       - name: Update error messages
         if: always() && steps.run-pre-commit.outcome == 'failure'
```

We only run ruff on changed files, but should run it on all files. For example, we might have a python file that violates UP011. Ruff can't detect it unless we run ruff on it.

**Comment by EdAbati** [comment]
Of course! I'll do that in the next PR 🙂

**Comment by harupy** [comment]
Thanks! Let's fix this first, then enable the new rules :)

**Pull request merged**
