### PR TITLE
Added diff-view switch

### LINKED ISSUE #4819: [FR] Diff-only view for runs table on experiments page
Thank you for submitting a feature request. **Before proceeding, please review MLflow's [Issue Policy for feature requests](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md#feature-requests) and the [MLflow Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst)**.

**Please fill in this feature request template to ensure a timely and thorough response.**

## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [ ] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [X] No. I cannot contribute this feature at this time.

## Proposal Summary

To make it easier for users to identify relevant parameters, tags, and metrics that differ between runs, we propose introducing a "diff-only" toggle to the Runs table. When selected, the "diff-only" toggle removes all columns from the Runs table that have a shared value (or are undefined) across all runs.

## Motivation
- What is the use case for this feature? Many MLflow runs share the same value for a particular param / tag / metric. This is particularly common for runs generated by autologging. When runs have many params, tags, and metrics, it can be difficult to view and compare them in the Runs table on the MLflow Experiment UI page.
- Why is this use case valuable to support for MLflow users in general? A diff-only view will make it easier for users to explore / compare runs and identify optimal runs via the MLflow UI.
- Why is this use case valuable to support for your project(s) or organization? Many Databricks customers use the MLflow UI to compare runs and identify optimal runs / models.
- Why is it currently difficult to achieve this use case? Presently, users must manually identify columns that are irrelevant to a comparison and manually hide them from the table.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

### PR DESCRIPTION
**Pull request by marijncv**
Signed-off-by: Marijn Valk <marijncv@hotmail.com>

## What changes are proposed in this pull request?

Added a checkbox for switching between diff-only view and regular view. closes #4819 

## How is this patch tested?

Create a couple of runs with params, metrics and tag of which some are different accross runs and some which are the same across runs. Mark/unmark the checkbox and see the columns disappear for which the value across all the runs is the same

### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [x] Yes. Give a description of this change to be included in the release notes for MLflow users.

Added a checkbox that will filter out all columns for which every run has the same value

### What component(s), interfaces, languages, and integrations does this PR affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [x] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>
### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [x] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by harupy** [comment]
Thanks for the PR! It looks great!

https://user-images.githubusercontent.com/17039389/135788919-b8400965-bb90-4973-92e2-3f7c0854b1d6.mov

image


### Scritp to generate test data:

```python
import mlflow
import random


def random_float():
    return random.random()


def random_string():
    return random.choice(["a", "b", "c"])


for _ in range(100):
    with mlflow.start_run():
        mlflow.log_param("p1", 0)
        mlflow.log_param("p2", random_string())

        mlflow.log_metric("m1", 0)
        mlflow.log_metric("m2", random_float())

        mlflow.set_tag("t1", 0)
        mlflow.set_tag("t2", random_string())


```

**Comment by marijncv** [comment]
Removed the source column from the diff view (it will be always visible unless unchecked by the user). Also moved the `getCategorizedColumnsDiffView` function to `ExperimentViewUtil`

**Comment by dbczumar** [comment]
@marijncv Thanks a bunch for addressing comments from @harupy ; this is looking great! Before finalizing the PR, we've asked one of our UX designers for input about the placement and text associated with the toggle. We'll provide a design mock with this information in the next few days.

**Comment by marijncv** [comment]
@dbczumar sounds good, looking forward to the design mock!

**Comment by dbczumar** [comment]
> @dbczumar sounds good, looking forward to the design mock!

Hi @marijncv , apologies for the delay. Here is the mock:

diff_only_mock

Please ignore the different styling on the toggle. For consistency with the rest of the MLflow UI, we can keep using the existing toggle element from your PR. The only practical differences are the text next to the toggle and the text displayed on hover.

**Comment by marijncv** [comment]
https://user-images.githubusercontent.com/9256667/136959683-e0bbe170-d730-4cdd-9d89-33b0711e2bb6.mp4

In the video I use the switch, then select username, it shows up but at the end of the list of columns instead of in it's original position

**Comment by harupy** [comment]
@marijncv Thanks for the video. Let me pull the latest commit and try again.

**Comment by harupy** [comment]
https://user-images.githubusercontent.com/17039389/136961698-0b1bab73-27d7-4339-8cec-bc4a1d7bd357.mov

On my machine, the column shows up in the right position.

**Comment by marijncv** [comment]
>  column-select-2.mov 
> On my machine, the column shows up in the right position.

Hmm that is interesting. Could it be OS/browser related? I've been running Windows/WSL and tried Chrome, Firefox and Edge, all with the same result.

**Review by dbczumar — APPROVED** [review]
LGTM! Thanks @marijncv !

**Review by harupy — APPROVED** [review]
LGTM! Thanks for the contribution!

**Pull request merged**
