### PR TITLE
Return dict-like object in `MlflowDeploymentClient.get_endpoint`

### LINKED ISSUE #10804: [BUG]  Failed to score model on payload. Error: 'Endpoint' object has no attribute 'get'
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.9.2
- Tracking server: 2.9.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 13.6
- **Python version**: Python 3.8.6

### Describe the problem

The llm evaluation metric generated with mlflow.evaluate() shows the following error
> Failed to score model on payload. Error: 'Endpoint' object has no attribute 'get'
endpoint_error

I was able to avoid the ahead error with the following source code change. In <virtual_environment>/lib/python3.8/site-packages/mlflow/metrics/genai/model_utils.py, I changed line 122 from endpoint_type = endpoint.get("task", endpoint.get("endpoint_type")) to endpoint_type = endpoint.endpoint_type. 

### Tracking information

```shell
MLflow version: 2.9.2
Tracking URI: http://127.0.0.1:5200/
Artifact URI: mlflow-artifacts:/587337650981774112/1149ed5fd34841f88e66c8303b25cf6e/artifacts
System information: Darwin Darwin Kernel Version 22.6.0: Tue Nov  7 21:48:06 PST 2023; root:xnu-8796.141.3.702.9~2/RELEASE_X86_64
Python version: 3.8.6
MLflow version: 2.9.2
MLflow module location: /Users/ys/dev/env/mlflow_jupyter/lib/python3.8/site-packages/mlflow/__init__.py
Tracking URI: http://127.0.0.1:5200/
Registry URI: http://127.0.0.1:5200/
Active experiment ID: 587337650981774112
Active run ID: 1149ed5fd34841f88e66c8303b25cf6e
Active run artifact URI: mlflow-artifacts:/587337650981774112/1149ed5fd34841f88e66c8303b25cf6e/artifacts
MLflow dependencies: 
  Flask: 3.0.0
  Jinja2: 3.1.2
  aiohttp: 3.9.1
  alembic: 1.13.1
  boto3: 1.34.15
  click: 8.1.7
  cloudpickle: 3.0.0
  databricks-cli: 0.18.0
  docker: 6.1.3
  entrypoints: 0.4
  fastapi: 0.108.0
  gitpython: 3.1.40
  gunicorn: 21.2.0
  importlib-metadata: 7.0.1
  markdown: 3.5.1
  matplotlib: 3.7.4
  numpy: 1.24.4
  packaging: 23.2
  pandas: 2.0.3
  protobuf: 4.25.1
  pyarrow: 14.0.2
  pydantic: 2.5.3
  pytz: 2023.3.post1
  pyyaml: 6.0.1
  querystring-parser: 1.2.4
  requests: 2.31.0
  scikit-learn: 1.3.2
  scipy: 1.10.1
  sqlalchemy: 2.0.25
  sqlparse: 0.4.4
  tiktoken: 0.5.2
  uvicorn: 0.25.0
  watchfiles: 0.21.0
```

### Code to reproduce issue

```
import pandas as pd
import mlflow
from mlflow.deployments import set_deployments_target
from mlflow.metrics.genai.metric_definitions import (
    answer_similarity,
)

df = pd.DataFrame(
    {
        "question": [
            "How does useEffect() work?",
            "What does the static keyword in a function mean?",
            "What does the 'finally' block in Python do?",
            "What is the difference between multiprocessing and multithreading?",
        ],
        "ground_truth": [
            "The useEffect() hook tells React that your component needs to do something after render. React will remember the function you passed (we’ll refer to it as our “effect”), and call it later after performing the DOM updates.",
            "Static members belongs to the class, rather than a specific instance. This means that only one instance of a static member exists, even if you create multiple objects of the class, or if you don't create any. It will be shared by all objects.",
            "'Finally' defines a block of code to run when the try... except...else block is final. The finally block will be executed no matter if the try block raises an error or not.",
            "Multithreading refers to the ability of a processor to execute multiple threads concurrently, where each thread runs a process. Whereas multiprocessing refers to the ability of a system to run multiple processors in parallel, where each processor can run one or more threads.",
        ],
    }
)

logged_model = 'runs:/397d4d9c82474edd8b0e8fe8a73b0650/model'
mlflow.set_tracking_uri('http://127.0.0.1:5200/')
mlflow.gateway.set_gateway_uri('http://127.0.0.1:5000/')
set_deployments_target("http://localhost:5000")
my_answer_similarity = answer_similarity(
    model="endpoints:/completions"
)

with mlflow.start_run():
    results = mlflow.evaluate(
        model=logged_model,
        data=df,
        targets="ground_truth",
        model_type="text-summarization",
        extra_metrics=[my_answer_similarity],
        evaluator_config={'col_mapping': {"inputs": "question"}}
    )
eval_table = results.tables["eval_results_table"]
print(f"See evaluation table below: \n{eval_table}")
```

### Stack trace

No error from stack trace

### Other info / logs

_No response_

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

### LINKED ISSUE #11087: [BUG] When using a custom LLM as judge model (endpoints:/endpoint_name), response is NaN
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.10.0
- Tracking server: 2.10.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: WSL (Ubuntu)
- **Python version**: 3.10.13
- **yarn version, if running the dev UI**:

### Describe the problem

I am trying to use a [custom LLM as judge model](https://mlflow.org/docs/latest/llms/llm-evaluate/index.html#selecting-the-llm-as-judge-model), but using `endpoints:/chat` doesn't work. The resulting metrics are NaN.
image

By default, is the chat or completions version of gpt-4 being used?

`config.yaml`
```
endpoints:
  - name: completions
    endpoint_type: llm/v1/completions
    model:
      provider: openai
      name: gpt-3.5-turbo
      config:
        openai_api_key: $OPENAI_API_KEY
    limit:
      renewal_period: minute
      calls: 10

  - name: chat
    endpoint_type: llm/v1/chat
    model:
      provider: openai
      name: gpt-3.5-turbo
      config:
        openai_api_key: $OPENAI_API_KEY

  - name: azure-chat
    endpoint_type: llm/v1/chat
    model:
      provider: openai
      name: gpt-4
      config:
        openai_api_type: "azure"
        openai_api_key: $AZURE_OPENAI_API_KEY
        openai_deployment_name: "gpt-4"
        openai_api_base: "_"
        openai_api_version: "2023-05-15"

  - name: azure-completions
    endpoint_type: llm/v1/completions
    model:
      provider: openai
      name: gpt-4
      config:
        openai_api_type: "azure"
        openai_api_key: $AZURE_OPENAI_API_KEY
        openai_deployment_name: "gpt-4"
        openai_api_base: "_"
        openai_api_version: "2023-05-15"

  - name: embeddings
    endpoint_type: llm/v1/embeddings
    model:
      provider: openai
      name: text-embedding-ada-002
      config:
        openai_api_key: $OPENAI_API_KEY
```
Create deployments server
```bash
mlflow deployments start-server --config-path config.yaml --port 7000
```
Connect tracking server and deployments server
```bash
export MLFLOW_DEPLOYMENTS_TARGET="http://127.0.0.1:7000"
mlflow server --port 5000
```

I can use the endpoints via `get_deploy_client`, so I am not sure what went wrong.
```python
from mlflow.deployments import get_deploy_client

client = get_deploy_client("http://localhost:7000")
response = client.predict(
    endpoint="chat",
    inputs={"messages": [{"role": "user", "content": "Tell me a joke about rabbits"}]},
)
print(response)
```
```
{'id': 'chatcmpl-8qR3CU9RyUMeOPQZJsfr2WPbBaX5Q', 'object': 'chat.completion', 'created': 1707507730, 'model': 'gpt-3.5-turbo-0613', 'choices': [{'index': 0, 'message': {'role': 'assistant', 'content': 'Why did the rabbit go to the barber?\n\nBecause it wanted a hare-cut!'}, 'finish_reason': 'stop'}], 'usage': {'prompt_tokens': 13, 'completion_tokens': 16, 'total_tokens': 29}}
```
### Tracking information

```shell
System information: Windows 10.0.19045
Python version: 3.10.13
MLflow version: 2.10.0
MLflow module location: [c:\Users\_\miniconda3\envs\ml-3.10\lib\site-packages\mlflow\__init__.py](file:///C:/Users/_/miniconda3/envs/ml-3.10/lib/site-packages/mlflow/__init__.py)
Tracking URI: http://127.0.0.1:5000/
Registry URI: http://127.0.0.1:5000/
MLflow dependencies: 
  Flask: 3.0.1
  Jinja2: 3.1.3
  aiohttp: 3.9.2
  alembic: 1.13.1
  boto3: 1.34.37
  botocore: 1.34.37
  click: 8.1.7
  cloudpickle: 3.0.0
  databricks-cli: 0.18.0
  docker: 7.0.0
  entrypoints: 0.4
  fastapi: 0.109.0
  gitpython: 3.1.41
  importlib-metadata: 6.11.0
  kubernetes: 29.0.0
  markdown: 3.5.2
  matplotlib: 3.8.2
  numpy: 1.26.3
  packaging: 23.2
  pandas: 2.2.0
  protobuf: 4.23.4
  pyarrow: 15.0.0
  pydantic: 2.6.0
  pytz: 2023.4
  pyyaml: 6.0.1
  querystring-parser: 1.2.4
  requests: 2.31.0
  scikit-learn: 1.4.0
  scipy: 1.12.0
  slowapi: 0.1.8
  sqlalchemy: 2.0.25
  sqlparse: 0.4.4
  tiktoken: 0.5.2
  uvicorn: 0.27.0.post1
  waitress: 2.1.2
  watchfiles: 0.21.0
```

### Code to reproduce issue

```python
from datasets import load_dataset

dataset = load_dataset("squad")
eval_df = dataset["train"].to_pandas().sample(n=10, random_state=0)
def get_answer(row):
    answers = row["answers"]["text"]
    return answers[0]

eval_df["answer"] = eval_df.apply(get_answer, axis=1)
eval_df = eval_df.drop(columns=["answers", "id", "title"])

import mlflow

mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_experiment("test-deployment")


from langchain_core.prompts import ChatPromptTemplate, PromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough
from langchain_core.runnables import RunnableLambda, RunnablePassthrough
from langchain_openai import ChatOpenAI

template = """Answer the question based only on the following context:
{context}

Question: {question}
"""
prompt = ChatPromptTemplate.from_template(template)

llm = ChatOpenAI()
chain = (
    RunnablePassthrough()
    | prompt 
    | llm
    | StrOutputParser()
)
chain.invoke({"question": "What is 1 + 1?", "context": "1 + 1 is 3"})

from mlflow.metrics.genai import EvaluationExample, answer_similarity

# Create an example to describe what answer_similarity means like for this problem.
example = EvaluationExample(
    input="What is MLflow?",
    output="MLflow is an open-source platform for managing machine "
    "learning workflows, including experiment tracking, model packaging, "
    "versioning, and deployment, simplifying the ML lifecycle.",
    score=4,
    justification="The definition effectively explains what MLflow is "
    "its purpose, and its developer. It could be more concise for a 5-score.",
    grading_context={
        "targets": "MLflow is an open-source platform for managing "
        "the end-to-end machine learning (ML) lifecycle. It was developed by Databricks, "
        "a company that specializes in big data and machine learning solutions. MLflow is "
        "designed to address the challenges that data scientists and machine learning "
        "engineers face when developing, training, and deploying machine learning models."
    },
)

# Construct the metric using OpenAI GPT-4 as the judge
mlflow.deployments.set_deployments_target("http://localhost:7000")

judge_model = "endpoints:/chat"
# judge_model = "openai:/gpt-4"

answer_similarity_metric = answer_similarity(model=judge_model, examples=[example])

mlflow.deployments.get_deployments_target() # wasn't set even if in env variable

def model(input_df):
    answers = []
    for _, row in input_df.iterrows():
        answer = chain.invoke({"question": row["question"], "context": row["context"]})
        answers.append(answer)
    return answers

with mlflow.start_run(run_name="mistral"):
    mlflow.evaluate(
        model,
        eval_df,
        # model_type="question-answering",
        # evaluators="default",
        targets="answer",
        extra_metrics=[answer_similarity_metric], # faithfulness_metric, relevance_metric],
        evaluator_config={
            "col_mapping": {
                "inputs": "question",
            }
        },
    )
```

### Stack trace

```
[c:\Users\_\miniconda3\envs\ml-3.10\lib\site-packages\mlflow\data\digest_utils.py:29](file:///C:/Users/_/miniconda3/envs/ml-3.10/lib/site-packages/mlflow/data/digest_utils.py:29): FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  string_columns = trimmed_df.columns[(df.applymap(type) == str).all(0)]
[c:\Users\_\miniconda3\envs\ml-3.10\lib\site-packages\mlflow\models\evaluation\base.py:414](file:///C:/Users/_/miniconda3/envs/ml-3.10/lib/site-packages/mlflow/models/evaluation/base.py:414): FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  data = data.applymap(_hash_array_like_element_as_bytes)
[c:\Users\_\miniconda3\envs\ml-3.10\lib\site-packages\mlflow\models\evaluation\base.py:414](file:///C:/Users/_/miniconda3/envs/ml-3.10/lib/site-packages/mlflow/models/evaluation/base.py:414): FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  data = data.applymap(_hash_array_like_element_as_bytes)
2024/02/09 15:08:14 INFO mlflow.models.evaluation.base: Evaluating the model with the default evaluator.
2024/02/09 15:08:14 INFO mlflow.models.evaluation.default_evaluator: Computing model predictions.
2024/02/09 15:08:23 INFO mlflow.models.evaluation.default_evaluator: Testing metrics on first row...
100%
1/1 [00:02<00:00, 2.03s/it]
[c:\Users\_\miniconda3\envs\ml-3.10\lib\site-packages\numpy\core\fromnumeric.py:3504](file:///C:/Users/_/miniconda3/envs/ml-3.10/lib/site-packages/numpy/core/fromnumeric.py:3504): RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
[c:\Users\_\miniconda3\envs\ml-3.10\lib\site-packages\numpy\core\_methods.py:129](file:///C:/Users/_/miniconda3/envs/ml-3.10/lib/site-packages/numpy/core/_methods.py:129): RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
[c:\Users\_\miniconda3\envs\ml-3.10\lib\site-packages\numpy\core\fromnumeric.py:3787](file:///C:/Users/_/miniconda3/envs/ml-3.10/lib/site-packages/numpy/core/fromnumeric.py:3787): RuntimeWarning: Degrees of freedom <= 0 for slice
  return _methods._var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
[c:\Users\_\miniconda3\envs\ml-3.10\lib\site-packages\numpy\core\_methods.py:163](file:///C:/Users/_/miniconda3/envs/ml-3.10/lib/site-packages/numpy/core/_methods.py:163): RuntimeWarning: invalid value encountered in divide
  arrmean = um.true_divide(arrmean, div, out=arrmean,
[c:\Users\_\miniconda3\envs\ml-3.10\lib\site-packages\numpy\core\_methods.py:198](file:///C:/Users/_/miniconda3/envs/ml-3.10/lib/site-packages/numpy/core/_methods.py:198): RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
2024/02/09 15:08:25 INFO mlflow.models.evaluation.default_evaluator: Evaluating metrics: answer_similarity
100%
10/10 [00:00<00:00, 42.78it/s]
```

### Other info / logs

```
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [x] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [x] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

### PR DESCRIPTION
**Pull request by harupy**
### Related Issues/PRs

 #xxx

### What changes are proposed in this pull request?

Resolve #11087.
Resolve #10804.
Return dict-like object in `MlflowDeploymentClient.get_endpoint` to fix the following error. This error is swallowed by try-catch and results in `answer_similarity=NaN`.

```
2024/02/13 13:18:53 INFO mlflow.models.evaluation.base: Evaluating the model with the default evaluator.
2024/02/13 13:18:53 INFO mlflow.models.evaluation.default_evaluator: Computing model predictions.
2024/02/13 13:19:00 INFO mlflow.models.evaluation.default_evaluator: Testing metrics on first row...
  0%|                                                          | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "a.py", line 79, in <module>
    ev = mlflow.evaluate(
  File "/Users/harutaka.kawamura/Desktop/repositories/mlflow/mlflow/models/evaluation/base.py", line 1946, in evaluate
    evaluate_result = _evaluate(
  File "/Users/harutaka.kawamura/Desktop/repositories/mlflow/mlflow/models/evaluation/base.py", line 1181, in _evaluate
    eval_result = evaluator.evaluate(
  File "/Users/harutaka.kawamura/Desktop/repositories/mlflow/mlflow/models/evaluation/default_evaluator.py", line 1956, in evaluate
    evaluation_result = self._evaluate(model, is_baseline_model=False)
  File "/Users/harutaka.kawamura/Desktop/repositories/mlflow/mlflow/models/evaluation/default_evaluator.py", line 1845, in _evaluate
    self._evaluate_metrics(eval_df)
  File "/Users/harutaka.kawamura/Desktop/repositories/mlflow/mlflow/models/evaluation/default_evaluator.py", line 1639, in _evaluate_metrics
    self._test_first_row(eval_df)
  File "/Users/harutaka.kawamura/Desktop/repositories/mlflow/mlflow/models/evaluation/default_evaluator.py", line 1630, in _test_first_row
    raise MlflowException("\n".join(exceptions))
mlflow.exceptions.MlflowException: Metric 'answer_similarity': Error:
AttributeError("'Endpoint' object has no attribute 'get'")
Traceback (most recent call last):
  File "/Users/harutaka.kawamura/Desktop/repositories/mlflow/mlflow/models/evaluation/default_evaluator.py", line 1610, in _test_first_row
    metric_value = _evaluate_metric(metric_tuple, eval_fn_args)
  File "/Users/harutaka.kawamura/Desktop/repositories/mlflow/mlflow/models/evaluation/default_evaluator.py", line 598, in _evaluate_metric
    metric = metric_tuple.function(*eval_fn_args)
  File "/Users/harutaka.kawamura/Desktop/repositories/mlflow/mlflow/metrics/genai/genai_metric.py", line 349, in eval_fn
    score, justification = future.result()
  File "/Users/harutaka.kawamura/.pyenv/versions/miniconda3-latest/envs/mlflow/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/Users/harutaka.kawamura/.pyenv/versions/miniconda3-latest/envs/mlflow/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/Users/harutaka.kawamura/.pyenv/versions/miniconda3-latest/envs/mlflow/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/harutaka.kawamura/Desktop/repositories/mlflow/mlflow/metrics/genai/genai_metric.py", line 307, in score_model_on_one_payload
    raw_result = model_utils.score_model_on_payload(
  File "/Users/harutaka.kawamura/Desktop/repositories/mlflow/mlflow/metrics/genai/model_utils.py", line 25, in score_model_on_payload
    return _call_deployments_api(suffix, payload, eval_parameters)
  File "/Users/harutaka.kawamura/Desktop/repositories/mlflow/mlflow/metrics/genai/model_utils.py", line 122, in _call_deployments_api
    endpoint_type = endpoint.get("task", endpoint.get("endpoint_type"))
  File "/Users/harutaka.kawamura/.pyenv/versions/miniconda3-latest/envs/mlflow/lib/python3.8/site-packages/pydantic/main.py", line 767, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'Endpoint' object has no attribute 'get'
```

### How is this PR tested?

- [ ] Existing unit/integration tests
- [ ] New unit/integration tests
- [x] Manual tests

```python
from datasets import load_dataset

dataset = load_dataset("squad")
eval_df = dataset["train"].to_pandas().sample(n=10, random_state=0)


def get_answer(row):
    answers = row["answers"]["text"]
    return answers[0]


eval_df["answer"] = eval_df.apply(get_answer, axis=1)
eval_df = eval_df.drop(columns=["answers", "id", "title"])

import mlflow

mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_experiment("test-deployment")


from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_openai import ChatOpenAI

template = """Answer the question based only on the following context:
{context}

Question: {question}
"""
prompt = ChatPromptTemplate.from_template(template)

llm = ChatOpenAI()
chain = RunnablePassthrough() | prompt | llm | StrOutputParser()
chain.invoke({"question": "What is 1 + 1?", "context": "1 + 1 is 3"})

from mlflow.metrics.genai import EvaluationExample, answer_similarity

# Create an example to describe what answer_similarity means like for this problem.
example = EvaluationExample(
    input="What is MLflow?",
    output="MLflow is an open-source platform for managing machine "
    "learning workflows, including experiment tracking, model packaging, "
    "versioning, and deployment, simplifying the ML lifecycle.",
    score=4,
    justification="The definition effectively explains what MLflow is "
    "its purpose, and its developer. It could be more concise for a 5-score.",
    grading_context={
        "targets": "MLflow is an open-source platform for managing "
        "the end-to-end machine learning (ML) lifecycle. It was developed by Databricks, "
        "a company that specializes in big data and machine learning solutions. MLflow is "
        "designed to address the challenges that data scientists and machine learning "
        "engineers face when developing, training, and deploying machine learning models."
    },
)

import mlflow.deployments

# Construct the metric using OpenAI GPT-4 as the judge
mlflow.deployments.set_deployments_target("http://localhost:7000")

judge_model = "endpoints:/chat"
# judge_model = "openai:/gpt-4"

answer_similarity_metric = answer_similarity(model=judge_model, examples=[example])

mlflow.deployments.get_deployments_target()  # wasn't set even if in env variable


def model(input_df):
    answers = []
    for _, row in input_df.iterrows():
        answer = chain.invoke({"question": row["question"], "context": row["context"]})
        answers.append(answer)
    return answers


with mlflow.start_run():
    ev = mlflow.evaluate(
        model,
        eval_df,
        # model_type="question-answering",
        # evaluators="default",
        targets="answer",
        extra_metrics=[answer_similarity_metric],  # faithfulness_metric, relevance_metric],
        evaluator_config={
            "col_mapping": {
                "inputs": "question",
            }
        },
    )
    print(ev.metrics)

```

### Does this PR require documentation update?

- [ ] No. You can skip the rest of this section.
- [ ] Yes. I've updated:
  - [ ] Examples
  - [ ] API references
  - [ ] Instructions

#### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

#### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>

#### How should the PR be classified in the release notes? Choose one:

- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Review by B-Step62 — COMMENTED** [review]
Can we simply call `.dict()` in our logic?
```
endpoint_dict = endpoint.dict() if endpoint else {}
endpoint_dict.get("task", endpoint_dict.get("endpoint_type"))
```
This is public API so changing the return type from pydantic object to dict can confuse users. Also the`Endpoint` type itself is also public exposed.

**Comment by harupy** [comment]
@B-Step62 It's possible but if we do that, we'd need to inspect the object type in `_call_deployments_api` because `DatabricksDeploymentClient.get_endpoint` returns `AttrDict`. The code would look like:

```
endpoint_dict = endpoint.dict() if is_pydantic_model(endpoint) else endpoint
endpoint_dict.get("task", endpoint_dict.get("endpoint_type"))
```

**Comment by harupy** [comment]
The real issue is each client returns different objects.

**Review by WeichenXu123 — APPROVED** [review]
LGTM

**Comment by WeichenXu123** [comment]
What about adding a method like `mlflow.deployments.server.config.Endpoint.to_attr_dict()` ?
This way looks less ambiguous.

**Comment by B-Step62** [comment]
> The real issue is each client returns different objects.

100%, and I assume making change to Databricks client is too dangerous here? 

I think the solution [here](https://github.com/mlflow/mlflow/pull/11096#issuecomment-1970539657) is safer, requiring just minimum hack to resolve the issue. Pathing Endpoint class might cause some long-term drift... like `from mlflow.deployment import Endpoint` and `from mlflow.deployments.server.config import Endpoint` returns different object, and once more ppl rely on these classes it becomes hard to unify.

Alternatively we could add a getter method to the Endpoint pydantic model, but it feels less clean than the solution above.

**Comment by harupy** [comment]
@B-Step62 Let's go with [this solution](https://github.com/mlflow/mlflow/pull/11096#issuecomment-1970539657)!

**Review by B-Step62 — APPROVED** [review]
LGTM, thanks for the flexibilty!!

**Pull request merged**
