### PR TITLE
Fix jest config for jest-canvas-mock

### PR DESCRIPTION
**Pull request by harupy**
## What changes are proposed in this pull request?

Fix for the following warning:

Screen Shot 2020-06-09 at 16 29 05

https://github.com/mlflow/mlflow/pull/2913/checks?check_run_id=752821984#step:6:8

According to the `jest-canvas-mock` repo, we need to use `setupFiles` instead of `setupFilesAfterEnv`

https://github.com/hustcc/jest-canvas-mock#setup

## How is this patch tested?

- Manually verified the warning is removed.
- The existing tests

### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [x] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by aarondav** [comment]
Weird that this didn't break anything, but LGTM!

**Review by aarondav — APPROVED** [review]

**Comment by aarondav** [comment]
(Btw, just to confirm before merging, should we  just remove these lines instead?)

**Comment by harupy** [comment]
@aarondav 

> (Btw, just to confirm before merging, should we just remove these lines instead?)

What does this comment mean?

**Comment by aarondav** [comment]
If

```
    "setupFiles": [
      "jest-canvas-mock"
    ]
```

wasn't working, but nothing was failing, do we need these lines at all? Can we just delete them instead of fixing the typo?

**Comment by harupy** [comment]
@aarondav This setting removes the following error:

```
Error: Not implemented: HTMLCanvasElement.prototype.getContext
```

### Before

Screen Shot 2020-06-13 at 11 18 33

### After

Screen Shot 2020-06-13 at 11 20 03

**Comment by aarondav** [comment]
Got it - thanks!

**Pull request merged**
