### PR TITLE
Changes needed to support the sqlplugin

### PR DESCRIPTION
**Pull request by avflor**
## What changes are proposed in this pull request?

Edits in the setup.py file to support the sqlplugin that provides the ability to use SQL Server as the artifact store for MLflow.

### CODE REVIEW

**Comment by dbczumar** [comment]
@avflor Thanks for this contribution! It's worth noting that these changes aren't necessarily required for users to leverage your plugin; this will just help with ease of installation and plugin discoverability.

**Comment by dbczumar** [comment]
@avflor I searched PyPI for the package name `sqlplugin` and couldn't find anything: https://pypi.org/search/?q=sqlplugin. Has this package name been registered? Is it subject to change?

**Comment by avflor** [comment]
@dbczumar I havent registered the package yet. I was waiting to have this PR merged first, then update the submodule in the plugin repo, test and then register the package. Would that make sense?

**Review by dbczumar — APPROVED** [review]
@avflor LGTM. Confirmed that `dbstoreplugin` is available on PyPI (https://pypi.org/project/dbstoreplugin/).

**Comment by avflor** [comment]
@dbczumar Please don't merge yet. I think we will have to include mlflow as part of the plugin name. Working on it now. Will update the PR soon,

**Comment by avflor** [comment]
@dbczumar I updated the plugin name and this PR. I think we can merge now.

**Pull request merged**
