### PR TITLE
Bugfix examples/hyperparam to use mlflow.tracking.MlflowClient()

### PR DESCRIPTION
**Pull request by parkerzf**
Use the new tracking API MlflowClient() instead of get_service() in examples/hyperparam.

### CODE REVIEW

**Review by tomasatdatabricks — APPROVED** [review]
Thanks for the fix!

**Comment by tomasatdatabricks** [comment]
Hey @parkerzf it looks like the build fails with some weird git merge  or Travis issue. I am gonna create a new PR for this using your commit.

**Comment by parkerzf** [comment]
Am I going to be the contributor for this PR then?

**Comment by tomasatdatabricks** [comment]
Yes. You can also close this PR, merge with master and reopen it

**Comment by tomasatdatabricks** [comment]
I would like to get this in as soon as possible.

**Comment by tomasatdatabricks** [comment]
Hey @parkerzf, the tests for the new PR are green: https://github.com/mlflow/mlflow/pull/487

It uses your commits so you will be contributor. I am gonna merge it in a few minutes unless you prefer to make a new PR yourself?

**Comment by tomasatdatabricks** [comment]
Actually I am gonna merge this as is. The tests passed for PR #487 which has the same diff.

Thanks for the contribution @parkerzf !

**Comment by parkerzf** [comment]
You are welcome. Unfortunately I don't think I am marked as contributor.

**Comment by parkerzf** [comment]
Awesome! Thanks!

**Pull request merged**
