### PR TITLE
Adding new flavor for BigML models

### PR DESCRIPTION
**Pull request by mmerce**
## What changes are proposed in this pull request?

It adds a new mlflow.bigml module that is able to register, save and load models exported from BigML (www.bigml.com). The models can also be trained and tracked if the needed credentials are set as environment variables for [authentication](https://bigml.readthedocs.io/en/latest/index.html?highlight=authentication#authentication). 

[https://github.com/bigmlcom/mlflow/blob/master/mlflow/bigml.py
](https://github.com/bigmlcom/mlflow/blob/master/mlflow/bigml.py
)
## How is this patch tested?

Tests have been included in the tests directory to check the registry, save, load and scoring of some of the supervised model types offered by BigML.

[https://github.com/bigmlcom/mlflow/tree/master/tests/bigml
](https://github.com/bigmlcom/mlflow/tree/master/tests/bigml
)

We also provide some examples in the [https://github.com/bigmlcom/mlflow/tree/master/examples/bigml](https://github.com/bigmlcom/mlflow/tree/master/examples/bigml) directory, that include tracking the entire training procedure. For this particular example, a BigML account is required and credentials need to be set as environment variables. Please, check the README instructions provided in the same directory.

## Does this PR change the documentation?

- [X] No. You can skip the rest of this section.
- [ ] Yes. Make sure the changed pages / sections render correctly by following the steps below.

1. Check the status of the `ci/circleci: build_doc` check. If it's successful, proceed to the
   next step, otherwise fix it.
2. Click `Details` on the right to open the job page of CircleCI.
3. Click the `Artifacts` tab.
4. Click `docs/build/html/index.html`.
5. Find the changed pages / sections and make sure they render correctly.

### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [X] Yes. Give a description of this change to be included in the release notes for MLflow users.

- New mlflow.bigml flavor, allows saving/loading BigML downloaded models enabled for scoring and deploy.
- Adding examples of use for the new mlflow.bigml module.
- Adding tests to check the mlflow.bigml save/load features.

### What component(s), interfaces, languages, and integrations does this PR affect?
Components
- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [X] `area/docs`: MLflow documentation pages
- [X] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [X] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>
### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [X] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by dbczumar** [comment]
Hi @mmerce ! Thank you for your contribution to MLflow! At this time, we're seeking to limit the number of flavors that are natively embedded in MLflow to reduce maintenance / testing overhead. To better ensure that BigML experts can maintain this flavor and publish updates quickly, we recommend introducing the flavor as a separate Python package / repository. Once it is published, we would be thrilled to include a link to it on the MLflow website. Thanks again! Please let me know if you have any questions.

**Comment by mmerce** [comment]
Hi @dbczumar! Thanks so much for your quick response. 
Let me comment on that.

>At this time, we're seeking to limit the number of flavors that are natively embedded in MLflow to reduce maintenance / testing overhead. To better ensure that BigML experts can maintain this flavor and publish updates quickly, we recommend introducing the flavor as a separate Python package / repository.

Sure, we understand. We followed the guidelines in your documentation (which  probably you might want to modify to reflect your actual view on flavors contributions)
https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#python-model-flavors

Can you provide any guidance as to how you'd like contributors to add a new flavor on top of MLFlow from an external package? We could keep the actual forked repo, but that would conflict with other companies doing the same with their own flavors. Maybe you could point us to an example of the kind of repo you that are thinking of? We'll be happy to change our code to replicate that.

>Once it is published, we would be thrilled to include a link to it on the MLflow website. 

That would be awesome! We were planning on publishing a blog post to explain our integration once the version was out. That would be released once the link is included.

Best!

**Comment by dbczumar** [comment]
> Hi @dbczumar! Thanks so much for your quick response. Let me comment on that.
> 
> > At this time, we're seeking to limit the number of flavors that are natively embedded in MLflow to reduce maintenance / testing overhead. To better ensure that BigML experts can maintain this flavor and publish updates quickly, we recommend introducing the flavor as a separate Python package / repository.
> 
> Sure, we understand. We followed the guidelines in your documentation (which  probably you might want to modify to reflect your actual view on flavors contributions) https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#python-model-flavors
> 
> Can you provide any guidance as to how you'd like contributors to add a new flavor on top of MLFlow from an external package? We could keep the actual forked repo, but that would conflict with other companies doing the same with their own flavors. Maybe you could point us to an example of the kind of repo you that are thinking of? We'll be happy to change our code to replicate that.
> 
> > Once it is published, we would be thrilled to include a link to it on the MLflow website.
> 
> That would be awesome! We were planning on publishing a blog post to explain our integration once the version was out. That would be released once the link is included.
> 
> Best!

@mmerce Our apologies! We will make sure to update the contribution guide to reflect this change in viewpoint shortly. Concretely, we recommend creating a fresh repository containing the contents of `mlflow/bigml.py` with a library dependency on MLflow. You can keep the method implementations the same; when users call the various model flavor methods in `mlflow/bigml.py`, MLflow Models will still be created successfully. The only important distinction to note is that you should include your library as a dependency in the model's conda environment / pip requirements. To ensure that your code remains compatible over time, we recommend running unit tests with the latest version of MLflow installed (e.g. using GitHub Actions to run a pytest suite). While we don't have any flavor examples with this structure for reference, we're happy to provide guidance as needed. Thanks again for contributing to the MLflow ecosystem!

**Comment by mmerce** [comment]
Hi @dbczumar. You can find a repo adding the library we were talking about at https://github.com/bigmlcom/bigmlflow. Comments are welcome. It would be great if you could include a pointer to it in your documentation as you gently offered to.

**Comment by mmerce** [comment]
Hi guys. The bigmlflow plugin is finally available in pypi. Here's our blog post introducing it: https://blog.bigml.com/2022/10/25/easily-operating-machine-learning-models/

Best.

**Comment by dbczumar** [comment]
Hi @mmerce , this is so awesome! We'd love to document the BigML flavor on the MLflow website. Would you be interested in filing a small PR that adds a "Community Model Flavors" section to https://mlflow.org/docs/latest/models.html, similar to https://mlflow.org/docs/latest/models.html#built-in-model-flavors, and provides a brief overview of the BigML flavor & how users can install it? I think this could help drive usage even more :D

**Pull request closed without merging**
