### PR TITLE
[UI] Separate selection checkbox into its own column

### LINKED ISSUE #2549: [FR] UI: separate selection checkbox into it's own column.
Currently, to select subset of runs the 'Date' field has to be active, since selection is tied to that.

IMO, when the experiment is not important and I always try to hide it.

It would be useful if selection column for runs was always visible.

### PR DESCRIPTION
**Pull request by harupy**
## What changes are proposed in this pull request?

- Separate selection checkbox into its own column, so a user can hide the `Start Time` column.
- Resolves #2549

Demo after the fix:

demo

## How is this patch tested?

Tested manually

### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [x] Yes. Give a description of this change to be included in the release notes for MLflow users.

Selection checkbox on the runs table is separated into its own column.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s) does this PR affect?

- [x] UI
- [ ] CLI
- [ ] API
- [ ] REST-API
- [ ] Examples
- [ ] Docs
- [ ] Tracking
- [ ] Projects
- [ ] Artifacts
- [ ] Models
- [ ] Scoring
- [ ] Serving
- [ ] R
- [ ] Java
- [ ] Python

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [x] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by harupy** [comment]
@Zangr What do you think?

**Comment by Zangr** [comment]
@harupy sorry for the late reply. Yes, it makes sense to move it to a separate column. The change looks good generally. Would you mind rebasing your change on top of the latest master?

**Review by Zangr — COMMENTED** [review]
@harupy sorry for the late reply. Yes, it makes sense to move it to a separate column. The change looks good generally. Would you mind rebasing your change on top of the latest master?

**Comment by harupy** [comment]
@Zangr Got it. I'll resolve the conflicts.

**Comment by harupy** [comment]
@Zangr Resolved the conflicts.

**Review by Zangr — APPROVED** [review]
LGTM!

**Pull request merged**
