### PR TITLE
Fix pydoc compatiblility with PYTHONOPTIMIZE=2

### LINKED ISSUE #7789: [BUG] mlflow does not work with PYTHONOPTIMIZE=2
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.1.1

### System information

- Ubuntu 20.04
- Python 3.10

### Describe the problem

`mlflow` internally shares docstrings by adding strings to `fun.__doc__`. However, when running in a `PYTHONOPTIMIZE=2` setting, these docstrings are `None`, leading to an exception. 

### Tracking information

_No response_

### Code to reproduce issue

```bash
PYTHONOPTIMIZE=2 mlflow --version
```

### Stack trace

```bash
Traceback (most recent call last):
  File "/home/bfe2rng/.conda/envs/test/bin/mlflow", line 5, in <module>
    from mlflow.cli import cli
  File "/home/bfe2rng/.conda/envs/test/lib/python3.10/site-packages/mlflow/__init__.py", line 41, in <module>
    from mlflow import projects  # pylint: disable=unused-import
  File "/home/bfe2rng/.conda/envs/test/lib/python3.10/site-packages/mlflow/projects/__init__.py", line 27, in <module>
    from mlflow.projects.backend import loader
  File "/home/bfe2rng/.conda/envs/test/lib/python3.10/site-packages/mlflow/projects/backend/loader.py", line 4, in <module>
    from mlflow.projects.backend.local import LocalBackend
  File "/home/bfe2rng/.conda/envs/test/lib/python3.10/site-packages/mlflow/projects/backend/local.py", line 31, in <module>
    from mlflow.utils.virtualenv import (
  File "/home/bfe2rng/.conda/envs/test/lib/python3.10/site-packages/mlflow/utils/virtualenv.py", line 11, in <module>
    from mlflow.models.model import Model, MLMODEL_FILE_NAME
  File "/home/bfe2rng/.conda/envs/test/lib/python3.10/site-packages/mlflow/models/__init__.py", line 99, in <module>
    from .utils import ModelInputExample, validate_schema  # pylint: disable=unused-import
  File "/home/bfe2rng/.conda/envs/test/lib/python3.10/site-packages/mlflow/models/utils.py", line 701, in <module>
    def add_libraries_to_model(model_uri, run_id=None, registered_model_name=None):
  File "/home/bfe2rng/.conda/envs/test/lib/python3.10/site-packages/mlflow/utils/annotations.py", line 20, in experimental
    return _experimental(api=api_or_type, api_type="function")
  File "/home/bfe2rng/.conda/envs/test/lib/python3.10/site-packages/mlflow/utils/annotations.py", line 30, in _experimental
    api.__doc__ = notice + api.__doc__
TypeError: can only concatenate str (not "NoneType") to str
```

### Other info / logs

_No response_

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

### PR DESCRIPTION
**Pull request by dbczumar**
Signed-off-by: dbczumar <corey.zumar@databricks.com>

## Related Issues/PRs

Closes #7789

Fix pydoc compatiblility with PYTHONOPTIMIZE=2

## How is this patch tested?

- [X] Existing unit/integration tests
- [ ] New unit/integration tests
- [ ] Manual tests (describe details, including test results, below)

## Does this PR change the documentation?

- [X] No. You can skip the rest of this section.
- [ ] Yes. Make sure the changed pages / sections render correctly in the documentation preview.

## Release Notes

Fix pydoc compatiblility with PYTHONOPTIMIZE=2

### Is this a user-facing change?

- [X] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [X] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [X] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Review by BenWilson2 — APPROVED** [review]
LGTM!
Do we need to test various options of running a Python script with `-oo` and `-ooo` to validate optimize settings throughout MLflow? (maybe a follow-on PR later?)

**Comment by dbczumar** [comment]
> LGTM! Do we need to test various options of running a Python script with `-oo` and `-ooo` to validate optimize settings throughout MLflow? (maybe a follow-on PR later?)

Yeah, probably a good follow-on :)

**Comment by dbczumar** [comment]
@mlflow-automation autoformat

**Comment by BenWilson2** [comment]
Added a ticket to next sprint :)

**Pull request merged**
