### PR TITLE
Artifact location was missing in mlflow.set_experiment

### PR DESCRIPTION
**Pull request by fhoering**
## What changes are proposed in this pull request?
 
Need to be able to set the artifact location for non existing experiments 
 
## How is this patch tested?
 
Tested with our MLFlow server
 
### Is this a user-facing change? 

- [x ] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.
 
(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)
 
### What component(s) does this PR affect?
 
- [ ] UI
- [ ] CLI 
- [x ] API 
- [ ] REST-API 
- [ ] Examples 
- [ ] Docs
- [ ] Tracking
- [ ] Projects 
- [ ] Artifacts 
- [ ] Models 
- [ ] Scoring 
- [ ] Serving
- [ ] R
- [ ] Java
- [x ] Python

### How should the PR be classified in the release notes? Choose one:
 
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [x ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Review by smurching — COMMENTED** [review]
@fhoering thanks for the PR! My one concern is that this makes the behavior of the `set_experiment` API a little tricky to reason about - as a user of the API you have to be aware that the `artifact_location` you pass won't be honored if the experiment already exists. Or in other words, you can't expect passing an `artifact_location` to `set_experiment` to guarantee that an experiment exists with the passed artifact URI, which seems like the main use case of passing `artifact_location`. 

Maybe as an alternative, we should consider pulling the `MlflowClient.get_experiment_by_name` and `MlflowClient.get_experiment` APIs into the fluent API (e.g. expose them as `mlflow.get_experiment_by_name` and `mlflow.get_experiment`) so that it's easier for users to write code that does a get-or-create-experiment-with-artifact-uri, if that's their goal.

**Comment by smurching** [comment]
Ah, I see your PR https://github.com/mlflow/mlflow/pull/1899 achieves^ - will take a look :)

**Comment by fhoering** [comment]
@smurching 
I agree it is somehow strange to add this parameter.

I'm trying to have a function the creates or sets the experiment with the fluent api only and it is not possible as is.

First I started exposing all functions from #1899 and then wrote the logic myself.

```
def set_or_create_experiment(experiment_name, artifact_location=None):
    experiment = client.get_experiment_by_name(experiment_name)
    if not experiment:
        exp_id = client.create_experiment(experiment_name, artifact_location)
    else:
        exp_id = experiment.id
    start_run(exp_id)
```

But this wrapper looks exactly the same as `set_experiment` so it seems like there is something wrong too. (In any case set_experiment is wrongly named. It should be rather something like `set_or_create_experiment`)

One alternative could be to add a safe create_experiment function (or add a param exist_ok=True to create_experiment)

```
mlflow.create_experiment_if_not_exists(experiment_name)
mlflow.set_experiment(experiment_name)
````

```
mlflow.create_experiment(experiment_name, exist_ok=True)
mlflow.set_experiment(experiment_name)
````

**Comment by fhoering** [comment]
@smurching What to do with this PR ? 
I think adding sth like `mlflow.create_experiment(experiment_name, artifact_location, exist_ok=True)` would bring value but I can do this on my side with the other PR.

So I let you decide if we close this or not.

**Comment by smurching** [comment]
@fhoering my preference would be to simplify this use case by merging the other PR (#1923) as opposed to adding new arguments/behavior to `set_experiment` or `create_experiment` for the reasons mentioned above - just went ahead & merged #1923, thanks again for both PRs / raising these questions :)

**Comment by fhoering** [comment]
Thanks @smurching. I'll close this one. 

If you have time can you also have a look at https://github.com/mlflow/mlflow/issues/2005
It is not related to this PR but to the Python API.

**Pull request closed without merging**
