### PR TITLE
Preview images with full width

### LINKED ISSUE #2901: [FR] Use all the width of screen to display feature importance artifacts
Thank you for submitting a feature request. **Before proceeding, please review MLflow's [Issue Policy for feature requests](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md#feature-requests) and the [MLflow Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst)**.

**Please fill in this feature request template to ensure a timely and thorough response.**

## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [ ] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [x] No. I cannot contribute this feature at this time.

## Proposal Summary

(In a few sentences, provide a clear, high-level description of the feature request)

I have a xgboost model with 100+ features. I keep track of feature importance (gain and weight).
I use mlflow in a standalone (localhost) mode with local storage (file).
I have made a minor modification in mlflow/xgboost.py to create higher resolutions pictures.
They are stored nicely in mlruns/*/artifacts directories.
However in mlflow ui, the display is tiny. It would be nice to have it using all the width of my screen. 

## Motivation
- What is the use case for this feature?
ergonomics mainly
- Why is this use case valuable to support for MLflow users in general?
- Why is this use case valuable to support for your project(s) or organization?
- Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient)

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [x] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [x] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations

## Details

(Use this section to include any additional information about the feature. If you have a proposal for how to implement this feature, please include it here. For implementation guidelines, please refer to the [Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#contribution-guidelines).)

Here is a screenshot to explain the need
artifact feature

### LINKED ISSUE #4900: [FR] Show image artifacts at highest possible width
## Willingness to contribute
- [ x] No. I cannot contribute this feature at this time.

## Proposal Summary
The images are currently shown relatively small. I am plotting many things and it would be great if I could see the artifacts in a higher resolution. It would be optimal to use all available width of the window.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [x ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

### LINKED ISSUE #5607: Expand artifact viewer height to > 500px for all artifact types
https://github.com/mlflow/mlflow/blob/e7caa0a1ffd47255f52b2818fad49d34ed332d99/mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactHtmlView.js#L57

Could you be so kind as to put "100%" instead of "500px" here?

I've patched this in my mlflow instance, and viewing the attached html files (especially plotly charts) became MUCH better.

### PR DESCRIPTION
**Pull request by szczeles**
## What changes are proposed in this pull request?

After changing the artifacts preview engine to Plotly (in https://github.com/mlflow/mlflow/pull/1934), the height is fixed to 500px. It makes the preview of tall images truncated, see: #4900, #2901, #2535

This fix makes the canvas use the entire width of the container, making the preview look nicer. I didn't manage to make the div scrollable, but the image can be still scrolled using Plotly's "Pan" tool.

mlflow_plotly

Fixes #4900
Fixes #2901
Fixes #5607

## How is this patch tested?

Manually, using [Development UI](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#launching-the-development-ui). Please, keep in mind I'm not a frontend developer, so I basically tried different CSS variants until I was happy with the results. It's worth having a look if I accidentally didn't break anything.

## Does this PR change the documentation?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Make sure the changed pages / sections render correctly by following the steps below.

### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [x] Yes. Give a description of this change to be included in the release notes for MLflow users.

Image artifacts preview uses now full canvas width.

### What component(s), interfaces, languages, and integrations does this PR affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [x] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>
### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [x] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by harupy** [comment]
@szczeles Thanks for the PR, it looks great! Is it possible to remove the space above the image?

## Before

https://user-images.githubusercontent.com/17039389/161958428-33ce042b-5b80-4fb8-996e-f42eb2d91d5c.mov

## After

https://user-images.githubusercontent.com/17039389/161958299-8e812d16-491f-4392-8f74-47f123dcc715.mov

### Python script to log sample images

```python
import tempfile
from io import BytesIO
from pathlib import Path

import requests
from PIL import Image

import mlflow


class TemporaryDirectory(tempfile.TemporaryDirectory):
    def __enter__(self):
        return Path(super().__enter__())


url = "https://upload.wikimedia.org/wikipedia/commons/c/cc/ESC_large_ISS022_ISS022-E-11387-edit_01.JPG"

response = requests.get(url)
img = Image.open(BytesIO(response.content))

with TemporaryDirectory() as tmpdir:
    for idx, ratio in enumerate([2.0, 1.0, 0.5, 0.2, 0.1]):
        width, height = map(lambda x: int(x * ratio), img.size)
        resized = img.resize((width, height), Image.LANCZOS)
        resized.save(tmpdir / f"{idx}_w_{width}_h_{height}_r_{ratio}.jpg")

    with mlflow.start_run():
        mlflow.log_artifacts(tmpdir, artifact_path="images")
```

**Comment by szczeles** [comment]
@harupy Thanks for the review. I will have a look if the image can be aligned to the top vertically - it's a good idea!

However, I'm not a frontend dev, so I can't guarantee success ;-) I will keep you posted

**Comment by szczeles** [comment]
@harupy I tried different settings of `yref` and `yanchor` in the [image properties](https://github.com/mlflow/mlflow/blob/v1.24.0/mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactImageView.js#L107), but, unfortunately, none of these worked. Current value `yanchor: 'bottom'` minimizes the top margin. 

It looks that Plotly library adds this margin depending on the canvas width, with a wide browser window (~1920px), the margin is really small:
image

But with narrow browser window, it's like on your videos.

**Comment by dbczumar** [comment]
@harupy Any updates here?

**Comment by harupy** [comment]
Hi @szczeles, sorry for the late reply. Let me try `yanchor: 'bottom'`.

**Comment by harupy** [comment]
I also tried fixing image properties such as `yanchor` but all attempts didn't work, and then threw away plotly and tried Ant Design's `Image` component ([doc](https://ant.design/components/image/)):

https://user-images.githubusercontent.com/17039389/164032176-985c595c-0927-4ccd-a381-f40c36a8c164.mov

Am I the only who thinks this is a way better than the current approach?

**Comment by szczeles** [comment]
@harupy That's a nice one! Did you test it on tall images as well? (with width:height ratio of 1:5 and more). When you generate images showing features importance on models built on categorical features, the images tend to be quite tall.

**Comment by harupy** [comment]
> @harupy That's a nice one! Did you test it on tall images as well? (with width:height ratio of 1:5 and more). When you generate images showing features importance on models built on categorical features, the images tend to be quite tall.

Thanks for the comment, let me try that :)

**Comment by harupy** [comment]
https://user-images.githubusercontent.com/17039389/164039764-f0780e00-8b51-4766-9364-b4a571d1f3e9.mov

**Comment by szczeles** [comment]
@harupy Fantastic!

**Comment by harupy** [comment]
https://user-images.githubusercontent.com/17039389/164128288-e382afe2-d133-411d-b515-a3ebb9981ae1.mov

**Comment by harupy** [comment]
@szczeles I shared the demo in the community slack to collect more feedback: https://mlflow-users.slack.com/archives/CBFQ95Y2G/p1650417579529729

**Comment by harupy** [comment]
@szczeles Here's how my implementation looks like https://github.com/mlflow/mlflow/pull/5751

**Comment by harupy** [comment]
https://user-images.githubusercontent.com/17039389/164882673-a5e10288-37ce-493d-89a9-811def056bbe.mov

**Comment by szczeles** [comment]
@harupy Looks good! I see you managed to add the code into existing branch in my fork? That's a nice feature, I didn't event know that github allows it :-)

**Review by harupy — APPROVED** [review]
LGTM!

**Comment by harupy** [comment]
```python
import tempfile
from io import BytesIO
from pathlib import Path

import requests
from PIL import Image

import mlflow


class TemporaryDirectory(tempfile.TemporaryDirectory):
    def __enter__(self):
        return Path(super().__enter__())


url1 = "https://upload.wikimedia.org/wikipedia/commons/c/cc/ESC_large_ISS022_ISS022-E-11387-edit_01.JPG"
tall_image = "https://images.unsplash.com/photo-1587410131477-f01b22c59e1c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8dGFsbCUyMHRvd2VyfGVufDB8fDB8fA%3D%3D&w=1000&q=80"
gif_url = "https://media.wired.jp/photos/61ce989a6e712a10a3de7e60/master/w_1600,c_limit/4c8da6532cd53ab03956208dd5ad4e24.gif"


def fetch_image(url):
    headers = {"User-Agent": "My User Agent 1.0", "From": "youremail@domain.com"}
    response = requests.get(url, headers=headers)
    return Image.open(BytesIO(response.content))


def long_barchart():
    import matplotlib.pyplot as plt

    import numpy as np
    import matplotlib.pyplot as plt

    fig, ax = plt.subplots(figsize=(10, 100))
    plt.barh(range(100), range(100), align="center", alpha=0.5)
    plt.savefig("tall_bar_chart.png")


with TemporaryDirectory() as tmpdir:
    img1 = fetch_image(url1)
    for idx, ratio in enumerate([2.0, 1.0, 0.5, 0.2, 0.1]):
        w, h = img1.size
        width = int(w * ratio)
        height = int(h * ratio)
        resized = img1.resize((width, height), Image.LANCZOS)
        resized.save(tmpdir / f"{idx}_w_{width}_h_{height}_r_{ratio}.jpg")

    with open("test.gif", "wb") as f:
        f.write(requests.get(gif_url).content)

    with open("tall.jpeg", "wb") as f:
        f.write(requests.get(tall_image).content)

    long_barchart()

    with mlflow.start_run():
        mlflow.log_artifacts(tmpdir, artifact_path="images")
        mlflow.log_artifact("test.gif", artifact_path="images")
        mlflow.log_artifact("tall.jpeg", artifact_path="images")
        mlflow.log_artifact("tall_bar_chart.png", artifact_path="images")

        mlflow.log_text("\n".join(["a"] * 1000), "long.txt")

```

**Review by dbczumar — APPROVED** [review]
LGTM! Thanks so much, @szczeles @harupy !

**Pull request merged**
