### PR TITLE
Documentation: Add help file for R package

### PR DESCRIPTION
**Pull request by lorenzwalthert**
## What changes are proposed in this pull request?

Adding a help file for the package itself to the R package MLflow as suggested [by Hadley Wickham and Jenny Brian](https://r-pkgs.org/man.html#man-packages), generated with `usethis::use_package_doc()`. This provides an easy entry point from the command line to the package documentation and all exported functions (via Index) with `?mlflow`.

## How is this patch tested?

Inspected the git diff of the documentation.

### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

### What component(s) does this PR affect?

- [ ] UI
- [ ] CLI
- [ ] API
- [ ] REST-API
- [ ] Examples
- [x] Docs
- [ ] Tracking
- [ ] Projects
- [ ] Artifacts
- [ ] Models
- [ ] Scoring
- [ ] Serving
- [x] R
- [ ] Java
- [ ] Python

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Review by smurching — APPROVED** [review]
Just pushed a change to exclude the `mlflow-package` function from the actual hosted R docs & fix a small bug that prevented model registry URIs from appearing in the supported artifact URIs when R docs were regenerated - LGTM otherwise, thanks @lorenzwalthert!

**Comment by lorenzwalthert** [comment]
Well two things:

- Your doc regeneration is now convoluted with the significant roxzgen2 line updates, for which I filed a separate PR with #2258. I'd suggest to first merge this before discussing #2259 (sorry for not linking it here).
- I am not sure removing the `.Rd` file is a good idea because when using the documentation routine, it will also not be  available as a help file from R I believe, which was the purpose of the PR.

**Comment by smurching** [comment]
@lorenzwalthert thanks for the catch, agreed on both points - just went ahead & merged #2258, if you're able to add the `roxygen2::roxygenize()` call to `docs/build-rdoc.sh` I'm happy to take another look, thanks!

**Comment by lorenzwalthert** [comment]
Done @smurching.

**Comment by lorenzwalthert** [comment]
I adapted but accidentally removed a blank line that matters. Will fix this later.

**Comment by lorenzwalthert** [comment]
Fixed.

**Review by smurching — APPROVED** [review]
LGTM thanks @lorenzwalthert!

**Pull request merged**
