### PR TITLE
Removing container hostname from sagemaker, as it is ignored

### PR DESCRIPTION
**Pull request by tallen94**
## What changes are proposed in this pull request?
See issue for details https://github.com/mlflow/mlflow/issues/2747

## How is this patch tested?

I created a sagemaker deployment and validated that the container hostname is set to a value described in the AWS documentation if it is left out.
Screen Shot 2020-05-21 at 10 36 19 AM

- I built a docker image with mlflow installed at this revision. 
- I used [opctl](https://opctl.io/) to create a procedure around the `mlflow sagemaker deploy` command to deploy a simple trained model called `hello-model`

### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [x] `integrations/sagemaker`: SageMaker integrations

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by tallen94** [comment]
@tomasatdatabricks Hey, I was able to test this out successfully (screenshot of container name in description). However, it seems that the tests are failing on a Tensorflow test. Im not sure that my change is related to this, do you have any insight here or know someone that would?

**Comment by tomasatdatabricks** [comment]
@tallen94 Yeah the failure is not related to your change. I have restarted the test and we'll see. I'll merge if it passes, otherwise I'll take a look what's going on with the tf test.

**Review by tomasatdatabricks — APPROVED** [review]
lgtm!

**Comment by tomasatdatabricks** [comment]
@dbczumar Can you double check this change is ok?

**Review by dbczumar — APPROVED** [review]
LGTM!

**Pull request merged**
