### PR TITLE
Add artifact views in the CompareRunView

### PR DESCRIPTION
**Pull request by kopytjuk**
## What changes are proposed in this pull request?

Show artifacts of multiple runs in the CompareRunView.

Related FRs:

- https://github.com/mlflow/mlflow/issues/2696
- https://github.com/mlflow/mlflow/issues/3843

After opening:

image

After selecting in both runs:

image
 

## How is this patch tested?

n. a.

### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>
### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [x] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Review by R0ll1ngSt0ne — APPROVED** [review]
Looks good - please make it live as soon as possible :)

**Review by alintact — APPROVED** [review]

**Comment by jinzhang21** [comment]
Thanks for working on this PR, @kopytjuk. It's a very interesting idea, though I'm afraid I cannot merge the change as is to the master branch. I'm going to close this PR for now, but we are actively exploring UX ideas to make run comparison better. Stay tuned!

**Comment by semperigrinus** [comment]
@jinzhang21 

> Thanks for working on this PR, @kopytjuk. It's a very interesting idea, though I'm afraid I cannot merge the change as is to the master branch. I'm going to close this PR for now, but we are actively exploring UX ideas to make run comparison better. Stay tuned!

What are the current roadblocks to adding this feature?

**Comment by HasnainRaz** [comment]
@jinzhang21 Any updates on this feature? or a timeline?

For us comparing bayesian models (sampling stats, traces and distributions) is very necessary, so for those kinds of experiments, it is very valuable to be able to log and compare figures. Would love to see even a barebones version of this included.

**Comment by jinzhang21** [comment]
@HasnainRaz we are actively exploring UX designs for this feature. I don't have a timeline but the feature is definitely being considered.

**Comment by lukasz-gawron** [comment]
@jinzhang21 
Any updates on this feature? Are there any concrete plans to make this happen?

**Comment by HasnainRaz** [comment]
@jinzhang21 I think tensorboard implements this quite well (add_image command), maybe that UX is helpful?

**Pull request closed without merging**
