### PR TITLE
Add context manager for creating or using a spark session

### LINKED ISSUE #10034: Use a context manager when creating a spark session
### Summary

A context manager should be used when creating a spark session to kill it gracefully on error:

```diff
diff --git a/tests/models/test_signature.py b/tests/models/test_signature.py
index 78c1f3848..d8525d6bc 100644
--- a/tests/models/test_signature.py
+++ b/tests/models/test_signature.py
@@ -163,14 +163,14 @@ def test_signature_inference_infers_datime_types_as_expected():
     signature = infer_signature(test_df)
     assert signature.inputs == Schema([ColSpec(DataType.datetime, name=col_name)])
 
-    spark = pyspark.sql.SparkSession.builder.getOrCreate()
-    spark_df = spark.range(1).selectExpr(
-        "current_timestamp() as timestamp", "current_date() as date"
-    )
-    signature = infer_signature(spark_df)
-    assert signature.inputs == Schema(
-        [ColSpec(DataType.datetime, name="timestamp"), ColSpec(DataType.datetime, name="date")]
-    )
+    with pyspark.sql.SparkSession.builder.getOrCreate() as spark:
+        spark_df = spark.range(1).selectExpr(
+            "current_timestamp() as timestamp", "current_date() as date"
+        )
+        signature = infer_signature(spark_df)
+        assert signature.inputs == Schema(
+            [ColSpec(DataType.datetime, name="timestamp"), ColSpec(DataType.datetime, name="date")]
+        )
 
 
 def test_set_signature_to_logged_model():
diff --git a/tests/pyfunc/test_spark.py b/tests/pyfunc/test_spark.py
index 6d7cdf1bf..bc785469c 100644
--- a/tests/pyfunc/test_spark.py
+++ b/tests/pyfunc/test_spark.py
@@ -15,6 +15,7 @@ import pyspark
 import pytest
 from packaging.version import Version
 from pandas.testing import assert_frame_equal
+from pyspark.sql import SparkSession
 from pyspark.sql.functions import col, pandas_udf, struct
 from pyspark.sql.types import (
     ArrayType,
@@ -58,13 +59,13 @@ types = [np.int32, int, str, np.float32, np.double, bool]
 
 
 def score_model_as_udf(model_uri, pandas_df, result_type="double"):
-    spark = get_spark_session(pyspark.SparkConf())
-    spark_df = spark.createDataFrame(pandas_df).coalesce(1)
-    pyfunc_udf = spark_udf(
-        spark=spark, model_uri=model_uri, result_type=result_type, env_manager="local"
-    )
-    new_df = spark_df.withColumn("prediction", pyfunc_udf(*pandas_df.columns))
-    return [x["prediction"] for x in new_df.collect()]
+    with get_spark_session(pyspark.SparkConf()) as spark:
+        spark_df = spark.createDataFrame(pandas_df).coalesce(1)
+        pyfunc_udf = spark_udf(
+            spark=spark, model_uri=model_uri, result_type=result_type, env_manager="local"
+        )
+        new_df = spark_df.withColumn("prediction", pyfunc_udf(*pandas_df.columns))
+        return [x["prediction"] for x in new_df.collect()]
 
 
 class ConstantPyfuncWrapper:
diff --git a/tests/spark/test_spark_model_export.py b/tests/spark/test_spark_model_export.py
index ada83712c..fe6d135fa 100644
--- a/tests/spark/test_spark_model_export.py
+++ b/tests/spark/test_spark_model_export.py
@@ -122,9 +122,9 @@ def iris_pandas_df():
 def iris_df(spark_context):
     pdf = iris_pandas_df()
     feature_names = list(pdf.drop("label", axis=1).columns)
-    spark_session = pyspark.sql.SparkSession(spark_context)
-    iris_spark_df = spark_session.createDataFrame(pdf)
-    return feature_names, pdf, iris_spark_df
+    with pyspark.sql.SparkSession(spark_context) as spark:
+        iris_spark_df = spark.createDataFrame(pdf)
+        yield feature_names, pdf, iris_spark_df
 
 
 @pytest.fixture(scope="module")
```

### Notes

- Make sure to open a PR from a **non-master** branch.
- Sign off the commit using the `-s` flag when making a commit:

  ```sh
  git commit -s -m "..."
           # ^^ make sure to use this
  ```

- Include `#{issue_number}` (e.g. `#123`) in the PR description when opening a PR.

### PR DESCRIPTION
**Pull request by Dennis40816**
<details><summary>&#x1F6E0 DevTools &#x1F6E0</summary>
<p>

[Open in GitHub Codespaces](https://codespaces.new/Dennis40816/mlflow/pull/10050?quickstart=1)

#### Install mlflow from this PR

```
pip install git+https://github.com/mlflow/mlflow.git@refs/pull/10050/merge
```

#### Checkout with GitHub CLI

```
gh pr checkout 10050
```

</p>
</details>

### Related Issues/PRs

Resolve  #10034

### What changes are proposed in this pull request?
This PR introduces a context manager for the creation and usage of a spark session (`SparkSession`). Utilizing Python's `with` statement, the lifecycle of `SparkSession` instances can be more effectively managed, reducing the need for manual resource allocation and deallocation. 

### How is this PR tested?

- [ ] Existing unit/integration tests
- [ ] New unit/integration tests
- [ ] Manual tests

### Does this PR require documentation update?

- [x] No. You can skip the rest of this section.
- [ ] Yes. I've updated:
  - [ ] Examples
  - [ ] API references
  - [ ] Instructions

#### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

#### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>

#### How should the PR be classified in the release notes? Choose one:

- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by Dennis40816** [comment]
I apologize for not fully considering the extra work my commit may have caused you. I also have a couple of questions, if you don't mind answering:

1. I'm curious as to why the scope of your `with` statement extends into areas where it's not actually used. Are you concerned that variables derived there might be affected by the Spark session?
   
2. According to [CONTRIBUTING.md](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.md#:~:text=pre%2Dcommit%20run%20%2D%2Dall%2Dfiles%0A./dev/run%2Dpython%2Dtests.sh), Python tests are executed by running `run-python-tests.sh`. However, it appears that this shell script is not present in the current master branch's dev directory. Has it been replaced by `run-python-skinny-tests.sh`?

I hope these questions don't cause any inconvenience. Thank you for your time.

**Review by harupy — APPROVED** [review]
Pushed a few commits to fix CI failures, LGTM!

**Comment by harupy** [comment]
@Dennis40816 

For 1, I think a spark session needs to be alive until we consume spark dataframes or models.

For 2, we recently removed run-python-tests.sh. `CONTRIBUTING.md` needs t be updated.

**Comment by harupy** [comment]
For examples/multistep_workflow/train_keras.py, I think we can exit the spark session after the `toPandas` calls.

**Comment by Dennis40816** [comment]
Oh I got it! Thank you so much for your kind reply. I'm also grateful for this experience. Thank you.

**Pull request merged**
