### PR TITLE
Add run_name when specified in start_run tags

### LINKED ISSUE #7217: [BUG] run_name doesn't work with start_run
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

- Client: 1.30.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS Ventura 13.0
- **Python version**: 3.9.10
- **yarn version, if running the dev UI**: N/A

### Describe the problem

When using MLFlow with the context manager, the specified `run_name` isn't saved to the MLFlow UI.

This issue only happens with version 1.30.0, I tried the following versions as well: 1.27.0, 1.28.0 and 1.29.0. For all of those versions, the `run_name` was saved properly.

### Tracking information

MLflow version: 1.30.0
Tracking URI: https://XXX.com/
Artifact URI: s3://XXX/XXX/artifacts

### Code to reproduce issue

```python
import mlflow

mlflow.set_experiment("mlflow_issue_experiment")
with mlflow.start_run(run_name="test_version_1.30.0"):
    mlflow.log_metric("score", 1)
```

### Stack trace

N/A

### Other info / logs

_No response_

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

### PR DESCRIPTION
**Pull request by Cokral**
Signed-off-by: Thomas Coquereau <thomas.coquereau@klm.com>

## Related Issues/PRs

Resolve #7217 

## What changes are proposed in this pull request?

Set the MLFLOW_RUN_NAME in user_specified_tags when specified by the user in the parameters in the function `start_run`.

## How is this patch tested?

I edited an existing test to include the run_name in the expected tags, but I am unsure if that covers it. I wasn't able to run the unit tests locally `./dev/run-python-tests.sh` outputs `pytest: error: unrecognized arguments: --cov=./mlflow --cov-report tests`
- [X] Existing unit/integration tests
- [ ] New unit/integration tests
- [ ] Manual tests (describe details, including test results, below)

## Does this PR change the documentation?

- [X] No. You can skip the rest of this section.
- [ ] Yes. Make sure the changed pages / sections render correctly in the documentation preview.

### Is this a user-facing change?

- [X] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?
Components
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>
### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [X] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by harupy** [comment]
@Cokral Thanks for the PR!

> pytest: error: unrecognized arguments: --cov=./mlflow --cov-report tests

You can run `pip install pytest-cov` to fix this error.

**Comment by harupy** [comment]
https://github.com/mlflow/mlflow/actions/runs/3376334447/jobs/5604026210#step:5:633

```
FAILED tests/test_runs.py::test_list_run - mlflow.exceptions.MlflowException: Both 'run_name' argument and 'mlflow.runName' tag are specified. Remove 'mlflow.runName' tag.
```

We currently do not allow specifying both `run_name` and `mlflow.runName` tag. We need to relax this constraint.

**Comment by harupy** [comment]
```diff
diff --git a/mlflow/store/tracking/sqlalchemy_store.py b/mlflow/store/tracking/sqlalchemy_store.py
index d72f2395f..45d0ebea3 100644
--- a/mlflow/store/tracking/sqlalchemy_store.py
+++ b/mlflow/store/tracking/sqlalchemy_store.py
@@ -470,11 +470,10 @@ class SqlAlchemyStore(AbstractStore):
             )
             tags = tags or []
             run_name_tag = _get_run_name_from_tags(tags)
-            if run_name and run_name_tag:
+            if run_name and run_name_tag and (run_name != run_name_tag.value):
                 raise MlflowException(
-                    "Both 'run_name' argument and 'mlflow.runName' tag are specified. "
-                    "Remove 'mlflow.runName' tag.",
-                    INVALID_PARAMETER_VALUE,
+                    "Both 'run_name' argument and 'mlflow.runName' tag are specified, but with "
+                    f"different values (run_name='{run_name}', mlflow.runName='{run_name_tag}')."
                 )
             run_name = run_name or run_name_tag or _generate_random_name()
             if not run_name_tag:
```

**Comment by Cokral** [comment]
Thanks @harupy. It is a bit easier now that the tests run. Turns out `run_name_tag` is directly a str variable by the way!

**Comment by BenWilson2** [comment]
The rest store mock in `test_rest_store.py` https://github.com/mlflow/mlflow/blob/dab36dc4fd6ac6e442bb78c016e7813ced8c0a21/tests/store/tracking/test_rest_store.py#L173-L177 is missing the now-auto-generated tag that your code change created. Adding 
```python
ProtoRunTag(key="mlflow.runName", value="my name")
``` 
after line 177 (or wherever in there, sorting is not important) will fix that test failure.

**Comment by BenWilson2** [comment]
The other failures (on expected collisions throwing) will require some modifications
test failure location (one of them) : https://github.com/mlflow/mlflow/blob/dab36dc4fd6ac6e442bb78c016e7813ced8c0a21/tests/store/tracking/test_sqlalchemy_store.py#L854-L864

1. Validate that both the run_name top-level entry and the tag entry match when both run_name and the tag value match on instantiation of the `start_run()` context. (No exception should be thrown :) )
2. Force an exception to be thrown by submitting conflicting run_name and tag (mlflow.runName) values and that the Exception message body performs a partial match to your reworded Exception message.

Let us know if you need any further clarification or assistance with this :)

**Comment by Cokral** [comment]
Thanks @BenWilson2. I'll be able to continue working on it after work, I'll reach out if I need any further clarification / assistance.

**Comment by Cokral** [comment]
Hey! I still have issues running the unit tests locally. When running `pytest tests/store/tracking/test_sqlalchemy_store.py`, I get the error `sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:https`.

It prevents me from testing that part of the code and I then have to push to the remote branch to see whether it works or not :/
Have you guys heard of that / know how to fix it?

**Comment by harupy** [comment]
@Cokral I've never seen that error before. Can you run `python -c 'import mlflow; mlflow.doctor()'` and share the output?

**Review by harupy — APPROVED** [review]

**Comment by harupy** [comment]
LGTM!

**Comment by BenWilson2** [comment]
Great work, @Cokral ! Looking forward to your next contribution! :)

**Review by BenWilson2 — APPROVED** [review]
LGTM!

**Comment by amie-roten** [comment]
Hello! I just switched over to MLFlow 2.0.1, but am still having an issue with the .start_run() 'run_name' parameter propagating to the 'run.info.run_name' field. Same issue with the description parameter. I do see both of these populated correctly in the corresponding 'tags' field, but they are not propagating to the GUI.

Any suggestions?

**Comment by BenWilson2** [comment]
Hi @amie-roten could you run `mlflow.doctor()` from an interactive environment and paste the results here?

**Comment by amie-roten** [comment]
Sure, @BenWilson2 : 

```
>> mlflow.doctor()
System information: Linux #124-Ubuntu SMP Thu Apr 14 19:46:19 UTC 2022
Python version: 3.9.12
MLflow version: 2.0.1
MLflow module location: <local server location>
Tracking URI: <our URI>
Registry URI: <our URI>
Active experiment ID: 6
Active run ID: d947622518be470c95602b06cf0c14e7
Active run artifact URI: mlflow-artifacts:/6/d947622518be470c95602b06cf0c14e7/artifacts
MLflow environment variables: {}
MLflow dependencies: {
    "click": "8.1.3",
    "cloudpickle": "2.1.0",
    "databricks-cli": "0.16.6",
    "entrypoints": "0.4",
    "gitpython": "3.1.27",
    "pyyaml": "6.0",
    "protobuf": "3.19.4",
    "pytz": "2022.1",
    "requests": "2.27.1",
    "packaging": "21.3",
    "importlib-metadata": "4.11.4",
    "sqlparse": "0.4.2",
    "alembic": "1.7.7",
    "docker": "5.0.3",
    "Flask": "2.0.0",
    "numpy": "1.21.5",
    "scipy": "1.8.1",
    "pandas": "1.4.2",
    "querystring-parser": "1.2.4",
    "sqlalchemy": "1.4.36",
    "scikit-learn": "1.0",
    "pyarrow": "10.0.0",
    "shap": "0.41.0",
    "markdown": "3.3.7",
    "matplotlib": "3.5.2",
    "gunicorn": "20.1.0",
    "Jinja2": "3.1.2"
}
```

**Pull request merged**
