### PR TITLE
make patched function still available after autolog disabled

### PR DESCRIPTION
**Pull request by WeichenXu123**
Signed-off-by: Weichen Xu <weichen.xu@databricks.com>

## What changes are proposed in this pull request?

Simple test:

```
import mlflow
mlflow.sklearn.autolog()
from sklearn.metrics import accuracy_score
mlflow.sklearn.autolog(disable=True)
accuracy_score([1,1],[0,1])  # ensure this call still works and behave the same with original function
```

## How is this patch tested?

N/A

### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>
### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by harupy** [comment]
@WeichenXu123 Can you add tests?

**Comment by dbczumar** [comment]
@WeichenXu123 Does this issue only come up during new scikit-learn `predict()` method patching, or is it a problem for existing calls to `fit()` as well?

**Comment by dbczumar** [comment]
> @WeichenXu123 Does this issue only come up during new scikit-learn `predict()` method patching, or is it a problem for existing calls to `fit()` as well?

Looks like this is an issue when we've imported a function from a module and then disable autologging after the import. I'll file an equivalent Universe PR for this. Nice catch, @WeichenXu123 !

**Comment by WeichenXu123** [comment]
@dbczumar 
I create a new PR to replace this:
https://github.com/mlflow/mlflow/pull/4631

because there's some other issues we can fix togethor.

**Pull request closed without merging**
