### PR TITLE
remove temp dir after local run in block mode

### PR DESCRIPTION
**Pull request by adrian555**
Temporary directory is created to save the fetched git project during mlflow run. This directory was not deleted after the run completed.

This PR adds rmtree call to remove this temporary directory.

### CODE REVIEW

**Comment by adrian555** [comment]
@smurching gently ping. :)

**Comment by smurching** [comment]
Hi @adrian555, sorry for the delay & thanks for the contribution! Just wanted to ask - what was the original motivation for this PR?

I can see that removing the tempdir used to fetch a project helps avoid leaking tempdirs, but IMO it complicates `mlflow.projects.run`'s behavior to do so only for blocking runs, since output files to the tempdir written during project execution may or may not exist depending on whether you ran in blocking mode. Curious to hear your thoughts, & thanks again for working on this :)

**Comment by adrian555** [comment]
@smurching thanks for looking at this. I am fully aware of the fact that the temp directories may be cleared on reboot etc. so that is not my concern. 

My problem is that I am seeing for every run, my disk space becomes 200MB less since the ML project I am running from local git repo contains not just the code but also the data. And I can run many times of the project every day. Sure, we can argue that the better solution could be to move the data out of the git repo. But that is a different topic. Then I also believe that it is a good coding practice to clean up temporary directory/file.

And btw, the PR checks whether tmpdir exists before removes.

**Comment by smurching** [comment]
Got it, yeah I do agree that cleaning up temporary directories is generally a good practice. For your use case, another possibility would be cloning the project locally - we don't create/use a tempdir to fetch projects already on the local filesystem.

My main ask is that we think through whether there's a way to do so in a way that's consistent across different run modes & captures the different tempdirs we generate during a run (for example, in addition to the tempdir we use for fetching projects, we also create a tempdir that's used to store artifacts passed to parameters of type `path` as specified by the `storage_dir` argument, and we should also try not to leak that directory).

One approach could be to modify `_run_entry_point_command` so that it accepts a list of directories to remove after the command executes. We could then augment the entry point shell command to also perform an `rm -r <dir-to-remove>` (after running the entry point) for each of the target directories. This would allow us to not leak tempdirs for async runs as well, & as future work also remove the `storage_dir` used for the run.

BTW, I think it's also worth considering how removing projects' working directories could affect future extensibility to e.g. running code from GitHub that's entirely unaware of MLflow (e.g. the TensorFlow examples, which write files to the working directory & where it might actually be undesirable to remove the working directory). However if this ends up being a major use case, I think we could just add a flag later on that disables the removal of tempdirs.

**Comment by smurching** [comment]
Just chatted with @aarondav - I actually missed the part about your git repository being a local repository. What exactly does your `mlflow run` command / `mlflow.projects.run()` call look like? If you're doing `mlflow run <some-local-path>`, the expected behavior is that we actually don't copy `<some-local-path>` into a tempdir, so if that's happening it's a bug.

More generally, another workaround could be to just configure the base tempdir used for the runs yourself e.g. by setting the `TMPDIR` environment variable as documented [here](https://docs.python.org/2/library/tempfile.html#tempfile.tempdir). You could then periodically clean out the base tempdir - managing the lifecycle of temporary directories is tough to reason about given async runs, since an async run may kick off other async runs of the same project (e.g. via `mlflow.run(".")`).

**Comment by adrian555** [comment]
Thanks @smurching and really appreciate. Yes, I had considered the other cases including the async executions. Therefore I only tackled the very specific and simple case. And I am with you that there are workarounds that can be done. My original thought was just to handle a situation that annoys me just a little bit. :)

So here is what I ran. I have `git clone` a project to my local directory. And I need to run the MLproject with a version. In current MLflow, the only way to achieve this is to run it such as this:
`mlflow run file:///Users/adrian555/mlflow#example/tutorial -v 87a421d0d4ff3f8668123cdc535ec23bf42443e6 -P alpha=2`. (Note that you can not specify a version for a local path hence the `file:` prefix.) Such run did fetch the project again to the temp directory.

And btw, I had also thought about a possible cleaner temp dir cleanup solution. Like in R, you can create an environment, or session, context as you like to call, and then register all the stuff that needs to clean up at the end. So for the stuff created during create run, they should be cleaned at the end of end run.

**Comment by adrian555** [comment]
@smurching any more comments on this please. :)

**Comment by smurching** [comment]
@adrian555 thanks for clarifying & sorry again for the delay - is there a reason you need to specify the version of the local project in your `mlflow run` command? I'm curious if it'd work to check out the commit you want to run against locally (e.g. `cd Users/adrian555/mlflow && git checkout 87a421d0d4ff3f8668123cdc535ec23bf42443e6`) and then run the project without specifying a version via `mlflow run /Users/adrian555/mlflow#example/tutorial -P alpha=2`. MLflow should still record the git version of the project & this way you could repeatedly run a specific version of your local project without creating temporary directories. Just want to make sure I fully understand your use case & see if there's a way we can satisfy it without modifying the existing logic, since a complete solution around removing tempdirs will likely take some extra design work. Thanks again for bringing this up!

**Comment by adrian555** [comment]
Thanks @smurching! Reason I provided a version is that currently MLflow does not support a `branch` option so version is the only way for me to run the same project with different source codes.

I recognized that you have concern on a temp solution for an issue that bothers some use case. I am fine if there is some work on going to address such cleanup issue.

Thanks again.

**Comment by smurching** [comment]
Hey @adrian555, just wanted to check on this - did either of the suggested workarounds (setting the `TMPDIR` environment variable to simplify cleaning out tempdirs or manually checking out the desired branch/version of a local git project) work for you? Just wanted to try to close out this PR - if there are issues / bugs with the workarounds, let's make a separate issue to track those. Thanks!

**Comment by adrian555** [comment]
@smurching sorry for the delay. I was supposed to close this PR.

**Pull request closed without merging**
