### PR TITLE
Updating torch version to latest stable release - 1.6.0

### PR DESCRIPTION
**Pull request by shrinath-suresh**
## What changes are proposed in this pull request?

Updating torch version to recent stable release - 1.6.0.  

## How is this patch tested?

Verified `mlflow/tests/pytorch/test_pytorch_model_export.py` and `mlflow/examples/pytorch/mnist_tensorboard_artifact.py` with pytorch 1.6.0. 

### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [x] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Review by smurching — COMMENTED** [review]
@shrinath-suresh thanks for the PR! We should definitely make sure we test against the latest pytorch :) (cc @apurva-koti who was also looking at bumping test dependency versions). It looks like one of the unit tests fails with torch 1.6.0 - would you have bandwidth to take a look at why?

**Review by smurching — COMMENTED** [review]
LGTM if we can fix the test breakage!

**Comment by shrinath-suresh** [comment]
> @shrinath-suresh thanks for the PR! We should definitely make sure we test against the latest pytorch :) (cc @apurva-koti who was also looking at bumping test dependency versions). It looks like one of the unit tests fails with torch 1.6.0 - would you have bandwidth to take a look at why?

@smurching Sure. I will check. With 1.6.0, i checked the pytorch test cases. Looks like the failure is on fastai test case. I will debug and let you know.

**Comment by shrinath-suresh** [comment]
@smurching Shall we update the cloud pickle version too ? Eventhough we are going to remove it from main script, cloud pickle is still used for the test script (where user wants to override default pickle argument) . Moreover,  I am facing error when using `mlflow.pytorch.log_model` with the model trained with pytorch lightning (not seeing the error with latest version of cloud pickle). Let me know your thoughts on it.

**Comment by shrinath-suresh** [comment]
> > @shrinath-suresh thanks for the PR! We should definitely make sure we test against the latest pytorch :) (cc @apurva-koti who was also looking at bumping test dependency versions). It looks like one of the unit tests fails with torch 1.6.0 - would you have bandwidth to take a look at why?
> 
> @smurching Sure. I will debug and let you know.

@smurching Figured out the reason why [test_load_model_allows_user_to_override_pickle_module_via_keyword_argument](https://github.com/mlflow/mlflow/blob/4f700b56cf0e389b31b67388947725da99221ef6/tests/pytorch/test_pytorch_model_export.py#L761) is getting failed. 

torch 1.6 saves the model as zip file and uses [_load](https://github.com/pytorch/pytorch/blob/6c4aa2a79cc6bfc720a958af569a9c80c0379e77/torch/serialization.py#L594) method and in turn uses [pickle_module.Unpickler](https://github.com/pytorch/pytorch/blob/6c4aa2a79cc6bfc720a958af569a9c80c0379e77/torch/serialization.py#L851) to load the model.

whereas in torch 1.4 , `torch.load`  loads via [_legacy_load](https://github.com/pytorch/pytorch/blob/6c4aa2a79cc6bfc720a958af569a9c80c0379e77/torch/serialization.py#L595) and uses [pickle_module.load](https://github.com/pytorch/pytorch/blob/6c4aa2a79cc6bfc720a958af569a9c80c0379e77/torch/serialization.py#L764) to load the model. 

Test case is passing locally by setting `mlflow_torch_pickle_load` to `mlflow_pytorch_pickle_module.Unpickler`.

**Comment by shrinath-suresh** [comment]
@apurva-koti @smurching  Getting some random linting failure - (mlflow/mlflow/pytorch/pickle_module.py). should i need to push any dummy change to restart the linting build or is there any other way to re-run the build ?

**Comment by apurva-koti** [comment]
@shrinath-suresh , you can re-run the build by clicking on the details link in the failed check, and pressing the "re-run workflows" button on the checks page.

**Comment by shrinath-suresh** [comment]
> @shrinath-suresh , you can re-run the build by clicking on the details link in the failed check, and pressing the "re-run workflows" button on the checks page.

@apurva-koti  I dont see the "re-run workflows" button on the checks page (may be due to lack of permission ??). i will try command line option to add one more commit. 
github

**Comment by apurva-koti** [comment]
Ah sorry! Probably a permissions issue. Let me take a look at this now you've addressed the lint issue.

**Review by apurva-koti — APPROVED** [review]
LGTM. Current failures are on master and unrelated to this PR.

Thanks @shrinath-suresh !

**Comment by shrinath-suresh** [comment]
@smurching Thank you very much. Can we merge the PR if the changes are fine?

**Review by smurching — APPROVED** [review]
LGTM

**Comment by smurching** [comment]
@shrinath-suresh yes! Done :)

**Pull request merged**
