### PR TITLE
[UI] Update react-mde to the latest version

### PR DESCRIPTION
**Pull request by harupy**
## What changes are proposed in this pull request?

- Update `react-mde` to the latest version (7.6.2) for more straightforward state handling.
- Add tooltip to the command buttons.

update-react-mde

## How is this patch tested?

Manually tested

### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [x] Yes. Give a description of this change to be included in the release notes for MLflow users.

### What component(s) does this PR affect?

- [x] UI
- [ ] CLI
- [ ] API
- [ ] REST-API
- [ ] Examples
- [ ] Docs
- [ ] Tracking
- [ ] Projects
- [ ] Artifacts
- [ ] Models
- [ ] Scoring
- [ ] Serving
- [ ] R
- [ ] Java
- [ ] Python

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [x] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Review by Zangr — APPROVED** [review]
Pretty nice upgrade, LGTM!

**Comment by harupy** [comment]
Is it possible to replace `NoteEditorView .js` with `EditableNote.js`?

**Comment by Zangr** [comment]
@harupy, yes we do want to replace the remaining 1 usage of NoteEditorView/NoteShowView in experiment page with EditableNote. Would you like to submit a PR?

**Comment by harupy** [comment]
@Zangr Yes, I'll create a PR to fix it.

**Pull request merged**
