### PR TITLE
Add ability to visualize CSVs in data grid

### PR DESCRIPTION
**Pull request by aadamson**
This PR adds the ability to view CSV file (and similar files such as tab-separated value files) in the artifact viewer. It adds papaparse (for CSV parsing) and react-data-grid (for displaying the data) as dependencies. 

All parsing and processing is done in the browser. This isn't necessarily ideal - I would have preferred to use something like [qgrid](https://github.com/quantopian/qgrid) that could use pandas for filtering, sorting, etc server-side, but doing everything in the browser is much more lightweight. The obvious downside to this is that trying to load very large CSV files can crash the browser. One approach that I was considering to mitigate this would be simply to only display CSV files under a certain size (say 10MB).

image

### CODE REVIEW

**Comment by aadamson** [comment]
Now trimming so that it only shows/loads the first 10000 rows and displays an alert when it hits that limit:
image

**Comment by mateiz** [comment]
That's pretty cool, but beware that some CSVs have a lot of columns so 10,000 rows might still be a lot of data. Is there any eas way to limit data to a certain number of MB instead? Or choose a round number of rows that's lower (for example 100, 1000 or 10000) based on the size of each row.

BTW, I've looked at a bunch of React grids for the main experiment list too, and I was wondering what you think of https://react-table.js.org/ and https://bvaughn.github.io/react-virtualized/#/components/Grid as alternatives. React-data-table is also one that I looked at. Have you used it successfully in other projects?

**Comment by aadamson** [comment]
The size issue can be addressed by setting the chunk size and only parsing the first few chunks (this wouldn't directly limit how large the array contents would be in memory, but it would be limited to some multiple of the number of chunks read * size of chunks).

I didn't honestly dig too deep on what library to use for the table since it was going to be pretty lightweight use of it (I don't really need anything other than a sortable, bare HTML table). That said, getting the size of the table right was pretty painful, so I'll explore those libraries you linked. Do you have a preference/history with either? react-virtualized looks really well supported

**Comment by mateiz** [comment]
No, I haven't tried them in detail yet. Going by # of GitHub stars, it seems that react-virtualized and react-table are more popular so that's why I wanted to give them a shot, but we don't have to overthink it here. We can switch these around later too.

**Comment by aadamson** [comment]
Yeah, I saw 2000 stars on react-data-grid and thought that was a lot. I'm very new to JS and didn't really have an appreciation for the number of people involved lol

**Comment by aadamson** [comment]
@mateiz gunicorn doesn't support byte-range headers out of the box, so I was mistaken in thinking that I had a way to control how much data I download from the server. We can add middleware that gives us support for byte-range, but that feels heavy-handed to support something like this. 

I think it might make sense to have the behavior be to a) always download the whole CSV and then b) stop parsing and toss the rest of the CSV after the parsed data exceeds let's say 100MB (or some other limit) in memory. We could place an absolute limit on the size of CSVs to be downloaded (say 1GB) so that we don't crash the browser while downloading. What do you think?

**Comment by hamroune** [comment]
I suggest using Handsonetable, they have excellent performance, also they have react-component, 
They have also COPY-PASTE feature, so in the future, if we need to do some inference in the Run page view, it will be easy to from excel to Handsonetable
the link:
https://handsontable.com/examples

**Comment by whiletruelearn** [comment]
@aadamson Just a thought that came across, rather than sending the entire [file](https://github.com/mlflow/mlflow/blob/master/mlflow/server/handlers.py#L81) , can we read the file at server side and create a minimalized file of say first 10k lines which can be send back to client. This might be needed only for `csv` , `tsv` and `txt` files as the other files we would expect to the be reasonably small. 

Currently i have also come across issues where the browser just crashes because of the large size of the file. 
cc : @mateiz

**Comment by aadamson** [comment]
@whiletruelearn I was hoping to get this out without any server-side changes. Limiting it to `n` lines on the server could be error-prone if e.g. `n` lines leaves you in the middle of a quoted field. If we end up having server-side parsing, I'd like to just go the whole way and implement server-side pagination of CSVs/TSVs/etc.

Can you give me an example of a CSV that crashes your browser on this branch?

**Comment by aadamson** [comment]
@whiletruelearn You're right, I could repro your browser crash with a modest CSV (100MB) on my machine. To be conservative, I've gone ahead and made the download limit low (10MB) to prevent peak heap usage from being much beyond that.

**Comment by aadamson** [comment]
@smurching can someone take a look at this? I'm happy to rework this in anyway you guys would like!

**Comment by smurching** [comment]
@aadamson yep happy to take a pass!

**Review by smurching — COMMENTED** [review]
@aadamson thanks for the PR, it looks pretty good! One nit - for CSVs with lots of columns, it looks like the sort toggle overlaps with the column name - see this screenshot (& see [this dataset](https://catalog.data.gov/dataset/demographic-statistics-by-zip-code-acfc9) to reproduce):
screen shot 2018-09-28 at 1 11 00 am

If there's a way we could address that it'd be great, maybe by truncating the column name via the `text-overflow: ellipsis` CSS attribute (this PR tries to do something similar [here](https://github.com/mlflow/mlflow/pull/476/files#diff-028a0b3d67336af7095ba0f71c96a9f4R172))

**Comment by smurching** [comment]
Hey @aadamson, thanks again for the patch! Just wanted to check in on this - would you be interested in continuing with this PR? It's a cool feature, we'd be happy to help tweak it & get it merged.

**Comment by AndersonReyes** [comment]
@smurching @aadamson any plans for this PR this would be super useful?

**Comment by jdlesage** [comment]
This is a great PR. We use to store also parquet files in artifacts. Do you think this feature can be used to get a preview of the data ? I can help to implement the parquet reader after you merge this PR but I will need some advice. I imagine in case of parquet files, server will have to read it (using pyarrow) and send to the javascript the values in tabular format. Wdyt ?

**Comment by r12king** [comment]
Any update on this? Would love to see this PR merged in as a feature we could use in mlflow.

**Comment by pogil** [comment]
Hey team, we've learned a lot about good components for displaying tabular data since this pull request. We'd recommend implementing this functionality using [ag-grid](https://ag-grid.com). I've closed this PR in favor of a new open feature request issue (https://github.com/mlflow/mlflow/issues/2617). We'd love help on this and @Zangr can give pointers if someone wants to pick this up.

**Pull request closed without merging**
