### PR TITLE
Fix protobuf id collision

### PR DESCRIPTION
**Pull request by vgod-dbx**
## What changes are proposed in this pull request?
 
* Added package `mlflow` to `databricks.proto` to avoid naming collision
* Replace the field numbers with something that is less likely to collide. (50000 is the widely used in the protobuf examples.)

## How is this patch tested?
 
* All unit tests should pass
 
### Is this a user-facing change? 

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.
 
(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)
 
### What component(s) does this PR affect?
 
- [ ] UI
- [ ] CLI 
- [x] API 
- [ ] REST-API 
- [ ] Examples 
- [ ] Docs
- [ ] Tracking
- [ ] Projects 
- [ ] Artifacts 
- [ ] Models 
- [ ] Scoring 
- [ ] Serving
- [ ] R
- [ ] Java
- [ ] Python

### How should the PR be classified in the release notes? Choose one:
 
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by aarondav** [comment]
Are there any backwards-compatibility implications of changing this number? Since the extension is not part of the serialized message, I would guess that in general it would not be, as long as the recipient server has recompiled both the target and this protobuf.

**Comment by vgod-dbx** [comment]
As long as the server and the client use the same protobuf, there's no backwards-compatibility issues.

**Comment by aarondav** [comment]
Er, but isn't it the exact problem that the server and client are unlikely to use the same protobuf?

**Comment by aarondav** [comment]
I am pretty confident that changing these extension numbers will not cause a problem, even if the client & server disagree on them. In particular, I do not think they are included in the serialized form.

As a result, I think we're OK to merge this. Mind rebasing and regenerating one more time?

**Comment by vgod-dbx** [comment]
Cool! Rebased. Thanks for the review!

**Comment by aarondav** [comment]
Thanks - merged!

**Pull request merged**
