### PR TITLE
correct missing tensorboardX module error in pytorch example when running in mlflow docker container 

### PR DESCRIPTION
**Pull request by jimthompson5802**
When running the [pytorch](https://github.com/jimthompson5802/mlflow/tree/master/examples/pytorch) example in the MLflow docker container, receive error message on import from tensorboardX.

- Error symptom.  Executing this command:

```
docker run --rm mlflow_testbed python examples/pytorch/mnist_tensorboard_artifact.py --epochs 1
```
results in these messages
```
Traceback (most recent call last):
  File "examples/pytorch/mnist_tensorboard_artifact.py", line 23, in <module>
    from tensorboardX import SummaryWriter
ImportError: No module named tensorboardX
```

- Added tensorboardX to test-requirements.txt and rebuilt docker image and successful run.

Execute the command:
```
docker run --rm mlflow_testbed python examples/pytorch/mnist_tensorboard_artifact.py --epochs 1
```
results in these messages
```
Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz
Downloading http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz
Downloading http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz
Downloading http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz
Processing...
Done!
Writing TensorBoard events locally to /tmp/tmpmhsc0u

Train Epoch: 1 [0/60000 (0%)]	Loss: 4.178357
Train Epoch: 1 [6400/60000 (11%)]	Loss: 3.857538
Train Epoch: 1 [12800/60000 (21%)]	Loss: 3.474207
Train Epoch: 1 [19200/60000 (32%)]	Loss: 3.196815
Train Epoch: 1 [25600/60000 (43%)]	Loss: 3.009940
Train Epoch: 1 [32000/60000 (53%)]	Loss: 2.768187
Train Epoch: 1 [38400/60000 (64%)]	Loss: 2.730309
Train Epoch: 1 [44800/60000 (75%)]	Loss: 2.652601
Train Epoch: 1 [51200/60000 (85%)]	Loss: 2.800699
Train Epoch: 1 [57600/60000 (96%)]	Loss: 2.464437

Test set: Average loss: 2.2250, Accuracy: 9238/10000 (92%)

Uploading TensorBoard events as a run artifact...

Launch TensorBoard with:

tensorboard --logdir=/app/mlruns/0/ca6ac56034374faaa21eca3e11bf0c19/artifacts/events
```

Edit:  Added example of error and fix.

### CODE REVIEW

**Comment by dbczumar** [comment]
@jimthompson5802 Thank you for the contribution. After discussing it with the team, we feel that it may make sense to introduce an `MLproject` specification with a `conda.yaml` specification that enumerates the required dependencies, including `matplotlib` (just like the example you tweaked in #829). 

Ideally, the `Dockerfile` included in the repository root is intended to include the minimal set of dependencies for developing MLflow and running existing tests, so I'd like to avoid extending the set of test requirements (which are also installed for every Travis build) as much as possible.

Would you be willing to add an `MLproject` with a Conda environment for this example? Users could then execute `mlflow run ...` inside the Docker container to achieve the desired result.

**Comment by jimthompson5802** [comment]
@dbczumar Yes I can convert to the `MLProject` structure.

**Comment by jimthompson5802** [comment]
@dbczumar  Requesting some guidance.  

Is there a preference on how parameters are passed to a Python program?  The current pytorch example uses the `argparse` package.  Sample code that uses the `MLProject` structure use the `click` package.

With the exception of a parameter `--no-cuda` used in the pytorch example, I can set up the `mlflow run . -P ....` construct to work with `argparse`.  The issue with `--no-cuda` is that this parameter is basically a boolean flag whose presence or absence set a variable `True` or `False`.  

From what I can tell the `mlflow run . -P key=value` expects to see a value.  When I try to `mlflow run . -P no-cuda`, the generated command contains '', this seems to cause `argparse` issues. 

One solution is to force a value like `-P no-cuda=False` or `P no-cuda=True`.  This will require modifying the Python program to handle this change.

If I have to change the program anyway, would it be preferred, I use the `click` package to make this consistent with the other examples that use the `MLProject` construct?

**Comment by dbczumar** [comment]
Hi @jimthompson5802, I think it makes sense to change the existing `--no-cuda` flag in `argparse` to a `cuda` boolean variable; I don't see a need to switch from `argparse` to `click`. The MLproject `cuda` boolean parameter could be given a default value of `True` to create the same default behavior. Does that make sense?

**Comment by jimthompson5802** [comment]
@dbczumar thank you for the guidance.  I'll keep `argparse` package.  

I've completed the changes.  It is ready for your review.  

Here is the log from a test run:
[pytorch_example_mlproject_macbook.txt](https://github.com/mlflow/mlflow/files/2789993/pytorch_example_mlproject_macbook.txt)

**Comment by jimthompson5802** [comment]
@dbczumar I've completed conversion to `MLProject` structure.  Ready for review.

Here is the log from a test run:
[sklearn_diabetes_mlproject_testrun.txt](https://github.com/mlflow/mlflow/files/2790121/sklearn_diabetes_mlproject_testrun.txt)

**Comment by jimthompson5802** [comment]
@dbczumar my bad...in re-reading your guidance, I realized that I glazed over the guidance on changing parameter orientation from  `--no-cuda` to `--cuda`.  I focused on mainly the `argparse` vs `click` package guidance.  I'll make the parameter orientation change shortly.

**Comment by jimthompson5802** [comment]
@dbczumar completed change orientation of the `coda` flag.

Log of test runs:
[pytorch_example_mlproject_testrun2.txt](https://github.com/mlflow/mlflow/files/2791324/pytorch_example_mlproject_testrun2.txt)

**Comment by jimthompson5802** [comment]
closing to restart travis ci build

**Comment by jimthompson5802** [comment]
reopen to restart travis ci build

**Review by dbczumar — APPROVED** [review]
LGTM! Thanks @jimthompson5802

**Pull request merged**
