### PR TITLE
Pin Python to 3.9 for statsmodels dev version

### PR DESCRIPTION
**Pull request by B-Step62**
<details><summary>&#x1F6E0 DevTools &#x1F6E0</summary>
<p>

[Open in GitHub Codespaces](https://codespaces.new/B-Step62/mlflow/pull/10771?quickstart=1)

#### Install mlflow from this PR

```
pip install git+https://github.com/mlflow/mlflow.git@refs/pull/10771/merge
```

#### Checkout with GitHub CLI

```
gh pr checkout 10771
```

</p>
</details>

### What changes are proposed in this pull request?

Statsmodels dev version requires Python 3.9 ([commit](https://github.com/statsmodels/statsmodels/commit/1d5492e748bee85477953b1dc62b33a9273e9cf5)).

Hardcoded Python version in cross-version test to 3.9 and also moved logic to Python script to avoid further complication.

### How is this PR tested?

- [x] Existing unit/integration tests
- [ ] New unit/integration tests
- [ ] Manual tests

Validated cross version tests passed with dev version using dummy commit.

### Does this PR require documentation update?

- [x] No. You can skip the rest of this section.
- [ ] Yes. I've updated:
  - [ ] Examples
  - [ ] API references
  - [ ] Instructions

#### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

#### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [x] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>

#### How should the PR be classified in the release notes? Choose one:

- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by BenWilson2** [comment]
Curious to hear your thoughts on leaving `get_requires_python` as abstract as possible. 

What do you think of adding a param to the function that defines the dev fallback?

```python
def get_requires_python(package: str, version: str, dev_package_fallback_versions: t.Dict[str, str]) -> t.Optional[str]:
    if version == "dev" and package in dev_package_fallback_versions:
        return dev_package_fallback_versions[package]

    resp = requests.get(f"https://pypi.python.org/pypi/{package}/json")
    resp.raise_for_status()
    return next(
        (
            distributions[0].get("requires_python")
            for ver, distributions in resp.json()["releases"].items()
            if ver == version and distributions
        ),
        None,
    )
```

And then doing something like this to have full control over the versions of dev packages (just so that if some new library decides to jump to Py3.10 for some reason, we're not stuck with bumping all of the versions up?

```yaml
      - name: Get Python version
        id: get-python-version
        run: |
          DEV_PACKAGE_FALLBACK_VERSIONS='{"tensorflow": ">=3.9", "scikit-learn": ">=3.9", "statsmodels": ">=3.9"}'
          python_version=$(python dev/get_minimum_required_python.py -p ${{ matrix.package }} -v ${{ matrix.version }} --python-versions "3.8,3.9" --dev-package-fallback-versions "$DEV_PACKAGE_FALLBACK_VERSIONS")
```

**Comment by B-Step62** [comment]
I agree with having dictionary to allow different versions! But I would hardcode it to Python script rather than args, so we don't have to hop between files. We don't reuse this in multiple shell scripts so it doesn't have to be parameters.

**Comment by BenWilson2** [comment]
> I agree with having dictionary to allow different versions! But I would hardcode it to Python script rather than args, so we don't have to hop between files. We don't reuse this in multiple shell scripts so it doesn't have to be parameters.

SGTM! Yeah, let's change to a Dict in the .py file as a constant, rename the constant variable to generic "dev" instead of a particular version of python and keep the cleaner new yaml implementation :)

**Review by WeichenXu123 — APPROVED** [review]

**Comment by WeichenXu123** [comment]
> > I agree with having dictionary to allow different versions! But I would hardcode it to Python script rather than args, so we don't have to hop between files. We don't reuse this in multiple shell scripts so it doesn't have to be parameters.
> 
> SGTM! Yeah, let's change to a Dict in the .py file as a constant, rename the constant variable to generic "dev" instead of a particular version of python and keep the cleaner new yaml implementation :)

This suggestion makes sense, let's keep yaml file simple :)

**Review by BenWilson2 — APPROVED** [review]
LGTM! Thanks for the fix :)

**Pull request merged**
