### PR TITLE
[R] Fix broken h2o archive link

### PR DESCRIPTION
**Pull request by harupy**
Signed-off-by: harupy <17039389+harupy@users.noreply.github.com>

## What changes are proposed in this pull request?

The h2o archive link (`https://cran.r-project.org/src/contrib/h2o_3.30.1.3.tar.gz`) is broken. This PR fixes it.

https://github.com/mlflow/mlflow/pull/3542/checks?check_run_id=1273179681#step:9:141

Screen Shot 2020-10-19 at 13 46 22

## How is this patch tested?

Unit tests

### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [x] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [x] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [x] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Review by smurching — APPROVED** [review]
LGTM to unbreak the build - maybe @yitao-li or @lorenzwalthert can comment on the version-pinning approach we're using here & whether it's standard/stable in R?

**Comment by yitao-li** [comment]
Hey @smurching @harupy I feel like I might be missing something there:

in my original implementation of H2O model mismatch in H2O patch version was ignored (see https://github.com/mlflow/mlflow/pull/3416#discussion_r507949778), and that logic was removed in https://github.com/mlflow/mlflow/pull/3477/files (and '>=' replaced with '==' as well for version requirement) -- I think a potential problem with that approach is `utils::packageVersion("h2o")` returns the version of the H2O R package, but that version is not necessarily in sync with the H2O Python package all the time, so, requiring an exact match might not work some of the times

**Comment by lorenzwalthert** [comment]
All I can say is that for XGBoost as implemented in #3085, we write the XGBoost version to the conda env file with the patch version striped and hope it exists for R and Python - but I don't think we test this anywhere. I don't know if you also write h20 versions to conda eng files. For testing, we use the latest version of both R and Python and it does not seem as this ever caused trouble. 

Unrelated: My experience with XGBoost was anyways that the conda environment was not used, which I think is a bug.

**Comment by lorenzwalthert** [comment]
Also, @smurching I think once a package is archived from CRAN using this link is save. But this means you can't ever pin a current version (because these don't live under /archived). More elegant is to use `remotes::install_version(version = ...)` and pin a version there if this is possible with the other install options you want to supply.

**Pull request merged**
