### PR TITLE
Add singularity container to project

### PR DESCRIPTION
**Pull request by vsoch**
## What changes are proposed in this pull request?

I'd like to propose adding Singularity containers as an option, akin to Docker! Singularity containers can be run on an HPC cluster, albeit we would need sudo for building from a base image (so perhaps the use case isn't quite right?) I'm opening this as a draft PR because I have several questions / things to discuss.

### black
What version of black do you use for formatting? I tried running black locally and most files were re-formatted, so I'm guessing I have a newer version.

### options vs args
akin to docker_args, singularity has base and command options, along with arguments you can add to the command itself. E.g.,

```
singularity <client-options> exec <command-options> <container> <args>
```
How should those map here, and do we need a different spec input?

### fakeroot
I'm wondering if [fakeroot]() should be used by default so that sudo is not needed. I'm also wondering what the purpose of having a base image is - is there any reason the user cannot provide an existing image under the `singularity_env.image` and use as is?

### common class
There is quite a bit of redundancy between docker and singularity, and I'm wondering if you would be interested in a refactor to have a common ContainerProject class. Also, why is it called a project? In other workflow manager terms, I'd think of Singularity as an executor or just a runtime container environment.

### testing
How would you like testing done? Singularity typically needs to be installed natively in the CI environment

### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [x] Yes. Give a description of this change to be included in the release notes for MLflow users.

Users will be allowed to use singularity_env in their project files.

### What component(s), interfaces, languages, and integrations does this PR affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [x] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [x] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [x] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

So - mostly just discussion for now! I'm especially interested in discussing some kind of common base, because there isn't any reason some other container technology (or similar) might come around, and it should be easy / non-redundant to plug in.

### CODE REVIEW

**Comment by Zethson** [comment]
@vsoch I have the same issues with using MLflow in HPC environments and am very happy to see that you pick this up!

Since I did not see it at a glance. Does your implementation allow for arbitrary Singularity parameters?

To access GPUs inside Singularity we for example need to run `singularity --nv`

**Comment by vsoch** [comment]
That would be easy to add, see my notes under “options and args.” More generally it would be very helpful if a maintainer could answer some of my questions, then I can finish up the work!

**Comment by Zethson** [comment]
Great.

For all things containers @dbczumar is maybe the right one to ask?

**Comment by sklingel** [comment]
This is a great initiative 👍

**Comment by Marcelo00** [comment]
Hey, 
is there any update on this or a way to help? We would really appreciate the support for singularity container :)

**Comment by vsoch** [comment]
As far as I can see, there was no review from a maintainer, and as expected the PR has fallen behind the main branch.

**Comment by Zethson** [comment]
Maybe we should ask in the Slack channel whether someone would be ready to take a look?
We also highly desire this feature.

**Comment by vsoch** [comment]
From the changes to master, it looks like the docker commands have been refactored so there is no longer an import, so I would need to refactor mine as well. If someone that can review this can provide me an overall update on changes that have been done (and then we can discuss how the PR here needs to be changed) that would be hugely appreciated!

**Comment by sklingel** [comment]
@vsoch, have you considered offering your work as a third-party plugin: https://www.mlflow.org/docs/latest/plugins.html#project-backend-plugins. 
I guess it would be a "backend" plugin.

**Comment by vsoch** [comment]
I suppose I could, but it would be nice to hear from even one maintainer about their preferences. I opened this PR three months ago, I would hope that is enough time to pop in and say something?

**Comment by Marcelo00** [comment]
I would think so and why not ask on slack directly?

**Comment by vsoch** [comment]
I’m not really wanting to join another slack - I’m hoping the maintainers respond to the community on GitHub?

**Comment by Marcelo00** [comment]
Sorry for not replying. I can check out the slack channel.

**Comment by vsoch** [comment]
Thank you @Marcelo00 ! Much appreciated :O)

**Comment by Marcelo00** [comment]
I asked on slack on Monday but there is no reaction yet. Thus, I am not sure how to proceed with this feature. If I have more time, I will take a deeper look on this MR. We can maybe provide a plugin but there is still the valid point of not having any feedback. At least we will be able to use it for our use cases.

**Comment by vsoch** [comment]
No worries @Marcelo00 - people are probably just really busy. We can pick up if/when there is interest.

**Comment by florianblume** [comment]
Any plans on merging the PR some time soon? If there's help needed I'd be happy to jump in :)

**Pull request closed without merging**
