### PR TITLE
Reorganize artifact module

### PR DESCRIPTION
**Pull request by Djailla**
## What changes are proposed in this pull request?

Reorder the store module

## How is this patch tested?

Unit tests

### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s) does this PR affect?

- [ ] UI
- [ ] CLI
- [ ] API
- [ ] REST-API
- [ ] Examples
- [ ] Docs
- [ ] Tracking
- [ ] Projects
- [ ] Artifacts
- [ ] Models
- [ ] Scoring
- [ ] Serving
- [ ] R
- [ ] Java
- [x] Python

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by aarondav** [comment]
Could you clarify the purpose of this refactoring? I'm not sure this extent of internal refactoring is worth it if it's not towards some goal.

**Comment by Djailla** [comment]
@aarondav it makes more clear what are the repo and avoid long files names with big repetitions.

It's pure code quality. As you mentioned earlier, you are not fan of this. I understand, but I find it really important to have easy to read code to promote and make it easy for external contributions.

**Comment by aarondav** [comment]
Thanks for the explanation. As I mentioned before, there is a cost to every code change, and I personally think code quality is typically not a sufficient reason to make a change -- of course it depends on the complexity of the change and the improvement of the clarity.

Anyway, in this case, for me this change does not seem worth the potential downstream issues, so I would propose to close this PR.

**Comment by Djailla** [comment]
@aarondav I disagree with your statement about code quality, especially for open source project where multiple people would contribute to the code base.

But agree on closing this PR.

**Pull request closed without merging**
