### PR TITLE
Model creation timestamp for log model in R

### PR DESCRIPTION
**Pull request by singankit**
## What changes are proposed in this pull request?

(Please fill in changes proposed in this fix)

## How is this patch tested?

(Details)

## Does this PR change the documentation?

- [X] No. You can skip the rest of this section.
- [ ] Yes. Make sure the changed pages / sections render correctly by following the steps below.

1. Check the status of the `ci/circleci: build_doc` check. If it's successful, proceed to the
   next step, otherwise fix it.
2. Click `Details` on the right to open the job page of CircleCI.
3. Click the `Artifacts` tab.
4. Click `docs/build/html/index.html`.
5. Find the changed pages / sections and make sure they render correctly.

### Is this a user-facing change?

- [X] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [X] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>
### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [X] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by lorenzwalthert** [comment]
Hi @singankit, looks like you fixed it 👍. As far as testing goes, one way is to create a `MLmodel` file with R and then do a regex match on the time stamp (with `testthat::expect_match()`). To make sure we pick up changes in the Python API, you could add a test to create such a file as well with the Python API using  {reticulate} and match it against the same regex. We do something similar with [xgboost tests](https://github.com/mlflow/mlflow/blob/master/mlflow/R/mlflow/tests/testthat/test-model-xgboost.R#L43), where we check compatibility for xgboost between R and Python.

**Comment by singankit** [comment]
> Hi @singankit, looks like you fixed it 👍. As far as testing goes, one way is to create a `MLmodel` file with R and then do a regex match on the time stamp (with `testthat::expect_match()`). To make sure we pick up changes in the Python API, you could add a test to create such a file as well with the Python API using {reticulate} and match it against the same regex. We do something similar with [xgboost tests](https://github.com/mlflow/mlflow/blob/master/mlflow/R/mlflow/tests/testthat/test-model-xgboost.R#L43), where we check compatibility for xgboost between R and Python.

Hi @lorenzwalthert I have updated the PR to include a test which validated the timestamp. Please share your feedback if it looks good. Also the test gates need someone to kick them off, it would be great if you can help me with kicking off the test pipelines. However I am running into issue when I run the tests locally so not able to run all the tests locally 

Error in `wait_for(function() mlflow_rest("experiments", "list", client = client),
    getOption("mlflow.connect.wait", 10), getOption("mlflow.connect.sleep",
        1))`: Operation failed after waiting for 10 seconds

**Comment by lorenzwalthert** [comment]
@dbczumar can you kick off the tests?

**Comment by lorenzwalthert** [comment]
Ok @singankit. If these tests are not related to your changes, they should pass nonetheless. Other option is rebase on default branch and force push, if it was something that recently got fixed.

**Comment by singankit** [comment]
@lorenzwalthert I have fixed the failing test. All other test pipelines passed. Would need another round of pipeline run. Please review and share any feedback.

**Comment by lorenzwalthert** [comment]
Great, I think for the R part, we are good.

However, I think we could take this as an opportunity to improve the Python API here as well. In Python, the datetime for a model is initialized upon creating a `Model` in https://github.com/mlflow/mlflow/blob/master/mlflow/models/model.py#L53:

```python
class Model(object):
    ... 
    self.utc_time_created = str(utc_time_created or datetime.utcnow())
    ... 
```

This code means I can create a model with an arbitrary value for `utc_time_created`, which will potentially cause problems downstream, e.g. when loading the model. What about going for a more strict `strftime()` like this?
```python
DATETIMEFORMAT="%Y-%m-%d %H:%M:%OS6"
... 
def Model(object): 
  ...
  if utc_time_created is None:
      utc_time_created = datetime.datetime.utcnow()
  self.utc_time_created  = utc_time_created.strftime(DATETIMEFORMAT)
  ..
```

Then, in R, we could assert that the two formats are identical to ensure compatibility.

```r
models <- reticulate::import('mlflow.models')
except_match(models$model$DATETIMEFORMAT, "put the literal constant here or also define it in `R/` as a constant and refer to it with DATETIMEFORMAT")
```

@dbczumar what do you think? Or a new PR? I don't know if there are other dependencies here we have to pay attention to.

**Comment by lorenzwalthert** [comment]
@singankit maybe just rebase on default branch and force push, the docker examples seem unrelated.

**Comment by singankit** [comment]
My mistake deleted and re-created the branch hence this PR got closed. Have opened a new one [here](https://github.com/mlflow/mlflow/pull/5236). Sorry about that.

**Pull request closed without merging**
