### PR TITLE
Monkero lint branch

### LINKED ISSUE #6535: Fix `use-set-literal` lint errors
Fix `use-set-literal` lint errors by following the instructions below (example PR: #6534):

https://github.com/mlflow/mlflow/blob/1b89add428da0a4453e7523a20d13f04f6291f37/pylint_plugins/set_checker.py#L12-L41

## What needs to be fixed?

`set` applied on `list` or `tuple` literal need to be converted to `set` literal:

```python
# Bad
set([1, 2, 3])
set((1, 2, 3))

# Good
{1, 2, 3}
```

## Files

| File                                                               | Assignee     | PR    |
| :----------------------------------------------------------------- | :----------- | :---- |
| mlflow/azure/client.py                                             | @Monkero     | #6544 |
| mlflow/entities/lifecycle_stage.py                                 | @Monkero     | #6544 |
| mlflow/entities/run_status.py                                      | @Monkero     | #6544 |
| mlflow/server/handlers.py                                          | @dsgibbons   | #6542 |
| mlflow/tracking/fluent.py                                          | @dsgibbons   | #6542 |
| mlflow/utils/autologging_utils/safety.py                           | @dsgibbons   | #6542 |
| tests/autologging/test_autologging_behaviors_unit.py               | @dsgibbons   | #6543 |
| tests/entities/test_run_info.py                                    | @dsgibbons   | #6543 |
| tests/entities/test_run_status.py                                  | @dsgibbons   | #6543 |
| tests/lightgbm/test_lightgbm_autolog.py                            | @iamthen0ise | #6560 |
| tests/models/test_model_input_examples.py                          | @iamthen0ise | #6560 |
| tests/projects/test_project_spec.py                                | @iamthen0ise | #6560 |
| tests/pyfunc/test_model_export_with_loader_module_and_data_path.py |              |       |
| tests/store/artifact/test_databricks_artifact_repo.py              |              |       |
| tests/store/artifact/test_ftp_artifact_repo.py                     |              |       |
| ~tests/tensorflow/test_tensorflow2_autolog.py~                     |              |       |
| tests/utils/test_requirements_utils.py                             |              |       |
| tests/xgboost/test_xgboost_autolog.py                              |              |       |
| mlflow/utils/search_utils.py                                       | @harupy      | #6534 |
| tests/entities/model_registry/test_model_version.py                | @harupy      | #6534 |
| tests/entities/model_registry/test_registered_model.py             | @harupy      | #6534 |
| tests/store/tracking/test_sqlalchemy_store.py                      | @harupy      | #6534 |
| tests/tracking/test_model_registry.py                              | @harupy      | #6534 |

If you're interested in working on this issue, ping me with the file you would like to work on. Please fix only 1 ~ 3 items per pull request.

### PR DESCRIPTION
**Pull request by ghost**
## Related Issues/PRs

#6535

## What changes are proposed in this pull request?
'use-set-error' fix for 3 files:
mlflow/azure/client.py
mlflow/entities/lifecycle_stage.py
mlflow/entities/run_status.py

## How is this patch tested?

- [x] I have written tests (not required for typo or doc fix) and confirmed the proposed feature/bug-fix/change works.

## Does this PR change the documentation?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Make sure the changed pages / sections render correctly by following the steps below.

1. Click the `Details` link on the `Preview docs` check.
2. Find the changed pages / sections and make sure they render correctly.

### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

### What component(s), interfaces, languages, and integrations does this PR affect?
Components
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by harupy** [comment]
@Monkero Commits created on GitHub UI won't pass the DCO check. Can you make updates on your machine and push them?

**Comment by Monkero** [comment]
@harupy , understood

**Comment by harupy** [comment]
@Monkero When you make a commit, please make sure to use `git commit -s` instead of `git commit` to sign off the commit.

**Comment by harupy** [comment]
@Monkero Thanks for the update. Can you fix [the DCO check failure](https://github.com/mlflow/mlflow/pull/6539/checks?check_run_id=7961282183)?

**Comment by harupy** [comment]
@Monkero You didn't have to close the PR.

**Pull request closed without merging**
