### PR TITLE
Add Twitte badge on README

### PR DESCRIPTION
**Pull request by guelate**
Addresses https://github.com/mlflow/mlflow/issues/5594

**What**

I added the dependency for twitter.

**Before**

avant

**After**

apres

### CODE REVIEW

**Comment by harupy** [comment]
@guelate Thanks for the PR, can you fix the DCO check failure?
https://github.com/mlflow/mlflow/pull/5605/checks?check_run_id=5831354328

**Comment by guelate** [comment]
@harupy Okay I'm looking for a way to do it.

**Comment by harupy** [comment]
@guelate You can run these commands:

```
git rebase HEAD~1 --signoff
git push --force-with-lease origin Twitter_link
```

**Comment by guelate** [comment]
@harupy Yes it's good thanks :)

**Review by harupy — APPROVED** [review]
@guelate LGTM, thanks for the contribution!

**Pull request merged**
