### PR TITLE
Add more tests to github actions

### PR DESCRIPTION
**Pull request by smurching**
## What changes are proposed in this pull request?

Adds most of the MLflow "large" tests that currently run in Travis to Github actions, following the pattern of https://github.com/mlflow/mlflow/pull/2700 and https://github.com/mlflow/mlflow/pull/2724, where we added MLflow small tests to github actions & later removed them from Travis CI once proven to be stable in Github actions.

I didn't try to add R or Windows to Github actions - R was found to be difficult to migrate in https://github.com/mlflow/mlflow/pull/2724 and Windows looks like it may be a bit more work to migrate than the other builds, which seem migratable simply by copying configs from existing builds :). I also tried for a bit to add the generic "Python large" tests to github actions, but gave up - there seems to be an issue with how conda is configured when running MLflow projects in the github actions environment.

The motivation here is twofold:
* Github actions allows up to 20 parallel builds on free plans ([docs](https://help.github.com/en/actions/getting-started-with-github-actions/about-github-actions#usage-limits)), and we could pay to get more. On the other hand, Travis only allows for 5 executors across PRs.
* Migrating to Github actions may reduce one of the primary sources of build flakiness, namely failure to install dependencies from conda due to "connection reset by peer". A survey of [Travis master builds (excluding CRON builds)](https://travis-ci.org/github/mlflow/mlflow/builds) since April 19 shows 59 passed builds, 5 failed builds, and 6 errored builds. Several of the failed builds and all of the errored builds failed during dependency installation steps (causing build failures if this happened while running a test, and build errors if this happened while installing dependencies). On the other hand, small tests running in Github actions seem to have never failed due to such flakiness - it seems the Github actions environment may be more robust to such flakiness. Note also that it's entirely possible this isn't true, but moving these tests to Github actions still seems nice given the limited number of build executors available in Travis

## How is this patch tested?
Ran tests via Github actions on this PR. Note that the whole [actions workflow run](https://github.com/mlflow/mlflow/actions/runs/128363529) took ~25 min, and the corresponding [Travis run](https://travis-ci.org/github/mlflow/mlflow/builds/695924210) took ~24 min.

### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by aarondav** [comment]
The docs build has 6k lines that look like this:

```
Progress (3): 737 kB | 53 kB | 108 kB    
Progress (4): 737 kB | 53 kB | 108 kB | 4.1/35 kB
Progress (4): 737 kB | 53 kB | 108 kB | 7.0/35 kB
Progress (4): 737 kB | 53 kB | 108 kB | 11/35 kB 
Progress (4): 737 kB | 53 kB | 108 kB | 15/35 kB
Progress (4): 737 kB | 53 kB | 108 kB | 19/35 kB
Progress (4): 737 kB | 53 kB | 108 kB | 23/35 kB
Progress (4): 737 kB | 53 kB | 108 kB | 27/35 kB
Progress (4): 737 kB | 53 kB | 108 kB | 31/35 kB
Progress (4): 737 kB | 53 kB | 108 kB | 35 kB   
```

I wonder if we can somehow reduce this noise to make this builder more debuggable.

**Comment by aarondav** [comment]
Looks great @smurching! Shouldn't we remove these from the Travis build as well?

**Comment by smurching** [comment]
@aarondav thanks! Yeah, will do RE removing the redundant builds from Travis - had planned to keep them around for a few days in in case there was some issue with the github actions build, but seems easy enough to reintroduce them to Travis if an issue arises

**Comment by smurching** [comment]
Note that the test failures introduced in [this commit](https://github.com/mlflow/mlflow/pull/2908/commits/287ce978cf4f4c16f624bb2ec63554ac11880121) were captured by github actions:

image

**Review by smurching — COMMENTED** [review]
Got offline approval from @aarondav (after verifying that tests failures would in fact trigger github actions failures in each of the new workflow steps), merging - thanks!

**Pull request merged**
