### PR TITLE
Reduce pandas profiling size

### PR DESCRIPTION
**Pull request by jinzhang21**
## Related Issues/PRs

#xxx

## What changes are proposed in this pull request?

Reduce the profiling max sizes by a factor of 10 to reduce the max amount time to run the profiler.

## How is this patch tested?

Manually tested.

## Does this PR change the documentation?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Make sure the changed pages / sections render correctly by following the steps below.

1. Click the `Details` link on the `Preview docs` check.
2. Find the changed pages / sections and make sure they render correctly.

### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?
Components
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [x] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>
### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Review by prithvikannan — COMMENTED** [review]
@jinzhang21 the reason for increasing profiling limits is based on bug bash feedback.

currently profiling performance is generally linear with `n_columns` (because profiling loops over columns). @sunishsheth2009 is working on adding multiprocessing to handle larger datasets.

i think it makes sense to merge this PR in the short term, but we plan to handle larger profiling datasets in a more performant manner soon.

**Comment by jinzhang21** [comment]
> @jinzhang21 the reason for increasing profiling limits is based on bug bash feedback.
> 
> currently profiling performance is generally linear with `n_columns` (because profiling loops over columns). @sunishsheth2009 is working on adding multiprocessing to handle larger datasets.
> 
> i think it makes sense to merge this PR in the short term, but we plan to handle larger profiling datasets in a more performant manner soon.

SG. These values probably will be adjusted / fine-tuned on a constant basis. We can always dial it to the other direction if needed.

**Review by sunishsheth2009 — COMMENTED** [review]
I think @prithvikannan did some analysis recently 
```
ingested 6 columns in 1.09 seconds (0.18166666666666667 cols/s)
ingested 126 columns in 3.02 seconds (0.02396825396825397 cols/s)
ingested 906 columns in 13.9 seconds (0.01534216335540839 cols/s)
```

I think since its seconds we should be fine to keep the limit. We can in future let users customize this as a config for profiling similar to skip_profile.

Also I feel the feedback that was given maybe when users are using pandas_profiling and might not be the new one. Since there was similar complain about skip_profiling not working. Just a thought. 🤔

**Comment by jinzhang21** [comment]
> I think @prithvikannan did some analysis recently
> 
> ```
> ingested 6 columns in 1.09 seconds (0.18166666666666667 cols/s)
> ingested 126 columns in 3.02 seconds (0.02396825396825397 cols/s)
> ingested 906 columns in 13.9 seconds (0.01534216335540839 cols/s)
> ```
> 
> I think since its seconds we should be fine to keep the limit. We can in future let users customize this as a config for profiling similar to skip_profile.
> 
> Also I feel the feedback that was given maybe when users are using pandas_profiling and might not be the new one. Since there was similar complain about skip_profiling not working. Just a thought. 🤔

Faire point. But realistically, I don't see any reason to profile more than 1k columns. How could anyone to sift through this many columns in a meaningful way?

**Review by dbczumar — CHANGES_REQUESTED** [review]
I'd prefer that we keep the current limits unless there's a strong performance-based reason to reduce them.

**Comment by jinzhang21** [comment]
lol. Didn't expect this much push back:) Fine. Let's keep it for now.

**Pull request closed without merging**
