### PR TITLE
Increase Gunicorn worker timeout for MLflow Deployment Server pagenation test

### LINKED ISSUE #10855: [ERROR] Worker (pid:2977) was sent SIGKILL! Perhaps out of memory?
https://github.com/mlflow/mlflow/actions/runs/7577835485/job/20639381554

```
----------------------------- Captured stderr call -----------------------------
[2024-01-19 00:48:01 +0000] [2973] [INFO] Starting gunicorn 21.2.0
[2024-01-19 00:48:01 +0000] [2973] [INFO] Listening at: http://127.0.0.1:37481/ (2973)
[2024-01-19 00:48:01 +0000] [2973] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2024-01-19 00:48:01 +0000] [2976] [INFO] Booting worker with pid: 2976
[2024-01-19 00:48:01 +0000] [2977] [INFO] Booting worker with pid: 2977
[2024-01-19 00:48:31 +0000] [2973] [CRITICAL] WORKER TIMEOUT (pid:2976)
[2024-01-19 00:48:31 +0000] [2973] [CRITICAL] WORKER TIMEOUT (pid:2977)
Error: 1-19 00:48:32 +0000] [2973] [ERROR] Worker (pid:2977) was sent SIGKILL! Perhaps out of memory?
Error: 1-19 00:48:32 +0000] [2973] [ERROR] Worker (pid:2976) was sent SIGKILL! Perhaps out of memory?
[2024-01-19 00:48:32 +0000] [3004] [INFO] Booting worker with pid: 3004
[2024-01-19 00:48:32 +0000] [3005] [INFO] Booting worker with pid: 3005
[2024-01-19 00:49:02 +0000] [2973] [CRITICAL] WORKER TIMEOUT (pid:3004)
[2024-01-19 00:49:02 +0000] [2973] [CRITICAL] WORKER TIMEOUT (pid:3005)
Error: 1-19 00:49:02 +0000] [2973] [ERROR] Worker (pid:3005) was sent code 134!
[2024-01-19 00:49:02 +0000] [3030] [INFO] Booting worker with pid: 3030
Error: 1-19 00:49:02 +0000] [2973] [ERROR] Worker (pid:3004) was sent code 134!
[2024-01-19 00:49:02 +0000] [3031] [INFO] Booting worker with pid: 3031
[2024-01-19 00:49:32 +0000] [2973] [CRITICAL] WORKER TIMEOUT (pid:3030)
[2024-01-19 00:49:32 +0000] [2973] [CRITICAL] WORKER TIMEOUT (pid:3031)
Error: 1-19 00:49:33 +0000] [2973] [ERROR] Worker (pid:3031) was sent code 134!
[2024-01-19 00:49:33 +0000] [3053] [INFO] Booting worker with pid: 3053
Error: 1-19 00:49:33 +0000] [2973] [ERROR] Worker (pid:3030) was sent code 134!
[2024-01-19 00:49:33 +0000] [3054] [INFO] Booting worker with pid: 3054
[2024-01-19 00:50:03 +0000] [2973] [CRITICAL] WORKER TIMEOUT (pid:3053)
[2024-01-19 00:50:03 +0000] [2973] [CRITICAL] WORKER TIMEOUT (pid:3054)
Error: 1-19 00:50:03 +0000] [2973] [ERROR] Worker (pid:3053) was sent code 134!
```

### PR DESCRIPTION
**Pull request by B-Step62**
<details><summary>&#x1F6E0 DevTools &#x1F6E0</summary>
<p>

[Open in GitHub Codespaces](https://codespaces.new/B-Step62/mlflow/pull/10857?quickstart=1)

#### Install mlflow from this PR

```
pip install git+https://github.com/mlflow/mlflow.git@refs/pull/10857/merge
```

#### Checkout with GitHub CLI

```
gh pr checkout 10857
```

</p>
</details>

### Related Issues/PRs

Close #10855

### What changes are proposed in this pull request?

Gateway tests (`test_fluent_search_routes_handles_pagination`) have occasionally been failing due to worker timeout. This was because the test case creates huge number (6001!) routes and breached timeout for Gunicorn workers which is 30 sec by default. This PR adds a new env variable `MLFLOW_DEPLOYMENT_SERVER_START_TIMEOUT` to configure the timeout and fix the broken test.

**Note**: Initially I was thinking of adding `--timeout` to the CLI command `mlflow deployment start-server`, but switched to env var considering the low likelihood of users need to change it. Also it might be confusing with prediction timeout.

### How is this PR tested?

- [x] Existing unit/integration tests
- [ ] New unit/integration tests
- [ ] Manual tests

### Does this PR require documentation update?

- [ ] No. You can skip the rest of this section.
- [ ] Yes. I've updated:
  - [ ] Examples
  - [ ] API references
  - [ ] Instructions

#### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

#### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [x] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>

#### How should the PR be classified in the release notes? Choose one:

- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by harupy** [comment]
Instead of creating a new environment variable, can we monkey-patch `MLFLOW_GATEWAY_SEARCH_ROUTES_PAGE_SIZE` with a smaller value?

**Comment by B-Step62** [comment]
> Instead of creating a new environment variable, can we monkey-patch MLFLOW_GATEWAY_SEARCH_ROUTES_PAGE_SIZE with a smaller value like 10?

ooh great idea!

**Comment by harupy** [comment]
@B-Step62 What about this approach?

```diff
diff --git a/tests/gateway/test_fluent.py b/tests/gateway/test_fluent.py
index 5b0d7d54a3..83ad165504 100644
--- a/tests/gateway/test_fluent.py
+++ b/tests/gateway/test_fluent.py
@@ -1,3 +1,4 @@
+import os
 from unittest import mock
 
 import pytest
@@ -157,7 +158,9 @@ def test_fluent_search_routes_handles_pagination(tmp_path):
         "routes": [{"name": route_name, **base_route_config} for route_name in gateway_route_names]
     }
     save_yaml(conf, gateway_config_dict)
-    with Gateway(conf) as gateway:
+    with Gateway(
+        conf, env={**os.environ, "GUNICORN_CMD_ARGS": "--timeout=60 --log-level=debug"}
+    ) as gateway:
         set_gateway_uri(gateway_uri=gateway.url)
         assert [route.name for route in search_routes()] == gateway_route_names
```

**Comment by B-Step62** [comment]
@harupy Awesome idea! That capability is like existing for this exact use case:)

**Comment by harupy** [comment]
We can remove `--log-level=debug`. I added this to confirm timeout is set to 60.

**Review by harupy — APPROVED** [review]
LGTM!

**Pull request merged**
