### PR TITLE
fix unneccessary collection (<dict/list/tuple>) call and rewrite them as literal

### LINKED ISSUE #7269: Enable `use-list-literal` rule
Make the following change and replaced `list()` with `[]`

```diff
diff --git a/pylintrc b/pylintrc
index c0d8e9866..d8efe2105 100644
--- a/pylintrc
+++ b/pylintrc
@@ -182,7 +182,8 @@ enable=c-extension-no-member,
        consider-merging-isinstance,
        consider-using-dict-items,
        unnecessary-comprehension,
-       consider-using-set-comprehension
+       consider-using-set-comprehension,
+       use-list-literal
```

See https://pylint.pycqa.org/en/latest/user_guide/messages/refactor/use-list-literal.html for more information.

### LINKED ISSUE #7270: Enable `use-dict-literal` rule
Make the following change and replaced `dict()` with `{}`.

```diff
diff --git a/pylintrc b/pylintrc
index c0d8e9866..d8efe2105 100644
--- a/pylintrc
+++ b/pylintrc
@@ -182,7 +182,8 @@ enable=c-extension-no-member,
        consider-merging-isinstance,
        consider-using-dict-items,
        unnecessary-comprehension,
-       consider-using-set-comprehension
+       consider-using-set-comprehension,
+       use-dict-literal
```

See https://pylint.pycqa.org/en/latest/user_guide/messages/refactor/use-dict-literal.html for more information.

### PR DESCRIPTION
**Pull request by ayushthe1**
##

  fixes #7270 , fixes #7269 

## What changes are proposed in this pull request?

According to pypi [flake8-comprehensions 3.10.1 rule C408](https://pypi.org/project/flake8-comprehensions/3.10.1/#:~:text=C408%3A%20Unnecessary%20%3Cdict/list/tuple%3E%20call%20%2D%20rewrite%20as%20a%20literal.) ,it's slower to call `dict() ,list() ,tuple() ` than using the empty literal `{} ,[] ,()` correspondingly .

This pr rewrites the unnecessary `(dict|list|tuple)` call to their corresponding literals by using [ruff](https://github.com/charliermarsh/ruff#ruff) linter .

## How is this patch tested?

- [x] Existing unit/integration tests
- [ ] New unit/integration tests
- [ ] Manual tests (describe details, including test results, below)

## Does this PR change the documentation?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Make sure the changed pages / sections render correctly in the documentation preview.

### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?
Components
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [x] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>
### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [x] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by ayushthe1** [comment]
hey @harupy ,i can't figure out why the tests are failing . Could you please check it.

**Comment by harupy** [comment]
@ayushthe1 Can you update `pylintrc`?

**Comment by harupy** [comment]
Can you file a follow-up PR to address https://github.com/mlflow/mlflow/pull/7272#issuecomment-1306330770?

**Review by harupy — APPROVED** [review]
LGTM

**Comment by ayushthe1** [comment]
> @ayushthe1 Can you file a follow-up PR to address https://github.com/mlflow/mlflow/pull/7272#issuecomment-1306330770? This PR looks good.

sure ,I will do it.

**Comment by ayushthe1** [comment]
hey @harupy  ,what do i need to update in the [pylintrc](https://github.com/mlflow/mlflow/blob/master/pylintrc) file ?

**Comment by harupy** [comment]
@ayushthe1 You make the change in https://github.com/mlflow/mlflow/issues/7270#issue-1438215606

**Pull request merged**
