### PR TITLE
Bump all package versions from 1.0.0 to 1.1.1.dev0

### PR DESCRIPTION
**Pull request by smurching**
## What changes are proposed in this pull request?
 
Bump all MLflow package versions from 1.0.0 to 1.1.1.dev0 (or 1.1.1 for Java and R, which don't support dev0 suffixes)
 
## How is this patch tested?
Existing tests
 
### Is this a user-facing change? 

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.
 
(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)
 
### What component(s) does this PR affect?
 
- [ ] UI
- [ ] CLI 
- [ ] API 
- [ ] REST-API 
- [ ] Examples 
- [ ] Docs
- [ ] Tracking
- [ ] Projects 
- [ ] Artifacts 
- [ ] Models 
- [ ] Scoring 
- [ ] Serving
- [ ] R
- [ ] Java
- [ ] Python

### How should the PR be classified in the release notes? Choose one:
 
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by mateiz** [comment]
Looks okay except that I think you can use dev versions in Java too. What did we do before?

**Comment by mateiz** [comment]
(For that matter, it may also work in R).

**Comment by smurching** [comment]
Good question, in the past we've used versions like 1.1.1.dev0 for Python and 1.1.1 for Java & R. Looks like there's a notion of SNAPSHOT releases for Java on Maven, but for R valid package versions must be of the form `major.minor.patch.[additional numbers allowed]`, as per [the CRAN docs](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#The-DESCRIPTION-file):

> The mandatory ‘Version’ field gives the version of the package. This is a sequence of at least two (and usually three) non-negative integers separated by single ‘.’ or ‘-’ characters. The canonical form is as shown in the example, and a version such as ‘0.01’ or ‘0.01.0’ will be handled as if it were ‘0.1-0’. It is not a decimal number, so for example 0.9 < 0.75 since 9 < 75.

**Comment by mateiz** [comment]
OK, looks good to me with this change!

**Review by dbczumar — APPROVED** [review]
LGTM

**Pull request merged**
