### PR TITLE
Add a copy button on code blocks in the documentation #7493

### LINKED ISSUE #7493: Add a copy button on code blocks in the documentation
## Task

Add a copy button on code blocks in the documentation to help users quickly run example code.

## What didn't work

I tested [sphinx-copybutton](https://sphinx-copybutton.readthedocs.io/en/latest/index.html) with the following changes:

```diff
diff --git a/docs/source/conf.py b/docs/source/conf.py
index dd99e5ec0..512667017 100644
--- a/docs/source/conf.py
+++ b/docs/source/conf.py
@@ -41,6 +41,7 @@ extensions = [
     "sphinx.ext.napoleon",
     "sphinx_click.ext",
     "test_code_block",
+    "sphinx_copybutton",
 ]
 
 # Add any paths that contain templates here, relative to this directory.
diff --git a/docs/theme/mlflow/layout.html b/docs/theme/mlflow/layout.html
index 318f6d935..58ea62618 100644
--- a/docs/theme/mlflow/layout.html
+++ b/docs/theme/mlflow/layout.html
@@ -96,6 +96,20 @@
 
 </head>
 
+{% if not embedded %}
+<script type="text/javascript">
+  var DOCUMENTATION_OPTIONS = {
+    URL_ROOT:'{{ url_root }}',
+    VERSION:'{{ release|e }}',
+    COLLAPSE_INDEX:false,
+    FILE_SUFFIX:'{{ '' if no_search_suffix else file_suffix }}',
+    LINK_SUFFIX: '.html',
+    HAS_SOURCE:  {{ has_source|lower }}
+  };
+</script>
+
+{% endif %}
+
 {%- for scriptfile in script_files %}
 <script type="text/javascript" src="{{ pathto(scriptfile, 1) }}"></script>
 {%- endfor %}
@@ -139,20 +153,6 @@
 
   {% include "versions.html" %}
 
-  {% if not embedded %}
-  <script type="text/javascript">
-    var DOCUMENTATION_OPTIONS = {
-      URL_ROOT:'{{ url_root }}',
-      VERSION:'{{ release|e }}',
-      COLLAPSE_INDEX:false,
-      FILE_SUFFIX:'{{ '' if no_search_suffix else file_suffix }}',
-      LINK_SUFFIX: '.html',
-      HAS_SOURCE:  {{ has_source|lower }}
-    };
-  </script>
-
-  {% endif %}
-
   <script type="text/javascript" src="{{ pathto('_static/js/clipboard.min.js', 1) }}"></script>
   <script type="text/javascript" src="{{ pathto('_static/js/jquery.waypoints.min.js', 1) }}"></script>
   {%- block scripts %} {%- endblock %}
```

but the button size and position don't seem correct (probably because of our custom theme). We need to adjust CSS.

image

### PR DESCRIPTION
**Pull request by arunkumarkota**
Resolve https://github.com/mlflow/mlflow/issues/7493

Add a copy button on code blocks in the documentation to help users quickly run example code. 

Updated the config file. Will continue working on it.

### CODE REVIEW

**Comment by harupy** [comment]
@arunkumarkota Ping me when push updates!

**Comment by dbczumar** [comment]
Hi @arunkumarkota, just gently pinging on this. Let me know if there are any updates :D

**Comment by tsabbir96** [comment]
Hi @dbczumar @harupy, incase @arunkumarkota isn't available right now, I would be very happy to pick up the work. Could you update me with your current thoughts on this PR?

**Review by harupy — APPROVED** [review]
LGTM!

**Pull request merged**
