### PR TITLE
Include README_skinny.rst in sdist

### PR DESCRIPTION
**Pull request by xhochy**
## What changes are proposed in this pull request?

This includes the `README_skinny.rst` file in the `sdist`. This enables to install the `mlflow-skinny` package from source tarballs.

Currently we need to manually add this file in the build process of the `mlflow` packages on conda-forge: https://github.com/conda-forge/mlflow-feedstock/pull/59

## How is this patch tested?

I have built an `mlflow` sdist tarball and verified that the `README_skinny.rst` was included in it.

### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>
### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by harupy** [comment]
@xhochy Thanks for the catch and fix! Could you tell me how to reproduce the error?

**Comment by xhochy** [comment]
On master the following fails: `python setup.py sdist && MLFLOW_SKINNY=1 pip install dist/mlflow-1.14.1.dev0.tar.gz`. 

`MLFLOW_SKINNY=1 python setup.py sdist && MLFLOW_SKINNY=1 pip install dist/mlflow-1.14.1.dev0.tar.gz` also fails

**Comment by harupy** [comment]
@xhochy I was able to reproduce the issue


```
% MLFLOW_SKINNY=1 pip install mlflow-skinny-1.14.0.tar.gz
Processing ./mlflow-skinny-1.14.0.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /Users/harutakakawamura/.pyenv/versions/miniconda3-4.7.12/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/33/kkm875tn7cxb89b8mmcykrx00000gn/T/pip-req-build-i5khje1l/setup.py'"'"'; __file__='"'"'/private/var/folders/33/kkm875tn7cxb89b8mmcykrx00000gn/T/pip-req-build-i5khje1l/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/33/kkm875tn7cxb89b8mmcykrx00000gn/T/pip-pip-egg-info-5gsafbx9
         cwd: /private/var/folders/33/kkm875tn7cxb89b8mmcykrx00000gn/T/pip-req-build-i5khje1l/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/33/kkm875tn7cxb89b8mmcykrx00000gn/T/pip-req-build-i5khje1l/setup.py", line 113, in <module>
        else open("README_SKINNY.rst").read() + open("README.rst").read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'README_SKINNY.rst'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by harupy** [comment]
@xhochy The proposed change looks good to me. Can I push a commit to ensure that we can install `mlflow-skinny` from tarballs

**Comment by xhochy** [comment]
> @xhochy The proposed change looks good to me. Can I push a commit to ensure that we can install `mlflow-skinny` from tarballs by updating `.github/workflows/test-package-build.yml`?

Sure, checkmark is set
image

**Comment by harupy** [comment]
@xhochy Done! I'll merge the PR once all the CI checks pass.

**Review by harupy — APPROVED** [review]
LGTM

**Pull request merged**
