### PR TITLE
Initial setup to migrate pipeline to recipe

### PR DESCRIPTION
**Pull request by sunishsheth2009**
## What changes are proposed in this pull request?
Initial setup to migrate pipeline to recipe

## How is this patch tested?
- [x] ran notebook from example repo
- [ ] Test passes

## Does this PR change the documentation?

- [ ] No. You can skip the rest of this section.
- [x] Yes. Make sure the changed pages / sections render correctly in the documentation preview.

### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [x] Yes. Give a description of this change to be included in the release notes for MLflow users.

Changing the name of MLFlow Pipelines to MLFlow Recipes

### What component(s), interfaces, languages, and integrations does this PR affect?
Components
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [x] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>
### How should the PR be classified in the release notes? Choose one:

- [x] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Review by dbczumar — APPROVED** [review]
LGTM! Couldn't find any remaining instances of "pipelines" and also tried this out with https://github.com/mlflow/recipes-examples & confirmed that everything works properly (ran the full recipe and each individual step, inspected outputs). Thanks @sunishsheth2009 !

Once this PR merges, I'll adjust required workflows for GitHub Actions to remove the mlflow-pipelines* expectations.

Also, do we have a ticket to track making the example README a bit more descriptive? https://github.com/mlflow/recipes-examples. I.e. Include links to the Recipes docs, provide a 1-2 sentence description of each example.

**Comment by sunishsheth2009** [comment]
> Also, do we have a ticket to track making the example README a bit more descriptive? https://github.com/mlflow/recipes-examples. I.e. Include links to the Recipes docs, provide a 1-2 sentence description of each example.

good idea. Let me add to the documentation ticket that we have to add more color here. thanks :)

**Comment by sunishsheth2009** [comment]
> LGTM! Couldn't find any remaining instances of "pipelines" and also tried this out with https://github.com/mlflow/recipes-examples & confirmed that everything works properly (ran the full recipe and each individual step, inspected outputs). Thanks @sunishsheth2009 !

Thank you @dbczumar for the exhaustive check. :) Appreciate that

**Review by jinzhang21 — APPROVED** [review]
Fantastic change, @sunishsheth2009 !

**Pull request merged**
