### PR TITLE
Log local variables

### PR DESCRIPTION
**Pull request by mgbckr**
## What changes are proposed in this pull request?

```python
import mlflow

def main(param1, param2, param3="defaultvalue", verbose=0, *args, **kwargs):
    some_variable = "x"
    with mlflow.start_run():
        mlflow.log_vars(exclude=["verbose"]) # logs local variables as parameters

if __name__ == '__main__':
    main("a", "b", something_else=6)
```
This will log:
```json
{
  "param1": "a",
  "param2": "b",
  "param3": "defaultvalue",
  "something_else": 6
}
```
For more info, also see the following feature request:
https://github.com/mlflow/mlflow/issues/1724
 
## How is this patch tested?
`pytest tests/tracking/test_tracking.py -k "test_log_vars"`

### Is this a user-facing change? 

- [ ] No. You can skip the rest of this section.
- [x] Yes. Give a description of this change to be included in the release notes for MLflow users.
 
Add `mlflow.log_vars` for automatically logging local variables.
 
### What component(s) does this PR affect?
 
- [ ] UI
- [ ] CLI 
- [ ] API 
- [ ] REST-API 
- [ ] Examples 
- [ ] Docs
- [x] Tracking
- [ ] Projects 
- [ ] Artifacts 
- [ ] Models 
- [ ] Scoring 
- [ ] Serving
- [ ] R
- [ ] Java
- [x] Python

### How should the PR be classified in the release notes? Choose one:
 
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [x] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by mgbckr** [comment]
Hi, I am not sure why the linting fails for the Travis tests. On my machine `./lint.sh` runs smoothly. 

Travis says:
```
ERROR: pylint-django 2.0.11 has requirement pylint>=2.0, but you'll have pylint 1.8.2 which is incompatible.
ERROR: flake8 3.7.8 has requirement pycodestyle<2.6.0,>=2.5.0, but you'll have pycodestyle 2.0.0 which is incompatible.
```

My changes should have nothing to do with this.

**Comment by mparkhe** [comment]
MLflow supports [Automatic logging](https://mlflow.org/docs/latest/tracking.html#automatic-logging) of ML params and metrics for several widely frameworks and algorithms. Can you describe the specific use case not covered by `log_params` and `set_tag` API and auto logging described above, you think will be solves with logging vars?

**Comment by mgbckr** [comment]
@mparkhe None of the auto logging functionality covers my rather simple use case: I am writing a function which runs an experiment, in my case `main`. Every time I want to add a parameter to that function, I have to add it twice: Once in the function call and once for logging it via `mlflow`. This introduces room for error: 1) forgetting to log a parameters your just added, and 2) simply more typos in the logging process. The `log_vars` method would alleviate these issue and makes logging are more seemless and "automatic" experience. Also, maybe see @LarsHill 's comment in [the corresponding feature request](https://github.com/mlflow/mlflow/issues/1724#issuecomment-554638078) for further details.

**Comment by mparkhe** [comment]
> ... Every time I want to add a parameter to that function, I have to add it twice: Once in the function call and once for logging it via `mlflow`. 

I understand what you are doing here, but what I am confused here is that if these are parameters you use for ML training in an ML algorithm used, you need instrument that in your code anyways. MLflow will record the git-hash for your code so what arguments are passed in can be back-calculated in case you are doing some math in your `main` function. If you are doing some feature computation for some input params, we recommend using [pyfunc model](https://github.com/mlflow/mlflow/blob/476dcd63a50d739ca8f4272bfd0215880419ce30/tests/pyfunc/test_model_export_with_loader_module_and_data_path.py#L72-L90) to do that.

> This introduces room for error: 1) forgetting to log a parameters your just added, and 2) simply more typos in the logging process. 

That sounds convenient, but most of these cases can be detected in dev stages. Additionally, this is where autologging will be useful. Currently it is available for a few frameworks and we will add more. 

> The `log_vars` method would alleviate these issues and make logging a more seamless and "automatic" experience. 

Yes. It sounds like it would solve the use case. However, I see two issues.
- It does not sounds like feature that is generally usage. For future maintainability, we are super careful about new APIs added to MLflow.
- In some cases, this sounds like a security risk. For instance, if some variables/params are used for credentials, they could get logged as params inadvertently.

Thanks for the pull request, however we will merge this. I am happy to chat more on how you can achieve this. Please do hit me up on [MLflow Slack](https://join.slack.com/t/mlflow-users/shared_invite/enQtMzkxMTAwNTcyODM5LTkzMDFhNzliNjExOGQ1ZGI1ZmFlMGE5YWE1OTI4ZGM1ZWZmYzc3NGNiZTM3YjgwOTdlODAzMjJhZTdiN2Y3MWY) if you like.

**Pull request closed without merging**
