### PR TITLE
Refactor: move tests cases to pytest in SQLAlchemy test suite [ver#7]

### PR DESCRIPTION
**Pull request by TomeHirata**
### Related Issues/PRs

https://github.com/mlflow/mlflow/issues/10042

### What changes are proposed in this pull request?

This is the 6th PR of https://github.com/mlflow/mlflow/issues/10042, which tries to refactor https://github.com/mlflow/mlflow/blob/master/tests/store/tracking/test_sqlalchemy_store.py into the pytest style

### How is this PR tested?

- [x] Existing unit/integration tests
- [ ] New unit/integration tests
- [ ] Manual tests

### Does this PR require documentation update?

- [x] No. You can skip the rest of this section.
- [ ] Yes. I've updated:
  - [ ] Examples
  - [ ] API references
  - [ ] Instructions

#### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

#### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>

#### How should the PR be classified in the release notes? Choose one:

- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by harupy** [comment]
@TomeHirata Thanks for the PR! Btw, any updates for the rate limits feature?

**Comment by TomeHirata** [comment]
>any updates for the rate limits feature?

Sorry, I couldn't work on that ticket since my main work has been busy for the past couple of weeks. I read the design doc, and asked one question on the PR.

**Comment by TomeHirata** [comment]
@harupy Could you please take a look when you have time? Some checks are failing probably since I initially created this PR as draft.

**Comment by TomeHirata** [comment]
@harupy Sorry, could you take a look at this PR?

**Comment by TomeHirata** [comment]
@BenWilson2 Would it be possible for you to review this MR?

**Comment by harupy** [comment]
@TomeHirata Sorry for the delay. Could you rebase on master?

**Review by harupy — APPROVED** [review]
LGTM!

**Comment by TomeHirata** [comment]
Rebased, could you help release it?

**Pull request merged**
