### PR TITLE
Add scheduled task to clean db

### PR DESCRIPTION
**Pull request by t-henri**
## What changes are proposed in this pull request?
 
The goal is to add a scheduler to be able to add periodic tasks in the server.
In this pull request, I only added one periodic task that samples the metrics for the oldest runs in the database. This will speed up the UI and also avoid infinite growth of the database.

The scheduler could then be used for many different tasks, for example:
- Archiving artifacts to save space in the artifact store.
- Deleting oldest runs along with their tags/parameters/metrics to free some DB space.
- Check for stuck runs and update their status to failed.

Corresponding issue: https://github.com/mlflow/mlflow/issues/1680
 
## How is this patch tested?
 
The scheduler has been tested manually, and there are integration tests for the method that samples the metrics.
 
### Is this a user-facing change? 

- [X] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.
 
(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)
 
### What component(s) does this PR affect?
 
- [ ] UI
- [ ] CLI 
- [ ] API 
- [ ] REST-API 
- [ ] Examples 
- [ ] Docs
- [X] Tracking
- [ ] Projects 
- [ ] Artifacts 
- [ ] Models 
- [ ] Scoring 
- [ ] Serving
- [ ] R
- [ ] Java
- [ ] Python

### How should the PR be classified in the release notes? Choose one:
 
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by t-henri** [comment]
Thanks for your feedback @pogil.

It would be possible to remove the tasks and add enough information to invoke them in the configuration, but don't you think that it could be relevant to keep some tasks inside MLflow core ? For example I think most people will want to remove the oldest runs from the db. I can also create a separate folder and not include the tasks code in mlflow/server/__init__.py so this code stays clean.

Also when you say that the task code could live outside of MLflow, do you include the functions I added in sqlalchemy store too ?

I will add some documentation so it is clearer how to use the scheduler.

**Comment by pogil** [comment]
@t-henri I think it makes sense to have the table and framework in MLflow tracking service (but I'll get some second opinions from the team). I'm not confident that the old run purging is an example of something that should be in by default - I'll get more input from others on this too. 

We should absolutely have a way to include tasks that live entirely outside of MLflow - we are working to have more points of extensibility throughout the project and this is a great example of an extension point that would be incredibly useful.

**Comment by t-henri** [comment]
Hello @pogil, I updated my pull request with your recommandations.
We can now use any function to pass to the scheduler using a json file, it was actually built-in in flask-apscheduler.
I added in examples an example of configuration/functions that can be used with the scheduler.
I also added a short documentation in docs/source folder.

Don't hesitate to tell me if it looks like what you were expecting, if the example/documentation is clear enough and if you have other remarks.

**Comment by pogil** [comment]
Hi @t-henri - thanks for your patience in me getting back to you. 

A recommendation from @mateiz was to instead run things outside the service - e.g. have a script that runs as a cron job on a machine and uses the API to perform tasks. I recognize this is differing a bit from my view expressed earlier, but wanted to make sure you hear this thought and explore it in your designs. It may be a much simpler solution than adding functionality to the service itself. This would also work with multiple backing stores.

Another point @mateiz raised was that we should be sure to think through implications adding the scheduler. We want to make sure that the tracking service be stateless, so that we can run multiple instances of the service to scale up the service easily with more replicas, especially with the SqlAlchemy store. What state does the scheduler have beyond the table you added to manage state of when a task was last run? Where is that state kept? How can we ensure that only a single instance of a tasks is running at one time>

**Comment by t-henri** [comment]
Hi @pogil, thanks for your feedbacks.

APScheduler do not scale natively (2 MLFlow servers would launch the same job at the same time) but it is easy to use the SQL database to make it atomic.
In my review, there is already a periodic_jobs table. I suggest to add the status of the job (RUNNING, DONE) and use a 'compare&swap' instruction to trigger the job once.

I still think a scheduler would be a great feature to have in MLflow since it could be useful for many usecases: monitoring jobs, cleaning database and artifact store...
Let's take the example of monitoring jobs. How to be check a run has not failed... we cannot rely on the fact the job has called the 'end_run' instruction. An external poller that will check the status  of running jobs in the databrick cluster, hadoop etc. is much more robust.

**Comment by mateiz** [comment]
@t-henri, is there any way to run this scheduler separately rather than having it be part of the tracking server? That server is supposed to be stateless, and it seems weird to combine it with this more stateful task. The micro services approach would be to have a different service for this stuff.

BTW, my recommendation for now would be to first write as shell command that users can run themselves to execute these tasks. For example, `mlflow cleanup`. Then users can schedule this through `cron`, Airflow, or other common scheduling mechanisms (we can recommend one in the doc and provide a template). Then if a lot of these come up and people want an MLflow-specific server to manage them, with a UI, we can add that as a new service.

Sorry for taking a while to reply to this BTW, I was busy in the past week. This is definitely a good feature but I'm not sure that the Flask server is the best place to do it.

**Comment by t-henri** [comment]
Hello @mateiz, thanks for your reply.

I understand your point of view, so I removed the scheduler and added it in my code.
I also added a new command line for the db cleanup `mlflow db cleanup`, is that what you meant by writing a shell command to execute the task ?

**Comment by mparkhe** [comment]
Hi @t-henri,

It will be safer to delete entire unused runs and experiments (or copy them to another database/move to another folder if using filestore). [`mlflow gc`](https://mlflow.org/docs/latest/cli.html#mlflow-gc) was recently added as a CLI feature to permanently delete runs in `deleted` lifecycle.  As recommended above, I would try adding `mlflow gc` to periodically clean up deleted runs using some mechanism like a cron job. The proposed approach in this pull request of sampling and deleting metrics is non-deterministic in nature and can leave in the database in an unpredictable state and may not be applicable in most use cases.

I am closing out this PR.

**Pull request closed without merging**
