### PR TITLE
Scoring Server - Added support for wrapped prediction responses

### PR DESCRIPTION
**Pull request by Ark-kun**
## What changes are proposed in this pull request?

Currently, MLFlow server returns predictions array as the response body.
However, some services require that the container endpoints they expose return results in a specific format. A common requirement is that the response should be a JSON object containing the predictions array as an attribute value. For example Google's Vertex Prediction service requires that the predictions are returned in the `{"predictions": PREDICTIONS_ARRAY}` format. https://cloud.google.com/vertex-ai/docs/predictions/custom-container-requirements#response_requirements

This commit makes it possible to specify the optional wrapper attribute name using the `PREDICTIONS_WRAPPER_ATTR_NAME` environment value.

### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [x] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

Scoring Server - Added support for wrapped prediction responses. It's now possible to specify the optional wrapper attribute name using the `PREDICTIONS_WRAPPER_ATTR_NAME` environment value. This makes the MLFlow server compatible with Google Cloud Vertex Predictions service.

### What component(s), interfaces, languages, and integrations does this PR affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [x] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>
### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [x] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by Ark-kun** [comment]
Hello. Is there any additional information you'd like me to provide?

**Review by tomasatdatabricks — APPROVED** [review]
lgtm

**Comment by rafa-am** [comment]
@Ark-kun It's a great feature, but I haven't found a way to use it when make a deploy to Sagemaker by `mlflow.sagwmaker` module. Do you have any tip how setup the `PREDICTIONS_WRAPPER_ATTR_NAME` environment value at that context?

Thanks!

**Comment by Ark-kun** [comment]
> @Ark-kun It's a great feature, but I haven't found a way to use it when make a deploy to Sagemaker by `mlflow.sagemaker` module. Do you have any tip how setup the `PREDICTIONS_WRAPPER_ATTR_NAME` environment value at that context?

I think this is only possible when you can control the env of the custom container you deploy.

Perhaps an alternative idea would have been to inject this configuration in the image being built.

**Comment by rafa-am** [comment]
> 

Nice! I was inspecting the [build_and_push_container(...)](https://github.com/mlflow/mlflow/blob/a90574dbb730935c815ff41a0660b9a823b81630/mlflow/sagemaker/cli.py#L571) functionality. I guess it should be good to have a additional input parameter to customize the `custom_setup_steps_hook` on:

https://github.com/mlflow/mlflow/blob/a90574dbb730935c815ff41a0660b9a823b81630/mlflow/sagemaker/cli.py#L587-L601

**Pull request merged**
