### PR TITLE
Update mlflow/R/mlflow/R/tracking-experiments.R

### PR DESCRIPTION
**Pull request by viktoriussuwandi**
## Related Issues/PRs

 #9166

## What changes are proposed in this pull request?

Hi [hn-jfitz](https://github.com/hn-jfitz),
I just try to update file [mlflow/mlflow/R/mlflow/R/tracking-experiments.R](https://github.com/mlflow/mlflow/blob/fe6434603499bc8e420b75492aa1c0ba64064f39/mlflow/R/mlflow/R/tracking-experiments.R#L214), please check it out

[Update mlflow/R/mlflow/R/tracking-experiments.R](https://github.com/mlflow/mlflow/commit/af46d3987cf1e99eaa502ee671bc92ed8301dc99)

(Please fill in changes proposed in this fix)

## How is this patch tested?

- [X] Existing unit/integration tests
- [ ] New unit/integration tests
- [ ] Manual tests (describe details, including test results, below)

## Does this PR change the documentation?

- [X] No. You can skip the rest of this section.
- [ ] Yes. Make sure the changed pages / sections render correctly in the documentation preview.

### Is this a user-facing change?

- [X] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [X] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by BenWilson2** [comment]
Hi @viktoriussuwandi could you add a unit test validation that confirms that this functions as expected?

**Comment by viktoriussuwandi** [comment]
Hi @BenWilson2,
Sorry,
I haven't write test code before, 
would you guide me step by step with `the code` possible for the test ?

Appreciate your guidance

**Comment by BenWilson2** [comment]
Hi @viktoriussuwandi here's the location of the R test suite that is relevant to your change: https://github.com/mlflow/mlflow/blob/master/mlflow/R/mlflow/tests/testthat/test-tracking-experiments.R 
We would just need an expectation assertion that the correct `experiment_id` is returned from the API call. 
This new behavior can be added as an assertion on the current no-op validation of line 11 in that test suite (`experiment_2_id` is not defined as there is not currently a return statement to the R func) to validate that the now returned value matches the value of `experiment_2a` (the result of the `mlflow_get_experiment()` API call). 

Should be pretty quick to add.

**Review by dbczumar — APPROVED** [review]
LGTM! Thanks @viktoriussuwandi . @BenWilson2 can we merge this without a test? All existing CI passes, and it's unclear to me why returning the experiment ID would break something :)

**Pull request merged**
