### PR TITLE
Capitalize stage name

### PR DESCRIPTION
**Pull request by keigohtr**
## What changes are proposed in this pull request?

Capitalize stage name on `.travis.yml`
Issued -> https://github.com/mlflow/mlflow/issues/2631

## How is this patch tested?

Run TravisCI

### Is this a user-facing change?

- [x] No. You can skip the rest of this section.

### CODE REVIEW

**Comment by keigohtr** [comment]
Errors are came from `PermissionError` of spark execution. It is same error to the other PR.

**Comment by keigohtr** [comment]
One of my changes is same as https://github.com/mlflow/mlflow/pull/2639
And the rest one is not necessary at the moment because "Large" stage name is not used in this repo. I can close this PR but how do you think?

**Review by dbczumar — APPROVED** [review]
@keigohtr Thanks for fixing this. I think it makes sense to merge the PR so that our stage name casing is consistent.

**Comment by keigohtr** [comment]
@dbczumar  Thanks :)
Could you merge this PR when you are ready 👍

**Comment by dbczumar** [comment]
@keigohtr This will be merged when tests pass. Thanks!

**Comment by keigohtr** [comment]
🤔 
Not finished yet...

**Comment by keigohtr** [comment]
Thanks :)

**Pull request merged**
