### PR TITLE
updated reference in Azure ML deployments

### PR DESCRIPTION
**Pull request by shivp950**
Signed-off-by: Shivani Patel 41974238+shivp950@users.noreply.github.com

## What changes are proposed in this pull request?

Added a reference to AzureML docs in the deploy to Azure section

## How is this patch tested?

(Details)

## Release Notes
Added a reference for model deployments to Azure

### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [ x] Yes. Give a description of this change to be included in the release notes for MLflow users.

Included a reference to Azure Machine Learning for model deployments
(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [x] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [x] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>
### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Review by harupy — DISMISSED** [review]
LGTM :)

**Comment by shivp950** [comment]
@harupy thanks for the quick review, is it possible to re run the failed tests? I don't think the failures have anything to do with my change. Would you suggest creating a new PR?

**Comment by harupy** [comment]
Hi @shivp950, could you merge the master branch on this PR's branch? I think it should fix the errors :)

**Comment by shivp950** [comment]
@harupy thanks that fixed almost every issue :) however the circleci test still fails, is there anything I can do to work around this error? 
     
ERROR: Cannot install sphinx-click==2.3.0 and sphinx==2.2.1 because these package versions have conflicting dependencies.
The conflict is caused by:
    The user requested sphinx==2.2.1
    sphinx-click 2.3.0 depends on sphinx<2.2 and >=1.5
To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

**Comment by harupy** [comment]
@shivp950 I think your local master is not synced with the upstream master.

**Comment by harupy** [comment]
@shivp950 Can I push a commit on this PR branch?

**Comment by shivp950** [comment]
> @shivp950 Can I push a commit on this PR branch?

go for it!

**Pull request closed without merging**
