### PR TITLE
Fix #825: add matplotlib to fix missing module error under docker image 

### LINKED ISSUE #825: ImportError: No module named matplotlib.pyplot in examples/sklearn_elasticnet_diabetes/train_diabetes.py in mlflow docker image
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
examples/sklearn_elasticnet_diabetes/train_diabetes.py
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 10.14.2
- **MLflow installed from (source or binary)**: MLflow Docker image
- **MLflow version (run ``mlflow --version``)**: mlflow, version 0.8.2.dev0
- **Python version**: 2.7.15
- **npm version (if running the dev UI):
- **Exact command to reproduce**:
```
docker run -it --rm mlflow /bin/bash
cd examples/sklearn_elasticnet_diabetes
python train_diabetes.py
```

### Describe the problem
When running this example, received ImportError message indicating missing matplotlib.pyplot

### Source code / logs
```
afc1d47c9ac2:python -u /opt/project/examples/sklearn_elasticnet_diabetes/train_diabetes.py
Traceback (most recent call last):
  File "/opt/project/examples/sklearn_elasticnet_diabetes/train_diabetes.py", line 26, in <module>
    import matplotlib.pyplot as plt
ImportError: No module named matplotlib.pyplot

Process finished with exit code 1
```

### Root Cause Analysis
matplotlib package not part of the Dockerfile to build the image.  Need to add matplotlib to the package requirements file (test-requirements.txt).  

Initial attempt at adding matplotlib to test-requirements.txt causes the docker image build to fail because install of dependent package (subprocess32)  fails.  Currently researching this.  See attached log file for details: [mlflow_dockerfile_build_failure.txt](https://github.com/mlflow/mlflow/files/2780626/mlflow_dockerfile_build_failure.txt)

### PR DESCRIPTION
**Pull request by jimthompson5802**
Fix #825: ImportError: No module named matplotlib.pyplot in examples/sklearn_elasticnet_diabetes/train_diabetes.py in mlflow docker image 

Overview of change:
* Added Python package matplotlib to test-requirements.txt
* Added support fo C compiler to Docker image to support install of one of matplotlib dependencies:  subprocess32.  pip install of this package is via source code and requires code compilation.  As a result add to Dockerfile `apt-get install -y build-essential` command.

### CODE REVIEW

**Comment by jimthompson5802** [comment]
Failure in Travis CI is on keras related tests.  AFAICT, these changes do not affect anything re: Keras. Two PR submitted after mine passed their CI checks.  Possible one-time fluke.  Trying to restart CI check by closing PR and re-opening.

**Comment by jimthompson5802** [comment]
reopening to try and restart CI tests based on this [posting](https://stackoverflow.com/questions/17606874/trigger-a-travis-ci-rebuild-without-pushing-a-commit)

**Comment by jimthompson5802** [comment]
Travis CI failed (Job 2926) again but this time on the R tests.  The Python 3 Keras test passed w/o issue.  Trying one more time to restart CI tests.

**Comment by jimthompson5802** [comment]
Restarting CI tests.

**Comment by dbczumar** [comment]
@jimthompson5802 Thank you for the contribution. After discussing it with the team, we feel that it may make sense to introduce an `MLproject` specification with a `conda.yaml` specification that enumerates the required dependencies, including `matplotlib` (just like the example you tweaked in #829). 

Ideally, the `Dockerfile` included in the repository root is intended to include the minimal set of dependencies for developing MLflow and running existing tests, so I'd like to avoid extending the set of test requirements (which are also installed for every Travis build) as much as possible.

Would you be willing to add an `MLproject` with a Conda environment for this example? Users could then execute `mlflow run ...` inside the Docker container to achieve the desired result.

**Comment by jimthompson5802** [comment]
@dbczumar Yes I can convert to `MLProject` structure. 

One process question: Should I do this work on this current pull request or should I close this pull request and submit a new pull request when I've the `MLProject` in place?

**Comment by dbczumar** [comment]
@jimthompson5802 Thanks so much! I think it's fine to perform this work in the same PR, no reason to submit a new one.

**Comment by jimthompson5802** [comment]
@dbczumar I've completed conversion to `MLProject` structure.  Ready for your review.

This is the log for a test run:
[sklearn_diabetes_mlproject_testrun.txt](https://github.com/mlflow/mlflow/files/2790130/sklearn_diabetes_mlproject_testrun.txt)

**Comment by jimthompson5802** [comment]
prep to restart travis ci build

**Comment by jimthompson5802** [comment]
restart travis ci build

**Review by dbczumar — APPROVED** [review]
LGTM!

**Comment by dbczumar** [comment]
@jimthompson5802 I tried the `MLproject` on OSX and Ubuntu. It ran properly on Ubuntu, but I encountered a matplotlib issue on OSX. It looks like there are extra dependencies for the conda environment that must be installed on OSX and are unavailable on Linux systems. They are documented here: https://matplotlib.org/faq/osx_framework.html#conda. 

I've updated the PR to divide the example into two subdirectories, one for each platform. Please let me know if this makes sense!

**Pull request merged**
