### PR TITLE
Revert "Correct R travis setup"

### PR DESCRIPTION
**Pull request by aarondav**
Reverts mlflow/mlflow#1259

### CODE REVIEW

**Review by javierluraschi — APPROVED** [review]

**Comment by javierluraschi** [comment]
Looks good, sorry about this!

**Comment by aarondav** [comment]
Going to cancel all builds but the R one, to see if we can soon merge this and retrigger the other PRs.

**Comment by aarondav** [comment]
https://travis-ci.org/mlflow/mlflow/jobs/532594103 is the R build for this PR

**Comment by aarondav** [comment]
Passed. Merging.

**Pull request merged**
