### PR TITLE
support xgboost for R

### PR DESCRIPTION
**Pull request by lorenzwalthert**
## What changes are proposed in this pull request?

This is a re-implementation of my previous attempt #2367. I hope @javierluraschi can review this since he already had a look at the previous implementation. Support saving and loading xgboost models from R. The models should be 100% compatible with the Python xgboost models, i.e. after saving with R or Python, they should be loadable with the other language too. The implementation closely follows the one for Keras models in the R package and the xgboost models from the Python package.

## How is this patch tested?

Unit tests, namely three types:

- save from R, predict from R.
- save from R, predict via CLI.
- save from R, load in R with python through reticulate.

The last two test types are important to ensure the model formats in `model/` are compatible between Python and R.

### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [x] Yes. Give a description of this change to be included in the release notes for MLflow users.

The model flavour xgboost is now also available for R. This means that xgboost models saved from R can be loaded in Python and vice versa. You can hence also deploy xgboost models trained in R as python_function on Microsoft Azure ML or Amazon AWS Sagemaker.

### What component(s) does this PR affect?

- [ ] UI
- [ ] CLI
- [ ] API
- [ ] REST-API
- [ ] Examples
- [ ] Docs
- [ ] Tracking
- [ ] Projects
- [ ] Artifacts
- [x] Models
- [ ] Scoring
- [ ] Serving
- [x] R
- [ ] Java
- [ ] Python

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [x] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by lorenzwalthert** [comment]
I think it would be great if @javierluraschi can you review this before @yl790 starts working on #1423 because this PR introduces some changes (`create_conda_env()` and some testing infra) that are going to be affect #1423 too.

**Review by yitao-li — APPROVED** [review]
Looks good to me!

**Review by javierluraschi — APPROVED** [review]

**Comment by javierluraschi** [comment]
Fixed merge conflict in GitHub master workflow specific to R section, hoping I can merge after tests succeed.

**Comment by lorenzwalthert** [comment]
Looks like things pass @javierluraschi.

**Pull request merged**
