### PR TITLE
Add optional Auth0 Integration

### PR DESCRIPTION
**Pull request by zbloss**
## What changes are proposed in this pull request?

This PR adds the option for end users to integrate MLflow with their Auth0 client of choice by setting Environment Variables:

- `REACT_APP_AUTH0_DOMAIN`
- `REACT_APP_AUTH0_CLIENT_ID`
- `REACT_APP_AUTH0_AUDIENCE`
- `REACT_APP_AUTH0_CALLBACK_URL`
- `REACT_APP_AUTH0_REFRESH_TOKENS`

## How is this patch tested?

Tested against the already-defined github workflows. The only failures are linting errors in tests that were written prior to this PR and have no effect on the new functionality.

### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [X] Yes. Give a description of this change to be included in the release notes for MLflow users.

This PR gives users the ability to secure their MLflow frontend application with the Auth0 provider of their choice. By setting a few environment variables, this feature will enforce that users are authenticated before they can view the MLflow UI.

### What component(s), interfaces, languages, and integrations does this PR affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>
### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [X] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by zbloss** [comment]
Hey all, I'm having some real issues getting the ExperimentPage test to pass. I could really use some help here if anyone has the time to help carry this across the finish line!

**Comment by zbloss** [comment]
@harupy @dbczumar @marijncv @WeichenXu123  Could someone please review this? I don't have the option to request a review for some reason.

**Comment by jdowning10** [comment]
@jinzhang21 This would be a very valuable feature for a range of users wanting even basic control over access. 
Given it's so close to completion, I would be grateful if this could be reviewed and merged.

**Comment by jinzhang21** [comment]
Sorry for the late reply, @jdowning10 . We plan to look into various solutions on authentications in the near future. Given the high stake of introducing security features, we need to plan this type of FR holistically. If the final design aligns with your implementation, we'll re-open this PR or at least get you involved in auth0 implementation. Thanks a lot for your understanding!

**Pull request closed without merging**
