### PR TITLE
SparkContext jvm issue [Credits : @smurching]

### PR DESCRIPTION
**Pull request by mparkhe**
gateway reported as `None` unless SparkContext initiated.

Credits to @smurching for finding a solution to this problem.

### CODE REVIEW

**Review by tomasatdatabricks — COMMENTED** [review]
Thanks Mani!

This code should not be called without having already existing  SparkContext. I want to be careful about when we create Spark Context;  e.g. Pyfunc creates its spark context with master set to "local[1]". Can you provide a bit of context for this fix? Is this a fix for a reported issue?

**Comment by mparkhe** [comment]
`examples/multistep_workflow` errored out with SparkContext not initialized. If there is a different place that `sc` should be initialized, please advise.

**Comment by tomasatdatabricks** [comment]
I am assuming it errored out in mlflow.spark.load_model? I would move the initialization there.

**Review by tomasatdatabricks — APPROVED** [review]
lgtm!

**Pull request merged**
