### PR TITLE
Set relative path to Font Awesome assets in CSS and fix missing resources when using `--static-prefix` option

### PR DESCRIPTION
**Pull request by danilopeixoto**
## Related Issues/PRs

#6556

## What changes are proposed in this pull request?

Set relative path to Font Awesome assets in CSS and fix missing resources when using `--static-prefix` option.

## How is this patch tested?

- [ ] Existing unit/integration tests
- [ ] New unit/integration tests
- [x] Manual tests (describe details, including test results, below)

Build server for production. The server was tested locally with and without `--static-prefix` option.

## Does this PR change the documentation?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Make sure the changed pages / sections render correctly in the documentation preview.

### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface

- [x] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [x] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by danilopeixoto** [comment]
@harupy Implemented Option 1 from #6556:

### Option 1: Use relative URLs (proposed by @danilopeixoto):

```diff
diff --git a/mlflow/server/js/craco.config.js b/mlflow/server/js/craco.config.js
index 38e717c1c..cf5764863 100644
--- a/mlflow/server/js/craco.config.js
+++ b/mlflow/server/js/craco.config.js
@@ -73,7 +73,7 @@ function configureIframeCSSPublicPaths(config, env) {
           cssRule.use
             ?.filter((loaderConfig) => loaderConfig?.loader.match(/\/mini-css-extract-plugin\//))
             .forEach((loaderConfig) => {
-              let publicPath = '/static-files/';
+              let publicPath = '../../';
               // eslint-disable-next-line no-param-reassign
               loaderConfig.options = { publicPath };
```

- This might not be compatible with MLflow UI on Databricks. Needs investigation.

### Option 2: Add a handler for `/static-files/`

```diff
diff --git a/mlflow/server/__init__.py b/mlflow/server/__init__.py
index 4718492a3..eaabc2fdd 100644
--- a/mlflow/server/__init__.py
+++ b/mlflow/server/__init__.py
@@ -67,6 +67,11 @@ def serve_static_file(path):
     return send_from_directory(STATIC_DIR, path)
 
 
+@app.route("/static-files/<path:path>")
+def serve_static_file_root(path):
+    return send_from_directory(STATIC_DIR, path)
+
+
 # Serve the index.html for the React App for all other routes.
 @app.route(_add_static_prefix("/"))
 def serve():
```

_Originally posted by @harupy in https://github.com/mlflow/mlflow/issues/6556#issuecomment-1225582525_

**Comment by WeichenXu123** [comment]
we need test on databricks, do you have databricks environment for testing ? @danilopeixoto

**Comment by danilopeixoto** [comment]
@WeichenXu123 Unfortunately not, would you provide reference or instructions to the test?
Thanks!

**Comment by WeichenXu123** [comment]
> @WeichenXu123 Unfortunately not, would you provide reference or instructions to the test? Thanks!

I just checked that databricks code already contains the change the same to your PR.

**Comment by danilopeixoto** [comment]
@WeichenXu123 Can you provide details on how this could affect Databricks?
The Databricks platform seems to use a different path for Font Awesome assets:

Databricks

**Comment by WeichenXu123** [comment]
Thank you. I think databricks code is not affected.

**Comment by danilopeixoto** [comment]
Will the fix make it into the next release?

**Review by WeichenXu123 — APPROVED** [review]

**Pull request merged**
