### PR TITLE
Adjust tolerance thresholds for TF DNN model in test suite

### PR DESCRIPTION
**Pull request by BenWilson2**
Signed-off-by: Ben Wilson <benjamin.wilson@databricks.com>

## Related Issues/PRs

 #xxx

## What changes are proposed in this pull request?

Adjust the absolute tolerance and relative tolerance for the result types of comparison in the categorical model to ensure that small-value floating point numbers are compared with the appropriate precision.

## How is this patch tested?

- [X] Existing unit/integration tests
- [ ] New unit/integration tests
- [X] Manual tests (describe details, including test results, below)

See notes below.

## Does this PR change the documentation?

- [X] No. You can skip the rest of this section.
- [ ] Yes. Make sure the changed pages / sections render correctly in the documentation preview.

### Is this a user-facing change?

- [X] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [X] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [X] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by BenWilson2** [comment]
For a recent test suite failure here: https://github.com/mlflow/mlflow/actions/runs/3648688477/jobs/6162437683

If we take the first 100 rows of this data set and compare them for absolute differences, we get the following: 

absolute_diff

The module `pandas.testing.assert_frame_equal()` uses the formula:

absolute(a - b) <= (atol + rtol * absolute(b))

in order to calculate the equivalency for each cell between the DataFrames. In most cases, this works pretty well and is relatively stable. However, with relatively small numbers (as in the dataset used for this test) the default atol value can dramatically impact the equivalency check and create issues with cast values. 

I tested the thresholds as follows, with output data directly from the test failure:

```
a = pd.DataFrame([1.3799863, 1.3799863, 1.8562052, 1.2268338, 0.72366196, 1.4768169, 1.4768169, 1.4768169, 0.36997527, 1.2778845, 1.2778845, 1.7735908, 1.7735908, 1.0262979, 1.6066658, 1.6066658, 1.2745115, 6.574765e-05, 0.073218286, 0.073218286, -0.32728773, 1.2742187, 1.2268338, 1.2742187, 1.2742187, 1.2742187, 1.2268338, 1.2268338, 1.077349, -0.57806355, 1.2742187, -0.38649637, 0.08716434, 0.08716434, 0.08716434, 0.08716434, 1.0736822, 1.0736822, 1.0736822, 1.0736822, 0.41735977, 1.1757839, 0.82209677, 0.82209677, 0.8768138, 0.8768138, 0.97679555, -1.3445327, 1.2742187, 1.2742187, 1.2742187, 1.2742187, 1.5653586, 1.5653586, 1.5653586, 2.0318508, 1.1247337, 1.1247337, 1.1247337, 1.1247337, 0.61422676, 1.1247337, 2.2723775, 1.6789558, 0.10110897, 0.10110897, 0.10110897, 0.10110897, -0.003360685, -0.003360685, 0.11505443, 0.11505443, 1.077349, -0.32728773, 1.2742187, 1.2742187, 1.2268338, 1.6788269, 1.5805209, 1.077349, 1.077349, 1.077349, 1.5805209, 1.5805209, 1.6788269, 1.6788269, 0.86948174, -0.34123498, 0.86948174, 0.86948174, 0.86948174, 0.86948174, 0.86948174, 0.86948174, 0.86948174, 0.86948174, 1.47842, 1.47842, 1.1788055, 1.1788055],
                columns=["a"])
                
b = pd.DataFrame([1.379986, 1.379986, 1.8562045, 1.2268342, 0.7236617, 1.4768177, 1.4768177, 1.4768177, 0.36997503, 1.2778835, 1.2778835, 1.7735897, 1.7735897, 1.0262985, 1.6066663, 1.6066663, 1.2745112, 6.527081e-05, 0.07321924, 0.07321924, -0.32728893, 1.2742181, 1.2268342, 1.2742181, 1.2742181, 1.2742181, 1.2268342, 1.2268342, 1.0773492, -0.578064, 1.2742181, -0.38649732, 0.087164104, 0.087164104, 0.087164104, 0.087164104, 1.0736825, 1.0736825, 1.0736825, 1.0736825, 0.4173581, 1.1757836, 0.8220963, 0.8220963, 0.8768138, 0.8768138, 0.9767965, -1.344533, 1.2742181, 1.2742181, 1.2742181, 1.2742181, 1.5653583, 1.5653583, 1.5653583, 2.031851, 1.124733, 1.124733, 1.124733, 1.124733, 0.6142265, 1.124733, 2.2723768, 1.6789544, 0.10110921, 0.10110921, 0.10110921, 0.10110921, -0.0033604465, -0.0033604465, 0.115054786, 0.115054786, 1.0773492, -0.32728893, 1.2742181, 1.2742181, 1.2268342, 1.678826, 1.5805206, 1.0773492, 1.0773492, 1.0773492, 1.5805206, 1.5805206, 1.678826, 1.678826, 0.8694801, -0.34123474, 0.8694801, 0.8694801, 0.8694801, 0.8694801, 0.8694801, 0.8694801, 0.8694801, 0.8694801, 1.4784197, 1.4784197, 1.1788052, 1.1788052],
                columns=["a"])

pd.testing.assert_frame_equal(a, b, rtol=1e-3)
```
Which clearly fails. with a 1.0% mismatch in rows.

Test 2:
```
pd.testing.assert_frame_equal(a, b, atol=1e-6)
```
This uses the default rtol value of 1e-5 (as per https://pandas.pydata.org/docs/reference/api/pandas.testing.assert_frame_equal.html). This passes, but is also highly dependent on the data values under test of the `b` set, making the stability less than ideal for small float values.

Test 3:
```
pd.testing.assert_frame_equal(a, b, atol=1e-5, rtol=0)
```
Passes and is purely looking at precision comparison at the 5th decimal place, which seems to be what we're going for with the pyfunc type casting for floating point numbers.

Test 4:
```
pd.testing.assert_frame_equal(a, b, atol=1e-6, rtol=0)
```
The fails (as expected) with 17% of values non-matching due to rounding precision.

**Comment by BenWilson2** [comment]
Fix for flavors is in https://github.com/mlflow/mlflow/pull/7485

**Review by harupy — APPROVED** [review]
LGTM!

**Review by dbczumar — APPROVED** [review]
LGTM! Thanks @BenWilson2 !

**Pull request merged**
