### PR TITLE
Make all links relative to root

### PR DESCRIPTION
**Pull request by ed-sa-ma**
### Related Issues/PRs

 #xxx

### What changes are proposed in this pull request?

This PR makes all the internal links in the documentation pages migrated up to now relative to the root page of the docs.

Let's consider the following folder example:

```
docs
    |__tracking
    |__models
        |__dependencies
            |__signatures
        |__notebooks
            |__tasks
            |__guide
```

Until now we used two approaches for links in the docs:

1. When a link points to a page outside of the current folder we would use paths relative to the root of the docs. For example if we were in `tasks` page and wanted to point to `signatures` we would use `[...](/models/dependencies/signatures)`.
2. When a link points to a page nested deeper in the current folder we would use paths relative to the current folder. For example if we were in `models` and wanted to point to `guide` we would use `[...](notebooks/guide)`.

We noticed a problem with the links on 2. where they would point to different directions depending on how the page URL is written. If the page URL has a trailing slash —and maybe "index.html", but it is the slash what changes the behavior—, the relative path works as expected, but if the page path excludes the trailing slash the browser treats it as a page instead of a folder and relative paths go one level up.

https://github.com/user-attachments/assets/ad427917-741c-40fd-8865-3b6670e7a5d7

#### Extra changes

- There are auto-format changes in `docs/introduction/index.mdx`, `docs/tracing/index.mdx`, `docs/model-evaluation/index.mdx`, `docs/tracing/production.mdx`, `docs/tracing/session.mdx`, `docs/tracing/client.mdx`, `docs/tracing/sdk/how-to.mdx`, `docs/tracing/sdk/manual-instrumentation.mdx`, `docs/tracing/sdk/search.mdx` and `docs/tracing/index.mdx`.
- There are a couple  of unnecessary headline id override removals in `docs/models/index.mdx` and `docs/tracking/tracking-api/index.mdx`.
- We fix one link where the protocol was "hhttp" in the notebook `docs/llms/transformers/tutorials/conversational/pyfunc-chat-model.ipynb`.

### How is this PR tested?

- [ ] Existing unit/integration tests
- [ ] New unit/integration tests
- [x] Manual tests

### Does this PR require documentation update?

- [ ] No. You can skip the rest of this section.
- [ ] Yes. I've updated:
  - [ ] Examples
  - [ ] API references
  - [ ] Instructions

#### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

#### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>

#### How should the PR be classified in the release notes? Choose one:

- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

#### Should this PR be included in the next patch release?

`Yes` should be selected for bug fixes, documentation updates, and other small changes. `No` should be selected for new features and larger changes. If you're unsure about the release classification of this PR, leave this unchecked to let the maintainers decide.

<details>
<summary>What is a minor/patch release?</summary>

- Minor release: a release that increments the second part of the version number (e.g., 1.2.0 -> 1.3.0).
  Bug fixes, doc updates and new features usually go into minor releases.
- Patch release: a release that increments the third part of the version number (e.g., 1.2.0 -> 1.2.1).
  Bug fixes and doc updates usually go into patch releases.

</details>

- [ ] Yes (this PR will be cherry-picked and included in the next patch release)
- [x] No (this PR will be included in the next minor release)

### CODE REVIEW

**Review by daniellok-db — APPROVED** [review]
looks good, thanks for spotting this!

**Comment by daniellok-db** [comment]
it looks like this might need a rebase due to some other changes that merged in the meantime!

**Comment by ed-sa-ma** [comment]
@B-Step62 added you as reviewer as I apply some changes to the new files you recently created [here](https://github.com/mlflow/mlflow/pull/14073).

**Review by daniellok-db — APPROVED** [review]
LGTM, i think it might be worth making a lint rule for this, but we can always improve developer experience further down the line (and that depends on us having a working linter 😅)

**Pull request merged**
