### PR TITLE
Adjustments to config retrieval when schema is Databricks

### PR DESCRIPTION
**Pull request by zacdav-db**
<details><summary>&#x1F6E0 DevTools &#x1F6E0</summary>
<p>

[Open in GitHub Codespaces](https://codespaces.new/zacdav-db/mlflow/pull/10117?quickstart=1)

#### Install mlflow from this PR

```
pip install git+https://github.com/mlflow/mlflow.git@refs/pull/10117/merge
```

#### Checkout with GitHub CLI

```
gh pr checkout 10117
```

</p>
</details>

### What changes are proposed in this pull request?

Currently within Databricks mlflow does not respect environment variables for configs when set.
This PR changes the underlying behaviour of `get_databricks_config()` such that the logic is changed to fetch the variables within the Databricks R session **last**.

[Previous Behaviour](https://github.com/mlflow/mlflow/blob/2801858f65203a7f3155e412ca3fc2e0bff92803/mlflow/R/mlflow/R/databricks-utils.R#L77-L99):

1. Check for presence of profile specified as part of URI, if present, attempt to return config
2. If no profile was specified as part of URI eagerly fetch variables from R session in Databricks
3. If not in Databricks:
   a. Attempt to fetch config from environment variables
   b. Attempt to fetch config from `DEFAULT` profile

This means users within Databricks are forced to create `.databrickscfg` file to remotely connect to another workspace for tracking.

It's not possible to set the environment variables and have them detected as the logic will preferentially use the notebook session variables which are re-injected after _every_ command run.

[New Behaviour:](https://github.com/zacdav-db/mlflow/blob/fd21339a2a3127818f0884bd3d96fcc2173bb552/mlflow/R/mlflow/R/databricks-utils.R#L77-L117)

1. Check for presence of profile specified as part of URI, if present, attempt to return config
2. Attempt to fetch config from environment variables, if successful and config is valid, return early
3. Attempt to fetch config from `DEFAULT` profile
   a. If fetching the `DEFAULT` profile errors (due to absence) then return a list that is known to be an invalid config
   b. If successful proceed to (3c)
   c. Return early if config is valid
4. If within a Databricks R session, fetch variables and validate config, return early if successful
 
### How is this PR tested?

- [x] Existing unit/integration tests
- [ ] New unit/integration tests
- [x] Manual tests

```r
# within databricks
library(mlflow)

exps <- mlflow_search_experiments()$experiments
display(exps[, 1:4])

# credentials for a workspace different to the one running code
Sys.setenv("DATABRICKS_HOST" = "<redacted>")
Sys.setenv("DATABRICKS_TOKEN" = "<redacted>")

# successfully shows external workspaces experiments
exps <- mlflow_search_experiments()$experiments
display(exps[, 1:4])

# revoke credentials
Sys.unsetenv("DATABRICKS_HOST")
Sys.unsetenv("DATABRICKS_TOKEN")

# same result as initially (current workspaces experiments) 
exps <- mlflow_search_experiments()$experiments
display(exps[, 1:4])
```

### Does this PR require documentation update?

- [x] No. You can skip the rest of this section.
- [ ] Yes. I've updated:
  - [ ] Examples
  - [ ] API references
  - [ ] Instructions

#### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [x] Yes. Give a description of this change to be included in the release notes for MLflow users.

R Mlflow running within Databricks will now correctly respect environment variables and the `DEFAULT` profile in `.databrickscfg` when present.

#### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language

- [x] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [x] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>

#### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [x] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by BenWilson2** [comment]
A few notes:

- Can the control logic flow be changed a bit? The previous implementation was somewhat straight forward with an if, else if, else scheme. The new logic here is if, else, short-circuit commands. It's a bit hard to read and would be challenging to modify in the future without a total rewrite. 

Can this be adapted to a sequential pattern of configuration check and short-circuit return iff the configuration is valid? 

- Explicit environment checks to make the logic more readable

Instead of using `exists`, can we make it explicit that we're checking the environment variables here within the .GlobalEnv?

- Use of `lapply` to define an NA collection

Can we just create a list directly with the rep(list()) command to define the list and index length?

- Final validation check is redundant. 

The previous behavior of doing a final check with a stop (raise) was a bit more straightforward and easier to read. 

- Reduce logical branching variable reassignment. 

It takes a bit of effort to follow along with what's going on when there are variable reassignments happening in different logical branches. The config reassignment makes sense, but it should be consumed immediately in this case. 

Here's a quick take on some of those suggestions (I didn't test it, but it could be a good reference for refactoring the logic to be a bit more readable):

``` r
get_databricks_config <- function(profile) {
  
  # If a profile is provided, fetch its configuration
  if (!is.na(profile)) {
    config <- get_databricks_config_for_profile(profile)
    if (databricks_config_is_valid(config)) {
      return(config)
    }
  }

  # Check for environment variables
  config <- get_databricks_config_from_env()
  if (databricks_config_is_valid(config)) {
    return(config)
  }

  # Check 'DEFAULT' profile
  config <- tryCatch({
    get_databricks_config_for_profile("DEFAULT")
  }, error = function(error_condition) {
    # Return known invalid config
    config <- list(host = NA, token = NA, username = NA, password = NA)
    return(config)
  })
  if (databricks_config_is_valid(config)) {
    return(config)
  }

  # When in Databricks (done last so other methods are explicit overrides)
  if (exists("spark.databricks.token", envir = .GlobalEnv) && 
      exists("spark.databricks.api.url", envir = .GlobalEnv)) {
    config_vars <- list(
      host = get("spark.databricks.api.url", envir = .GlobalEnv),
      token = get("spark.databricks.token", envir = .GlobalEnv),
      insecure = Sys.getenv(config_variable_map$insecure, "False")
    )
    config <- new_databricks_config(config_source = "db_dynamic", config_vars = config_vars)
    if (databricks_config_is_valid(config)) {
      return(config)
    }
  }

  # If no valid configuration is found by this point, raise an error
  stop("Could not find valid Databricks configuration.")
}
```

**Review by BenWilson2 — CHANGES_REQUESTED** [review]
See https://github.com/mlflow/mlflow/pull/10117#issuecomment-1779630937

**Comment by zacdav-db** [comment]
I've adjusted to be very similar to your feedback @BenWilson2.

Ended up keeping logic for checking for `DEFAULT` profile as I think users outside of Databricks will expect this.

Adding screenshots of testing in Databricks:

**[OLD] DBR 14.1 ML**
See that IDs are same for each cell.
dbr141ml-old

**[NEW] DBR 14.1 ML**
Correctly see different IDs in second cell.
dbr141ml

**[NEW] DBR 14.1 Standard**
Correctly see different IDs in second cell.
dbr141std

**Review by BenWilson2 — APPROVED** [review]
This is a great fix @zacdav-db ! Thank you so much for providing it and validating the fix works exactly as intended!

**Pull request merged**
