### PR TITLE
Update TF version to 1.15.2

### PR DESCRIPTION
**Pull request by mparkhe**
Updating `tensorflow` to `1.15.2`, based on **high severity** security alert: https://github.com/mlflow/mlflow/network/alert/travis/large-requirements.txt/tensorflow/open

## What changes are proposed in this pull request?

(Please fill in changes proposed in this fix)

## How is this patch tested?

(Details)

### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s) does this PR affect?

- [ ] UI
- [ ] CLI
- [ ] API
- [ ] REST-API
- [ ] Examples
- [ ] Docs
- [ ] Tracking
- [ ] Projects
- [ ] Artifacts
- [ ] Models
- [ ] Scoring
- [ ] Serving
- [ ] R
- [ ] Java
- [ ] Python

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by juntai-zheng** [comment]
Would it be good to change https://github.com/mlflow/mlflow/blob/d05e1cd2be6f7d5e950e70115dae7e6f5d7acbe2/mlflow/R/mlflow/.travis.R, https://github.com/mlflow/mlflow/blob/8a9b5f1ef494f531dbf88896f1048cb855c0e078/examples/multistep_workflow/conda.yaml, and https://github.com/mlflow/mlflow/blob/45b01d1e99c98aed9d5852e905f91827f89e9170/examples/tensorflow/tf1/conda.yaml as well since they're below 1.15.2? Will tests break if we update those?

**Comment by mparkhe** [comment]
@juntai-zheng : `examples/tensorflow/tf1` ran into some issues with existing conda environment. I suspect, I would have to upgrade `keras` as well to get this working.  I have fixed the others. I will experiment with it independently, with different versions for `tensorflow` and `keras`

**Review by juntai-zheng — APPROVED** [review]
LGTM, we will need to see how we can upgrade the example up to 1.15.2 as well.

**Comment by mparkhe** [comment]
> LGTM, we will need to see how we can upgrade the example up to 1.15.2 as well.

yeah! changing `conda.yaml` to include `tensorflow` inside pip worked locally on my machine but balked on travis.

**Pull request merged**
