### PR TITLE
Fix run ID handling in OAI autologging

### LINKED ISSUE #13608: [BUG] Trace recorded by openai.autolog does not map correct Run
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

- Client: 2.15.1
- Tracking server: 2.15.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Rocky Linux9
- **Python version**: python3.9
- **yarn version, if running the dev UI**:

### Describe the problem

I created runs with two different system prompts and executed openai.autolog within them. By specifying log_trace=True, I recorded the trace. While parameters and metrics were recorded for each run, the trace is associated with the first run in both cases.

I create 2 run and use openai.autlog on each run. 
1st Run: openai-evaluate-20241030-134133-0
2nd Run: openai-evaluate-20241030-134133-1
image

but the both traces is associated with the first Run.
I think trace should be associated with each Run.
image

I think the reason for this bug is that when run_id is retrieved with getattr, it is not checked if the id matches the active_run.

https://github.com/mlflow/mlflow/blob/master/mlflow/openai/_openai_autolog.py#L101
```
    config = AutoLoggingConfig.init(flavor_name=mlflow.openai.FLAVOR_NAME)
    run_id = getattr(self, "_mlflow_run_id", None)
    active_run = mlflow.active_run()
    mlflow_client = mlflow.MlflowClient()
```

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
import mlflow
import os
from openai import OpenAI
import datetime

client = OpenAI(api_key=os.environ.get("OPENAI_API_KEY", "<your OpenAI API key if not set as env var>"))

system_prompts = [
    "Please provide an answer to the question in 50 characters or less.",
    "You are a Python expert. Please provide an answer related to Python in response to the question, within 100 characters.",
]

test_input = "What is MLflow？"
mlflow.set_experiment("examin-openai-en")
run_date = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

# Change the system prompt with each run. Record the input and the corresponding output (OpenAI API response).
for i, system_prompt in enumerate(system_prompts):
    with mlflow.start_run(run_name=f"openai-evaluate-{run_date}-{i}") as run:
        print(f"active_run_id: {mlflow.active_run().info.run_id}")
        mlflow.openai.autolog(log_input_examples=True,
                                log_model_signatures=True,
                                log_models=True,
                                log_traces=True,
                                extra_tags={"system_prompt": system_prompt})

        response = client.chat.completions.create(
            model="gpt-4o",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": test_input},
            ],
            temperature=0,
        )
```

### Stack trace

This bug has no stack trace. But I explained the detail cause of this bug on description.

### Other info / logs

```
[13:38:49] -> % python mlflow_openai_autolog_en.py

# here is the first active run
active_run_id: 9678e903550846308c6f08c62c6bd113

2024/10/30 13:41:46 INFO mlflow.tracking._tracking_service.client: 🏃 View run openai-evaluate-20241030-134133-0 at: https://myuhara.mlflow.yahoo.co.jp/#/experiments/2705/runs/9678e903550846308c6f08c62c6bd113.
2024/10/30 13:41:46 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: https://myuhara.mlflow.yahoo.co.jp/#/experiments/2705.

# here is the second active run
active_run_id: cbbf2c5ed2404faea7135ffc3c0184a2
2024/10/30 13:41:47 INFO mlflow.tracking._tracking_service.client: 🏃 View run openai-evaluate-20241030-134133-0 at: https://myuhara.mlflow.yahoo.co.jp/#/experiments/2705/runs/9678e903550846308c6f08c62c6bd113.
2024/10/30 13:41:47 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: https://myuhara.mlflow.yahoo.co.jp/#/experiments/2705.
2024/10/30 13:41:47 INFO mlflow.tracking._tracking_service.client: 🏃 View run openai-evaluate-20241030-134133-1 at: https://myuhara.mlflow.yahoo.co.jp/#/experiments/2705/runs/cbbf2c5ed2404faea7135ffc3c0184a2.
2024/10/30 13:41:47 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: https://myuhara.mlflow.yahoo.co.jp/#/experiments/2705.
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

### PR DESCRIPTION
**Pull request by B-Step62**
### Related Issues/PRs

Fix https://github.com/mlflow/mlflow/issues/13608

### What changes are proposed in this pull request?

The bug happens when user invokes OAI client multiple times but in separate runs. When autologging is enabled and `log_model` is set to `True`, MLflow logs the OAI model when the OAI client is called. At this time, if there is no active run, MLflow creates a new run and log the model/trace there. However, if the same client is called again, we want to avoid creating a run again. This deduplication is done by storing extra attribute `_mlflow_run_id` attribute. MLflow looks at this attribute and only create a run when it is not present.

```
    # Even if the model is not logged, we keep a single run per model
    if not hasattr(self, "_mlflow_run_id"):
        self._mlflow_run_id = run_id
```

We use this `self._mlflow_run_id` for tracing to determine which Run to associate the auto-generated trace.

However, the problem is that this `self._mlflow_run_id` is not updated when the user creates a new active Run. Since that attribute is only updated once for the first run, MLflow keep using the old run ID for logging new traces and models.

```
mlflow.openai.autolog(log_models=True)

with mlflow.start_run() as run_1:
    # Here the `_mlflow_run_id` attribute is set to run_1's ID
    client.chat.completion.create(...)

with mlflow.start_run() as run_2:
    # Here we must log trace/model to run_2, but `_mlflow_run_id` is still run_1's ID, so MLflow use run_1 instead!
    client.chat.completion.create(...)
```

↓ as a result, both traces are linked to run 1.

Screenshot 2024-10-30 at 20 50 33

The correct behavior is that the active Run should always take precedence and MLflow updates `_mlflow_run_id` attribute accordingly. This PR implements that solution.

### How is this PR tested?

- [x] Existing unit/integration tests
- [x] New unit/integration tests
- [x] Manual tests

Screenshot 2024-10-30 at 20 52 42

Traces are linked to the correct Runs respectively.

### Does this PR require documentation update?

- [x] No. You can skip the rest of this section.
- [ ] Yes. I've updated:
  - [ ] Examples
  - [ ] API references
  - [ ] Instructions

#### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

#### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>

#### How should the PR be classified in the release notes? Choose one:

- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

#### Should this PR be included in the next patch release?

`Yes` should be selected for bug fixes, documentation updates, and other small changes. `No` should be selected for new features and larger changes. If you're unsure about the release classification of this PR, leave this unchecked to let the maintainers decide.

<details>
<summary>What is a minor/patch release?</summary>

- Minor release: a release that increments the second part of the version number (e.g., 1.2.0 -> 1.3.0).
  Bug fixes, doc updates and new features usually go into minor releases.
- Patch release: a release that increments the third part of the version number (e.g., 1.2.0 -> 1.2.1).
  Bug fixes and doc updates usually go into patch releases.

</details>

- [x] Yes (this PR will be cherry-picked and included in the next patch release)
- [ ] No (this PR will be included in the next minor release)

### CODE REVIEW

**Review by harupy — APPROVED** [review]
LGTM!

**Review by harupy — APPROVED** [review]
LGTM!

**Review by harupy — APPROVED** [review]
re-approve to test #13606

**Comment by B-Step62** [comment]
oops sorry I might messed up the test opportunity😂

**Comment by B-Step62** [comment]
build-doc job is broken on master, force merging

**Pull request merged**
