### PR TITLE
Fixes sqlalchemy schema failures in master

### PR DESCRIPTION
**Pull request by AveshCSingh**
Signed-off-by: Avesh Singh <aveshcsingh@gmail.com>

## What changes are proposed in this pull request?

The [1.3.21 release](https://docs.sqlalchemy.org/en/14/changelog/changelog_13.html#change-1.3.21) of SQLAlchemy introduced a fix to the ordering of composite primary key columns:

```
Fixed issue with composite primary key columns not being reported in the correct order.
```

As a result, our tests started failing with errors like:
```
E           AssertionError: Generated schema did not match expected schema. Generated schema had table definition:
E             
E             CREATE TABLE metrics (
E             	key VARCHAR(250) NOT NULL,
E             	value FLOAT NOT NULL,
E             	timestamp BIGINT NOT NULL,
E             	run_uuid VARCHAR(32) NOT NULL,
E             	step BIGINT DEFAULT '0' NOT NULL,
E             	is_nan BOOLEAN DEFAULT '0' NOT NULL,
E             	CONSTRAINT metric_pk PRIMARY KEY (key, timestamp, step, run_uuid, value, is_nan),
E             	FOREIGN KEY(run_uuid) REFERENCES runs (run_uuid)
E             )
E             Expected schema had table definition:
E             
E             CREATE TABLE metrics (
E             	key VARCHAR(250) NOT NULL,
E             	value FLOAT NOT NULL,
E             	timestamp BIGINT NOT NULL,
E             	run_uuid VARCHAR(32) NOT NULL,
E             	step BIGINT DEFAULT '0' NOT NULL,
E             	is_nan BOOLEAN DEFAULT '0' NOT NULL,
E             	CONSTRAINT metric_pk PRIMARY KEY (key, value, timestamp, run_uuid, step, is_nan),
E             	FOREIGN KEY(run_uuid) REFERENCES runs (run_uuid)
E             )
```

Notice the change: Ordering of composite primary keys.

This PR fixes this issue by requiring a minimum SQLAlchemy version which fixes this bug, and updating our schema to reflect the correct composite primary key ordering.

## How is this patch tested?

Unit tests

### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [x] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Review by dbczumar — APPROVED** [review]
LGTM! Thanks @AveshCSingh !

**Comment by harupy** [comment]
https://github.com/mlflow/mlflow/pull/3864/checks?check_run_id=1574060010#step:4:309

**Comment by dbczumar** [comment]
> `test-anaconda-compatibility.sh` fails with
> 
> ```
> MLflow installation modified the Anaconda distribution:
> 
> ...
> 
> < SQLAlchemy==1.3.13
> ---
> > SQLAlchemy==1.3.21
> ```
> 
> https://github.com/mlflow/mlflow/pull/3864/checks?check_run_id=1574060010#step:4:309

Thanks @harupy ! After some offline discussion with @AveshCSingh , I think it seems reasonable to specify a min version of sqlalchemy for our tests while leaving the MLflow one unpinned.

**Comment by harupy** [comment]
btw can we create two `.sql` files?

**Pull request merged**
