### PR TITLE
view ui from another machine

### PR DESCRIPTION
**Pull request by sameermahajan**
## What changes are proposed in this pull request?
 
(Please fill in changes proposed in this fix)
 
## How is this patch tested?
 
(Details)
 
### Is this a user-facing change? 

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.
 
(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)
 
### What component(s) does this PR affect?
 
- [ ] UI
- [ ] CLI 
- [ ] API 
- [ ] REST-API 
- [ ] Examples 
- [x] Docs
- [ ] Tracking
- [ ] Projects 
- [ ] Artifacts 
- [ ] Models 
- [ ] Scoring 
- [ ] Serving
- [ ] R
- [ ] Java
- [ ] Python

### How should the PR be classified in the release notes? Choose one:
 
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by mateiz** [comment]
Thanks for the change, but this shouldn't go into the Quickstart IMO. The Quickstart is supposed to be a very short tutorial to get people running. Can this go into the section on running a tracking server?

**Comment by sameermahajan** [comment]
thanks @mateiz for your feedback. Submitting PR with new set of changes based on your feedback.

**Review by Lucas-Cerqueira — CHANGES_REQUESTED** [review]
I suggest changing "you can view the ui using URL" with "you can view the UI using URL". In the rest of the file, "UI" is being used, in capital letters.

**Comment by mateiz** [comment]
This looks good, thanks! Sorry it took a while to review it again.

**Pull request merged**
