### PR TITLE
Run autolabeling action less frequently & only scan past week's worth of issues to avoid hitting rate limits

### PR DESCRIPTION
**Pull request by smurching**
## What changes are proposed in this pull request?

Runs the autolabeling action introduced in #3070 less frequently & only scan past day's worth of issues to avoid hitting rate limits (see that the labeling workflow failed in https://github.com/mlflow/mlflow/actions/runs/165088333)

## How is this patch tested?

It's not 😬 - I think I could test it by merging this commit into the master branch of my MLflow fork? I did verify though that my updated offset param was valid by looking at https://github.com/harupy/auto-labeling/blob/master/src/enums.ts#L8

### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Review by harupy — COMMENTED** [review]
@smurching Thanks for the fix. LGTM!

**Review by harupy — APPROVED** [review]

**Comment by harupy** [comment]
@smurching I fixed the logic to minimize the number of the API calls. It became almost half.

### Before:

Screen Shot 2020-07-11 at 12 20 22

https://github.com/mlflow/mlflow/runs/860108299?check_suite_focus=true#step:3:1131

### After:

Screen Shot 2020-07-11 at 12 20 42


https://github.com/mlflow/mlflow/runs/860184933?check_suite_focus=true#step:3:1131

**Comment by smurching** [comment]
Nice, thanks for the fix @harupy! Will merge this as well since I think scanning a smaller time window of previous issues is now acceptable (given that we've run the labeler for a while/it's already labeled the past month's issues) and running the labeling job daily is hopefully sufficient for triage purposes :)

**Comment by harupy** [comment]
@sid Looks like the `auto-labeling` action has not been triggered for a while.

https://github.com/mlflow/mlflow/actions?query=workflow%3ALabeling

**Comment by harupy** [comment]
The [doc](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule) says:

> Scheduled workflows run on the latest commit on the default or base branch.

It sounds like a scheduled job gets refreshed when a new commit is pushed to the deafualt branch.

**Comment by sid** [comment]
@harupy you have the wrong Sid!

**Comment by harupy** [comment]
@sid Sorry 😅 I have fixed the comment.

**Comment by sid** [comment]
@harupy Lol, no worries! You won't believe how many times this happens, especially when someone starts discussing a ruby instance variable named sid! 😑

**Pull request merged**
