### PR TITLE
Fix issue #1798

### PR DESCRIPTION
**Pull request by ustcscgyer**
## What changes are proposed in this pull request?
 Fixed inconsistency caused by using seconds/milliseconds based timestamp
 
## How is this patch tested?
 Passed all existing tests
 
### Is this a user-facing change? 

- [X] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.
 
(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)
 
### What component(s) does this PR affect?
 
- [ ] UI
- [ ] CLI 
- [ ] API 
- [ ] REST-API 
- [ ] Examples 
- [ ] Docs
- [X] Tracking
- [ ] Projects 
- [ ] Artifacts 
- [ ] Models 
- [ ] Scoring 
- [ ] Serving
- [ ] R
- [ ] Java
- [ ] Python

### How should the PR be classified in the release notes? Choose one:
 
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [X] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by dbczumar** [comment]
@ustcscgyer Thank you for fixing this! Can you also add a `test_client_log_metric_uses_millisecond_timestamp_resolution` test case to the `test_tracking` suite with similar behavior to the existing `test_log_metrics_uses_millisecond_timestamp_resolution` test case (https://github.com/mlflow/mlflow/blob/007bf13b9639786979d0566d85bb5e04111b3816/tests/tracking/test_tracking.py#L267)?

**Comment by ustcscgyer** [comment]
@dbczumar No problem, I will add that.

**Review by dbczumar — APPROVED** [review]
LGTM. Waiting for tests to pass before merging. Thanks @ustcscgyer!

**Comment by ustcscgyer** [comment]
@dbczumar I don't seem to have the write permission to this repo. Can you grant the permission or help merge the PR? Thanks

**Comment by dbczumar** [comment]
@ustcscgyer These test failures do not appear to be related to your changes. I've restarted the build in hopes that the test suite initialization failures were transient.

**Comment by ustcscgyer** [comment]
@dbczumar I have tried many times and it always fails. I just modified the travis.yaml and hope it passes this time. By the way, can you grant me permission to merge the PR, and permission to claim issues?

**Comment by dbczumar** [comment]
@ustcscgyer Looks like the tests passed once #1821 was merged. Unfortunately, I'm unable to grant write access permissions. I'll look into issue claim permissions. Thanks so much for this fix!

**Pull request merged**
