### PR TITLE
Add more file extensions to show content on frontend side

### LINKED ISSUE #5948: [FR] Add more file formats to artifact section UI.
### Willingness to contribute

Yes. I would be willing to contribute this feature with guidance from the MLflow community.

### Proposal Summary

With this feature there are files that could be check in the browser itself, like this [`yolo.cfg`](https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov4.cfg) files, which are just plain text but with a different format.

I guess many other files can benefit from this feature and it will be faster to check those kind of files because you will not need to download them.

### Motivation

> #### What is the use case for this feature?
Be able to see more files in the Artifact section without downloading them.

> #### Why is this use case valuable to support for MLflow users in general?
With this feature you will be able to see the file in the browser instead of downloading it and then check it out in a text editor.

> #### Why is this use case valuable to support for your project(s) or organization?
I use MLflow to see models trained with YOLO networks and the artifact logged into the server are the `weights` and `cfg`, so this will be useful if I want to see the `cfg` file without downloading it.

> #### Why is it currently difficult to achieve this use case?
There isn't a way to check files that are unsupported even if they are plain text files without the `.txt` extension.

### Details

I guess this could easily done by including more file formats to the Artifact show section, or at least check if the file is readable by the browser.

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

### PR DESCRIPTION
**Pull request by dolfinus**
## What changes are proposed in this pull request?

Showing file content on the frontend is a quite useful feature because you don't need to go to S3 and search here for a file.
But unfortunately, list of file extensions which are shown here does not include some popular config formats, like `.ini`, `.toml`, `.properties` and `.xml`.
I've just added them into this list.

Close #5948

## How is this patch tested?

No tests are needed here.

### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [X] Yes. Give a description of this change to be included in the release notes for MLflow users.

Added support of showing more config formats on the interface, like `.ini`, `.toml`, `.properties` and `.xml`.

### What component(s), interfaces, languages, and integrations does this PR affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [X] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [X] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by dolfinus** [comment]
There is a failed sagemaker integration test, but it does not connecter with PR.

**Comment by harupy** [comment]
I have rerun the CI.

**Comment by dolfinus** [comment]
Any updates here?

**Comment by dolfinus** [comment]
@harupy Can you check this PR, please?

**Comment by jinzhang21** [comment]
@dbczumar @harupy This PR is interesting. Should we merge or merge after modification?

**Comment by harupy** [comment]
@jinzhang21 Let me merge the master branch to ensure the change doesn't break unit tests.

**Comment by dolfinus** [comment]
Any updates here?

**Review by harupy — APPROVED** [review]
LGTM!

**Pull request merged**
