### PR TITLE
fix: Add py.typed file to appease mypy.

### PR DESCRIPTION
**Pull request by DanCardin**
<details><summary>&#x1F6E0 DevTools &#x1F6E0</summary>
<p>

[Open in GitHub Codespaces](https://codespaces.new/DanCardin/mlflow/pull/11713?quickstart=1)

#### Install mlflow from this PR

```
pip install git+https://github.com/mlflow/mlflow.git@refs/pull/11713/merge
```

#### Checkout with GitHub CLI

```
gh pr checkout 11713
```

</p>
</details>

### What changes are proposed in this pull request?

Adds an empty `py.typed` file to get mypy to typecheck the library. 

### How is this PR tested?

Before this PR, a trivial script:
```python
import mlflow
mlflow.get_run
mlflow.set_experiment
```
Yields (against latest `mlflow` and latest `mypy`)
```
foo.py:2: error: Module has no attribute "get_run"  [attr-defined]
foo.py:49: error: Module has no attribute "set_experiment"  [attr-defined]
```

### Does this PR require documentation update?

- [x] No. You can skip the rest of this section.

#### Is this a user-facing change?

- [x] No. You can skip the rest of this section.

#### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>

#### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [x] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

#### Should this PR be included in the next patch release?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by harupy** [comment]
mlflow is not fully typed.

**Comment by harupy** [comment]
What I'm concerned is:

- Add `py.typed`
- mypy starts complaining
- we need to silence mypy by fixing type hints

**Comment by DanCardin** [comment]
For what it's worth, mypy is already complaining for lack of `py.typed`, and from what I've seen all the functions we're using at least are provisionally typed already. If you didn't **have** any inline types already, I could imagine the situation being different.

Insofar as this causes downstream consumers to reveal new typing related issues; At worst, I'd expect this to just generate bug reports or PRs that fix actual issues and/or make the typing experience better. **or** users disable mypy for `mlflow`, which is what we've had to do in lieu of it having the `py.typed` file anyways.

I dont think there's any imperative that the whole library be typed (https://peps.python.org/pep-0561/#packaging-type-information).

**Comment by DanCardin** [comment]
I guess with that said, I had looked through the issues and saw one about mypy that was closed purple, which I took to mean you were running mypy against the library; which upon second look doesn't seem true...

`mypy -p mlflow.tracking --ignore-missing-imports --follow-imports skip --implicit-optional` doesn't reveal an insurmountable number of issues, although the whole package sort of does (at least without installing any library stubs).

Although the internal mypy issues one gets from executing mypy against the library are entirely different from what one gets by interfacing with the public API. So it still ends up being more of a question of how much you trust your existing annotations, and whether you intend for downstream users to be able to rely on them or not.

**Comment by harupy** [comment]
@DanCardin Thanks for the comments. I don't think we're ready to do this. There are still many untyped typed APIs. I'm not sure if the existing type hints are really correct (because there is no check or validation now).

**Comment by DanCardin** [comment]
Aight, I'll close this then.

There are other options:
i believe, for example, i could put the py.typed inside mlflow/tracking. but to address your other concern, you'd need to run mypy against valid uses of those functions (tests presumably) to make sure the API annotations were "correct", running it against your actual impl code is ultimately less important for this

**Pull request closed without merging**
