### PR TITLE
Numpy 1.20.0 compatibility: Using object and int instead of deprecated np aliases

### PR DESCRIPTION
**Pull request by aloosley**
## What changes are proposed in this pull request?

Starting in numpy 1.20.0, `np.int` and `np.object` have been deprecated.  As these are just aliases for `int` and `object`, respectively, I've changed them in mlflow accordingly.

See [here](https://numpy.org/doc/stable/release/1.20.0-notes.html#deprecations) for more details about these numpy dtype deprecations.

See [issue](https://github.com/mlflow/mlflow/issues/4048) for more details.

## How is this patch tested?

There is nothing failing yet, just a DeprecationWarning thrown without this patch.  Should I check that a warning is explicitly not shown?

### Is this a user-facing change?

- [X] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>
### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [X] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by aloosley** [comment]
Hi @harupy, other than getting some linters to pass (which I do not know how to do given the contributor instructions didn't work for me), is there anything else that needs to be done to finish this simple PR?

Thank you!

**Comment by harupy** [comment]
@aloosley Thanks for the PR and sorry for the late reply :) The proposed changes look good to me.

The `MLflow tests / lint (pull_request)` check failure should be fixed by running:

```
# please make sure black version is 19.10b0 by running `black --version`
black --line-length=100 --exclude=mlflow/protos .
```

Other failures should be fixed by merging the master branch

**Comment by aloosley** [comment]
> @aloosley Thanks for the PR and sorry for the late reply :) The proposed changes look good to me. Other failures should be fixed by merging the master branch (be careful not to forget signing-off your commit). The lint failure should be fixed by running:
> 
> ```
> # please make sure black version is 19.10b0 by running `black --version`
> black --line-length=100 --exclude=mlflow/protos .
> ```

Thank you very much for the tips.  I pushed an update and will wait to see what happens.

Is there anything else (changelog entry, etc.) that is needed?  Many thanks.

**Comment by aloosley** [comment]
You probably have this problem all the time. I cannot for the life of me get the tests to recognize a sign-off on an intermediate commit.

I've tried:
```bash
$ git commit --amend --no-edit --signoff -c 54dc0f0e3246ebd4128f000113a571e97ce8e7ab
$ git push --force-with-lease
```
and a couple other variants but none seem to make the CI happy.  Do you have any tip?

**Comment by aloosley** [comment]
All set @harupy :-)

**Comment by harupy** [comment]
@aloosley I'm writing a test to ensure our code base doesn't contain the deprecated aliases [here](https://github.com/mlflow/mlflow/pull/4098). I'll ping you when it's ready.

**Comment by aloosley** [comment]
Hi @harupy , is there anything blocking this PR from being merged? 
Best.

**Comment by aloosley** [comment]
Hey @harupy, how is this PR coming along?

**Pull request closed without merging**
