### PR TITLE
Remove f-strings because we still support Python 3.5

### PR DESCRIPTION
**Pull request by harupy**
Signed-off-by: harupy <17039389+harupy@users.noreply.github.com>

## What changes are proposed in this pull request?

Remove f-strings because we still support Python 3.5.

## How is this patch tested?

`test_no_f_strings.py`

### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [x] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by ankitmathur-db** [comment]
Given that Python 3.5 EOL is in < 2 months and that Spark dropped Python 3.5, do we want to continue supporting Python 3.5 @smurching ?

**Comment by harupy** [comment]
+1 for dropping Python 3.5

**Comment by smurching** [comment]
It would be good to start thinking about Python 3.5 deprecation, although I think we should wait to deprecate and remove till after it's actually EOL. When we dropped Python 2.x support, the process was:

* Email community & reach out to key stakeholders to understand the impact / make sure we took into account any potential opposition to dropping support
* Deprecate Python 2.x in MLflow 1.7
* Drop Python 2.x support in the subsequent MLflow 1.8 release

We could follow a similar process for Python 3.5 once it's EOL. Given that we'll want to continue dropping support for EOL'd Python versions in the future, IMO we should put in the extra effort to execute on a previous recommendation from @akshaya-a, and additionally get community buy-in & publish a policy around Python version support / deprecation timelines.

Filed https://github.com/mlflow/mlflow/issues/3132 to track establishing a policy around Python versioning

**Review by smurching — APPROVED** [review]
@harupy this LGTM btw, merging to unblock the 1.10 release

**Review by andychow-db — APPROVED** [review]
lgtm

**Pull request merged**
