### PR TITLE
Avoid global import of fastapi in Gateway Adapters.

### PR DESCRIPTION
**Pull request by B-Step62**
<details><summary>&#x1F6E0 DevTools &#x1F6E0</summary>
<p>

[Open in GitHub Codespaces](https://codespaces.new/B-Step62/mlflow/pull/13721?quickstart=1)

#### Install mlflow from this PR

```
pip install git+https://github.com/mlflow/mlflow.git@refs/pull/13721/merge
```

#### Checkout with GitHub CLI

```
gh pr checkout 13721
```

</p>
</details>

### What changes are proposed in this pull request?

Currently, all LLM provider module for MLflow Gateway imports `fastapi` at globally and use its `HTTPException` class within the adapter implementation. This is fine for normal gateway usage where `fastapi` is always installed.

Then, now we are trying to re-use adapters implementation for other use cases, e.g. support non-OAI LLM models as a judge in MLflow evaluation. By using existing adapters, we can significantly reduce the implementation effort and duplication in our code base (see [design doc](https://docs.google.com/document/d/1OJj5cwFSGH2W76PE7nUmoBPQj7zt8ks1mhsqz9b6RSE/edit?tab=t.0#heading=h.9yq8unor1ydo) for more detailed discussion). However, `fastapi` should not be a hard dependency for such use cases where we don't need to spin up a web server but just want to convert requests and responses.

Therefore, this PR removes this needs by 
1. Move global `fastapi` import to lazy load in each provider.
2. Add a new custom exception and use it instead of `HTTPException`, which will be translated to `HTTPException` in the API handler.

### How is this PR tested?

- [x] Existing unit/integration tests
- [x] New unit/integration tests
- [ ] Manual tests

### Does this PR require documentation update?

- [x] No. You can skip the rest of this section.
- [ ] Yes. I've updated:
  - [ ] Examples
  - [ ] API references
  - [ ] Instructions

#### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

#### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>

#### How should the PR be classified in the release notes? Choose one:

- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

#### Should this PR be included in the next patch release?

`Yes` should be selected for bug fixes, documentation updates, and other small changes. `No` should be selected for new features and larger changes. If you're unsure about the release classification of this PR, leave this unchecked to let the maintainers decide.

<details>
<summary>What is a minor/patch release?</summary>

- Minor release: a release that increments the second part of the version number (e.g., 1.2.0 -> 1.3.0).
  Bug fixes, doc updates and new features usually go into minor releases.
- Patch release: a release that increments the third part of the version number (e.g., 1.2.0 -> 1.2.1).
  Bug fixes and doc updates usually go into patch releases.

</details>

- [x] Yes (this PR will be cherry-picked and included in the next patch release)
- [ ] No (this PR will be included in the next minor release)

### CODE REVIEW

**Comment by harupy** [comment]
How can we prevent a globalfastapi import? An external contributor might add `import fastapi`?

```python
# mlflow/gateway/providers/<provider>.py

import fastapi
```

Should we prevent this?

**Comment by B-Step62** [comment]
> How can we prevent a globalfastapi import? An external contributor might add import fastapi?

Great point! Once we start using the adapters in evaluation (will submit one pr today), importing `fastapi` globally would cause `evaluate` test fail and blocks CI. However, this might not be very friendly to contributors cuz they never know it until opening a PR.

Do you perhaps know a good lint rule to prevent that? It's nice to have because "prevent global import" is needed in many places across the code base🙂

**Comment by harupy** [comment]
@B-Step62 

> Do you perhaps know a good lint rule to prevent that? It's nice to have because "prevent global import" is needed in many places across the code base

It's possible to prevent global fastapi imports under a specific file/directory.

**Comment by B-Step62** [comment]
> It's possible to prevent global fastapi imports under a specific file/directory

That's awesome! I also asked GPT and it suggests custom lint rule, is this what you would do as well? If so I can file a follow-up PR to do that.

**Review by harupy — APPROVED** [review]
LGTM! Let's add a custom lint rule as a follow-up.

**Comment by harupy** [comment]
> I've asked GPT and it suggests custom lint rule, is this what you would do as well?

I actually don't need a GPT. Let me know if you need help :)

**Comment by B-Step62** [comment]
> I actually don't need a GPT. Let me know if you need help :)

Hehe I'm sure you don't. I'll give a try later today but ping you if I face any challenge🙂

**Pull request merged**
