### PR TITLE
Remove duplicate `_SPARK_MODEL_PATH_SUB`

### LINKED ISSUE #6682: [BUG] Duplicate _SPARK_MODEL_PATH_SUB in mlflow.spark.log_model
### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

v1.28.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Python version**:
- **yarn version, if running the dev UI**:

### Describe the problem

There is a duplicate `_SPARK_MODEL_PATH_SUB` in `_maybe_save_model` function

https://github.com/mlflow/mlflow/blob/c9f64728f93331a4b1d70d685c17694fb2ac45fc/mlflow/spark.py#L226-L250

https://github.com/mlflow/mlflow/blob/c9f64728f93331a4b1d70d685c17694fb2ac45fc/mlflow/spark.py#L291-L298

### Tracking information

_No response_

### Code to reproduce issue

https://github.com/mlflow/mlflow/blob/c9f64728f93331a4b1d70d685c17694fb2ac45fc/mlflow/spark.py#L234

https://github.com/mlflow/mlflow/blob/c9f64728f93331a4b1d70d685c17694fb2ac45fc/mlflow/spark.py#L291-L298

### Stack trace

Up version incompatible.

### Other info / logs

_No response_

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

### PR DESCRIPTION
**Pull request by gwy1995**
Signed-off-by: zero <164434719@qq.com>

## Related Issues/PRs
Fix #6682 

## What changes are proposed in this pull request?

Remove duplicate `_SPARK_MODEL_PATH_SUB` in `mlflow.spark.log_model`

## Does this PR change the documentation?

- [ ] No. You can skip the rest of this section.

### CODE REVIEW

**Review by bbarnes52 — APPROVED** [review]
thanks @gwy1995 !

**Comment by dbczumar** [comment]
@bbarnes52 @gwy1995 Looks like a number of Spark tests fail with this change. Can we confirm whether this is a test-only issue (i.e. the tests' expectations are incorrect) or a problematic change in behavior?

**Comment by gwy1995** [comment]
@dbczumar I think the tests' expectations are incorrect. I have a new commit on them.

**Comment by dbczumar** [comment]
Thanks @gwy1995 

@bbarnes52 Can you take a look and also verify that this duplicate path was introduced in MLflow 1.28.0 and wasn't present before? @BenWilson2 flagged that we should be particularly careful about backwards compatibility here - if 1.28.0 introduced a regression, we should absolutely fix it. If this duplicate path component has been around for a long time, we should maintain backwards compatibility.

**Comment by dbczumar** [comment]
Confirmed offline with @bbarnes52 that this is indeed a regression in MLflow 1.28.0. Merging! cc @BenWilson2

**Pull request merged**
