### PR TITLE
Fix `mlflow models serve` failure in Windows

### PR DESCRIPTION
**Pull request by simonvanbernem**
Fixing issue 3332 by not splitting the command-string in pyfunc/backend.py anymore. This didn't work on windows 10.

## What changes are proposed in this pull request?

The subprocess.Popen in pyfunc/backend.py is now called with the command as a single string, instead of the command splitted into a list of strings. This is necessary to fix issue #3332.

## How is this patch tested?

It was tested on Windows 10 with Python 3.9.5 and Python 3.8.0. @mpbrigham, the reporter of issue #3332 who first proposed this as a workaround also tested it on Python 3.5, 3.6, 3.7, and 3.8 under Anaconda Prompt and Anaconda Powershell Prompt, and it worked for two other people on the issue.

### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [x] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>
### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [x] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by simonvanbernem** [comment]
So all the tests now have the status "Expected — Waiting for status to be reported" and I have no idea what to do now. Can anybody help? Is this related to "5 workflows awaiting approval"?

**Comment by mpbrigham** [comment]
Hey @simonvanbernem, thank you for pushing this patch! Please let me know if I can help with further testing, etc. Cheers!

**Comment by simonvanbernem** [comment]
Thanks @mpbrigham, right now I'm just struggling with the pull request system :D

**Comment by harupy** [comment]
@simonvanbernem Thanks for the PR! Let me just add a test to make sure the proposed change works.

**Comment by harupy** [comment]
The windows check failed with:

https://github.com/mlflow/mlflow/pull/4377/checks?check_run_id=2672402456#step:5:1397

```
    def _start_scoring_proc(cmd, env, stdout=sys.stdout, stderr=sys.stderr):
        proc = Popen(
            cmd,
            stdout=stdout,
            stderr=stderr,
            universal_newlines=True,
            env=env,
            # Assign the scoring process to a process group. All child processes of the
            # scoring process will be assigned to this group as well. This allows child
            # processes of the scoring process to be terminated successfully
>           preexec_fn=os.setsid,
        )
E       AttributeError: module 'os' has no attribute 'setsid'
```

**Review by harupy — APPROVED** [review]
LGTM

**Pull request merged**
