### PR TITLE
List directories first in artifact file tree view

### PR DESCRIPTION
**Pull request by harupy**
## What changes are proposed in this pull request?

List directories first in the artifact file tree view.

Before
Screen Shot 2020-02-22 at 15 58 52

After
Screen Shot 2020-02-22 at 15 58 29

## How is this patch tested?

Tested manually

### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s) does this PR affect?

- [ ] UI
- [ ] CLI
- [ ] API
- [ ] REST-API
- [ ] Examples
- [ ] Docs
- [ ] Tracking
- [ ] Projects
- [ ] Artifacts
- [ ] Models
- [ ] Scoring
- [ ] Serving
- [ ] R
- [ ] Java
- [ ] Python

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by harupy** [comment]
The CI failed with the following error.

```
ImportError: No module named enum
```

https://travis-ci.org/mlflow/mlflow/jobs/653762665#L2395-L2414


Related issue
https://bitbucket.org/stoneleaf/enum34/issues/27/enum34-118-broken

Release history of enum34
https://pypi.org/project/enum34/#history

EDIT:
Triggered the CI again after [1.1.9](https://pypi.org/project/enum34/1.1.9/) was released.

**Comment by Zangr** [comment]
@harupy Thank you for the fix! It makes sense to show the folders on top. Would you like to help to tweak the padding of the non-directory nodes a little bit to make the arrow, icons, and texts align? We can use IntelliJ's alignment as an example:
Screen Shot 2020-02-29 at 10 00 21 AM

**Comment by harupy** [comment]
@Zangr 
> Would you like to help to tweak the margin-left of the non-directory nodes a little bit to make the arrow, icons, and texts align?

Aligned the nodes to make them look pretty in the last commit 👍 It looks like this:

Screen Shot 2020-03-01 at 13 39 41

**Comment by harupy** [comment]
When no directory exists:

Before:
Screen Shot 2020-03-01 at 14 01 01

After:
Screen Shot 2020-03-01 at 13 57 54

Should we remove the margin-left when no directory exists?

**Comment by harupy** [comment]
In Visual Studio Code, files are already pre-aligned.

vscode-pre-align

**Review by Zangr — APPROVED** [review]
LGTM!

**Pull request merged**
