### PR TITLE
Revert "Implement promptflow model flavor (#10104)"

### PR DESCRIPTION
**Pull request by B-Step62**
<details><summary>&#x1F6E0 DevTools &#x1F6E0</summary>
<p>

[Open in GitHub Codespaces](https://codespaces.new/B-Step62/mlflow/pull/10903?quickstart=1)

#### Install mlflow from this PR

```
pip install git+https://github.com/mlflow/mlflow.git@refs/pull/10903/merge
```

#### Checkout with GitHub CLI

```
gh pr checkout 10903
```

</p>
</details>

This reverts commit d77d58458e1cf659407074809067186699e88975.

### Related Issues/PRs

 #xxx

### What changes are proposed in this pull request?

Promptflow flavor was introduced in #10104, however, it doesn't work currently because its dependency `promptflow-tools` requires OpenAI >= 1.0, which is not compatible with MLflow. The tools library is not optional as it's used in the core logic in logging, when FlowExecutor is called and reaches to code [here](https://github.com/microsoft/promptflow/blob/0744b1ffe718f402af3ccc839c0f3d19d65f917e/src/promptflow/promptflow/executor/_tool_resolver.py#L249).

### How is this PR tested?

- [x] Existing unit/integration tests
- [ ] New unit/integration tests
- [ ] Manual tests

### Does this PR require documentation update?

- [x] No. You can skip the rest of this section.
- [ ] Yes. I've updated:
  - [ ] Examples
  - [ ] API references
  - [ ] Instructions

#### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

#### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [x] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>

#### How should the PR be classified in the release notes? Choose one:

- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Review by BenWilson2 — APPROVED** [review]
LGTM! Thanks :)

**Comment by wxpjimmy** [comment]
@B-Step62 There's lots of new features which depends on the openai SDK>=1.0, is there any reason that we don't want to update the openai sdk version in MLFlow?

**Comment by B-Step62** [comment]
@wxpjimmy No we've updated it for the incoming release:https://github.com/mlflow/mlflow/pull/11034
The revert was because we were not ready at the moment of last release, and also several test cases failed with the change. Now we should be unblocked and the flavor can be added back if those tests pass:)
cc: @BenWilson2

**Comment by BenWilson2** [comment]
Confirmed. If the PR is re-filed and everything's passing, we can get the PromptFlow flavor in for the 2.11 release :)

**Comment by brynn-code** [comment]
Hi @B-Step62 , I'm trying to get the pr back, there is a 'build_doc_r' CI failed due to image unavailable, I'm not sure if it is related to my changes, either can't get run logs, could you please help take a look on it? Thanks in advance! #11311

**Comment by B-Step62** [comment]
@brynn-code, thanks for working on the revamp! The failure is due to the EOL image and failing for other PRs, so should be irrelevant to the PR. I'm working on the fix so feel free to ignore it now:)

**Comment by brynn-code** [comment]
Thank you, I've made all workflow passed, could you help take a look on my pr? Thanks in advance! @B-Step62

**Pull request merged**
