### PR TITLE
fix: abstract classes use metaclass=ABCMeta

### PR DESCRIPTION
**Pull request by keenranger**
### Related Issues/PRs

 #xxx

### What changes are proposed in this pull request?

Fix abstract classes to use `metaclass=ABCMeta` instead of `__metaclass__=ABCMeta` which was for python2

[doc_for_metaclass_python3](https://docs.python.org/3/reference/datamodel.html#metaclasses)
[doc_for_metaclass_python2](https://docs.python.org/2.7/reference/datamodel.html#customizing-class-creation)
[doc_for_abcMeta_python3](https://docs.python.org/3/library/abc.html#abc.ABCMeta)
[doc_for_abcMeta_python2](https://docs.python.org/2.7/library/abc.html#abc.ABCMeta)
### How is this PR tested?

- [x] Existing unit/integration tests
- [ ] New unit/integration tests
- [x] Manual tests

### Does this PR require documentation update?

- [x] No. You can skip the rest of this section.
- [ ] Yes. I've updated:
  - [ ] Examples
  - [ ] API references
  - [ ] Instructions

#### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [x] Yes. Give a description of this change to be included in the release notes for MLflow users.

#### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [x] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>

#### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [x] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Review by B-Step62 — COMMENTED** [review]
@keenranger Thank you for submitting this PR! 

Could you kindly run `pre-commit run --all-files` to ensure that the code adheres to the coding standard? If you haven't already set up the pre-commit hook, you can install it by `pre-commit install -t pre-commit -t prepare-commit-msg` as described in [CONTRIBUTING.md](https://github.com/B-Step62/mlflow/blob/master/CONTRIBUTING.md#manual-python-development-environment-configuration).

Aside from that, everything looks great!

**Comment by keenranger** [comment]
@B-Step62 Sorry for inconvenience, I forgot to run pre-commit.
All check and re-pushed. Thank you for reviewing.

**Review by B-Step62 — APPROVED** [review]
Thanks a lot for the update! LGTM!

**Comment by keenranger** [comment]
@B-Step62 There were some classes without implementing abstract method. Please check new commit!

**Comment by B-Step62** [comment]
@keenranger Thanks a bunch for proactively fixing those test cases! LGTM, merging:)

**Pull request merged**
