### PR TITLE
Refactor callback injection

### PR DESCRIPTION
**Pull request by serena-ruan**
<details><summary>&#x1F6E0 DevTools &#x1F6E0</summary>
<p>

[Open in GitHub Codespaces](https://codespaces.new/serena-ruan/mlflow/pull/12392?quickstart=1)

#### Install mlflow from this PR

```
pip install git+https://github.com/mlflow/mlflow.git@refs/pull/12392/merge
```

#### Checkout with GitHub CLI

```
gh pr checkout 12392
```

</p>
</details>

### Related Issues/PRs

 
Address this comment: https://github.com/mlflow/mlflow/pull/12326#discussion_r1639104720
I haven't found a way to make the logic even simpler than below 4 context managers, but this refactoring makes sure we reuse sub-cms for updating callbacks. LMK if you have any better ideas :)

### What changes are proposed in this pull request?
Refactored callback injection logics to four CMs now:
1. MlflowCallbackInjectionCM: directly used for inject callbacks for all patched method in langchain autologging
2. RunnableCallbackInjectionCM: update args and kwargs passed in inference with callbacks, this only applies to Runnables and also update args & kwargs when entering/exiting. (So when the function is runnable specific, we directly use this CM inside MlflowCallbackInjectionCM)
3. RunnableConfigCallbackInjectionCM: update config field for runnables. The runnable config passed during inference can be RunnableConfig or List[RunnableConfig] (for batch only). This CM handles both cases and reverts the changes made to runnableConfig after exiting.
4. CallbackInjectionCM: low level CM for mutating callbacks field that is called in above CMs. callbacks field can be either BaseCallbackManager or List[BaseCallbackHandler], and this CM updates callbacks in them when entering, reverts the changes after exiting. 

### How is this PR tested?

- [x] Existing unit/integration tests
- [ ] New unit/integration tests
- [ ] Manual tests

### Does this PR require documentation update?

- [ ] No. You can skip the rest of this section.
- [ ] Yes. I've updated:
  - [ ] Examples
  - [ ] API references
  - [ ] Instructions

#### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

#### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>

#### How should the PR be classified in the release notes? Choose one:

- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

#### Should this PR be included in the next patch release?

`Yes` should be selected for bug fixes, documentation updates, and other small changes. `No` should be selected for new features and larger changes. If you're unsure about the release classification of this PR, leave this unchecked to let the maintainers decide.

<details>
<summary>What is a minor/patch release?</summary>

- Minor release: a release that increments the second part of the version number (e.g., 1.2.0 -> 1.3.0).
  Bug fixes, doc updates and new features usually go into minor releases.
- Patch release: a release that increments the third part of the version number (e.g., 1.2.0 -> 1.2.1).
  Bug fixes and doc updates usually go into patch releases.

</details>

- [ ] Yes (this PR will be cherry-picked and included in the next patch release)
- [x] No (this PR will be included in the next minor release)

### CODE REVIEW

**Comment by serena-ruan** [comment]
@B-Step62 Hey Yuki, do you mind taking a look at this PR?

**Review by B-Step62 — COMMENTED** [review]
@serena-ruan Thank you so much for working on this refactoring! And I totally agree with the idea of having multiple context manager definition. 

However, it appears that one major complexity remains - the nested structure. Nesting context managers makes it hard to see when/how it enters and exists. For example, it's a bit hard to answer questions like "at L179, which context managers we already entered?". This is essentially a problem of indefinite state.

I'm not 100% sure if it's feasible or not (it may be stupid unrealistic idea), but is it worth trying to refactor the logic a bit further to only enter once and exist once? The enter and exit logic may split into multiple reusable class or functions, but only single context manager is applied. Each context manager class should not call each other's `__enter__` or `__exit__` in it.

How does this sound to you?

**Comment by serena-ruan** [comment]
> only enter once and exist once

Thanks for the thoughts! But I'm assuming this is hard. This is because even different functions accept different config types, the underlying callback to mutate is the same, and now we're extracting this as `CallbackInjectionCM`.
All over the end it's always `CallbackInjectionCM` that we're entering, and all other CMs are making sure we don't modify any params at each level, from original callbacks all the way up to config and args/kwargs.
Does this make sense? And what is the concern of entering another CM inside a CM? 
I feel like the nested structure is because originally the arguments passed are nested (and we have to deal with the final layer), but if you have any better ideas I'm open to it!

**Comment by B-Step62** [comment]
@serena-ruan 

> I feel like the nested structure is because originally the arguments passed are nested

This is True, but it seems two different things are coupled together.
1. How to extract callbacks from given input.
2. Modify callback and clean it.

Currently, both are implemented inside callback managers, where (1) is mainly in `__init__` and (2) is in `__enter__` and __exit__`. However, only the latter has to be in context manager. And great thing is that, only 1 is suffered from the nesting problem!! This indicates the chance that we don't have to nest context managers. The 2 is agnostic to the input structure as you said `the underlying callback to mutate is the same, and now we're extracting this as CallbackInjectionCM.`🙂

Then we can split them into two different functions.
1. A function `extract_callbacks(func_name, args, kwargs)` to return all callbacks list or manager passed in the input.
2. A context manager `inject_mlflow_callback(callbacks)` to inject the mlflow callback to each of instances returned by above. 

```
def extract_callbacks(func_name, args, kwargs) -> List[List[Callback] | CallbackManager]:
      """This function is responsible for extracting any instances of callback list or manager."""
       if func_name in ["invoke", ...]: # runnables
            configs = args[1] if len(args) >= 2 else kwargs.get("config")
            return extract_callbacks_from_configs(args, kwargs)
       elif self.func_name == "__call__"
           if len(args) >= 3:
               callbacks = args[2] or []
               args = args[:2] + (callbacks) + args[3:]
               return callbacks
           ...


@contextmanager
def inject_mlflow_callback(callback_list_or_managers: List[List[Callback] | CallbackManager]):
    try:
        for callbacks in callback_list_or_managers:
            inject_callback(callbacks, new_callbacks) # Handles list and manager like current CallbackInjectionCM.__enter__
    finally:
        for callbacks in callback_list_or_managers:
            remove_callback(callbacks, new_callbacks)
        
def patched_inference(...):
    ...
    callback_list_or_managers = extract_callbacks(func_name, args, kwargs)
    with inject_mlflow_callback(callback_list_or_managers, new_callbacks):
        ...
        result = _invoke(self, *args, **kwargs)
    return result
```

Several benefits of this approach:
1. Testability. We can test `extract_callbacks` and `inject_mlflow_callback` separately.
2. Easier to debug. For example, if we get an issue "MLflow doesn't log my model" -> then it is an issue of extraction side. 
3. No nested context manager. The problem of nested context manager is that it is really hard to see what context manager currently applied at some place of the code. At L178, is `args` already updated? At L234, is the input config already mutated? And whenever we make code change without clearly knowing those states, it can introduce a bug.

**Pull request closed without merging**
