### PR TITLE
Missing pandas dependency on examples/sklearn_elasticnet_wine

### PR DESCRIPTION
**Pull request by dvilelaf**
Adding missing pandas dependency on examples/sklearn_elasticnet_wine

- [X] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section

### CODE REVIEW

**Comment by harupy** [comment]
@derkomai Thanks for the contribution! Could you fix the DCO check failure by following the instruction [here](https://github.com/mlflow/mlflow/pull/4554/checks?check_run_id=3055672564)?

**Comment by derkomai** [comment]
@harupy I've just followed the --signoff and --force-with-lease instructions, but it seems it's still failing. Not sure what I'm doing wrong. BTW, I've moved the dependency to pip as required.

**Comment by harupy** [comment]
I think it's because the first commit is not signed off yet.

**Comment by derkomai** [comment]
Ok, not sure how to proceed, but here's what I just did: I created a new branch where I signed that commit, cherry-picked the second one and merged into master.

**Comment by harupy** [comment]
Can you reset your commits?

**Comment by derkomai** [comment]
Hard-resetted, signed and force-pushed.

**Comment by harupy** [comment]
Looks like it worked!

**Review by harupy — APPROVED** [review]
LGTM

**Pull request merged**
