### PR TITLE
Add conf option to configure result type for the Predict step spark UDF

### PR DESCRIPTION
**Pull request by jerrylian-db**
Signed-off-by: Jerry Liang <jerry.liang@databricks.com>

## Related Issues/PRs

#xxx

## What changes are proposed in this pull request?

As title. Let me know if I should add conf checks or unit tests for this.

## How is this patch tested?

- [ ] I have written tests (not required for typo or doc fix) and confirmed the proposed feature/bug-fix/change works.

## Does this PR change the documentation?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Make sure the changed pages / sections render correctly by following the steps below.

1. Click the `Details` link on the `Preview docs` check.
2. Find the changed pages / sections and make sure they render correctly.

### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?
Components
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [x] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>
### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by jerrylian-db** [comment]
Note: I didn’t add any unit tests because I see this param as simply a way pass specify the result_type for the Spark UDF use in the batch scoring. I also didn’t add any conf validation logic for the new `result_type` conf, because I figured that the spark UDF would error out on its own and it would be difficult to keep the validation logic consistent with the Spark UDF. Let me know if I should add any of those things though!

**Review by jinzhang21 — COMMENTED** [review]
Any context to add this option?

**Comment by jerrylian-db** [comment]
@jinzhang21 Seems like an important parameter of the Spark UDF to provide (see [function signature](https://www.mlflow.org/docs/latest/python_api/mlflow.pyfunc.html#mlflow.pyfunc.spark_udf)). Also, in the Databricks autogenerated batch inference notebook, they call out this parameter as well.
Screen Shot 2022-09-29 at 3 37 12 PM

**Review by jinzhang21 — APPROVED** [review]
Can we also update the example repo YAML config to show an example usage? https://github.com/mlflow/mlr-regression-example

**Comment by jerrylian-db** [comment]
@jinzhang21 I will write a larger PR adding confs and documentation to the example repo.

**Pull request merged**
