### PR TITLE
Do not create zero id experiment if it exists

### PR DESCRIPTION
**Pull request by schipiga**

### CODE REVIEW

**Comment by schipiga** [comment]
hey @tomasatdatabricks could you please review my fix?

**Comment by schipiga** [comment]
hey @tomasatdatabricks could you please review my fix?

**Comment by schipiga** [comment]
hey @tomasatdatabricks could you please review my fix?

**Comment by schipiga** [comment]
hey @tomasatdatabricks could you please review my fix?

**Comment by schipiga** [comment]
hey @tomasatdatabricks could you please review my fix?

**Comment by schipiga** [comment]
hey @tomasatdatabricks could you please review my fix?

**Review by tomasatdatabricks — APPROVED** [review]
Good catch, thanks @schipiga!

**Pull request merged**
