### PR TITLE
Log params recurrently

### PR DESCRIPTION
**Pull request by OrlMat**
## What changes are proposed in this pull request?
 
Slight modification of tracking function log_params(). With this modification, if parameter in dictionary is another dictionary or partial definition of function, it will be parsed accordingly to its content creating more or less class-like entity (separated with dots in case of dictionary and splited into function name and keywords arguments for partial definition). Function preserves its behavior in case of simple dictionary.
 
## How is this patch tested?
 
Patch has been tested while using in our internal project.
 
### Is this a user-facing change? 

- [ ] No. You can skip the rest of this section.
- [x] Yes. Give a description of this change to be included in the release notes for MLflow users.
 
(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

Ability to recurrently log dictionary of parameters, in which parameters are dictionaries or partial definition of functions. Instead of stringifing their instances, parameters will be logged according to their content. 
 
### What component(s) does this PR affect?
 
- [ ] UI
- [ ] CLI 
- [ ] API 
- [ ] REST-API 
- [ ] Examples 
- [ ] Docs
- [x] Tracking
- [ ] Projects 
- [ ] Artifacts 
- [ ] Models 
- [ ] Scoring 
- [ ] Serving
- [ ] R
- [ ] Java
- [x] Python

### How should the PR be classified in the release notes? Choose one:
 
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [x] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by tomasatdatabricks** [comment]
Hi @OrlMat, thanks for the contribution!

Can you elaborate on design decisions behind your changes? Does logging dictionaries as string not work for you?

**Comment by OrlMat** [comment]
Hi @tomasatdatabricks, 

yes - we had some issues. In our RL project we are using quite complex and centralized hyperparameters structure.  Very often they contain partial definition of functions (function like linear decay which steers some learning attribute according to current step/epoch). In case of straight forward approach, especially when we dealt with sub-dictionaries in our parameters, partial function was just _stringified_, which resulted in very long entry (with not needed pointers included) which was exceeding maximum number of characters (and was unreadable). 

Regarding this patch, it was easy one which helped log those parameters with class-like naming embedding . 

With this, more complex parameter structure, like:
```
params:
   memory_params:
      size = 100
      decay = partial(Linear, x0=0.0, y0=0.0, x1=1.0, y1=1.0))
   subparam1 = 1.1
```
will be logged as
```
memory_params.size
memory_params.decay.func = <class math.Linear>
memory_params.decay.kw.x0 = 0.0
memory_params.decay.kw.y0 = 0.0
memory_params.decay.kw.x1 = 1.0
memory_params.decay.kw.y1 = 1.0
subparam1 = 1.1
```
Which seems to be more elegant way of logging those, still having everything "on the same level".

**Comment by tomasatdatabricks** [comment]
Hi @OrlMat, thanks for the clarification!

Yes, it makes a lot of sense in your case, I am just wondering if it generalizes well (if this is what people would always want to do with nested dictionaries and partials). I'l get back to you on that later today.

**Comment by smurching** [comment]
@tomasatdatabricks @OrlMat agree that expanding out nested dicts does seem nicer than what we currently do (stringifying them). One edge case to consider is that Python dict keys don't need to be strings - I guess we'd handle this by stringifying non-string dictionary keys, which is at least on par with what we currently do.

Also, another potential risk/downside of the proposed change that we should consider - it is technically a breaking behavior change, in that people who depend on current-style param values (stringified dicts) may be surprised to find that their code now splits up the stringified dict across multiple params, etc.

**Comment by OrlMat** [comment]
Another idea could be to log dict as it is (without stringifing it or splitting across params) and then handle it nicely in GUI (by some expandable list which could be presented as string or list of params in drop-down menu- somewhat similar how IDE debuggers are able to present data). That however seemed like much more work to do (in tracking API as well as GUI) so I have decide for quick fix which worked for me.

**Comment by tomasatdatabricks** [comment]
Hi @OrlMat. 

After considering this PR carefully, I don't think that it is general enough to merge it directly into MLflow at this time. It makes a lot of sense in your case, however I don't think that this behavior is what most users would expect when logging nested dictionaries. I think it's best to leave it as a utility function. However, I think it would be great if you could submit this code to ./examples. That way it will be visible to MLflow users and if it turns out to be something people often use we can reconsider merging it directly into MLflow.

Let me know what you think.

**Comment by verasativa** [comment]
This will be pretty useful for my user case too. As utility or core, but would love to have in the next release!

**Comment by dbczumar** [comment]
@OrlMat @tomasatdatabricks I'm going to go ahead and close this PR, as we've decided that this would fit better as an example or utility function rather than a modification to `log_params`.

@verasativa @OrlMat feel free to re-open this or file another PR to introduce this functionality as a utility; we would love to include it in a future release.

**Comment by olbapjose** [comment]
It would also be pretty would to me. Was this finally pushed as a utility into the examples folder?

**Pull request closed without merging**
