### PR TITLE
Replace deprecated flag in examples

### PR DESCRIPTION
**Pull request by aashish-khub**
Signed-off-by: Aashish Khubchandani <ak7164@nyu.edu>

## What changes are proposed in this pull request?

This PR addresses issue #5697. Example documentation `README` files have been updated to reflect deprecation of the `--no conda` flag and its replacement with `--env-manager=local`.  All instances of

> If you have the required modules for the file and would like to skip the creation of a conda environment, add the argument `--no-conda`.
> 
> ```mlflow run . --no-conda```

have been replaced with:

> If you have the required modules for the file and would like to skip the creation of a conda environment, add the argument `--env-manager=local`.
> 
> ```mlflow run . --env-manager=local```

## How is this patch tested?

Documentation Change, see next section. 

## Does this PR change the documentation?

- [ ] No. You can skip the rest of this section.
- [x] Yes. Make sure the changed pages / sections render correctly by following the steps below.

1. Check the status of the `ci/circleci: build_doc` check. If it's successful, proceed to the
   next step, otherwise fix it.
2. Click `Details` on the right to open the job page of CircleCI.
3. Click the `Artifacts` tab.
4. Click `docs/build/html/index.html`.
5. Find the changed pages / sections and make sure they render correctly.

### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [x] Yes. Give a description of this change to be included in the release notes for MLflow users.

Due to the deprecation of the `--no-conda` flag, examples have been updated to now use `--env-manager=local`. 

### What component(s), interfaces, languages, and integrations does this PR affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [x] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>
### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by aashish-khub** [comment]
@harupy This addresses issue #5697, which you raised and assigned to me. This is my first contribution so let me know if anything is needed on my end! :)

**Review by harupy — APPROVED** [review]
LGTM!

**Comment by harupy** [comment]
@aashish-khub 

Looks like we have one more `--no-conda` in `examples/rapids/mlflow_projects`

image

Can we replace it?

**Comment by aashish-khub** [comment]
Sorry about that! I saw that one but wasn't sure if it applied here too and not just for `mlflow run`. Committed again with the new change.

**Comment by harupy** [comment]
Thanks! Let's wait for the CI checks to finish, and then merge.

**Comment by harupy** [comment]
@aashish-khub Merged!

**Comment by aashish-khub** [comment]
Thanks! :)

**Pull request merged**
