### PR TITLE
Add `pytest` unit tests for `mlflow` example programs

### PR DESCRIPTION
**Pull request by jimthompson5802**
This PR introduces unit tests for an initial set of example programs.  Unit tests help ensure the quality of these programs, which for many users are the first exposure to `mlflow`.  Properly functioning code examples will help promote confidence in `mlflow`.

Current scope of these tests check to see if the sample program completed successfully, i.e., generated return code zero.  This scope is sufficient to capture issues related to use of the correct api version, building the conda environment identified in the MLProject file and abnormal termination of the example code.  Unit tests for example programs would have prevented past issues such as #849, #940, #812 and #809.

The tests do not examine the content of any generated output by the example programs.  Also out of scope is testing of `mlflow`'s internal functions. These are expected to be tested by the existing `pytest` routines. 

This initial set of unit tests demonstrates a method for running the example programs using Python's `pytest` and `subprocess` packages.  This initial set example programs were chosen because the examples' software environment are minimal and could run in a Docker container based on `mlflow`'s Dockerfile.  

Python's `subprocess` package is used to start a shell environment.  Within this shell, the example program's appropriate `mlflow` command is executed.  Here are some example commands:
```
python train.py
mlflow run .
mlflow run . -P alpha=0.5
mlflow experiments create hyper_param_runs
mlflow run -e random --experiment-id 2  -P training_experiment_id=1 . 
```

The unit test checks for two conditions:

* Return code from the shell is zero.  
* Directory ./mlruns exists

If either of this conditions are not true, the unit test fails.

If adding unit tests for the example programs are useful, then we'll need to discuss the 
required software environment.  Based my testing, some unit tests for other examples require additional software components, such as gcc compiler, which is needed to install packages called out by the example's `conda.yaml` file.

This is the `pytest` log from a run for the proposed tests:

```
base) root@f96aa7078161:/opt/project# pytest -v examples/tests
=========================================================== test session starts ============================================================
platform linux2 -- Python 2.7.15, pytest-3.2.1, py-1.8.0, pluggy-0.4.0 -- /opt/conda/bin/python
cachedir: .cache
rootdir: /opt/project, inifile:
plugins: localserver-0.5.0, cov-2.6.0
collected 3 items

examples/tests/test_examples.py::test_example[examples/sklearn_logistic_regression-python train.py-True] PASSED
examples/tests/test_examples.py::test_example[examples/sklearn_elasticnet_wine-mlflow run . -P alpha=0.5-True] PASSED
examples/tests/test_examples.py::test_example[examples/sklearn_elasticnet_diabetes/linux-mlflow run .-True] PASSED

======================================================== 3 passed in 51.46 seconds =========================================================
(base) root@f96aa7078161:/opt/project#

```

For purposes of discussing this PR, I've placed the examples' unit tests in `examples/tests` directory.  Eventually these tests could be moved to the `tests` directory to be part of the Travis CI/CD pipeline.

If unit tests for example code are deemed useful, I'll submit additional PRs for the remaining example programs.

Addendum:  Example of unit test failing for situation in #812:
```
(base) root@f96aa7078161:/opt/project# pytest -v examples/tests
=========================================================== test session starts ============================================================
platform linux2 -- Python 2.7.15, pytest-3.2.1, py-1.8.0, pluggy-0.4.0 -- /opt/conda/bin/python
cachedir: .cache
rootdir: /opt/project, inifile:
plugins: localserver-0.5.0, cov-2.6.0
collected 4 items

examples/tests/test_examples.py::test_example[examples/sklearn_logistic_regression-python train.py-True] PASSED
examples/tests/test_examples.py::test_example[examples/sklearn_elasticnet_wine-mlflow run . -P alpha=0.5-True] PASSED
examples/tests/test_examples.py::test_example[examples/sklearn_elasticnet_diabetes/linux-mlflow run .-True] PASSED
examples/tests/test_examples.py::test_example[examples/h2o-python random_forest.py-True] FAILED

================================================================= FAILURES =================================================================
_________________________________________ test_example[examples/h2o-python random_forest.py-True] __________________________________________

directory = 'examples/h2o', command = 'python random_forest.py', clear_mlruns = True

    @pytest.mark.parametrize("directory,command,clear_mlruns",[
        ("examples/sklearn_logistic_regression","python train.py",True),
        ("examples/sklearn_elasticnet_wine","mlflow run . -P alpha=0.5",True),
        ("examples/sklearn_elasticnet_diabetes/linux", "mlflow run .",True),
        ("examples/h2o", "python random_forest.py",True),
    ])
    def test_example(directory, command, clear_mlruns):
>       run_an_example(directory, command, clear_mlruns)

examples/tests/test_examples.py:35:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

example_dir = 'examples/h2o', example_command = 'python random_forest.py', clear_mlruns = True

    def run_an_example(example_dir, example_command, clear_mlruns):
        # construct command to run
        if clear_mlruns:
            command = "cd " + example_dir + " && rm -fr mlruns && " + example_command
        else:
            command = "cd " + example_dir + " && " + example_command

        # example code
        test_run = Popen(command, shell=True)

        # check exit code for return code 0
        test_run.wait()

        # check that example ran successfully
>       assert test_run.returncode == 0
E       assert 1 == 0
E        +  where 1 = <subprocess.Popen object at 0x7f3e0146c110>.returncode

examples/tests/test_examples.py:22: AssertionError
----------------------------------------------------------- Captured stdout call -----------------------------------------------------------
Checking whether there is an H2O instance running at http://localhost:54321..... not found.
Attempting to start a local H2O server...
  Java Version: openjdk version "1.8.0_212"; OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1~deb9u1-b01); OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)
  Starting server from /opt/conda/lib/python2.7/site-packages/h2o/backend/bin/h2o.jar
  Ice root: /tmp/tmplCSzVs
  JVM stdout: /tmp/tmplCSzVs/h2o_unknownUser_started_from_python.out
  JVM stderr: /tmp/tmplCSzVs/h2o_unknownUser_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321... successful.
--------------------------  ---------------------------------------------------
H2O cluster uptime:         01 secs
H2O cluster timezone:       Etc/UTC
H2O data parsing timezone:  UTC
H2O cluster version:        3.22.1.4
H2O cluster version age:    1 month and 22 days
H2O cluster name:           H2O_from_python_unknownUser_7gwrs7
H2O cluster total nodes:    1
H2O cluster free memory:    3.042 Gb
H2O cluster total cores:    7
H2O cluster allowed cores:  7
H2O cluster status:         accepting new members, healthy
H2O connection url:         http://127.0.0.1:54321
H2O connection proxy:
H2O internal security:      False
H2O API Extensions:         Amazon S3, XGBoost, Algos, AutoML, Core V3, Core V4
Python version:             2.7.15 final
--------------------------  ---------------------------------------------------
Parse progress: [#########################################################] 100%
H2O session _sid_8e80 closed.
----------------------------------------------------------- Captured stderr call -----------------------------------------------------------
/app/mlflow/tracking/context.py:181: UserWarning: Failure attempting to register context provider "unused": 'module' object has no attribute 'PluginRunContextProvider'
  _run_context_provider_registry.register_entrypoints()
/app/mlflow/utils/environment.py:26: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  env = yaml.load(_conda_header)
Traceback (most recent call last):
  File "random_forest.py", line 32, in <module>
    trainRandomForest(ntrees)
NameError: name 'trainRandomForest' is not defined
=================================================== 1 failed, 3 passed in 19.84 seconds ====================================================
(base) root@f96aa7078161:/opt/project#
```

### CODE REVIEW

**Review by smurching — COMMENTED** [review]
Hi @jimthompson5802, this is a great idea - thanks for the PR! Agree that it makes sense to have these tests run as part of CI. There's already an existing set of unit tests for the MLflow Projects component in `tests/projects/test_projects_cli.py` ([see here](https://github.com/mlflow/mlflow/blob/94fa3f160bd5c1f980caac7db69fae20a929c62a/tests/projects/test_projects_cli.py#L20)). My recommendation would be to add a file at `tests/examples/test_examples.py` that mirrors the structure of the `test_projects_cli.py` tests. Note that `test_projects_cli.py` has logic already for running against a temporary tracking directory (via `tracking_uri_mock`) and verifying the status of a CLI command (via `invoke_cli_runner`), so we should be able to reuse those helpers in our example program tests.

#1097 adds support for running tests in stages, so after that PR & this one are merged we can probably arrange for the `examples` tests to run e.g. nightly to avoid slowing down PR builds. For now I think Travis will run your tests by default if you add them under the `tests` directory (e.g. under `tests/examples/test_examples.py`)

**Comment by jimthompson5802** [comment]
@smurching  thank you for the feedback.  I'll create `tests/examples/test_examples.py` and update this PR to reflect the guidance.

**Comment by jimthompson5802** [comment]
@smurching I've updated the PR per the guidance for three of the example programs.  If this looks like a reasonable way to do the tests, I'll start working on the remaining examples.  

I do have some questions:
* Right now I have not used the pytest.mark decorator.  Do I need to mark any of the examples test?
* What flexibility is there to add additional software to the Travis environment?  The reason I'm asking is that tests for some examples will need a gcc compiler to support building the conda environment for the MLProject conda specification.  I can support testing Jupyter notebooks  with the `jupyter nbconvert` cli.  If these components can't be added then some of the examples won't have tests.

**Comment by jimthompson5802** [comment]
@smurching added two more examples (h2o random forest and quickstart mlflow tracking).  As I wrote earlier, I'd like to better understand the software environment for running the tests.

**Comment by smurching** [comment]
Hi @jimthompson5802, sorry for the delay - Travis refactoring to allow splitting builds across stages has been merged, so let's try to get this in :).

It looks like gcc is already available by default in Travis's build environment ([link](https://docs.travis-ci.com/user/reference/trusty/#compilers--build-toolchain)), so I don't think we have to do anything special to make it available. Regarding adding `jupyter` as a test dependency, I think it's reasonable to do so - you can add it to `./travis/large-requirements.txt`. However I'd prefer to add additional tests in a follow-up, and focus this PR on getting an initial set of tests merged to speed review.

I pushed a commit to run the new examples tests as part of our large test runner, hopefully the tests will pass - will take a pass over the rest of the code ASAP

**Comment by smurching** [comment]
Hi @jimthompson5802, sorry for the delay - Travis refactoring to allow splitting builds across stages has been merged, so let's try to get this in :).

It looks like gcc is already available by default in Travis's build environment ([link](https://docs.travis-ci.com/user/reference/trusty/#compilers--build-toolchain)), so I don't think we have to do anything special to make it available. Regarding adding `jupyter` as a test dependency, I think it's reasonable to do so - you can add it to `./travis/large-requirements.txt`. However I'd prefer to add additional tests in a follow-up, and focus this PR on getting an initial set of tests merged to speed review.

I pushed a commit to run the new examples tests as part of our large test runner, hopefully the tests will pass - will take a pass over the rest of the code ASAP

**Comment by smurching** [comment]
Hm, it looks like some of the changes we made to add Windows support have broken running projects that depend on older MLflow versions - will ask around about this tomorrow so that we can fix the tests for this PR.

**Comment by jimthompson5802** [comment]
@smurching Thank you for the feedback.  NP on the delay, I figured you guys were busy getting ready for the recent Spark AI Summit.

I understand you want me to add the remaining tests in a different PR. I'll start that new PR.  

As for this current PR, it looks like the Travis error is environment related.  From what I can tell I have no action as of now.  If I do have an action, just let me know.

**Comment by jimthompson5802** [comment]
@smurching   Just checking in...did you get an answer on " Windows support have broken running projects that depend on older MLflow versions"?

**Comment by juntai-zheng** [comment]
Hi @jimthompson5802, sorry for the delay! We'd love to get this PR in and eventually expand on it. What can we do to help you with this PR?

**Comment by jimthompson5802** [comment]
@juntai-zheng   In looking over what I had done, the issue seems to be the tests running on a Windows platform.  Can you restart the travis-ci tests to confirm there is still a problem?  If it fails again, then we it will gives us a starting point.

**Comment by juntai-zheng** [comment]
@jimthompson5802 We went and merged master into your branch since MLflow and the Travis tests have updated a lot since the last commit. The small python 3.6 test stage is failing because we have a [check](https://github.com/mlflow/mlflow/blob/master/test-generate-protos.sh) for no new files being created by the small tests, and the [sklearn elasticnet example](https://github.com/mlflow/mlflow/blob/master/examples/sklearn_elasticnet_diabetes/osx/train_diabetes.py#L119) is saving a figure that [fails](https://travis-ci.org/mlflow/mlflow/jobs/611517288#L2527) the Travis test. You can probably bypass this by adding the decorator `@pytest.mark.large` to your tests.

**Comment by jimthompson5802** [comment]
@juntai-zheng   I made the recommended changes.  However, I still get a failure in the Windows platform test.  The failure occurs in mlflow.util.process.exec_cmd() function.  Any guidance will be appreciated.
```
__________________ test_command_example[quickstart-command0] __________________
1275
1276tmpdir = local('C:\\Users\\travis\\AppData\\Local\\Temp\\pytest-of-travis\\pytest-0\\test_command_example_quickstar0')
1277directory = 'quickstart', command = ['python', 'mlflow_tracking.py']
1278
1279    @pytest.mark.parametrize("directory, command", [
1280        ('quickstart', ['python', 'mlflow_tracking.py']),
1281    ])
1282    def test_command_example(tmpdir, directory, command):
1283    
1284        os.environ['MLFLOW_TRACKING_URI'] = str(tmpdir.join("mlruns"))
1285        cwd_dir = os.path.join(EXAMPLES_DIR, directory)
1286    
1287        try:
1288            process.exec_cmd(command,
1289>                            cwd=cwd_dir)
1290
1291tests\examples\test_examples.py:44: 
```

**Comment by juntai-zheng** [comment]
@jimthompson5802 It looks like MLflow doesn't support the `C:` schema format that's being passed in as the `MLFLOW_TRACKING_URI` (`C:\\Users\\travis\\AppData\\Local\\Temp\\pytest-of-travis\\pytest-0\\test_command_example_quickstar0\mlruns`). MLflow does support the `file` format though (you can see the supported types in the error of the Travis build), so you can use `mlflow.utils.file_utils.path_to_local_file()` in order to convert `tmpdir` to a schema that MLflow can work with. This could be a future followup we could work on!

**Comment by jimthompson5802** [comment]
@juntai-zheng   I made the recommended change.  the ci tests no longer fail on the Windows platform.  Thank you for the guidance.

In reviewing the ci logs, it appears that not all the test are executed.   Specifically, I can't find results for these tests:
```
@pytest.mark.parametrize("directory, params", [
    ('sklearn_logistic_regression', []),
    ('sklearn_elasticnet_wine', ['-P', 'alpha=0.5']),
    ('h2o', []),
])
def test_mlflow_run_example(tracking_uri_mock, directory, params):
    cli_run_list = [os.path.join(EXAMPLES_DIR, directory)] + params
    invoke_cli_runner(cli.run, cli_run_list)
```
I was expecting the missing tests to be part of the small tests.  In the log file for the small test I find only this entry
```
tests/examples/test_examples.py::test_command_example[quickstart-command0] [32mPASSED[0m
```
In the large test logs, I find this entry
```
tests/examples/test_examples.py F++err=1
```

I've looked at `travis/run-small-python-tests.sh` and `travis/run-large-python-tests.sh`.  Not sure if I need to modify  one or both of these files.

**Comment by juntai-zheng** [comment]
@jimthompson5802 Looks like you have two tests named `test_mlflow_run_example()`, which usually causes `pytest` to act weirdly or even skip over tests. I would recommend either combining your tests into one via the `pytest.mark.parametrize` decorator, or just rename one of the tests. Your tests should all correctly pop up in the Travis logs then.

As for the line
```
tests/examples/test_examples.py F++err=1
```

It looks like one of the tests failed (most likely `test_mlflow_run_example()`), but Travis didn't log it as an error. Let's get the test to run with the fix above first, and see if that fixes this failed test.

I would also recommend marking `test_command_example` as a `large` test as well, since these are heavier, end to end tests. 

Thanks!

**Comment by jimthompson5802** [comment]
@juntai-zheng I made the recommended changes.  From what I can tell the tests passed in the large Python 2 set:
```
tests/examples/test_examples.py .....
```
Note:  the Python 2 test set encountered an error but it was in the tensorflow tests.

In large Python 3, the error still occurs
```
tests/examples/test_examples.py F++err=1
```
Guidance will be appreciated.

**Comment by jimthompson5802** [comment]
@juntai-zheng   Finally...I think we have the tests for the examples working.  To resolve this error
```
tests/examples/test_examples.py F++err=1
```

I had to update `travis/run-large-python-tests.sh` as follows:
```
pytest tests --large --ignore=tests/examples --ignore=tests/h2o --ignore=tests/keras \
  --ignore=tests/pytorch --ignore=tests/pyfunc --ignore=tests/sagemaker --ignore=tests/sklearn \
  --ignore=tests/spark --ignore=tests/tensorflow --ignore=tests/azureml --ignore=tests/onnx \
  --ignore=tests/keras_autolog --ignore=tests/tensorflow_autolog
# Run ML framework tests in their own Python processes to avoid OOM issues due to per-framework
# overhead
pytest --verbose tests/examples --large
```

I have to admit, I'm not clear on why this change is needed.  I came on this fix because in my local testing, whenever I just ran `pytest --large tests` the `examples` test suite failsl.  OTOH if I executed this command `pytest --large tests/examples` the test suite completes w/o error.

If this is an an acceptable solution, please merge the PR.  I'll look to see what other examples I can include in the test suite in subsequent PRs.

**Review by juntai-zheng — APPROVED** [review]
From my guess, other tests before the `examples` tests may be leaky in terms of keeping an environment stable. It's hard to debug via pytest since pytest seems like it just crashes after the first failed test from your tests, but I was able to replicate the results of both successful and unsuccessful travis builds on my local machines (when the test failed, pytest ended with no output). 

Your solution for the `F++err=1` error looks like it works well, so the PR LGTM and I'll merge it in. Thanks for your work, and we'll be happy to review any future work on expanding the examples test suite!

**Pull request merged**
