### PR TITLE
[ML-19871] R documentation fix

### PR DESCRIPTION
**Pull request by kriscon-db**
## Related Issues/PRs

#5199

## What changes are proposed in this pull request?

Minor typo in documentation fixed.

## How is this patch tested?

- [ ] I have written tests (not required for typo or doc fix) and confirmed the proposed feature/bug-fix/change works.

## Does this PR change the documentation?

- [ ] No. You can skip the rest of this section.
- [x] Yes. Make sure the changed pages / sections render correctly by following the steps below.

1. Click the `Details` link on the `Preview docs` check.
2. Find the changed pages / sections and make sure they render correctly.

### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?
Components
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [x] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language
- [x] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>
### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by harupy** [comment]
@kriscon-db Can you fill in the PR description and add tests?

**Comment by kriscon-db** [comment]
> @kriscon-db Can you fill in the PR description and add tests?

Oh sorry.  I wasn't ready for this to be reviewed yet. 🙂   Will def. add all of that.

**Comment by kriscon-db** [comment]
The original approach won't work because it causes an error here:

``` ══ Failed tests ════════════════════════════════════════════════════════════════
── Error (test-tracking-runs.R:428:3): mlflow_log_batch() works ────────────────
Error in `vapply(x, asJSON, character(nrow(x)), collapse = FALSE, complex = complex, 
    na = na, oldna = oldna, rownames = rownames, dataframe = dataframe, 
    indent = indent + 2L, no_dots = no_dots, ..., USE.NAMES = FALSE)`: values must be length 7,
 but FUN(X[[1]]) result is length 1
Backtrace:
     ▆
  1. └─mlflow::mlflow_log_batch(...) at test-tracking-runs.R:428:2
  2.   └─mlflow:::mlflow_rest(...)
  3.     └─mlflow (local) get_response()
  4.       └─httr::POST(...)
  5.         ├─httr:::request_build(...)
  6.         └─httr:::body_config(body, match.arg(encode))
  7.           ├─httr:::body_raw(...)
  8.           └─jsonlite::toJSON(body, auto_unbox = TRUE, digits = 22)
  9.             ├─jsonlite:::asJSON(...)
 10.             └─jsonlite:::asJSON(...)
 11.               └─jsonlite (local) .local(x, ...)
 12.                 └─base::vapply(...)
 13.                   ├─jsonlite (local) FUN(X[[i]], ...)
 14.                   └─jsonlite (local) FUN(X[[i]], ...)
 15.                     └─jsonlite (local) .local(x, ...)
 16.                       └─base::vapply(...)```

**Review by harupy — APPROVED** [review]
lgtm :)

**Pull request merged**
