### PR TITLE
Implement GraphQL endpoint for SearchRuns API

### PR DESCRIPTION
**Pull request by daniellok-db**
## 🥞 Stacked PR
Use this [link](https://github.com/mlflow/mlflow/pull/12601/files) to review incremental changes.
- [**stack/search-runs-graphql**](https://github.com/mlflow/mlflow/pull/12601) [[Files changed](https://github.com/mlflow/mlflow/pull/12601/files)]
  - [stack/list-artifacts-graphql](https://github.com/mlflow/mlflow/pull/12602) [[Files changed](https://github.com/mlflow/mlflow/pull/12602/files/9ed7681a16529953531e85efcfa82a8c19f5ebde..c1e49e92ae85f417ae0ba51f549b88329998f957)]

---------
### Related Issues/PRs

 #xxx

### What changes are proposed in this pull request?

To support the eventual migration to GraphQL, this PR onboards the SearchRuns API handler to GraphQL, following [this guide](https://github.com/mlflow/mlflow/blob/14577103c15b243441e951f0e84891f13efaea4f/dev/proto_to_graphql/README.md#how-to-onboard-a-new-rpc-to-graphql).

This API powers the experiment page in the frontend.

### How is this PR tested?

- [x] Existing unit/integration tests
- [x] New unit/integration tests
- [x] Manual tests

Screenshot 2024-07-08 at 4 38 18 PM

### Does this PR require documentation update?

- [x] No. You can skip the rest of this section.
- [ ] Yes. I've updated:
  - [ ] Examples
  - [ ] API references
  - [ ] Instructions

#### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

#### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>

#### How should the PR be classified in the release notes? Choose one:

- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

#### Should this PR be included in the next patch release?

`Yes` should be selected for bug fixes, documentation updates, and other small changes. `No` should be selected for new features and larger changes. If you're unsure about the release classification of this PR, leave this unchecked to let the maintainers decide.

<details>
<summary>What is a minor/patch release?</summary>

- Minor release: a release that increments the second part of the version number (e.g., 1.2.0 -> 1.3.0).
  Bug fixes, doc updates and new features usually go into minor releases.
- Patch release: a release that increments the third part of the version number (e.g., 1.2.0 -> 1.2.1).
  Bug fixes and doc updates usually go into patch releases.

</details>

- [ ] Yes (this PR will be cherry-picked and included in the next patch release)
- [x] No (this PR will be included in the next minor release)

### CODE REVIEW

**Review by hubertzub-db — APPROVED** [review]
looks good for starters! Let @edwardfeng-db take a look here as well. BTW let's migrate more endpoints and consider creating joint resolvers!

**Review by edwardfeng-db — APPROVED** [review]
Nice, thanks!

It looks like these are all 1:1 mappings to existing endpoints, do we have the need to do any joins (linking multiple apis together like what I did [here](https://github.com/mlflow/mlflow/pull/11173))?

**Comment by hubertzub-db** [comment]
Additional thought on:

> It looks like these are all 1:1 mappings to existing endpoints, do we have the need to do any joins (linking multiple apis together like what I did https://github.com/mlflow/mlflow/pull/11173)?

I think that considering existing use cases, the most useful solution would be to expand `experiments/batch-get-experiments` with possibility to fetch associated runs, endpoints, model versions and datasets. In other words, squeezing those into one:

Screenshot 2024-07-11 at 10 36 58

**Comment by daniellok-db** [comment]
> expand experiments/batch-get-experiments with possibility to fetch associated runs, endpoints, model versions and datasets

Yeah i think this is possible! Let me first implement the graphql endpoints since that will be required for this anyway, and I'll do the joins after.

**Pull request merged**
