### PR TITLE
Bug/correct forwards when using path prefixes and traefik in k8s

### PR DESCRIPTION
**Pull request by martimors**
## What changes are proposed in this pull request?

A quick fix of [this issue](https://github.com/mlflow/mlflow/issues/3530).

## How is this patch tested?

Not tested yet - need guidance on how to write a proper test.

### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [x] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [x] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by chck** [comment]
I am getting the same problem.
This PR is critical to use MLflow with Kubernetes.
@andrewmchen @Zangr @harupy @arjundc-db Can you merge it?

**Comment by jasonhadi** [comment]
+1 for this PR for the same reason (use with nginx-ingress).

**Review by prashant2402 — APPROVED** [review]

**Comment by prashant2402** [comment]
Could we have this merged pl, it's critical bug fix that will unblock our use of mlflow behind nginx ingress?

**Comment by genert** [comment]
Bump.

CC: @andrewmchen @Zangr @harupy @arjundc-db

**Review by chck — APPROVED** [review]

**Comment by nijkah** [comment]
is this still hanging yet?

**Comment by dingobar** [comment]
Hi guys, an update on this. As it turns out, we were able to run mlflow behind traefik by adding a trailing `/` to the path. This could be unrelated to mlflow? I lack the knowledge on networking to understand why this works.

I'll close this PR now, but please use it as a reference for how to solve this problem (if you are indeed facing it).

**Comment by ericcheng09** [comment]
Hi @dingobar,
I am also facing this problem recently and I managed to set flags to run mlflow behind traefik in K3s properly. Below are the settings I used.

Arguments in mlflow deployment:
```
...
args:
    - --host=0.0.0.0
    - --port=5000
    - --backend-store-uri=postgresql://test:test@1.2.3.4/mlflow
    - --default-artifact-root=s3://my-bucket/
    - --static-prefix=/my/mlflow
...
``` 
and Ingress(I didn't set host in rules but I think it could work in both empty or non-empty host):
```
apiVersion:  networking.k8s.io/v1
kind: Ingress
metadata:
  name: mlflow-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - http:
      paths:
      - path: /my/mlflow
        pathType: Prefix
        backend:
          service:
            name: mlflow-service
            port:
              number: 5000
```

After applying deployment, service, and ingress, I could see mlflow UI in browser with `http://1.2.3.4/my/flow` (don't need to add a trailing `/`)

**Comment by ca-scribner** [comment]
I don't understand how this works, but with an istio ingress, adding the trailing `/` I think makes the ingress handle the static files that mlflow needs properly?  If I use a rule with just `/mlflow` (no `/`) and look at the Developer->Network tab, I see `304`'s and a bunch of attempts to get `IP/static-files/...`.  But if I do `/mlflow/`, then I see `200`'s gettting `IP/mlflow/static-files/...`.  Would love if someone who understands this stuff better could explain.

**Pull request closed without merging**
