### PR TITLE
Update docs by adding LIKE/ILIKE into comparator

### LINKED ISSUE #1598: [Feature request] Support for more advanced search in UI
Allow more advanced searches:
- Partial string matching (`in` operator?)
- Regex support
- Allow searching notes

### PR DESCRIPTION
**Pull request by abawchen**
Signed-off-by: Abaw Chen <abaw.chen@gmail.com>

## What changes are proposed in this pull request?

Update document by adding LIKE and ILIKE into comparator section, fixed #1598 

## How is this patch tested?

N/A

### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by abawchen** [comment]
Hi @dmatrix
Do you (or other maintainer) have a change to review this one? Thanks.

**Review by dmatrix — APPROVED** [review]

**Comment by dmatrix** [comment]
@abawchen You need to [sign your commit](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#sign-your-work).  for the DCO test to pass.

**Comment by abawchen** [comment]
@dmatrix : signed, thanks.

**Comment by dmatrix** [comment]
@abawchen Seems like there was a discrepancy in your name and what it expected: 

Screen Shot 2020-10-16 at 10 11 14 AM

Hence the DCO tests are failing. Unless all tests pass, we cannot merge it. Might want to resolve this to ensure that your
`user.name` in the git/config is consistent.

Cheers
Jules

**Comment by abawchen** [comment]
@dmatrix 
Thanks for your time, now DCO passed.
But I don't know why r test failed ..., does it matter?

**Comment by harupy** [comment]
@abawchen #3544 has been merged. Can you merge the master branch?

**Comment by harupy** [comment]
@abawchen Merged! Thanks for the contribution!

**Comment by elgalu** [comment]
Hi, is it possible to use this search filters from MLFlow UI ? or is it only an API feature?

**Pull request merged**
