### PR TITLE
Allow pandas to have duplicated column names for 2d tensors in neural net

### PR DESCRIPTION
**Pull request by schipiga**
AWS Sagemaker converts keras models to tensorflow graph on saving.
In order to process 2D input tensors in such models, pandas duplicated column
names should be allowed.

### CODE REVIEW

**Comment by schipiga** [comment]
hey @smurching could you please review my patch?

Working sagemaker, tensorflow & keras I had meet a problem, that when I train keras model with sagemaker, then it saves keras model as tensorflow graph.
In such tensorflow graph has one input tensor with 2 dimensions minimally. In order get data with pandas for such input tensor, it needs to allow pandas to have duplicated column names. As I know, similar approach is already used in official mlflow example: https://github.com/mlflow/mlflow/blob/master/examples/tensorflow/train_predict.py#L42

**Review by tomasatdatabricks — CHANGES_REQUESTED** [review]
Thanks for the contribution  @schipiga! I have a few comments:

1. Your tests do not really invoke the scoring_server. I understand you use the same code but they need to call the scoring_server to ensure this functionality will keep working going forward. You can look e.g. at https://github.com/mlflow/mlflow/blob/master/tests/keras/test_keras_model_export.py#L60

2. I don't think we want to change the format of the json data for pyfunc right now. It might be a good idea but we need to think about it more and change other flavors (mleap) as well. 

You can actually send multidimensional array via json oriented as records. We would just need to update the _TFWrapper to 'unlist' the embedded arrays. I would prefer that instead of switching the format for now. 

3. Your csv fix works but it is a bit of a hack, I am not sure if we need it.

Overall, I would rather update the _TFWrapper code to handle multi-dimensional arrays passed in as json(orient=records) and add an example (your tests are great for that) showing how to use it and update documentation. 

Let me know what you think.

**Comment by schipiga** [comment]
@tomasatdatabricks , thank you for review. I will update your comments.
About duplicated pandas column names in csv. Currently pandas csv import doesn't support option `mangle_dupe_cols`, despite of it's present in documentation https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html. So I don't know another workaround except that.

And could you provide example of json multidimensional array with duplicated column names oriented as records? Unfortunately I didn't find it.

**Comment by tomasatdatabricks** [comment]
Hey @schipiga. 

1. Yeah I understand the duplicate column names in csv currently do not work, I am just not sure whether it is worth fixing, given the fix is a hack. I think it might be better to just tell tensorflow users to use json format instead. 

2. Here is an example of a multidimensional dataframe:

```
df = pd.DataFrame(
        pd.Series(boston_housing_model["test_data"].tolist(), dtype="object"),
        columns=[boston_housing_model["input_tensor_name"]])
```

You can write that out to json with orient='records' and read it back as is. You need to convert it to multidim numpy array before scoring. That can happen in _TFWrapper, e.g:

```
    def predict(self, df):

        def _nparray(x):
            if isinstance(x[0], list):
                import numpy as np
                return np.array([np.array(y) for y in x])
            return x

        with self.tf_graph.as_default():
            # Build the feed dict, mapping input tensors to DataFrame column values.
            feed_dict = {
                    self.input_tensor_mapping[tensor_column_name]:
                        _nparray(df[tensor_column_name].values)
                    for tensor_column_name in self.input_tensor_mapping.keys()
            }
            raw_preds = self.tf_sess.run(self.output_tensors, feed_dict=feed_dict)
            pred_dict = {column_name: values.ravel() for column_name, values in raw_preds.items()}
            return pandas.DataFrame(data=pred_dict)
```

**Comment by juntai-zheng** [comment]
I'm going to close this for inactivity - feel free to reopen if you'd like to continue work on this. Thanks for your contribution!

**Pull request closed without merging**
