### PR TITLE
Enable arrow-parens for ESLint

### PR DESCRIPTION
**Pull request by harupy**
## What changes are proposed in this pull request?

Enable `arrow-parens` for ESLInt to improve code consistency.

doc: https://eslint.org/docs/rules/arrow-parens

## How is this patch tested?

`npm run lint`

### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s) does this PR affect?

- [ ] UI
- [ ] CLI
- [ ] API
- [ ] REST-API
- [ ] Examples
- [ ] Docs
- [ ] Tracking
- [ ] Projects
- [ ] Artifacts
- [ ] Models
- [ ] Scoring
- [ ] Serving
- [ ] R
- [ ] Java
- [ ] Python

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by harupy** [comment]
@Zangr @smurching What do you think about this change?

**Comment by Zangr** [comment]
@harupy, thanks for proposing this. We actually prefer `['error', 'always']` for this rule. We have a recent plan to do some folder reordering and lint clean up which will do lint changes all together.

**Comment by harupy** [comment]
Oh ok, shoud I close this PR?

**Comment by Zangr** [comment]
Yes

**Comment by harupy** [comment]
@Zangr 

> lint clean up which will do lint changes all together.

Any updates on this?

**Comment by Zangr** [comment]
@harupy We have a batch of JS fixes yet to be applied to OSS MLFlow. Massive re-lint will likely to happen after that.

**Comment by harupy** [comment]
@Zangr Got it. Thank you!

**Pull request closed without merging**
