### PR TITLE
Introducing the Giskard community plugin for mlflow.evaluate() 🐢

### PR DESCRIPTION
**Pull request by rabah-khalek**
## What changes are proposed in this pull request?

Introducing the Giskard `mlflow.evaluate()` [plugin](https://docs.giskard.ai/en/latest/integrations/mlflow/) to the mlflow docs. 

## How is this patch tested?

- [ ] Existing unit/integration tests
- [ ] New unit/integration tests
- [ ] Manual tests (describe details, including test results, below)

## Does this PR change the documentation?

- [ ] No. You can skip the rest of this section.
- [x] Yes. Make sure the changed pages / sections render correctly in the documentation preview.

### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [x] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by BenWilson2** [comment]
Neat package! 
Could you revert the formatting changes made to the .rst that isn't in the blocks of text that you're adding?

**Comment by rabah-khalek** [comment]
Thanks @BenWilson2! I have made the necessary changes.

Also, we have drafted an article to explain the usage of this plugin. We're illustrating how MLflow users can leverage `mlflow.evaluate()` with Giskard to build robust and ethical LLMs, complying with upcoming AI regulations.

Would you and the team at Databricks be open to collaborating on a joint publication?

Our first draft is available here: https://giskard.notion.site/Detecting-LLM-vulnerabilities-in-MLflow-with-Giskard-c08f9a8419d048e8bc9cd048f3ed5330?pvs=4. We're interested in your feedback :pray:

**Comment by rabah-khalek** [comment]
Hello @BenWilson2! I wanted to check if you had a chance to give this PR another read. If there's someone else I should reach out to for the joint publication instead, please let me know.

**Review by BenWilson2 — APPROVED** [review]
LGTM!

**Pull request merged**
