### PR TITLE
Updated azure-storage-blob to v12

### PR DESCRIPTION
**Pull request by Trollgeir**
## What changes are proposed in this pull request?

azure-storage-(blob) is updated to version 12.

This version has breaking changes in the API, hence a lot of code rewriting.

## How is this patch tested?

Unittests (rewritten)
pylint

### Is this a user-facing change?

- [x] No.

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Review by tomasatdatabricks — COMMENTED** [review]
Thanks for the contribution! I need to test it out with actual blob storage but in general the PR looks good. 

I have a slight concern about breaking dependencies of other azure libraries. For example, it looks like azure python sdk requires azure-blob-storage~=1.3.  That would mean that mlflow users who also use azure sdk would not be able to use the new repository. I am not sure if this was already the case (i.e. if the current mlflow client would work with 1.3 or not) but I will test that as well. Do you have any context on this by any chance?

**Comment by Trollgeir** [comment]
> Thanks for the contribution! I need to test it out with actual blob storage but in general the PR looks good.
> 
> I have a slight concern about breaking dependencies of other azure libraries. For example, it looks like azure python sdk requires azure-blob-storage~=1.3. That would mean that mlflow users who also use azure sdk would not be able to use the new repository. I am not sure if this was already the case (i.e. if the current mlflow client would work with 1.3 or not) but I will test that as well. Do you have any context on this by any chance?

From what I can see at https://azure.github.io/azure-sdk-for-python/ref/Storage.html#azure-storage-blob - azure python SDK 2.0 is up to date with azure-storage-blob 12.x. Are you referring to SDK 1.0 ?

**Comment by tomasatdatabricks** [comment]
I am talking about azure pip package:
```
pip show azure             
Name: azure
Version: 4.0.0
Summary: Microsoft Azure Client Libraries for Python
Home-page: https://github.com/Azure/azure-sdk-for-python
Author: Microsoft Corporation
Author-email: azpysdkhelp@microsoft.com
License: MIT License
```

**Comment by Trollgeir** [comment]
I understand. Although I'd advocate that the MLFlow should not guarantee any support for azure 4.0.0  
`azure-blob-storage` is as minimalistic of a dependency as you'd get. Given the big change to drop python 2 in the upcoming 1.8, I take it people are prepared for changes in their current environment.

**Review by tomasatdatabricks — APPROVED** [review]
lgtm! Thanks for the contributiuon!

**Pull request merged**
