### PR TITLE
Update tracking.rst

### PR DESCRIPTION
**Pull request by mahesh-venkatachalam**
Fixed a typo:  RestoreStore -> RestStore

### CODE REVIEW

**Comment by pogil** [comment]
Thanks for the PR Mahesh (@kvmakes)! For this to merge you'll need to sign off on your code. See the instructions here https://github.com/mlflow/mlflow/pull/4674/checks?check_run_id=3286011007 -- more detail here: https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#sign-your-work

**Comment by kvmakes** [comment]
Thanks for the review @pogil. I was able to sign off my changes, but I ran into a permissions issue when I tried to push my changes. See below:

```
mvenkat1@mvenkat1-mn1: ~/workspace/mlflow$ git push --force-with-lease origin patch-1
remote: Permission to mlflow/mlflow.git denied to kvmakes.
fatal: unable to access 'https://github.com/mlflow/mlflow.git/': The requested URL returned error: 403
```

Any group that I need to be a part of or something for me to be able to push my changes?

**Comment by harupy** [comment]
@kvmakes Hi Mahesh, I guess your `origin` points to `https://github.com/mlflow/mlflow.git`, but it actually should point to your fork. Could you check what `git remote -v` prints out?

```
$ git remote -v | g origin
origin  git@github.com:harupy/mlflow.git (fetch)
origin  git@github.com:harupy/mlflow.git (push)
                                                                                                                                                                                                                  
$ git remote -v | g upstream
upstream        https://github.com/mlflow/mlflow.git (fetch)
upstream        https://github.com/mlflow/mlflow.git (push)
```

**Comment by kvmakes** [comment]
Good catch, @harupy! Updated.

**Review by harupy — APPROVED** [review]
LGTM!

**Pull request merged**
