### PR TITLE
Add Swagger API Docs

### PR DESCRIPTION
**Pull request by adrian555**
Use [`flasgger`](https://github.com/rochacbruno/flasgger) package to extract REST API documentation and show in Swagger UI through `http://127.0.0.1/apidocs`.

### CODE REVIEW

**Comment by mateiz** [comment]
Just wondering, what's the benefit of this versus the docs at https://mlflow.org/docs/latest/rest-api.html? Do you find these easier to read, etc? It adds a bunch of duplication of the API spec (from Protobuf format to Swagger JSON) so it will create a significant risk of the two diverging.

**Comment by adrian555** [comment]
Thanks @mateiz. Swagger has been widely used to describe REST APIs. It is easier to read (at least for me) and also it provides `try it out` function. Attached a couple of snapshots.
image

image.

Also, the current way mlflow documenting the REST APIs is through [rest-api.rst](https://mlflow.org/docs/latest/rest-api.html) as you mentioned above. There is a disconnect between this doc and the API code. For example, with 0.5.2 release, there are two new APIs (delete and restore experiment). However, the doc does not reflect them.

On the contrary, this PR adds the API descriptions as part of the API python code. Since the code and doc are in one place, it is easy to keep in-sync compared to current approach.

I understand your concern between gRPC and Swagger but I could not find a better tool that can automatically generate REST APIs through protobuf. This PR is not going to do worse than the current documenting approach (as writing in a separate text), which is already not synced.

**Comment by adrian555** [comment]
@mateiz any more comments on above? Thanks.

**Comment by pogil** [comment]
@adrian555 we do auto-generate the rest-api RST from the protocol buffers in our release tools. It looks like there may be ways to generate swagger json from the protocol buffer definitions. We'll add investigating Swagger docs as a part of our backlog for consideration.

**Pull request closed without merging**
