### PR TITLE
Unpin cloudpickle

### PR DESCRIPTION
**Pull request by B-Step62**
<details><summary>&#x1F6E0 DevTools &#x1F6E0</summary>
<p>

[Open in GitHub Codespaces](https://codespaces.new/B-Step62/mlflow/pull/10265?quickstart=1)

#### Install mlflow from this PR

```
pip install git+https://github.com/mlflow/mlflow.git@refs/pull/10265/merge
```

#### Checkout with GitHub CLI

```
gh pr checkout 10265
```

</p>
</details>

### Related Issues/PRs

 #xxx

### What changes are proposed in this pull request?

With https://github.com/mlflow/mlflow/pull/10247, we should be unblocked to unpin cloudpickle.

### How is this PR tested?

- [x] Existing unit/integration tests
- [ ] New unit/integration tests
- [ ] Manual tests

### Does this PR require documentation update?

- [x] No. You can skip the rest of this section.
- [ ] Yes. I've updated:
  - [ ] Examples
  - [ ] API references
  - [ ] Instructions

#### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

#### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>

#### How should the PR be classified in the release notes? Choose one:

- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Review by harupy — APPROVED** [review]
LGTM (assuming all the CI checks will pass)!

**Comment by harupy** [comment]
Interesting error. Where does `TypeError: _predict() missing 1 required positional argument: 'json_format'` come from?

**Comment by harupy** [comment]
The failed test works fine on my machine.

**Comment by B-Step62** [comment]
> The failed test works fine on my machine.

Same, might be intermittent. Thanks for retrying.

**Comment by harupy** [comment]
I forgot to update cloudpickle. The following change fixed the issue:

```diff
diff --git a/mlflow/utils/environment.py b/mlflow/utils/environment.py
index c7d7ee7478..b2e35b2c61 100644
--- a/mlflow/utils/environment.py
+++ b/mlflow/utils/environment.py
@@ -7,6 +7,7 @@ import yaml
 from packaging.requirements import InvalidRequirement, Requirement
 from packaging.version import Version
 
+import mlflow
 from mlflow.environment_variables import _MLFLOW_TESTING
 from mlflow.exceptions import MlflowException
 from mlflow.protos.databricks_pb2 import INVALID_PARAMETER_VALUE
@@ -214,7 +215,7 @@ def _mlflow_conda_env(
     :return: ``None`` if ``path`` is specified. Otherwise, the a dictionary representation of the
              Conda environment.
     """
-    pip_deps = (["mlflow"] if install_mlflow else []) + (
+    pip_deps = ([f"mlflow=={mlflow.__version__}"] if install_mlflow else []) + (
         additional_pip_deps if additional_pip_deps else []
     )
     conda_deps = additional_conda_deps if additional_conda_deps else []
```

**Comment by harupy** [comment]
I think `json_format` comes from an ancient mlflow. pip tries to resolve `mlflow` and `cloudpickle==3.0`, and ends up installing an old version of mlflow.

**Comment by B-Step62** [comment]
> I think json_format comes from an ancient mlflow. pip tries to resolve mlflow and cloudpickle==3.0, and ends up installing an old version of mlflow.

That makes sense, some old doc refers to `json_format` ([ref](https://mlflow.org/docs/1.3.0/python_api/mlflow.models.html#mlflow.models.FlavorBackend.predict)). Thanks for the quick investigation!!

Will merge PR once all tests pass.

**Comment by B-Step62** [comment]
The python test failure doesn't come from this change, unfortunately hit issue from latest minio release; https://github.com/minio/minio/issues/18372

There is an open PR for pinning container version: https://github.com/mlflow/mlflow/pull/10268

**Comment by AndreaPiccions** [comment]
Hi, will this be part of a new release soon? I have been waiting for the update to `cloudpickle >= 3` for a while and have a lot of open MRs to have an MLFlow version with unpinned `cloudpickle`

**Comment by BenWilson2** [comment]
@AndreaPiccions it will be released in MLflow 2.9.0, which is scheduled for the last week of November / 1st week of December for release.

**Pull request merged**
