### PR TITLE
Fix type annotations for list_artifacts method

### PR DESCRIPTION
**Pull request by benglewis**
<details><summary>&#x1F6E0 DevTools &#x1F6E0</summary>
<p>

[Open in GitHub Codespaces](https://codespaces.new/benglewis/mlflow/pull/13948?quickstart=1)

#### Install mlflow from this PR

```
# Use `%sh` to run this command on Databricks
OPTIONS=$(if pip freeze | grep -q 'mlflow @ git+https://github.com/mlflow/mlflow.git'; then echo '--force-reinstall --no-deps'; fi)
pip install $OPTIONS git+https://github.com/mlflow/mlflow.git@refs/pull/13948/merge
```

#### Checkout with GitHub CLI

```
gh pr checkout 13948
```

</p>
</details>

Updated type annotations and added `NotImplementedError` to `list_artifacts` methods.

* **mlflow/store/artifact/artifact_repo.py**
  - Updated `list_artifacts` method signature to include type annotations.
  - Added `NotImplementedError` to `list_artifacts` method.
* **mlflow/store/artifact/databricks_artifact_repo.py**
  - Updated `list_artifacts` method signature to include type annotations.
* **mlflow/store/artifact/databricks_models_artifact_repo.py**
  - Updated `list_artifacts` method signature to include type annotations.
* **mlflow/store/artifact/databricks_sdk_models_artifact_repo.py**
  - Updated `list_artifacts` method signature to include type annotations.
* **mlflow/store/artifact/dbfs_artifact_repo.py**
  - Updated `list_artifacts` method signature to include type annotations.

---

For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/benglewis/mlflow?shareId=03b9d304-f394-40d4-88c5-6bbadb73f451).

### What changes are proposed in this pull request?

Fix type annotation issues

### How is this PR tested?

- [ ] Existing unit/integration tests
- [ ] New unit/integration tests
- [ ] Manual tests

### Does this PR require documentation update?

- [x] No. You can skip the rest of this section.
- [ ] Yes. I've updated:
  - [ ] Examples
  - [ ] API references
  - [ ] Instructions

#### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

#### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations

- [x] `integrations/azure`: Azure and Azure ML integrations
- [x] `integrations/sagemaker`: SageMaker integrations
- [x] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>

#### How should the PR be classified in the release notes? Choose one:

- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

#### Should this PR be included in the next patch release?

`Yes` should be selected for bug fixes, documentation updates, and other small changes. `No` should be selected for new features and larger changes. If you're unsure about the release classification of this PR, leave this unchecked to let the maintainers decide.

<details>
<summary>What is a minor/patch release?</summary>

- Minor release: a release that increments the second part of the version number (e.g., 1.2.0 -> 1.3.0).
  Bug fixes, doc updates and new features usually go into minor releases.
- Patch release: a release that increments the third part of the version number (e.g., 1.2.0 -> 1.2.1).
  Bug fixes and doc updates usually go into patch releases.

</details>

- [ ] Yes (this PR will be cherry-picked and included in the next patch release)
- [x] No (this PR will be included in the next minor release)

### CODE REVIEW

**Comment by daniellok-db** [comment]
@benglewis thanks for the PR! the changes look good to me, would you mind fixing the lint errors? you can run `python dev/ruff.py` to fix all auto-fixable errors (we use `ruff==0.7.4` as a linter), but you might have to manually fix some.

**Comment by benglewis** [comment]
Done @daniellok-db

**Review by daniellok-db — APPROVED** [review]
lgtm

**Comment by benglewis** [comment]
@daniellok-db I see that all checks passed except for "Maintainer approval / check", and the "MLflow tests / windows (1)" and "MLflow tests / windows (2)" as well as "Protect / protect". From the looks of it, the failures of the tests on Windows are unrelated to the PR. Is there anything blocking from my end here? Or should I just be patient and this will eventually be merged? 🙏

**Comment by daniellok-db** [comment]
@benglewis i believe the tests are fixed in master, if you rebase your changes the tests should pass and i'll merge this PR after!

**Comment by benglewis** [comment]
@daniellok-db I have rebased this morning. It looks ready to me, but I see that some checks are marked as "Expected" and "Required" but haven't run yet. I am guessing that it requires some interaction from you to run such checks

**Pull request merged**
