### PR TITLE
Enable the ESLint comma-dangle rule

### PR DESCRIPTION
**Pull request by harupy**
## What changes are proposed in this pull request?

Enable the ESLint `comma-dangle` rule and set it to `always-multiline` to enhance code consistency.

https://eslint.org/docs/rules/comma-dangle

## How is this patch tested?
Manually tested

### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s) does this PR affect?

- [ ] UI
- [ ] CLI
- [ ] API
- [ ] REST-API
- [ ] Examples
- [ ] Docs
- [ ] Tracking
- [ ] Projects
- [ ] Artifacts
- [ ] Models
- [ ] Scoring
- [ ] Serving
- [ ] R
- [ ] Java
- [ ] Python

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by harupy** [comment]
Found 97 lint errors.

https://travis-ci.org/mlflow/mlflow/jobs/609531617#L489-L659

**Comment by Zangr** [comment]
The rule change looks good. Could you please run a lint fix and include the fixed changes?

**Comment by harupy** [comment]
@Zangr 
Ran `npm run lint:fix` and fixed the violations.

**Comment by Zangr** [comment]
Thank you @harupy, would you like to rebase the conflicting files?

**Comment by harupy** [comment]
@Zangr oh I will fix it.

**Comment by harupy** [comment]
@Zangr Fixed the conflict.

**Comment by harupy** [comment]
@Zangr Can you merge this PR?

**Review by Zangr — APPROVED** [review]
LGTM!

**Pull request merged**
