### PR TITLE
Remove requirements update assertion

### PR DESCRIPTION
**Pull request by BenWilson2**
## Related Issues/PRs

 #xxx

## What changes are proposed in this pull request?

Remove the version check assertion in update_requirements.py to prevent CI failures when manually increasing supported package version beyond released major version cutoffs on pypi.

## How is this patch tested?

- [ ] Existing unit/integration tests
- [ ] New unit/integration tests
- [X] Manual tests (describe details, including test results, below)

## Does this PR change the documentation?

- [X] No. You can skip the rest of this section.
- [ ] Yes. Make sure the changed pages / sections render correctly in the documentation preview.

### Is this a user-facing change?

- [X] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [X] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [X] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by harupy** [comment]
> running the update_requirements.py script do not provide contextual information in the assertion check. This allows for local testing.

If so, can we fix `update_requirements.py`?

**Comment by harupy** [comment]
This relates to https://github.com/mlflow/mlflow/actions/runs/4314312216/jobs/7527176422, right? I think we can just make the following change:

```
diff --git a/dev/update_requirements.py b/dev/update_requirements.py
index d04febf93..6b8265ac7 100644
--- a/dev/update_requirements.py
+++ b/dev/update_requirements.py
@@ -62,7 +62,6 @@ def main():
         pip_release = req_info["pip_release"]
         max_major_version = req_info["max_major_version"]
         latest_major_version = get_latest_major_version(pip_release)
-        assert latest_major_version >= max_major_version
         if latest_major_version > max_major_version:
             requirements[key]["max_major_version"] = latest_major_version
             print(f"Updated {key}.max_major_version to {latest_major_version}")
```

in case we manually update requirements.

**Comment by harupy** [comment]
I forgot why I inserted `assert latest_major_version >= max_major_version`...

**Comment by harupy** [comment]
Maybe because to avoid using non-existing versions such pandas 100?

**Review by harupy — APPROVED** [review]
LGTM!

**Review by WeichenXu123 — APPROVED** [review]

**Pull request merged**
