### PR TITLE
[DOCS][MINOR] Minor typo update

### PR DESCRIPTION
**Pull request by keypointt**
## What changes are proposed in this pull request?

Minor typo update

## How is this patch tested?

Local test.

### Is this a user-facing change?

No code logic change.

### What component(s), interfaces, languages, and integrations does this PR affect?
Components 
- [x] `area/docs`: MLflow documentation pages

### How should the PR be classified in the release notes? Choose one:

- [x] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by harupy** [comment]
@keypointt Thanks for the contribution! The proposed changes look good. Could you fix the DCO check failures?

https://github.com/mlflow/mlflow/pull/4511/checks?check_run_id=2947464636

**Comment by keypointt** [comment]
hi Harutaka, seems DCO check passed, could you please double check?
thanks :)

**Review by harupy — APPROVED** [review]
LGTM, thanks for the contribution!

**Comment by keypointt** [comment]
Thank you Harutaka!

**Pull request merged**
