### PR TITLE
Update documentation with actual output and file contents

### PR DESCRIPTION
**Pull request by akainth015**
Co-authored-by: Rithvik Rao <rithvik321@gmail.com>

## What changes are proposed in this pull request?
- Update the tracking quick start code example to match the version that is currently in the repository
- Fix the example command so that it no longer fails upon execution
- Update the output of the command to what `mlflow` currently returns

## How is this patch tested?
@rithvikrao and I went through the quick start yesterday, and fixed the issues we came across

## Release Notes
Core quick start examples work as expected out of the box

### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

### What component(s), interfaces, languages, and integrations does this PR affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [x] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by ankitmathur-db** [comment]
@akainth015 - could you please clarify in more detail in the PR description why you've filed this PR?

**Comment by akainth015** [comment]
@ankitmathur-db I updated the description, hopefully it entails the changes we made more clearly

**Comment by ankitmathur-db** [comment]
Passing to @dmatrix to determine who the right reviewer for such a docs change might be

**Comment by dmatrix** [comment]
@akainth015  the typo LGTM. But now you have [sign-off your commits](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#sign-your-work) as part of your commits before we can merge it.

**Comment by dmatrix** [comment]
Thanks for signing it.

**Review by dmatrix — APPROVED** [review]

**Pull request merged**
