### PR TITLE
Added the option to use AAD for auth for store

### PR DESCRIPTION
**Pull request by thomasfrederikhoeck**
## What changes are proposed in this pull request?

This change allows for using a Azure blob storage where AAD is used as authentication as described in #3483 

The main idea is that it allows for using a service principal that only has access to the blob container. It futhermore
allows for controlling access to the Artifact Store through AAD as user/developers/model-builders can login with Azure CLI locally through the Azure Activate Directory login flow. This means that the normal Azure login flow can be used for model-builders to get access to the Artifact store.

## How is this patch tested?

The current unit-test has been extended, and I have tried connecting to a AAD enabled blob container.

### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [x] Yes. Give a description of this change to be included in the release notes for MLflow users.

Azure Activate Directory authentication when using Azure blob as storage for artifact store.

### What component(s), interfaces, languages, and integrations does this PR affect?
Components 
- [x] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [x] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [x] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [x] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [x] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by thomasfrederikhoeck** [comment]
Looks like the R fail is fixed in #3477

**Comment by thomasfrederikhoeck** [comment]
> Looks like the R fail is fixed in #3477 or #3472

Solved now.

**Comment by thomasfrederikhoeck** [comment]
@dbczumar will you review this? Sorry for tagging you if that is not how you go about it on the MLflow repo, but I couldn't find anything in the contribution guide on how to show that your PR as ready for review 😄

**Comment by thomasfrederikhoeck** [comment]
Hi @javierluraschi - do you want to review this? 😄

**Comment by thomasfrederikhoeck** [comment]
@dmatrix I have been struggling with finding someone to review this? Do you want to do this?

**Comment by thomasfrederikhoeck** [comment]
@sueann I have been struggling with finding someone to review this? Do you want to do this? :-)

**Comment by bastidas** [comment]
I tried out `python -m pip install git+https://github.com/thomasfrederikhoeck/mlflow.git@feat_store_add --upgrade` and it works. I want to avoid the need to have passwords in a connection string in our git repo; this PR does that.

**I would like this to be merged with master.**

**Comment by alanjcastonguay** [comment]
I do wonder whether `azure.identity.DefaultAzureCredential` should be considered instead of `azure.identity.AzureCliCredential` directly, to support other methods automagically per https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-authenticate?tabs=cmd. But the current implementation in commit 4feaf5bc16f3c0015fb7aa4b150c8f39bc15b60b does work - I helped @bastidas validate above. It looks good to me. @dbczumar could you take a look?

**Comment by thomasfrederikhoeck** [comment]
@alanjcastonguay I think DefaultAzureCredential can work as long as long as Interactive is disabled (this is the default) which can give silent blocks. It might be a bit harder writing specific error in the style of the ones used for the Env Var login approach. This is why I went for the CLI add.

**Comment by alanjcastonguay** [comment]
@dbczumar @harupy What else is needed here?

**Comment by gdippolito** [comment]
@thomasfrederikhoeck I think interactive is disabled by default as per constrcutor -> https://docs.microsoft.com/en-us/python/api/azure-identity/azure.identity.defaultazurecredential?view=azure-python#constructor 

I think it would be valuable to use `DefaultAzureCredential` so that user can login via managed identities if they have mlflow deployed in Azure. This would be a much more elegant and secure option instead of using an environment variable containing sensible data.  

I have created a similar PR (https://github.com/mlflow/mlflow/pull/4510) where I have given the ability to use azure-identity if necessary (avoid breaking changes) when an environment variable is set. I also believe environment variable like `AZURE_STORAGE_ACCESS_KEY` should be namespaced to be clear what the intention of that environment variable is and to avoid any conflict with other clients that will use the same environment variable.

**Comment by thomasfrederikhoeck** [comment]
@gdippolito I agree that using `DefaultAzureCredential ` is better. Fine with another PR - to be honest I had written this PR off as I was struggling to get someone from the mlflow team to review it. :-D

**Pull request closed without merging**
