### PR TITLE
chore: remove pyarrow upper bound

### PR DESCRIPTION
**Pull request by ion-elgreco**
<details><summary>&#x1F6E0 DevTools &#x1F6E0</summary>
<p>

[Open in GitHub Codespaces](https://codespaces.new/ion-elgreco/mlflow/pull/12980?quickstart=1)

#### Install mlflow from this PR

```
pip install git+https://github.com/mlflow/mlflow.git@refs/pull/12980/merge
```

#### Checkout with GitHub CLI

```
gh pr checkout 12980
```

</p>
</details>

### Related Issues/PRs
Due to this upper bound people can't use `deltalake` anymore in newer versions

### CODE REVIEW

**Comment by Koenkk** [comment]
I don't think this can be merged without additional changes. E.g. `pyarrow.hdfs` has been removed in pyarrow 16+ which breaks:

https://github.com/mlflow/mlflow/blob/474be52ae273358b62b69cb7eb904adf11e79970/mlflow/store/artifact/hdfs_artifact_repo.py#L204

image

**Comment by B-Step62** [comment]
The condition issue is being addressed in https://github.com/mlflow/mlflow/pull/12592, with additional changes to handle new interface. Closing as duplicates.

**Comment by JonCoens** [comment]
What's needed to get this PR to move forward? It appears unblocked

**Comment by B-Step62** [comment]
@ion-elgreco There are some conflict against main branch and format issues. Could you fix them so we can unblock this PR?

* Please follow the PR template like [other PRs](https://github.com/mlflow/mlflow/pull/12996). They are required for us to label PRs and manage them for release.
* All the setting files should be consistent, but only `pyproject.release.toml` is updated. Could you apply the same change to other files listed here? https://github.com/search?q=repo%3Amlflow%2Fmlflow+pyarrow%3C&type=code

**Comment by ion-elgreco** [comment]
@B-Step62 I'll see if I have time tomorrow

**Comment by victoriarouton** [comment]
Curious on the status of this? Every time pyarrow releases a new version we’re getting dependency conflicts, removing the upper bounds would be greatly appreciated

**Pull request closed without merging**
