### PR TITLE
Add tag with used Conda environment

### PR DESCRIPTION
**Pull request by kirillmakhonin**
## What changes are proposed in this pull request?
 
This PR adds new tag named `mlflow.conda.envName` (MLFLOW_CONDA_ENV_NAME) to standard MLflow tags. This tag is added for runs that are used Conda and it contains name of Conda environment. 

This PR is required to allow external applications reuse MLflow models with theirs environments (e.g. install additional package into them).

This tag with description has been added into documentation.
 
## How is this patch tested?
 
New test named `tests/projects/test_projects.py::test_use_conda_tags` has been added. It uses test model `example_project` with main entrypoint.
 
### Is this a user-facing change? 

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.
  
### What component(s) does this PR affect?
 
- [ ] UI
- [ ] CLI 
- [ ] API 
- [ ] REST-API 
- [ ] Examples 
- [x] Docs
- [ ] Tracking
- [ ] Projects 
- [ ] Artifacts 
- [ ] Models 
- [ ] Scoring 
- [ ] Serving
- [ ] R
- [ ] Java
- [x] Python

### How should the PR be classified in the release notes? Choose one:
 
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by tomasatdatabricks** [comment]
Hi Kiril, thanks for the PR! 

Can you clarify a bit more why do you want to introduce this tag? From your descriptions it sounds like you want to use that environment manually from outside of mlflow? 

The mlflow conda environments are named with a hash of the respective  conda.yml file. This is so that we can cache environments. If you would manually change such environment, this caching would not work properly and you could get unexpected results. I would recommend logging the contents of conda.yml file instead in your project.

**Comment by kirillmakhonin** [comment]
Hi @tomasatdatabricks!

I want to extend environment (add some extra packages), that has been used by MLflow training, to use my serving layer, inside one env. with trained model.

E.g. I trained model X, it has created and used env. Y. I want to add package Z to env. Y to use my script P, that required package Z, inside env. Y for model X.

**Comment by kirillmakhonin** [comment]
As for other cases, it might be helpful for garbage collection. (e.g. for analyzing which envs can be cleaned)

**Comment by aarondav** [comment]
Sorry for the ball being dropped on this PR -- I think this tag does make sense, it's in line with the docker image tag above. If you get a chance to resolve conflicts, I think it looks good to merge.

**Review by aarondav — CHANGES_REQUESTED** [review]
(Requesting just a merge conflict revision)

**Pull request closed without merging**
