### PR TITLE
Remove run from mlflow module to reduce confusion with mlflow.projects.run

### PR DESCRIPTION
**Pull request by ghost**
This method is not referenced in any docs, so not clear if used.

### CODE REVIEW

**Comment by mateiz** [comment]
It's OK to remove it, but I don't see too much potential confusion here. The question is whether we want to have a bunch of convenient shortcut methods in `mlflow` or ask people to learn all the sub-packages, etc. In Python at least it's pretty common to put the most commonly used APIs together and reduce the number of imports that people have to memorize. Think about using MLflow in a notebook for example -- do you want to have three import statements or just one.

**Comment by aarondav** [comment]
I guess one question is how popular is `mlflow.run` -- `start_run` is probably way more likely what people are looking for than `run` by a wide margin. It's easier to add something as top level if we see a lot of people redundantly import it than remove it later.

Anyway, choice is up to you. Let us know if you'd prefer to remove it for now or not.

**Comment by mateiz** [comment]
I'd say let's leave it for now to see what happens as we improve multi-step workflows. BTW we do talk about it in the docs at https://mlflow.org/docs/latest/projects.html, and it matches the command line tool `mlflow run`.

**Comment by aarondav** [comment]
Alright -- @stbof, good to close this out, or have other points to raise in favor of removal?

**Comment by stbof** [comment]
Yes, closing.

**Pull request closed without merging**
