### PR TITLE
Start experiment ID with 0 if no experiments exist

### PR DESCRIPTION
**Pull request by schipiga**
Actual for case, when custom folder is used for tracking, and no experiments were created there before.

### CODE REVIEW

**Review by tomasatdatabricks — CHANGES_REQUESTED** [review]
Thanks for the contribution! Can you please add a test as well?

**Comment by tomasatdatabricks** [comment]
Yes, it's a conda issue. I am looking into it.

**Comment by schipiga** [comment]
@tomasatdatabricks as I see, conda issue is fixed. Pls review again

**Review by tomasatdatabricks — APPROVED** [review]
LGTM, thanks @schipiga

**Pull request merged**
