### PR TITLE
Allow specifying mlflow command line args as env variables.

### LINKED ISSUE #3122: [FR] Allow specifying mlflow server configurations as environment variables
## MLflow Roadmap Item

This is an MLflow Roadmap item that has been prioritized by the MLflow maintainers. We’ve identified this feature as a highly requested addition to the MLflow package based on community feedback. 
We're seeking a community contribution for the implementation of this feature and will enthusiastically support the development and review of a submitted PR for this.

## Feature scope

This roadmap feature’s complexity is classified as:

- [X] `good-first-issue`: This feature is limited in complexity and effort required to implement.

## Proposal Summary

When running an MLFlow server, I would like to propose having the ability to specify flags as environment variable, such as `MLFLOW_BACKEND_STORE_URI`, `MLFLOW_DEFAULT_ARTIFACT_ROOT`,  `MLFLOW_SERVE_ARTIFACTS`, `MLFLOW_ARTIFACTS_DESTINATION`, `MLFLOW_HOST`, ...

## Motivation

The `backend-store-uri` will oftentimes contain sensitive information like database passwords. Some deployment options, like AWS ECS, won't allow you to interpolate secrets in CLI arguments at runtime.

Workarounds to this limitation of ECS include creating a custom docker image with an entrypoint that interpolates said secret, or overriding the entrypoint to use a shell.

Although this limitation is not the responsibility of MLFlow, I would argue that giving people the option to specify values that contain secret information in multiple ways (env vars, files, ...) provides a better UX for systems engineers.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

## Details

Leverage [Click's `envvar` argument for the `.option()` decorator](https://click.palletsprojects.com/en/7.x/options/#values-from-environment-variables).

### PR DESCRIPTION
**Pull request by cnphil**
Signed-off-by: Phil Xiaojun Hu <phil@cnphil.com>

## Related Issues/PRs

Close #3122 

## What changes are proposed in this pull request?

Allow the following flags to be read from environment variables:

* MLFLOW_BACKEND_STORE_URI
* MLFLOW_DEFAULT_ARTIFACT_ROOT
* MLFLOW_ARTIFACTS_DESTINATION
* MLFLOW_SERVE_ARTIFACTS
* MLFLOW_HOST
* MLFLOW_PORT

## How is this patch tested?

Some help/guidance wanted:
- Ran `pytest tests/test_cli.py`, all tests pass except for `tests/test_cli.py::test_mlflow_models_serve[True]` which seems to be stuck in an infinite loop, is this expected? (The test also fails on master/HEAD for me, so probably unrelated to the PR)
- Manually tested by running `mlflow server` with the added env variables, seems to work.
- Also please give some guidance on whether this PR deserves its own test case in test_cli.py.

- [ ] I have written tests (not required for typo or doc fix) and confirmed the proposed feature/bug-fix/change works.

## Does this PR change the documentation?

Please also give some guidance on whether this PR needs a docs change.

- [x] No. You can skip the rest of this section.
- [ ] Yes. Make sure the changed pages / sections render correctly by following the steps below.

1. Click the `Details` link on the `Preview docs` check.
2. Find the changed pages / sections and make sure they render correctly.

### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [x] Yes. Give a description of this change to be included in the release notes for MLflow users.

mlflow server configurations can also be specified in environment variables.

### What component(s), interfaces, languages, and integrations does this PR affect?
Components
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>
### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Review by dbczumar — COMMENTED** [review]
@cnphil Thank you for this excellent PR! Can we also add these environment variables to `mlflow server` (https://github.com/mlflow/mlflow/blob/897dc966dde7283f1b9e3e2279529c9aff47fb8a/mlflow/cli.py#L422)?

**Comment by harupy** [comment]
Can we use `auto_envvar_prefix`? https://click.palletsprojects.com/en/8.1.x/options/#values-from-environment-variables

**Comment by dbczumar** [comment]
> auto_envvar_prefix

@harupy This sounds like a great idea!

**Comment by cnphil** [comment]
@harupy Thanks that's a great idea!

Just to confirm, per [Click's documentation](https://click.palletsprojects.com/en/8.1.x/options/#values-from-environment-variables), when using command groups with `auto_envvar_prefix`, the command name will be included in the environment variable name. E.g. we would have:
* `MLFLOW_UI_BACKEND_STORE_URI`
* `MLFLOW_SERVER_BACKEND_STORE_URI`
* `MLFLOW_UI_DEFAULT_ARTIFACT_ROOT`
* `MLFLOW_SERVER_DEFAULT_ARTIFACT_ROOT`
* `MLFLOW_UI_PORT`
* `MLFLOW_SERVER_PORT`
* `MLFLOW_RUN_ENTRY_POINT`
* etc.

So that there would be different environment variables for the same flag for `ui` and `server`.  Since I'm new to this project, I couldn't tell whether this is a desired behavior.  If this is not the desired behavior, we could manually name the env vars for `ui` and `server` so that they could share the same env var name.

@dbczumar Could you please help confirm? I'll update the PR once this is confirmed.

Thanks!

**Comment by harupy** [comment]
@cnphil Thanks for the comment.

> when using command groups with auto_envvar_prefix, the command name will be included in the environment variable name.

I didn't notice this. Let's manually name the env vars (as you already do).

**Comment by cnphil** [comment]
@harupy Thanks for clarifying!

I've just updated the PR to manually add the env vars for each command line argument for the `ui()` and `server()` functions in `mlflow/cli.py`.

Please take another look. :)

**Comment by cnphil** [comment]
@dbczumar Feel free to take a look when you've got a chance. :)

**Review by dbczumar — APPROVED** [review]
LGTM! Thanks so much for your contribution, @cnphil !

**Pull request merged**
