### PR TITLE
Adding train.ipynb Jupyter notebook and update tutorial.rst 

### PR DESCRIPTION
**Pull request by dennyglee**
Per #83  - updated Jupyter notebook and tutorial.rst,

### CODE REVIEW

**Comment by mateiz** [comment]
Looks good, thanks!

**Comment by drorata** [comment]
Before opening an issue: it seems like when using mlflow from within a Jupyter notebook, the tracking overwrites the data. I guess the reason is twofold:
- The source is captured as `__main__.py` and
- The timestamp when the Jupyter server was started is considered as the starting time.

Am I missing something? Is this the intended behavior? Bug? Am I trying to abuse the system?

**Comment by dennyglee** [comment]
Could you clarify the issue?   At least in my current environment, when I'm executed three different runs, I see three different folders adn runs within the MLflow UI.  Perhaps I'm missing some context?

**Comment by drorata** [comment]
Assume you have:

```python
# This is stored in a file foo.py
import os
from mlflow import log_metric, log_param, log_artifact

def bar(p1) :
    # Log a parameter (key-value pair)
    log_param("param1", p1)

    # Log a metric; metrics can be updated throughout the run
    log_metric("foo", 1)
    log_metric("foo", 2)
    log_metric("foo", 3)

    # Log an artifact (output file)
    with open("output.txt", "w") as f:
        f.write("Hello world!")
    log_artifact("output.txt")
```

Next, in a notebook, I have the following cell: 
```python
import foo
foo.bar(9)
```

Running it multiple time (changing the parameter) yields a single line in the UI which is changing. But there are *no* separate lines for each execution of the cell.

**Comment by drorata** [comment]
I packed a minimal example in docker. The problem is there as well and turns mlflow to sort of useless when combined with Jupyter. See: https://github.com/drorata/test-mlflow

**Comment by mateiz** [comment]
The problem is that your code didn't explicitly call start_run and end_run, so it counts as a single run. You can fix this by adding `with mlflow.start_run():` around your MLflow code. For example:
```
def bar(p1) :
  with mlflow.start_run():
    # Log a parameter (key-value pair)
    log_param("param1", p1)

    # Log a metric; metrics can be updated throughout the run
    log_metric("foo", 1)
    log_metric("foo", 2)
    log_metric("foo", 3)

    # Log an artifact (output file)
    with open("output.txt", "w") as f:
      f.write("Hello world!")
    log_artifact("output.txt")
```

**Pull request merged**
