### PR TITLE
Updating versions in mlflow docker example

### PR DESCRIPTION
**Pull request by ksaur**
Signed-off-by: Karla Saur <kasaur@microsoft.com>

## What changes are proposed in this pull request?

Updating versions of mlflow docker example

## How is this patch tested?

Was able to complete the example instructions with this fix.

### Is this a user-facing change?

- [ X] No. You can skip the rest of this section.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?
Components 

- [X ] `area/examples`: Example code

Interface 

- [X ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models

<a name="release-note-category"></a>
### How should the PR be classified in the release notes? Choose one:

- [X ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section

### CODE REVIEW

**Comment by ksaur** [comment]
Closes #4833

**Comment by ksaur** [comment]
Hi @sueann or @tomasatdatabricks , I see you reviewed PRs related to this file earlier. Is this something you could take a look at, or point me to who to ping? Thanks! :)

**Review by tomasatdatabricks — COMMENTED** [review]
lgtm! thanks for the contribution!

**Comment by ksaur** [comment]
Thanks @tomasatdatabricks !  What do I need to do to get approval for the workflow run?

**Comment by tomasatdatabricks** [comment]
I have just started them, thanks for the ping @ksaur!

**Comment by ksaur** [comment]
thank you @tomasatdatabricks !  What steps do i need to do for the final checkmark?

**Review by tomasatdatabricks — APPROVED** [review]
lgtm

**Pull request merged**
