### PR TITLE
Inject private git webserver in mlflow (#45)

### PR DESCRIPTION
**Pull request by amrqt**
## What changes are proposed in this pull request?

Allow usage of a private version control system when displaying experiment source and version links

We want to package the app without having to rebuild the UI with custom VCS settings so these settings are passed at runtime to the Python backend through environment variables and served to the UI.

In `mlflow/server/js/src/utils/Utils.js`:
* Added cases to `Utils.getGitRepoUrl()` and `Utils.getGitCommitUrl()` to generate urls to a private vcs. 
* Added `getPrivateVcsRegex` and `getPrivateVcsUrl` which are called when Utils.js is loaded to set the values we need for regex matching and url generation.

## How is this patch tested?

Added tests for the new JS functions, and manual testing.
 
### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [X] Yes. Give a description of this change to be included in the release notes for MLflow users.

Displays links pointing to a private version control system for run source repo and version.

### What component(s) does this PR affect?

- [X] UI
- [ ] CLI
- [ ] API
- [x] REST-API
- [ ] Examples
- [x] Docs
- [ ] Tracking
- [ ] Projects
- [ ] Artifacts
- [ ] Models
- [ ] Scoring
- [ ] Serving
- [ ] R
- [ ] Java
- [X] Python

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [X] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by smurching** [comment]
Hi @amrqt, sorry for my ignorance on this topic - would you mind clarifying which challenge(s) you're currently facing with  exposing private VCS URLs in the MLflow UI? I'd expect such URLs to render properly in the UI, and only those with access to be able to actually view the code in the repositories

**Comment by amrqt** [comment]
Hi @smurching,
The current implementation (in js/src/utils/Utils.js) only recognizes and generates links for Github, Gitlab and Bitbucket repositories. We wanted to be able to display repository and version links to our own vcs which is a self-hosted Gerrit.
In addition we wanted to avoid setting the required regex and vcs host name directly in the UI js files to keep the distributable generic and configurable at runtime through environment variables, thus the need for the UI to fetch these parameters from the backend. We tried to make this as generic as possible so that anyone with another VCS solution can pass a regex and host name for their own setup.
I hope this answer your questions, I'm available if you have more and also open to suggestions for a better implementation

**Comment by smurching** [comment]
@amrqt sorry for the delay, that use case makes sense & definitely agree that it'd be good to make the VCS-URL-parsing configurable vs adding more hardcoded regexes.

I wonder if we could make the list of recognized regexes configurable via an environment variable read at JS build time - that way we could avoid adding a new MLflow REST API to satisfy this particular UI-only use case. See this PR for example https://github.com/mlflow/mlflow/pull/734/files, let me know what you think!

**Comment by aarondav** [comment]
@amrqt Did you get a chance to look at @smurching 's feedback?  What do you think?

**Pull request closed without merging**
