### PR TITLE
fix mlflow version when creating conda env

### LINKED ISSUE #2979: [BUG] mlflow version is not fixed in default conda env
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [x] Yes. I can contribute a fix for this bug independently.
- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS 10.15.2
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 1.5.0
- **Python version**: 3.7
- **npm version, if running the dev UI**:
- **Exact command to reproduce**: mlflow.sklearn.log_model(lr, "model")

### Describe the problem
When loging any kind of supported model, `mlflow` is added as a pip dependency to the `conda.yaml`. The issue is that it is added without any fixed version, which results in the conda env having the latest `mlflow` version even if the training environment had an older one.

### Code to reproduce issue
Any log model function uses `_mlflow_conda_env()` which adds the version less `mlflow` pip dependency.

https://github.com/mlflow/mlflow/blob/10f336a0c86cbabab3089fdfc3943884d2f807ca/mlflow/utils/environment.py#L13-L14

https://github.com/mlflow/mlflow/blob/10f336a0c86cbabab3089fdfc3943884d2f807ca/mlflow/utils/environment.py#L31-L32

for instance, the following code

```python
mlflow.sklearn.log_model(lr, "model")
```

will results in the following `conda.yaml`
```yaml
channels:
- defaults
dependencies:
- python=3.6.10
- scikit-learn=0.22.1
- pip:
  - mlflow
  - cloudpickle==1.4.1
name: mlflow-env
```

a simple fix would be to infer `mlflow` version similar to what is done with other dependencies. for instance:

https://github.com/mlflow/mlflow/blob/6e60e79a593fed2ff5a08aa637a79354bee1be0e/mlflow/sklearn.py#L46-L49

### PR DESCRIPTION
**Pull request by eavidan**
## What changes are proposed in this pull request?

When loging any kind of supported model, mlflow is added as a pip dependency to the `conda.yaml`. The following change with fix the mlflow version to the one used to log the model.

Fixes: #2979 

## How is this patch tested?
```py
import numpy as np
from sklearn.linear_model import LinearRegression
import mlflow
import mlflow.sklearn

X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
y = np.dot(X, np.array([1, 2])) + 3
reg = LinearRegression().fit(X, y)
reg.score(X, y)

with mlflow.start_run():
    mlflow.sklearn.log_model(sk_model=reg, artifact_path="model")
```

results in the following `conda.yaml`
```yaml
channels:
- defaults
- conda-forge
dependencies:
- python=3.6.10
- scikit-learn=0.20.2
- pip
- pip:
  - mlflow==1.9.2.dev0
  - cloudpickle==0.8.0
name: mlflow-env
```

unit test added

### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

When logging a model the `conda.yaml` file will an `mlflow` pip dependency with the version used to log the model

### What component(s), interfaces, languages, and integrations does this PR affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [x] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by harupy** [comment]
@eavidan Thanks for the PR, but we don't restrict mlflow version for forward compatibility (please take a look at [this issue](https://github.com/mlflow/mlflow/issues/3043))

**Comment by eavidan** [comment]
@harupy I was sure it was a bug (#2979). 
I can understand your motivation for forward compatibility for old models. 

having said that, we are using mlflow in production and my issue was reported due to real world experience,
 where some of our models started failing due to dependencies collisions. Since the mlflow version was not fixed so does its dependencies.
for us this was an issue and we found ourselves writing a work around for each mlflow model deployed, fixing the mlflow version to the one existing on our mlflow server.

Do you have any suggestions on how to handle this issue better?

**Comment by harupy** [comment]
@eavidan 
How about using `conda_env` argument in `mlflow.<flavor>.log_model`? For example,

```python
with mlflow.start_run():
    mlflow.sklearn.log_model(
        sk_model=sk_model,
        artifact_path="model",
        conda_env=conda_env_dict_where_mlflow_version_is_specified,
 )
```

**Comment by eavidan** [comment]
@harupy thanks for the suggestions, but this will require all our data scientists to start defining their serving dependencies which we wanted to avoid. Currently, I believe we will keep solving this on our deployment side.

If the reason is forward compatibility then maybe the way to go is to align the conda env with the mlflow server version during the invocation of the `load_model`.
This way we can get an alignment between the model and server mlflow versions. 
Getting the latest mlflow version for the model can conflict with an mlflow server with a fixed version as well.
does this make sense or am I am missing something?

**Comment by dbczumar** [comment]
@eavidan Can you provide more details about the dependency collision / undesirable behavior you encountered? Did the latest version of MLflow specify minimum / maximum library version dependencies that conflicted with other libraries in your conda environment?

**Comment by eavidan** [comment]
hi @dbczumar. We use `seldon-core 1.1` as our serving platform. Seldon core requires `azure-storage-blob >= 2.0.1, < 3.0.0`.
everything went well while we were working with `mlflow 1.5.0` as azure in general was an extra requirement, but `mlflow 1.9.0` requires `azure-storage-blob>=12.0`. Hence the conflict. The funny thing is that we don't use azure :).

as a side note, I would move these kind of the dependencies to the `extras_require` section and the import statement into the relevant methods, but I understand that this is not always possible.

**Pull request closed without merging**
