### PR TITLE
Improve readability

### PR DESCRIPTION
**Pull request by ryanrussell**
## What changes are proposed in this pull request?

Improve readability around typos in docs; docstrings and a variable name

## How is this patch tested?

No testing necessary. Only var changed is not used out of function scope.

## Does this PR change the documentation?

- [ ] No. You can skip the rest of this section.
- [x] Yes. Make sure the changed pages / sections render correctly by following the steps below.

1. Check the status of the `ci/circleci: build_doc` check. If it's successful, proceed to the
   next step, otherwise fix it.
2. Click `Details` on the right to open the job page of CircleCI.
3. Click the `Artifacts` tab.
4. Click `docs/build/html/index.html`.
5. Find the changed pages / sections and make sure they render correctly.

### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?
Components
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>
### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [x] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by harupy** [comment]
@ryanrussell Thanks for the PR! I found some typos today. Can you also fix them? I'll link where they are.

**Comment by harupy** [comment]
https://github.com/mlflow/mlflow/blob/2a05d7d0cc65d4d72bc42b47321ae5b5011944dc/mlflow/projects/__init__.py#L258

**Comment by harupy** [comment]
https://github.com/mlflow/mlflow/blob/da12400db9a405465cae76c237c48ecdfdc3b978/mlflow/pyspark/ml/__init__.py#L768

**Comment by harupy** [comment]
https://github.com/mlflow/mlflow/blob/ebfd6af2092b0d8f35045e564919c4243143fb1d/mlflow/sklearn/__init__.py#L757

**Comment by harupy** [comment]
https://github.com/mlflow/mlflow/blob/3b92f328e577dd69e20713f9d4b82840cbcc1844/dev/get_minimum_required_python.py#L34

**Comment by harupy** [comment]
https://github.com/mlflow/mlflow/blob/4ab6f5111b26a7a8eb31a77c43ea241e5e72f8db/mlflow/models/evaluation/default_evaluator.py#L194

classiifer -> classifier

**Comment by harupy** [comment]
https://github.com/mlflow/mlflow/blob/4ab6f5111b26a7a8eb31a77c43ea241e5e72f8db/mlflow/models/evaluation/default_evaluator.py#L519

mulitnomial -> multinomial

**Comment by harupy** [comment]
https://github.com/mlflow/mlflow/blob/d3ddd59a2333b6cf88e719157453aeeb8d9c2632/mlflow/store/model_registry/abstract_store.py#L188

automically -> automatically

**Comment by harupy** [comment]
@@ryanrussell Ping me once you fix them :)

**Comment by harupy** [comment]
Can we revert https://github.com/mlflow/mlflow/pull/5959/commits/adfe8e5778cdd485c6dedc76b635ae609c6190fe?

We periodically sync JS code between OSS MLflow and our internal private MLflow. https://github.com/mlflow/mlflow/pull/5959/commits/adfe8e5778cdd485c6dedc76b635ae609c6190fe may lead to conflicts.

**Comment by ryanrussell** [comment]
@harupy 

I added those and a few more. The PR started getting larger and including python and js, so I stopped.

Please take a look; it feels pretty solid. 

I put the JS stuff with changed var names related to server in a separate commit at https://github.com/mlflow/mlflow/commit/adfe8e5778cdd485c6dedc76b635ae609c6190fe. Feel free to reject/postpone if that is a more involved merge... that's beyond initial PR scope.

If this is all good, I can run through the rest soon...

**Comment by harupy** [comment]
Thanks for the revert!

**Comment by ryanrussell** [comment]
> Can we revert [adfe8e5](https://github.com/mlflow/mlflow/commit/adfe8e5778cdd485c6dedc76b635ae609c6190fe)? We periodically sync JS code between OSS MLflow and our internal private MLflow. [adfe8e5](https://github.com/mlflow/mlflow/commit/adfe8e5778cdd485c6dedc76b635ae609c6190fe) may lead to conflicts.

Done.

Glad I stopped there :)

Let me know if there's anything else you don't like in the PR.

**Comment by harupy** [comment]
LGTM :)

**Comment by harupy** [comment]
Can you fix the DCO check failure?

**Comment by ryanrussell** [comment]
Hmm, it wants me to redo the DCO after the revert... Have to do another rebase. Sorry about the mess. Doing now.

I'm assuming the rest of the python stuff is fair game to clean up... and leave the js alone?

**Review by harupy — APPROVED** [review]

**Review by harupy — APPROVED** [review]

**Comment by ryanrussell** [comment]
@harupy 

Oops. I just added a gpg key so commits are verified moving forward and accidentally rebased and pushed over on this commit. 

There were no code changes; the only difference is these are Verified. 

Please let me know if that creates any issues on your end. 

Best,
Ryan

**Comment by harupy** [comment]
> Please let me know if that creates any issues on your end.

Not at all :)

**Pull request merged**
