### PR TITLE
Initial support for pip projects

### PR DESCRIPTION
**Pull request by fhoering**
## What changes are proposed in this pull request?

Add support for pip only projects (not using conda or docker)

## How is this patch tested?

Tested with mlflow projects local backend and mlflow-yarn backend.

### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [x ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

Add support for pip only projects.

### What component(s), interfaces, languages, and integrations does this PR affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [x ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [x ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by fhoering** [comment]
@dbczumar @smurching @juntai-zheng 
Any news ? There not so many changes actually and it would unlock to be able to use only pip instead of conda.
I guess this could be also reused for other parts where having an isolated python env is important.

**Comment by juntai-zheng** [comment]
Hey @fhoering, could you answer some questions regarding this new feature in regards to the motivation behind it? These are pulled from the motivation section for FRs:
- What is the use case for this feature?
- Why is this use case valuable to support for MLflow users in general?
- Why is this use case valuable to support for your project(s) or organization?
- Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient)

**Comment by fhoering** [comment]
>     What is the use case for this feature?
>  Why is this use case valuable to support for your project(s) or organization?

We don't use conda at all in our organization. So what currently we can't use any feature of MLflow that makes use of conda for packaging. It is not an option to use conda becasue we have our own internal pypi mirror and it is used by many other Python projects. All our CI/Prod code is based on Pypi and pip. That's why we alignd our datascience tools to that.

>  Why is this use case valuable to support for MLflow users in general?
I'm not sure I understand the question. pip is widely used in the Python community. This would open up  mlflow to much more users than what is currently existing with conda.

>   Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient)
As you can see in the PR it is not that difficult and the maintenance effort seems limited but it would be cleaner to integrate this by default into MLflow.

**Comment by jinzhang21** [comment]
We've added support to use pip-only for mlflow installation. Closing this PR. Thanks for the contribution!

**Pull request closed without merging**
