### PR TITLE
[docs] fix information hierarchy in model registry workflow page

### PR DESCRIPTION
**Pull request by ankit-db**
## What changes are proposed in this pull request?

Currently, the table of contents looks like this:
image

This is incorrect, since the UI workflow and the API workflow should be subheadings of Model Registry workflows

This PR adjusts this so that the UI/API workflows fall under the Model Registry workflows section

## How is this patch tested?

Go to docs/ and run make livehtml

### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [x] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Review by dmatrix — APPROVED** [review]

**Comment by dmatrix** [comment]
Makes perfect sense! LGTM

**Comment by dmatrix** [comment]
@ankitmathur-db one  MLflow tests fails. Looks like an RST error. 

```
make: *** [rsthtml] Error 1
Makefile:70: recipe for target 'rsthtml' failed
##[error]Process completed with exit code 2.
```

**Comment by ankitmathur-db** [comment]
Will look into the test failure later today!

**Comment by dmatrix** [comment]
@ankitmathur-db Should you worry about install dependencies test failing and maybe heed to updating?

`WARNING: You are using pip version 19.3.1; however, version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
##[error]Process completed with exit code 1.
 Run tests`

**Comment by ankitmathur-db** [comment]
Yeah, I saw this failed - doesn't seem like an issue from this PR, so I've re-triggered the jobs to see if that helps!

**Comment by dmatrix** [comment]
@ankitmathur-db should we close this since you have merged it and all your tests passed?

**Pull request merged**
