### PR TITLE
[UI] Change default x-axis type of metrics plot to "step"

### PR DESCRIPTION
**Pull request by harupy**
## What changes are proposed in this pull request?

This PR changes the default x-axis type of the metrics plot to "step" because it's rare to see (or compare) metrics on the relative time axis.

Screen Shot 2020-02-29 at 14 14 41

## How is this patch tested?

Manually tested.

### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s) does this PR affect?

- [ ] UI
- [ ] CLI
- [ ] API
- [ ] REST-API
- [ ] Examples
- [ ] Docs
- [ ] Tracking
- [ ] Projects
- [ ] Artifacts
- [ ] Models
- [ ] Scoring
- [ ] Serving
- [ ] R
- [ ] Java
- [ ] Python

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by harupy** [comment]
@smurching @Zangr 
Does this change make sense?

**Comment by smurching** [comment]
@harupy thanks for the PR! I'm not immediately convinced we should change the default x axis to step, primarily because the various clients log a default step value of 0 (which would cause the graph to just look like a vertical line). We could maybe try to do something more complex, e.g. set the default to STEP if each unique `(metric_key, run_id)` tuple has >1 distinct step value, but not sure if that's worth it - let me know what you think

**Comment by harupy** [comment]
@smurching Thanks for the comment! +1 for the selective default x-axis type.

**Comment by aarondav** [comment]
@harupy Are you planning on updating the PR to select the default based on the data?

**Pull request closed without merging**
