### PR TITLE
Set minimum version of opentelemetry packages

### PR DESCRIPTION
**Pull request by JoostvDoorn**
<details><summary>&#x1F6E0 DevTools &#x1F6E0</summary>
<p>

[Open in GitHub Codespaces](https://codespaces.new/JoostvDoorn/mlflow/pull/12089?quickstart=1)

#### Install mlflow from this PR

```
pip install git+https://github.com/mlflow/mlflow.git@refs/pull/12089/merge
```

#### Checkout with GitHub CLI

```
gh pr checkout 12089
```

</p>
</details>

### Related Issues/PRs

This fixes an incompatibility issue with old versions of opentelemetry by setting a minimum version.

```
ModuleNotFoundError: No module named 'opentelemetry.util._once'
```

The module `opentelemetry.util._once` was introduced in opentelemetry `v1.6.0` https://github.com/open-telemetry/opentelemetry-python/blob/v1.6.0/opentelemetry-api/src/opentelemetry/util/_once.py

### How is this PR tested?

- [ ] Existing unit/integration tests
- [ ] New unit/integration tests
- [ ] Manual tests

### Does this PR require documentation update?

- [ ] No. You can skip the rest of this section.
- [ ] Yes. I've updated:
  - [ ] Examples
  - [ ] API references
  - [ ] Instructions

#### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

#### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>

#### How should the PR be classified in the release notes? Choose one:

- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

#### Should this PR be included in the next patch release?

`Yes` should be selected for bug fixes, documentation updates, and other small changes. `No` should be selected for new features and larger changes. If you're unsure about the release classification of this PR, leave this unchecked to let the maintainers decide.

<details>
<summary>What is a minor/patch release?</summary>

- Minor release: a release that increments the second part of the version number (e.g., 1.2.0 -> 1.3.0).
  Bug fixes, doc updates and new features usually go into minor releases.
- Patch release: a release that increments the third part of the version number (e.g., 1.2.0 -> 1.2.1).
  Bug fixes and doc updates usually go into patch releases.

</details>

- [x] Yes (this PR will be cherry-picked and included in the next patch release)
- [ ] No (this PR will be included in the next minor release)

### CODE REVIEW

**Review by WeichenXu123 — APPROVED** [review]

**Comment by harupy** [comment]
@JoostvDoorn how can we reproduce this issue?

**Comment by harupy** [comment]
I see, we're using `_once` here:

https://github.com/mlflow/mlflow/blob/5f3101e9c91aaea37cad2667082974028fe16bd6/mlflow/tracing/provider.py#L7

**Comment by harupy** [comment]
@B-Step62 Instead of importing `Once` from a private module, can we define `Once` in mlflow and use it?

https://github.com/open-telemetry/opentelemetry-python/blob/a156bf161d4de96766cac09a5ef4fcddbf367604/opentelemetry-api/src/opentelemetry/util/_once.py#L19

**Comment by B-Step62** [comment]
> @B-Step62 Instead of importing Once from a private module, can we define Once in mlflow and use it?

We can, but lemme verify the old version of opentelemetry actually works - there may be other compatibility issue

**Comment by harupy** [comment]
> lemme verify the old version of opentelemetry actually works - there may be other compatibility issue

Sounds good. We can bump the lower limit if necessary.

**Comment by B-Step62** [comment]
@harupy Sorry for the late turnaround! I've tested tracing with early versions; it seems `1.6.0` is not enough, we need to pin `>= 1.9.0` to make current MLflow tracing work.

Particularly, [this change](https://github.com/open-telemetry/opentelemetry-python/commit/1a52e9df1c10a42da7562f8b4d11f43576ed0aed) of adding NoOpTracer needs to be included. We use the `NoOpTracer` in a few places to manage enable/disable of tracing feature. It might be possible to handle it with older OTel logic, but probably we can wait until requested since it already passed 2 years since `1.9.0` is released. WDYT?

**Comment by harupy** [comment]
@B-Step62 Pinning >= 1.9.0 sounds good to me :) I don't think it will conflict with Databricks runtimes.

**Comment by B-Step62** [comment]
Since the required version is newer and there are a few more files to edit, I went ahead and created a new PR: https://github.com/mlflow/mlflow/pull/12148

Thank you so much @JoostvDoorn for bringing this issue up to our attention!

**Pull request closed without merging**
