### PR TITLE
Add Aliyun OSS Storage support for artifact store

### PR DESCRIPTION
**Pull request by SeaOfOcean**
## What changes are proposed in this pull request?
Add Aliyun OSS Storage support for artifact store
https://www.alibabacloud.com/help/doc-detail/31817.htm

## How is this patch tested?

unit test

### Is this a user-facing change?

- [X] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s) does this PR affect?

- [ ] UI
- [ ] Command Line Interface
- [ ] API
- [ ] Examples
- [ ] Docs
- [X] Tracking
- [ ] Projects
- [X] Artifacts
- [ ] Models
- [ ] Model Registry
- [ ] Scoring
- [ ] R
- [ ] Java
- [X] Python

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [X] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by dbczumar** [comment]
Hi @SeaOfOcean, thank you for filing this PR! We will review it shortly!

**Comment by SeaOfOcean** [comment]
> Hi @SeaOfOcean, thank you for filing this PR! We will review it shortly!

thanks, could you please help review the code.

**Comment by dbczumar** [comment]
Hi @SeaOfOcean, sorry for the delay here. After conferring with other MLflow Committers, we'd love to accept this contribution in the form of an MLflow Plugin that users can install in addition to the main MLflow library. This allows you to maintain and extend the artifact repository implementation independently (of course, the MLflow community is also willing to provide guidance, answer questions, and test the implementation prior to its initial release).

https://mlflow.org/docs/latest/plugins.html provides information about writing plugins for ArtifactRepositories. A great example of an existing plugin is the artifact repository for SQL Server: https://pypi.org/project/mlflow-dbstore/. Here's a high-level proposal for how to proceed:

1. Create a new GitHub repository containing the `aliyun_oss_artifact_repo.py` implementation, as well as a `setup.py` file that defines an `mlflow.artifact_repository` entry point (see https://mlflow.org/docs/latest/plugins.html#defining-a-plugin).
2. In the meantime, I will review this PR for the purposes of testing the artifact repository's behavior and verifying that it works properly.
3. Once the review is complete and changes have been merged into your GitHub repository, proceed to release the artifact repository as a PyPI package
4. After the PyPI package has been released, we can work together to add information about your plugin to the `community plugins` section of the docs: https://mlflow.org/docs/latest/plugins.html#community-plugins. We can also add an `[aliyun]` installation option to MLflow that automatically installs your plugin when specified; for example, users can currently run `pip install mlflow[sqlserver]` to install the SQL Server plugin automatically.

Please let me know if you have any questions about this process! Eventually, we hope to move existing artifact repositories to plugins / optional dependencies of the MLflow project to reduce the set of required library dependencies.

**Comment by SeaOfOcean** [comment]
Hi @dbczumar , thanks for the suggestion. I have created a new repo for the plugin. https://github.com/SeaOfOcean/mlflow-aliyunstore/pull/1
Can you help review it? thanks~

**Comment by dbczumar** [comment]
@SeaOfOcean Sorry for the delay - reviewing it now!

**Comment by dbczumar** [comment]
@SeaOfOcean The plugin looks awesome and was a lot of fun to test out manually. I left a small comment about including `oss2` as a dependency of the plugin in `setup.py`; you can see the full details here: https://github.com/SeaOfOcean/mlflow-aliyunstore/pull/1#pullrequestreview-425679666. We should be all set to move forward with uploading the plugin to PyPI and adding documentation to the MLflow Plugins page about the new functionality (https://mlflow.org/docs/latest/plugins.html#community-plugins). Thank you so much for this contribution!

**Comment by SeaOfOcean** [comment]
@dbczumar thanks so much for the review comment! I have uploaded it to PyPI and added the documentation. I have just opened another pull request https://github.com/mlflow/mlflow/pull/2917

**Pull request closed without merging**
